== Chapter II.

Joins another Deputation to an Indian Treaty--Address from Friends to
the Indians--Journey from Philadelphia to the western part of New
York--Hard fare in the Wilderness--Canandaigua--Interview with
Oneidas--Jemima Wilkinson and her followers--Oneida Council--Col.
Pickering--Council of the Six Nations--Speeches of Indian Chiefs--Red
Jacket--Cornplanter--Interference of British Agent--Number and
Possessions of the Six Nations--Speech of Col.
Pickering--Remarkable Spring--Speech of Red Jacket to
the Friends--Red Jacket`'s reply to Col.
Pickering--Another Speech by the Commissioner--Reply by Red Jacket--
Interruptions to closing the Treaty--Efforts of Friends to compensate
the Indians formerly owning the land about Hopewell.
Va.--Speech of Cornplanter--Reply of Commissioner--Treaty signed--Address of
the Indians to the Friends--Start for Home--Difficulties of the Journey--
Arrival in Philadelphia--Reflections respecting the Indians--Visit to
Virginia Yearly Meeting--Remarkable Service in Richmond--Return Home.

+++[+++Editor`'s Note:
The following chapter is largely taken up with the details of treaty
negotiated between commissioners appointed on behalf of the United States,
and the chiefs of the Six Nations Indian confederacy.
Large portions of the speeches from both sides seem to
have been taken down in shorthand by William Savery,
and preserved in his journal.
If this information (being more of a historical than a
spiritual nature) is not of interest to the reader,
he or she is encouraged to skip ahead to the third chapter,
where the journal continues with descriptions of his own
inward and outward experiences as a devoted follower of Christ
and a minister in the Society of Friends.--FLP]

[.asterism]
'''

In the Eighth month, 1794,
the Meeting for Sufferings was informed through the officers of government,
that a treaty was shortly to he held at Canandaigua, in the State of New York,
between commissioners appointed on behalf of the United States,
and the chiefs of the Six Nations;
and that they were particularly solicitous Friends should
attend it--the government also encouraging their doing so.

After seriously deliberating on this important movement, four Friends, namely,
David Bacon, John Parrish, William Savery, and James Emlen,
under an apprehension that it was their religious duty,
offered themselves for the service, and being approved by the meeting,
were furnished with a number of articles, as presents for the Indians,
and with the following address:

"`The people called Quakers, in Pennsylvania, New Jersey, etc.,
by their representatives assembled at Philadelphia, the 9th of Ninth month, 1794:

To our brothers, the Indians of the Six Nations,
who have appointed to meet at Canandaigua, in order for the promotion of lasting peace;

Brothers,--We are always glad when we have an opportunity of hearing from you,
our old friends, and using our endeavors in promoting the good work of peace.

Brothers,--We understand the President of the United
States has proposed holding a treaty with you,
by his commissioners.
Our religious profession has always led us to promote so good a work;
and having been informed that the President of the United States, as also your nations,
are willing and desirous we should be at the treaty,
we have therefore authorized our beloved friends, David Bacon, John Parrish,
William Savery, and James Emlen, to attend the said treaty for us;
on whose behalf we make known to you, that they are our friends, whom we greatly love,
being true men, whose love is so great to their Indian brethren,
the old inhabitants of this land of America, that they are willing to come to see you,
with desires to do you good.

Brothers,--We meddle not with the affairs of government;
but we desire to do all we can to preserve and promote peace and good-will among all men.

Brothers,--Our grandfathers and friend Onas +++[+++William Penn],
were careful in their day to preserve peace and love with their brothers,
the Indians:--We, their children and successors, endeavor to do the same,
and are happy when we can prevail on the people to be kind,
and do good and not evil to one another.

Brothers,--We pity the Indians, as well as the white people,
when they are brought into suffering and distress,
and would do them all the good in our power.--We hope the
Great and Good Spirit will put it into the hearts of the great
men of the United States and your great men,
to adjust and compromise all their differences.

Brothers,--We hope you will receive kindly our friends and brothers, David Bacon,
John Parrish, William Savery and James Emlen.
We have put under their care a small token of love for you,
as the descendants of the first inhabitants of this land of North America,
whom our forefathers found here after they had crossed the great water.
Desiring that the chain of our friendship may be kept bright, we bid you farewell.

Signed by forty-four Friends.

The benevolent and sympathetic mind of our beloved friend,
was so deeply interested for this injured people,
that though he had endured so much in the late painful and hazardous journey to Detroit,
yet he could not withhold his aid,
when another attempt was to be made for adjusting the
many grievances of his red brethren,
and, if possible, settling the terms of a lasting peace.
He has left the following narrative of the undertaking:

"`Left Philadelphia in company with my friends, David Bacon, John Parrish,
and James Emlen, the 15th of ninth month, 1794;
being accompanied by several Friends to Germantown,
where we took an affectionate leave of them.
Nothing from without affords so great consolation and
strength in undertaking such arduous journeys,
as a sense that we are favored with the precious unity and
affectionate concern of our near connections and brethren.
This, to me, has been a comfortable reflection,
and softens the trials I have felt at leaving my home at this time,
especially as the Yearly Meeting is near at hand.

"`Having got on the Blue mountains the 18th,
we proceeded a short distance when it began to rain,
and increased till our clothes were wet through; but after riding several miles,
we stopped at a house, got some refreshment, dried our clothes and rode to Cattawissa.
Neither the land nor the appearance of the
country round this place appears very attractive.

"`19th. Riding through a better country on the west side of the Susquehanna,
we stopped at a place where they at times entertain travellers, and expected to dine;
but they having neither feed for our horses, bread nor meat,
we rode two miles further and dined upon bread, the people having neither food nor milk.

"`20th. Got to the house of a Friend at Loyalsock.
Before I alighted from my horse I felt unwell, and immediately went to lie down.
A fever coming on, I was very sick until evening,
and began to doubt the propriety of going on,
yet was glad that my indisposition was not the cause of detaining my friends,
for it rained too hard to travel, until near night.

"`21st. Being much recruited I went on, and after crossing the Lycoming eight times,
proceeded over an exceedingly stony and miry path through the woods;
we thought the road very long and tiresome, both to ourselves and the horses.
At dark we heard the barking of a dog, which rejoiced us;
but it proved to be at a place called the Block-house, a poor shelter indeed.
We were now convinced of our neglect in not providing
ourselves with necessary stores when we had the opportunity;
such as sugar, tea, meat, bread, etc.,
for this family had nothing for us but a little flour,
which the woman in a very dirty manner kneaded up in the fat of an elk,
shot some days before.
Our lodging and fare were truly uncomfortable.
I could but admire how very few, even of what are called the necessaries of life,
supported this family; the children, however,
have a far more healthy appearance than is common in luxurious and populous cities;
and having near thirty miles to send for salt, sugar, flour and other necessaries,
a girl about fourteen, and a boy about thirteen years of age,
generally performed the journey alone, sometimes lying all night in the woods.
We had to lie on the floor, with the house open on all sides; yet were content,
though we slept but little.

"`22nd. Our horses being tied up all night without either hay or pasture,
we fed them with some oats and rode about ten miles over an exceedingly bad path,
the most difficult we had yet seen.
Stopping a short time on the banks of the Tioga at the house of a new settler,
we procured some feed for our horses, and a small piece of meat for ourselves.
The country so abounds with wild game, bears, deer, elk, foxes and wolves,
that it is difficult to keep hogs or sheep.--There being no taverns,
all the farm-houses take in travellers and charge very high for poor fare.

"`24th. We got to an Indian cabin on the bank of
the river which runs by the town of Bath,
and twelve miles further reached a sort of public house,
having rode the whole of this day through the woods.

"`On the 25th, we arrived at Canandaigua, in the afternoon,
where Colonel Pickering and General Chapin were
holding a conference with the Oneida Indians.
Having welcomed us, they directed us to the lodgings prepared for us.

"`26th. Attended a second conference with the Oneidas,
which chiefly consisted in a relation of what had befallen them since the last treaty.
They informed us, that as we were now met again,
they hoped we should discuss all the necessary
objects of the treaty with candor and freedom,
and for that purpose they now unstopped our ears that we might hear,
and opened our throats that we might speak freely.
To this Colonel Pickering expressed his wish to conduct
the business with the unreserved candor they desired,
and that he also opened their ears and unstopped their throats.

"`27th. Seeing some persons in the garb of Friends,
they informed us they lived about five miles beyond this, and being glad to see us,
invited us to their houses.

"`28th. First-day, having appointed a meeting, to begin at eleven o`'clock,
it was largely attended by the people, and a considerable number of Indians,
so that the house could not contain the whole.
Appointed another at four o`'clock in the afternoon, both of which were to satisfaction,
and we believe to the people generally.
There is no public worship maintained within many miles of this place.

"`30th. Abraham Lapham came to our lodgings, and conducted us to his house,
where we were kindly received, and spent a pleasant day.
This country has two great disadvantages attending it,
the scarcity of springs and rivulets,
and the unhealthiness of the climate in its present uncultivated state,
yet it is settling very fast, the land being very fertile;
but as the Indians are all round, and the settlements of the whites very thin,
there still is some danger to he apprehended.
The first settlers have passed through great difficulties,
having near one hundred miles to go to mill,
and struggling under many privations to procure a living for their large families;
some have staid for many weeks under the shelter
of bark and bushes before they could erect a hut.

"`Tenth month, 2nd, fifth-day.
Six of the Indians, each of them brought in a deer,
and one of them made us a present of a piece,
signifying that he gave it to us for Jesus Christ`'s sake, who had made us brethren.

"`First-day, 5th of the month.
The weather not being very favorable, the meeting was not so large as last First-day,
nor so satisfactory.
The Indians were remarkably sober, making but little noise;
the Oneidas pay some regard to the First-day of the week.

"`7th of the month.
Went to Judge Potter`'s, and being kindly received stayed all night.
The Judge is a respectable man,
but having some years back been induced to entertain a
favorable opinion of Jemima Wilkinson and her doctrines,
he and several others came with her into this country,
and took up forty-one thousand acres of excellent land near the west side of Seneca lake,
at four pence per acre.
But the good understanding of the Judge not allowing
him to remain a dupe to the delusions of an assuming,
presumptuous woman, he has for some time past thrown off the shackles,
and is now no more accounted one of her fraternity.
He said he believed her whole scheme was for self-interest and aggrandizement;
he-himself having Buffered by her in a pecuniary point of view,
but had now asserted his right to a part of the land occupied by these people,
and forbade their making use of it.
After breakfast we went to see Jemima, and found her about three miles from Potter`'s,
in a sequestered, romantic place, suited to her genius.
The family appeared to consist of ten or twelve persons,
one of whom being acquainted with us, welcomed us in;
another was a man far gone in a consumption,
who had left his wife at some miles distance and
brought so much of his little property with him,
as to reduce her to great difficulty in getting a subsistence.
His design appears to be to spend his last breath under Jemima`'s benediction,
assuring us he was very easy about his soul.
O, wretched infatuation! that can break the most solemn ties of God and nature,
and yet flatter its votaries that they are the favorites of heaven.

"`Here are several hovels adjacent,
which are the residences of women who have forsaken husband and children;
and also of men who have left their families, to become what they now literally are,
hewers of wood and drawers of water to an artful and designing woman.
One young woman who had been with them several years,
told me the women frequently washed Jemima`'s
feet and wiped them with the hair of their heads.
Asking for the rest of the family,
Rachel Malin stepped into Jemima`'s room and invited her out.
She was attired in a loose gown or rather a surplice of calico,
and some parts of her dress were quite masculine;
she accosted us with a look of importance, and called me by name.
The conversation becoming of a religious nature,
she said much in a kind of prophetic manner.
So great was her volubility,
that we were obliged to interrupt her in order to express our
disapprobation of the exalted character she gave to her own mission,
and that it savored strongly of pride and ambition to distinguish herself
from the rest of mankind by the appellation of the Universal Friend.
Some other remarks were made to check her rhapsodies, but her assurance,
and artful manner of leading off from a subject which she did not relish,
rendered our efforts abortive.
We were, however, not disappointed,
for it cannot be expected that any power but that which is Divine,
can bring her to a state of reason or of Christianity.
This people have a meeting-house,
and some of the scattered neighbors meet with them on First-days,
but it appears they are declining fast; and both reason and religion inform us,
that their fall is at no great distance,
and perhaps the last days of this deluded woman may be spent in contempt,
unless her heart becomes humbled and contrite,
and the mercy of the Lord be eminently manifest to pity and spare her.
Some credible persons resident in the neighborhood informed us, that Jemima had asserted,
and it was believed by her credulous disciples,
that the prophet Elijah had taken possession of the
body of one James Parker and spoke through his organs;
and that the prophet Daniel, in like manner, inhabited the body of Sarah Richards,
another of her followers; but the prophet Elijah,
(James Parker,) and she having afterward disagreed and separated,
and Sarah Richards having died, they are now deprived of their counsel.

"`9th. The Senecas are very slow in coming to attend the treaty,
and the lesson of last year is to be learned over again; this is patience,
which will always be needed by those who attend Indian treaties.

"`11th. Colonel Pickering having called on David Bacon and myself,
we attended him to the Oneida camp, where an interesting council was held,
in which Captain John, an Indian sachem, and Peter the chief warrior, were the speakers.
Colonel Pickering made a very suitable speech,
informing them that he had heard of divisions among them,
and if they would inform him of the cause of them he
should be happy in using his endeavors to settle them.
Captain John then informed us in a long speech of many
things which had occasioned uneasiness in their nation,
principally in relation to the manner wherein they had
several times suffered in the sale of their lands;
and lately by leasing to Peter Smith one-third of the land they had reserved,
being a tract of four miles wide and twenty-four miles long,
which they had leased to him for twenty-one years, at two hundred dollars per annum.
This had occasioned great dissatisfaction between the sachems and the warriors,
the warriors protesting against the lease; that the two parties,
while the land was surveying, faced each other in arms,
and had not the surveyors desisted, it might have proved destructive to the nation,
and they were yet divided into parties.
He began by observing, that we were all in the presence of the Great Spirit,
and he knew that he could not conceal anything from Him,
and as he was now surrounded by his brethren,
he should speak uprightly and withhold nothing.
He spoke nearly an hour, and delivered to Peter, the chief warrior,
five strings of wampum,
which Colonel Pickering gave into his hand as he closed his speech.
He then desired, if the warriors had heard anything that was not true,
they would point it out.
Peter,
after reminding Colonel Pickering of the advice
which he gave them at Newtown in the last treaty,
said he found no fault with what the sachems had said,
but desired that if they had gone out of the path they
were recommended to walk in when at Newtown,
which he suspected they had, the colonel would put them right again.

"`Colonel Pickering told them he believed they had,
but as it was a matter of great importance,
he desired to consider it until the day after tomorrow, that he might prepare an answer.
The conference held three hours,
after which Colonel Pickering acknowledged that both private persons and the
governor of New York had given great occasion for their complaints.
Smith`'s lease contained sixty-one thousand four hundred and forty acres.
In the evening John Parrish and James Emlen returned
from the encampment of the Senecas at Gennessee river,
about twenty-six miles distant,
bringing an account that there were about five hundred of them at that place.

"`12th. Understanding a person expected to occupy our former place of meeting,
we concluded to prepare the house where we lodge for holding a meeting.
Friends who are settled in the neighborhood, and several others,
with a number of the Indians coming in, we had a solid favored opportunity.
Some who had expected us at the school-house as usual, came after that meeting was over,
and said that they had been disappointed in not finding us there,
but thought that for the future they should come to our lodgings on a
First-day morning to know where the meeting was to be held.
In the afternoon we went at four o`'clock to the Oneida camp,
having previously informed the chiefs of our intention of a meeting there,
the interpreter being with us.
We found some collected in the woods where many trees were felled, which served as seats,
and one of the chiefs went round the camp,
vociferating a certain sound used as a signal for them to assemble,
which they did in large numbers.
The curiosity of the white people being raised, and some coming from other motives,
we had a large and good meeting, which held till near sunset;
both whites and Indians were quiet and behaved decently;
as many of the Indians had received some notion
of the Christian religion from missionaries,
and were desirous to begin the service with singing of hymns or psalms,
and we not thinking it would be best to object to their wishes,
they appeared very devout,
and I thought that the melody and softness of their voices in the Indian language,
and the sweetness and harmony that attended,
exceeded by far anything of the land I had ever heard among the white people.
Being in the midst of the woods,
the satisfaction of hearing these poor untutored people sing,
with every appearance of devotion, their Maker`'s praise,
and the serious attention they paid to what was delivered to them,
conspired to make it a solemn meeting, long to be remembered by me.
We left them in much love and sympathy,
rejoicing in the midst of the wilderness that the Lord is indeed everywhere.

"`13th. Eliminating on the state of the Oneida Indians,
who are said to be more civilized and better instructed in religion than any others,
it is natural to inquire what influence it has had on their manners and morals, which,
from anything I can discover, has yet been very small.
It is true, they generally cultivate a small portion of land,
and for that reason are less exposed to absolute want than other Indians:
they have also heard of Jesus Christ through their missionary,
and have been taught to sing psalms and hymns in their own soft and engaging language;
but it appears to me that the great body of the
nation have received the Gospel in word only,
and not in power.
It has therefore had but little influence on their conduct; and a few excepted,
they appear to remain enslaved to all the vices common to the other Indians;
yet I think the way is gradually preparing when some more enlightened
and spiritual men than have yet been their teachers,
men who will unite example with precept, may be sent among them with a good effect.

"`Colonel Pickering having called on us again, we went with him to the camp,
where the chiefs and warriors being assembled, he delivered a long written speech,
containing suitable advice for reconciling the differences in the nation,
and also as a rule for their conduct in future respecting their lands,
which appeared well calculated to prevent the frauds and impositions of designing men.
They heard all patiently,
and then desired us to withdraw a few minutes while they consulted among themselves.
Being again called in,
Captain John said they were in hopes that Colonel Pickering would
have informed them whether the sachems or warriors had been wrong,
for it would not have hurt the sachems if they had been so told plainly.
The advice to them had been very long, and he could not retain all parts of it,
but he recollected they were told that Peter Smith, agreeably to our laws,
was not only subject to have his bargain made void,
but also liable to pay a fine of a thousand dollars and suffer a year`'s imprisonment;
the two latter they hoped would not be inflicted, as it was not their wish.
He also noticed what was said concerning our government and laws, saying,
the Indians had also their mode of law, which had been handed down by their forefathers;
and one of their customs was, for the sachems only to sit in council on civil affairs;
but of late, their warriors appeared jealous of them,
and had intruded into matters contrary to the ancient customs of Indians;
hence we might see, that when they were about to answer the commissioner,
Peter the chief warrior had gone off and took the warriors with him,
which indicated his being displeased;
and he thought he would show it either during the present council-fire, or afterwards.
Indeed,
he apprehended that Peter was aspiring to be something
more than the nation was willing he should be,
and aimed at being the chief sachem.
He then told us in very drolling style,
the manner of the white people persuading them out of their lands,
even some who had not half the understanding naturally,
that was possessed by some of their chiefs,
but they were skilled in dissimulation and
acquainted with the propensities of the Indians.
They agreed to take the advice given them and wished it again repeated.

"`Colonel Pickering told them, he would use his influence to have their lands,
which Peter Smith had taken upon lease, restored to them,
and that after they were restored, if that could be obtained,
he wished them still to offer them upon lease,
and to take the assistance of some judicious men that might be appointed by government;
they might then lease them in three hundred separate farms,
with certain stipulations that the land and timber should not be ruined, etc.
The consequence of this would be, that in twenty-one years,
there would be so many improved farms in their possession,
which would result in a great accumulation of wealth to the Oneida nation.
He concluded by promising to return by the Oneida castle, as he went home,
where he would repeat his advice to them, that they might not forget it;
and told them they had reason to rest peaceably-and quietly,
though it should not even be in the power of government
to reclaim the lands which Smith had got upon lease;
for they should consider that a great estate was still in their possession,
if the best use was made of it: whereupon the council broke up.

"`14th of Tenth month.
The party of Senecas, headed by the Farmer`'s Brother, Little Billy, etc.,
having arrived, last evening, within four miles, were expected this forenoon;
but having to paint and ornament themselves before their public entry,
they did not arrive till three o`'clock this afternoon.
The Oneidas, Cayugas, and Onondagoes, were drawn up, dressed and painted,
with their arms prepared for a salute before General Chapin`'s door.
The men able to bear arms marched in, assuming a good deal of importance,
and drew up in a line facing the Oneidas, etc; Colonel Pickering, General Chapin,
and many white people being present.
The Indians fired three rounds, which the other Indians answered by a like number,
making a long and loud echo through the woods.
Their commanders then ordered them to form a circle
around the commissioner and General Chapin;
then sitting down on the ground, they delivered a speech through the Farmer`'s Brother,
and returned the strings of wampum which were sent them,
when they were requested to come to the treaty.
Colonel Pickering answered them in the usual complimentary manner,
and ordered several kettles of rum to be brought; after drinking which, they dispersed,
and went to prepare their camp.
Each chief delivered in a bundle of sticks, answerable to the number of persons, men,
women, and children, under his command, which amounted to four hundred and seventy-two.
They made a truly terrific and warlike appearance.

"`16th. About three o`'clock this afternoon,
Cornplanter and his party of the Senecas arrived, amounting to about four hundred.
They drew up in three sides of a square, the Oneidas, Onondagoes, etc., facing them;
each fired three rounds, and performed some maneuvers; all in full Indian dress,
and painted in an extraordinary manner.
Then encircling the commissioners and us,
they exchanged a short speech of congratulation, and as it rained,
the rum was soon brought, and the company dispersed.
There are now about sixteen hundred Indians assembled.
Last night one Indian stabbed another, who, although not yet dead,
is unlikely to continue long.

"`17th. Sixteen hundred Indians are around us, many of them very noisy night and day,
dancing, yelling, and constantly intruding upon us to beg for rum, etc.,
but we uniformly resist their importunities for strong drink.
The attendance at Indian treaties is a painful task,
wherein resignation is highly necessary.
May it be granted.
They kill plenty of venison, and sell it for three half-pence, or less, per pound.
While at our present place of abode, I sat in company with an Indian Queen,
who had a small child in one of their kind of cradles,
hung with about one hundred small brass bells, intended to soothe the child to rest.

"`18th. This morning Cornplanter, Farmer`'s Brother, Red Jacket, Little Beard,
and a number more of the Seneca chiefs, came to our lodgings to hold a conference,
the interpreter being with them.
Cornplanter congratulated us upon our safe arrival among them,
and acknowledged the kindness of General Washington in
informing Friends of the request of the Indians,
that they should attend the treaty.
He then opened the business, which more particularly occasioned their present visit.
This was to answer a request made to them a year or two past by Friends at Philadelphia,
that they might make inquiry after the Indiana, or their descendants,
who formerly lived about Hopewell, in Virginia.^
footnote:[Some members of the Society of Friends had
purchased and settled upon lands about Hopewell,
and there was reason to believe that the Indian title had not been
extinguished by a fair and honorable purchase of the natives,
by those occupants who had sold to Friends.
The Society, consonant with its known principles, wis desirous,
that notwithstanding the Indians had left or been driven to remote parts,
yet that if the original proprietors could be found,
however feeble and insignificant they might now be, they should be fully compensated,
in order that its members might hold those possessions
on such a firm and justly acquired fee,
as true Christian principles would dictate.]
He said that they had conferred together on the subject several times,
and believed they had come to the knowledge of the original owners of that land,
two of whom, ancient men, were now present,
who said their people were once settled about Coneslogo,
and that they remembered well the state of matters respecting the land in question:
they had no doubt those two ancient men could clear up the matter to our satisfaction,
at a future opportunity, and would retire for the present.

"`In the afternoon, Obeal, son of Cornplanter, came with a message from the Indians,
inviting us to council.
We found a large body of them collected, Colonel Pickering, General Chapin,
and three interpreters being in the centre,
and the surrounding assemblage presenting a very striking aspect;
the chiefs appeared solid and thoughtful.
Captain John, and another of the Oneidas, spoke, addressing themselves to their brothers,
the Senecas, Tuscaroras, and Delawares, who lived westward, holding in their hands,
as they spoke, one after the other, several strings of wampum and belts;
which they handed to the Seneca chiefs, one by one, at certain periods of their address,
till they delivered all they had.
As it was only an address to their brethren, the Indians of other nations,
agreeably to their ancient custom, when they meet at a council fire,
it was not publicly interpreted; but we understood it was in the way of condolence,
on account of the loss of many chiefs of the Six Nations by death,
since they last met at a council fire.
They expressed their desire to wipe the tears from their brethren`'s eyes,
to brighten their countenances, and to unstop their throats,
that they might speak clearly in the present council fire.
The Fish Carrier, Clear Sky, and Red Jacket, returned a brotherly salutation,
handing the eastern Indians belts and strings of wampum, to unite each to the other,
and thus to open the council as with the heart of one man.
They then informed Colonel Pickering, that the Six Nations were now embodied in council.
He made them a complimentary and congratulatory address,
informing them that he should hold a council of
condolence tomorrow at four o`'clock in the afternoon,
to wipe away the tears from the eyes of the Delawares, who had lost a young brother,
murdered by a white man at Venango, last summer;
he would then take the hatchet out of the head of the deceased, and bury it in the earth,
preparatory to the treaty.
Several kettles of rum and glasses were brought, and the conference closed.

"`19th, First-day.
Held a meeting for worship; a considerable number attended,
who lived generally from two to ten miles distant.
Many of them came on foot, there being but few horses in this country,
and fewer wheel-carriages of any kind.
One family came a considerable distance upon a sled drawn by four stout oxen.
The people were solid, and through Divine favor it proved a good meeting,
many were very tender and parted with us lovingly.
It does our hearts good to see the gratitude some of the poor frontier people manifest,
and the pains they take to be at a religious meeting.
O Philadelphians,
how abundant ought your gratitude to be for the enjoyment of your multiplied blessings.

"`Tenth month, 20th. Attended a very large Indian council,
at which the commissioner condoled with the
Delawares for the loss of one of their people,
and by his speech and gestures performed the
ceremony of burying him after the Indian custom,
and covering the grave with leaves,
so that when they passed by they should not see it any more.
He took the hatchet out of his head,
and in words tore up a large pine tree and buried the hatchet in the hole,
then covered it thick with stones and planted the pine tree on the top of it again,
so that it should never more be taken up.
He wiped the blood from their beds and the tears from their eyes,
and opened the path of peace,
which the Indians were requested to keep open at
one end and the United States at the other,
as long as the sun shone.
Many other things of the like nature he said to them,
after the figurative style of the natives,
that all might be cleared out of the way before the business of the treaty commenced.
In the course of his speaking on different subjects,
he gave them as many strings of wampum as were
thought to be worth near one hundred dollars.

"`The Farmer`'s Brother then spoke with great energy to his Indian brethren,
and they not being ready to answer Colonel Pickering`'s speech,
the council fire was covered and the rum brought in as usual.

"`Third-day, 21st. Jemima Wilkinson being come to this place last evening,
sent a message by two of her flock to James Emlen and myself, desiring our company;
but as it snowed very fast and was a stormy time,
we did not immediately obey the summons.
After an early dinner, David Bacon being with us,
we went and found her at Thomas Morris`'s,
by invitation of Colonel Pickering to dine with him; D. Waggoner,
and Enoch and Rachel Malin were also there.
The Colonel paid great attention to Jemima,
and seemed to be glad of having an opportunity to gratify his curiosity,
as he had never seen her before.
She was placed at the head of the table,
and the conversation being on a variety of subjects,
she bore a considerable part therein.
A message was received informing that the Indians were collected.
We went to council, where Jemima and her disciples followed us,
and were placed in the centre.
Fish Carrier spoke in answer to the commissioner`'s address yesterday,
till he had passed through his hands one by one, all the strings that were given them,
and made a full reply:
then with assurances of the determination of the Six Nations
to keep hold of the chain of friendship with the fifteen fires,
he delivered fifteen strings of chequered wampum as a seal to it.
Colonel Pickering introduced himself as sole
commissioner on the part of the United States,
whom the Six Nations had requested might be appointed on the present occasion;
gave them assurances of his desire to promote the happiness and peace of their nations,
and told them that they might depend upon one thing at least, which was,
that he never would deceive them.
He also introduced us, their old friends the Quakers,
as having come forward at their (the Indians`') request,
and with the approbation of the President.
We then read the address from Friends, Jasper Parrish interpreting,
which they received with frequent expressions of entaw or approbation;
and afterwards Clear Sky said, they were glad to see us among them,
and thanked us for our speech.
It is however expected that they will give us a
more full answer before the treaty is over.
Immediately after we had read our speech,
Jemima and all her company kneeled down and she uttered something in the form of prayer,
after which she desired to speak, and liberty not being refused,
she used many texts of Scripture, without much similarity or connection.
The Indians having prepared belts as records of
the death of several of their noted chiefs,
intended to preserve the memory of their usefulness to the nation;
a short speech was made on each of them to their brethren,
and they were then delivered to the care of an ancient chief,
whereupon the council fire was covered.

"`23rd. Captain John, an Indian chief, visited us,
and had much to say about the many deceptions which had
been practised upon them by the white people;
observing, that however good and honest white men might be in other matters,
they were all deceivers when they wanted to buy Indian lands;
and that the advantages of learning which they possessed,
made them capable of doing much good and much evil.

"`Colonel Pickering requesting our attendance at a council, we went about eleven o`'clock.
Nearly forty chiefs being assembled, Captain John, in a humorous manner,
informed the commissioner of a council they were called to attend;
but when the chiefs had collected,
they were invited up stairs to take a dram before they began.
Perceiving that Berry was to be the commissioner,
they concluded it was no good council fire,
so he came off and drew the rest of the Indians with him;
it appearing that it was a design to get the chiefs to convey to him some Indian lands,
after he should have filled them with liquor.
The colonel highly approved of the Indians`' conduct,
and said he would have Berry removed off those lands.
An account was brought to the council of the death of an ancient Oneida,
upon which Captain John made a speech to their brothers of the other nations.
They agreed that as the Great Spirit had brought
them together to promote the work of peace,
it could not be unacceptable to Him if they went on with the council,
though it was contrary to their common custom.
Being about to proceed to business, a request was made from three Indian women,
to be admitted to the council, and deliver their sentiments, which being granted,
they were introduced by Red Jacket.
He addressed himself to the sachems and warriors, desiring their indulgence of the women,
and also to the commissioner, enforcing their request by observing,
that the other day one of our women had liberty to speak in council.
He was then desired to act as orator for the women,
and deliver to the council what they had to say.
The substance of this was, that they felt a deep interest in the affairs of their nation,
and having heard the opinions of their sachems, they fully concurred in them,
that the white people had been the cause of all the Indians`' distresses;
that they had pressed and squeezed them together,
until it gave them great pain at their hearts,
and that the whites ought to give them back the lands they had taken from them.
That one of the white women had yesterday told the Indians to repent;
and they now called on the white people to repent,
for they had as much need as the Indians, and that they should wrong the Indians no more.

"`The colonel thanked them for the speech, and replied,
that it was far from him to think meanly of women:
he should always be willing to hear them when they had anything of importance to say,
but as they had mentioned as a precedent, the woman who spoke the other day,
he must assure them, that it was not with his approbation;
she had forced herself into council contrary to his advice; but as she was a woman,
he was tender of her.

"`The commissioner gave us some information of the speech of the Indians yesterday,
when we were not present.
They said, when the white people first came on this island, they saw that they were men,
and must have something to subsist upon, they therefore pitied them,
and gave them some land,
and when they complained that the land became too small for them, they gave them more,
from time to time, for they pitied them.
At length a great council fire was kindled at Albany, where a silver chain was made,
which was kept bright for many years,
till the United States and the great king over the water differed;
then their brothers in Canada talked with them,
and they let the chain fall out of their hands, yet it was not their fault,
it was the white people`'s. They then repeated how things went at the end of the war,
the substance of the treaty at Fort Stanwix,
and several grievances which they had suffered.
The commissioner spoke, perhaps two hours,
respecting the ancient boundaries of the Six Nations`' land,
and inquired what was the extent of it.
They told him, all the land from a point on Lake Erie to Muskingum was theirs,
and that the council at the Miami, last summer, acknowledged it.
This takes in a great part of what the Western Indians are fighting for.
The commissioner told them,
he did not approve of the conduct of the commissioners at Fort
Stanwix--that they had just then become conquerors,
and the Indians must make some allowances, if they spoke harshly and proudly to them.
This council held "`five hours, and much was said on both sides.

"`This morning, the 25th, snow was seven or eight inches deep,
and having been out in it yesterday, I was unwell.
Abundance of deer are killed by the Indians, perhaps not less than one hundred today,
within a few miles of this place, some in sight; one man killed three in a short time.
A man named Johnson, having arrived two days ago from Fort Erie,
with a message from Captain Brandt, a Mohawk chief, to the Six Nations,
assembled some chiefs yesterday and delivered it to them.
Being in the character of a British interpreter,
he appeared at the council with the Indians today, and seemed very intimate with them.
Cornplanter rose to vindicate his coming,
being privy to the great uneasiness it had given Colonel Pickering:
he expressed his surprise,
that ever since the conclusion of the peace with the British nation,
such an antipathy had existed,
that the United States and the British could not bear
to sit side by side in treaties held with the Indians.
He said, Johnson had the care of the Senecas at Buffalo-creek,
and had brought a message to the Six Nations assembled at this council fire, from Brandt,
whom he left with Governor Simcoe at Fort Erie;
they having just returned together from Detroit:
that when he went some time ago to see the Western Indians,
he sat in council with the Delawares, Shawnese, Wyandots and Miamies,
and the Western Indians expressed great joy at seeing
the Six Nations represented by him among them;
they told him he recollected that the business of the treaty last year did not go on,
but the fault was not theirs, it was that of other people,
and the Indians were led astray, for which they were sorry.
The misfortunes that had fallen upon them were very heavy, and our brothers the British,
who were sitting by, gave us no relief.
We allow you who are listening to us, to be the greatest,
we will therefore hear what you say.
We desire a council fire may be kindled next spring at Sandusky,
for all nations of Indians.
Captain Brandt sends his compliments to the chiefs at Canandaigua, and says,
you remember what we agreed on last year, and the line we then marked out:
If this line is complied with, peace will take place;
and he desires us to mention this at Canandaigua; after the council at Canada is over,
it Is my earnest desire you will immediately come to Buffalo-creek,
and bring General Chapin with you--I will wait here till you return.

"`Colonel Pickering rose and said,
he was sorry that anything should happen to interrupt this council fire:
but it is now interrupted by the coming of Johnson, whom he considered as a British spy,
and that his I fling here was an insult to him, to their friends the Quakers,
and to the fifteen fires.
That the intrusion of this man into our councils, betrayed great impudence,
and was a fresh proof of British insolence.
It was perhaps as well that there was no council yesterday,
for he could not say how far the first emotions of his mind at seeing this fellow here,
might have carried him; he hoped he was now a little cool,
and would endeavor to moderate his expressions as much as he was capable of.
He begged their patience,
for he must be obliged to say a great deal to inform them of many of
the reasons of his indignation at this step of the British government,
and why it was totally improper to go on with
the business while a British spy was present.
He then went into a very lengthy detail of the ill-
treatment of that government to the United States,
for several years past, and concluded with saying,
that either this man must immediately be sent back to those who sent him, or he,
Pickering, would cover up the council fire;
for his instructions from General Washington were,
to permit no British agents at the present treaty.

"`The Indians appeared in amazement at the warmth with
which the commissioner delivered himself,
and said, when he sat down, the council fire grows warm,
the sparks of it fly about very thick.
As to Johnson, he appeared like one that was condemned to die, and now rose and left us.
The Indians requesting we would withdraw, counselled among themselves about half an hour,
and sent for us again.
Cornplanter rose and said,
the reason why the council fire has not been uncovered today is,
because of a British man being present.
It was caused by us, we requested him to come here, it is true,
but the fault is in the white people.
I am very much surprised and deceived by what you told us at Fort Stanwix,
when you laid before us a paper which contained the terms of
peace agreed on between you and the English nation;
and told us it was agreed on in the presence of the Great Spirit,
and under his influence.
We now discover what the commissioners then told us was a lie,
when they said they had made the chain of friendship bright;
but I now find there has been an antipathy to each other ever since.
Now our sachems and warriors say, What shall we do?
we will shove Johnson off: Yet this is not agreeable to my mind,
for if I had kindled the council fire,
I would allow a very bad man to sit in it that he might be made better:
but if the peace you made had been a good peace,
all animosities would have been done away,
and you could then have sat side by side in council.
I have one request to make, which is,
that you would furnish him with provisions to carry him home.
The council having sat about five hours, adjourned till tomorrow.
We dined by candle light, with the commissioner and about fifteen chiefs,
among whom were Cornplanter, Red Jacket, Little Beard, Big Sky, Farmer`'s Brother,
Fish Carrier, Little Billy, etc.
Many repartees of the Indians, which Jones interpreted,
manifested a high turn for wit and humor.
Red Jacket has the most conspicuous talent that way;
he is a man of a pleasing countenance,
and one of the greatest orators amongst the Six Nations.

"`26th. First-day, several of our friends from parts adjacent came in,
expecting a meeting for worship, but the commissioner having called the council together,
Do meeting was held.
The council being assembled,
the first business was the presentation of a letter
which the Indians having got prepared since yesterday;
they thought proper for the commissioner to see it,
as they intended to send it by Johnson to Captain Brandt.
The contents of it were not altogether agreeable to the commissioner.
They expressed their sorrow that Johnson could not be permitted to stay,
the reasons for which, he would doubtless inform them when he got home.
It assured Brandt, they were determined to insist on the line agreed to last year,
and expressed the sense they now had, that they were a poor, despised,
though independent people,
and were brought into suffering by the two white nations striving who should be greatest.
The Indians appeared pretty high today,
and little was done but clearing up some misunderstanding respecting
the cause why the treaty was not held at Buffalo-creek,
agreeably to the Indians`' request--the disposition of the
Senecas appeared rather more uncompromising than heretofore.

"`27th. Expecting a council,
we went to the commissioner who was in private conference with some chiefs;
but he informed us he is now preparing the way for a furl and general council tomorrow,
when he will cut the business short by decidedly opening the proposals of accommodation:
this is agreeable news to us, who have been already much wearied with continual delays.
Colonel Butler of Niagara, had despatched a runner, a Tuscarora,
who brought intelligence of a late engagement between the
Western Indians connected with some British soldiers,
and General Wayne, fought near the forks of the Glaize,
in which many on both sides were killed; and being weary,
the combatants withdrew from the field of battle.
The Indians appear cautious of letting out the particulars,
probably from the fear that they may operate to their
disadvantage at this critical juncture of the treaty;
and the accounts being very various, nothing can be clearly ascertained.
Sagareesa, chief of the Tuscoraras, and several others of his nation,
spent most of the afternoon with us; a half-Indian who lives with them, interpreted,
and the conference was to satisfaction.
We endeavored to obtain a correct account of the numbers remaining in the Six Nations,
and find as follows: the Senecas number about nineteen hundred; the Tuscaroras,
three hundred; the Oneidas, six hundred; the Cayugas, four hundred; the Onondagoes,
five hundred; the Mohawks, eight hundred.
A considerable part of the Cayugas and Onondagoes,
have moved off their reservation and reside mostly with the Senecas and Tuscaroras,
but some of them have gone over the lake to the Mohawks, within the British territories.
By the best computation we can make, the number of acres that each nation still holds,
is as follows: The Senecas, about four millions of acres; the Oneidas,
two hundred and fifty-six thousand; the Cayugas, sixty-four thousand; the Onondagoes,
seventy thousand.
The Tuscaroras have no land of their own, but are settled near the Senecas on their lands.
The Stockbridge and Brotherton Indians, two small remnants,
have some land which was granted to them by the Oneidas and confirmed by government,
namely: Stockbridge, twenty-three thousand and forty acres; Brotherton,
thirty-eight thousand and forty acres.
The Brothertons are an assemblage of about one hundred and fifty Indians,
of various tribes from New England, settled near Brotherton on the Mohawk river.
The Mohawks are at the Grand river and the bay of Quinta,
on the North sides of Lake Erie and Lake Ontario, in the British government.

"`This evening Friends being quietly together,
our minds were seriously turned to consider the present state of these Six Nations;
and a lively prospect presented,
that a mode could be adopted by which Friends and other humane people might
be made useful to them in a greater degree than has ever yet been effected:
at least for the cause of humanity and justice, and for the sake of this poor,
declining people, we are induced to hope so.
The prospect and feelings of our minds were such as will not be forgotten,
if we are favored to return home.
The happy effects of steady perseverance in the cause of the Africans,
is an encouraging reflection, and may serve as an animating example in this.
Our business here, though trying and tedious,
is sometimes accompanied with an ample reward.

"`28th. Red Jacket visited us with his wife and five children,
whom he had brought to see us; they were exceedingly well clad in their manner,
and the best behaved and prettiest Indian children I have ever met with:
Jones came to interpret.
Red Jacket informed us of the views which the Indians had in inviting us to the treaty;
which Jones confirmed, being present at the council at Buffalo-creek; namely:
Believing that the Quakers were an honest people and friends to them,
they wished them to be present that they might see the
Indians were not deceived or imposed upon.

Yesterday many of the chiefs and warriors were very uneasy at
Cornplanter`'s frequent private interviews with the commissioner,
and Little Billy spoke roughly to him, told him he should consider who he was,
that he was only a war chief,
and it did not become him to be so forward as he appeared to be;
it was the business of the sachems, more than his, to conduct the treaty.
He told them he had exerted himself for several years,
and taken a great deal of pains for the good of the nation,
but if they had no further occasion for him, he would return home;
and he really intended it;
but Colonel Pickering and General Chapin interested themselves to detain him.
The dissatisfaction of the Senecas rose so high,
that it was doubtful whether a council would be obtained today,
but about three o`'clock they met; Cornplanter not attending.
The commissioner spoke,
and told them of the several conferences that had been held
with a number of the chiefs since last public council,
and what the substance of their business was.
He also told them he was sorry that they were
made uneasy at the conduct of their war chief,
but they ought not to blame him, for he, the commissioner,
had invited Cornplanter to his quarters, and therefore if there was any impropriety,
to blame him, for it was his fault.
This pacifying them, he then said the business of the treaty had been retarded so long,
that he was now determined to open to them, fully and candidly,
the terms upon which the chain of friendship would be brightened,
and the extent of what he intended to do towards it.
He produced his commission,
with full power to propose and adjust the accommodation
of all differences between them and the United States;
which he handed me to read.

"`After many observations upon former treaties, and the grant made by their old father,
the king, to William Penn, he opened the terms, which were as follows:
but in the first place, perhaps, as this is an important matter,
it will be most proper to take notice, that he acquainted the Indians now collected,
both chiefs and warriors, being more than at any council we have yet had,
that the chiefs had laid before him only two rusty places in the chain,
one of which he had already brightened,
the other was thought by their chief warrior to be very deep,
though the sachems thought it not of so great importance;
that in order to clean this rusty spot,
their chief warrior had proposed a new line between them and the United States,
to begin where the Alleghany crosses the north line of Pennsylvania,
from there to French creek below the forks of +++_______+++ creek;
from there to the forks of Muskingum; from there down the Muskingum to the Ohio.
This, he apprehended, would remove every cloud of difficulty.
He observed to them,
that the sachems had acknowledged it was now four years since he had been
brightening the chain of friendship between them and the United States,
and that it had been even as in the days of Sir William Johnson,
that the rusty part now alluded to had never before been complained of to him,
except by their elder brother, the Mohawk.
Colonel Pickering thought it was rather within the claim of the Western Indians;
and as they had, from time to time, acquiesced in the treaty of Fort Stanwix,
they might reasonably suppose that their conduct in relation to the
affair at Presque Isle must have given surprise to the President,
who, feeling a fatherly care for their nations, had required of the persons to desist,
who were about to form a settlement at that place; and had appointed him to inquire into,
and endeavor to adjust, the difference subsisting between them:
since which he had examined all former treaties, and reminded them,
that at the treaty of Fort Stanwix,
they had ceded all the lands within the bounds of Pennsylvania--that
many of them were acquainted with the charter granted by the king of
Great Britain to William Penn;
that at the last treaty held before the war, at Fort Stanwix, about twenty-six years ago,
they had received ten thousand dollars from Pennsylvania,
and had agreed that they would sell no lands within the said boundaries,
but to the proprietors of that (then) province.
That treaty at Fort Stanwix had been confirmed at Muskingum in 1786,
which was also acknowledged by the chiefs at Tioga;
at which last place complaint was made that Phelps had cheated them,
yet not a word of the former treaties.
He then had reference to the triangle on Lake Erie,
which Pennsylvania has purchased of Congress,
and showed them on the map that it was ceded by them to
the United States at the treaty of Fort Stanwix;
and for which the State of Pennsylvania paid them two
thousand dollars at the treaty of Muskingum,
in confirmation of the title.
Butler and Gibson, the commissioners at the last mentioned treaty,
expected the east line of the triangle would have extended to Buffalo-creek;
but that not being the case,
he offered to cede back to them all the land between
the triangle and a line running due south,
from near the mouth of the said creek to the Pennsylvania line,
which comprehends three or four times the quantity of land included in the triangle;
and that the new line might run thus: to begin at Johnson`'s landing-place,
about four miles distant from Niagara; from there along the inlet,
including a strip of land four miles wide,
till it comes within four miles of Buffalo-creek;
from there to said creek at one mile distant from the mouth of it;
from there along Lake Erie to the aforesaid triangle;
bounded on the west by the said triangle, and on the south by the Pennsylvania line.
The commissioner observed that the four mile path on the side of the inlet,
between Lake Erie and Lake Ontario, was ceded to our predecessors, the British,
in the days of Sir William Johnson; yet,
that the Indians shall have the right of hunting on these lands,
as well as on all those coded at the treaty of Fort Stanwix;
and on all other lands ceded by them since the peace;
and their settlements thereon shall remain undisturbed: and also,
that in addition to the annuity of fifteen hundred
dollars which had heretofore been paid to them,
the President had empowered him to add the sum of three thousand dollars more,
amounting in all to four thousand five hundred dollars, to be paid to them annually,
and to their posterity forever; for the providing of clothing,
encouragement of artificers, school-masters, etc., to settle among them.
He had also goods at this place to the amount of
ten thousand dollars to distribute Among them,
if the treaty should issue to mutual satisfaction.
In consequence of the liberal offers now made,
he hoped the Indians would cheerfully comply,
and join him in digging a deep pit to bury all former differences,
and take hold of the chain of friendship so fast,
that nothing should ever be able to force it out of their hands.
The Indians, after considering a few minutes what had been said,
concluded to take it into further consideration, and return an answer.

"`29th. Sagareesa, or the Sword-Carrier, visited us; he appears to be a thoughtful man,
and mentioned a desire he had,
that some of our young men might come among them as teachers;
we supposed he meant as schoolmasters and artisans.
Perhaps this intimation may be so made use of in a future day,
that great good may accrue to the poor Indians,
if some religious young men of our Society, could, from a sense of duty,
be induced to spend some time among them, either as schoolmasters or mechanics.
At eleven o`'clock, Colonel Pickering called and gave us an invitation to dinner;
Captain Hendricks, an Indian, and several strangers, dined with us; after which,
Robert Nealy came in, who had been taken prisoner about forty years ago,
being then about nine years old, and had continued with the Indians ever since,
without any desire of returning or making much inquiry after his parents.
Being entirely reconciled to the Indian life, he had taken several wives among them,
none of whom were dead; but whenever they grew dissatisfied with each other,
they parted and took others more agreeable, which, he said, was the general custom;
and when the Indians lost a near connection,
they were inconsolable till some of their friends made up a belt of wampum,
and gave it to the family of the deceased, in remembrance of their deceased relation;
after which, they betrayed no sorrow--a scalp from an enemy answered the same purpose,
if taken with that design.
Many of the Indian chiefs being drunk, no council was held today.

"`Fifth-day, 30th. A fine warm day, the Indians almost all turned out of their cabins;
some of the young warriors having good horses,
wore running races all day with the white people; others engaged in different sports,
dancing, etc., which is almost a daily exercise.
They performed one which they call the brag-dance; when,
whoever deposits a bottle of rum,
has the liberty to make a brag of the feats he has performed in war,
the number of scalps he has taken, etc.
A sensible man being present, after he had deposited his bottle,
and the others had boasted of many marvellous exploits, made his brag, which was,
that he had been a man of peace all his days, in the profession of a physician;
that he had been very industrious, and restored many who had been ready to die.
He said, all that the others had bragged of, was nothing to this,
for any child might kill a man,
but it required the judgment and wisdom of a great man to save another`'s life.
They all acknowledged the doctor`'s was the best of all.
The sachems and chiefs were engaged in council, by themselves, and sat till near night,
and inform that they will meet us in council tomorrow.
The interpreter says, parties rise high against Cornplanter,
that he is in a difficult situation with his nation,
and they are not able to conceive what he has done with
eight hundred dollars received in Philadelphia,
from the Pennsylvania government,
and what induced the government to give him fifteen hundred acres of land for a farm;
these things have created jealousies unfavorable to him.

"`There is a remarkable spring near this place, called the brimstone spring,
which is so strong, as to have deposited in its course a large quantity of sulphur.
Also, the salt springs of Onondago, which are said to be inexhaustible,
and all this country is supplied with salt made from the waters.

"`31st. Red Jacket, Clear Sky, Sagareesa, and a chief of the Cayugas,
waited on us at our lodgings,
being a deputation from the Indian council that has been deliberating
several days upon the proposals of the commissioner,
bringing with them the interpreter.
Several Indians and some white people being in the room with us,
they were desired to depart,
as the business they came about would not admit of their presence.
Apprehending that we should be interrupted in the house, we retired to a distance,
and sat down upon some logs, when Red Jacket spoke nearly as follows:

"`Brothers,--You see here four of us of the Six Nations, who are assembled at this place,
in the will of the Great Spirit, to transact the business of the treaty.
You have been waiting here a long time, and often visited by our chiefs,
and as yet no marks of respect have been shown you.

"`Brothers,--We are deputed by the council of chiefs assembled, to come and see you.
We understand that you told Sagareesa, that you should not have come, but at our request,
and that you stood ready to afford us any assistance in your power.

"`Brothers,--We hope you will make your minds easy.
We who are now here are but children; the ancients being deceased.
We know that your fathers and ours transacted business together,
and that you look up to the Great Spirit for his direction and assistance,
and take no part in war.
We expect you were all born on this island, and consider you as brethren.
Your ancestors came over the great water, and ours were born here;
this ought to be no impediment to our considering each other as brethren.

"`Brothers,--You all know the proposals that
have been made by Cunnitsutty (Colonel Pickering,
the commissioner), as well as the offers made by us to him.
We are all now in the presence of the Great Spirit, and we place more confidence in you,
than in any other people.
As you expressed your desire for peace,
we now desire your help and assistance--we hope you will not deceive us;
for if you should do so, we shall no more place any confidence in mankind.

"`Brothers,--We wish, if you know the will of Congress,
or the extent of the commissioner`'s powers, that you will candidly inform us.

"`Brothers,--We desire that what we are now about communicating, may be kept secret.
We are willing to give up the four-mile path,
from Johnson`'s landing place to Cayuga-creek,
agreeably to our compact with Sir William Johnson, long ago.
The other part proposed by Colonel Pickering to be relinquished by us; that is,
from Cayuga to Buffalo-creek, we wish to reserve on account of the fisheries;
that our women and children may have the use of it for that purpose.
We desire to know if you can inform us, why the triangle on Lake Erie cannot be given up.

"`Brothers,--Cornplanter and Captain Brandt, who were only war chiefs,
were the persons who attended the treaty at Fort Stanwix,
and they were to have sent forward the proposals for our more general consideration.
At that time Old Smoke was alive, who was a man of great understanding;
but they were threatened into a compliance,
in consequence of which Captain Brandt went off to Canada,
desiring Cornplanter to do the best he could.`"

"`They delivered us seven strings of wampum,
and we desired them to call on us about three o`'clock for an answer.
We felt it to be a weighty and delicate matter to answer their request in our situation.
They returned about the time fixed,
but finding us not entirely prepared to give them an answer,
told us not to hurry ourselves, and they would come tomorrow morning;
for they are never in haste.

"`Eleventh month, 1st. Our house was full of Indians and others all the morning.
About ten o`'clock, the interpreter and the four chiefs came for our answer;
we had endeavored to digest their request as well as we were capable of,
desirous of dealing honestly with the poor Indians and
of keeping a conscience void of offence.
My friends laid it upon me to deliver the answer, which I did,
holding the seven strings of wampum in my hand; and the reply being interpreted to them,
I returned the strings at the end of our speech according to the Indian custom.
Red Jacket went over the three points to which we had spoken,
to know whether he had perfectly understood us,
that he might deliver our sentiments to the greet council.
He thanked us for our advice, and said, though we might account it of small value,
they did not consider it so, but thought it would afford them considerable strength.

"`After dinner, John Parrish and myself rode to view the Farmer`'s Brother`'s encampment,
which contained about five hundred Indians.
They are located by the side of a brook, in the woods;
having built about seventy or eighty huts,
by far the most commodious and ingeniously made of any that I have seen;
the principal materials are bark and boughs of trees,
so nicely put together as to keep the family dry and warm.
The women as well as the men, appeared to be mostly employed.
In this camp, there are a large number of pretty children, who,
in all the activity and buoyancy of health,
were diverting themselves according to their fancy.
The vast number of deer they have killed, since coming here,
which they cut up and hang round their huts, inside and out, to dry,
together with the rations of beef which they draw daily,
give the appearance of plenty to supply the few needs to which they are subjected.
The ease and cheerfulness of every countenance, and the delightfulness of the afternoon,
which these inhabitants of the woods seemed to enjoy with a relish
far superior to those who are pent up in crowded and populous cities,
all combined to make this the most pleasant visit I have paid to Indians;
and induced me to believe,
that before they became acquainted with white people and were infected with their vices,
they must have been as happy a people as any in the world.
In returning to our quarters we passed by the Indian council,
where Red Jacket was displaying his oratory to his brother chiefs,
on the subject of Colonel Pickering`'s proposals.

"`Eleventh month, 2nd. Held a meeting for worship in the school-house;
a number of Friends residing in this part of the country, came in;
and a considerable body of Indians were in and about the house; several of whom,
as well as the white people of other societies, behaved well,
and it was thought to be a good meeting.
We went immediately after meeting to the council which had just assembled,
and was very numerously attended both by Indians and whites.
The business was introduced by Clear Sky, an Onondaga chief, in the following manner:
He expressed a hope that there would be no hard thoughts entertained,
on account of their having been several days deliberating on an answer;
the subject was of importance, and he wished his brethren to be preserved in unanimity.
Then Red Jacket being principal speaker, said,

"`Brothers,--We request that all the nations present
will attend to what we are about to deliver.
We are now convened on one of the days of the Great Spirit;
Then addressing Colonel Pickering:--

"`Brother,--You now represent the President of the United States,
and when you spoke to us, we considered it as the voice of the fifteen fires.
You desired that we would take the matter under our
deliberate consideration and consult each other well,
that where the chain was rusty, it might be brightened.
We took General Washington by the hand, and desired this council-fire,
that all the lines in dispute might be settled.

"`Brothers,--We told you before of the two rusty places on the chain,
which were also pointed out by the sachems.
Instead of complying with our request,
respecting the places where we told you the chain was rusty,
you offered to relinquish the land on Lake Erie,
eastward of the triangular piece sold by Congress to Pennsylvania,
and to retain the four-mile path between Cayuga and Buffalo-creek,
by which you expect to brighten the chain.

"`Brothers,--We thought you had a sharp file to take off the rust,
but we believe it must have been dull, or else you let it slip out of your hands.
With respect to the four-mile path, we are in need of it on account of the fisheries;
although we are but children, we are sharp-sighted,
and we see that you want that strip of land for a road,
that when you have vessels on the lakes, you may have harbors, etc.
But we wish, that in respect to that land, the treaty at Fort Stanwix may be broken.
You white people have increased very fast on this island,
which was given to us Indians by the Great Spirit; we are now become a small people,
and you are cutting off our lands, piece after piece--you are a very hard-hearted people,
seeking your own advantages.

"`Brothers,--We are tender-hearted,
and desirous of peace--you told us what you would give us for our land,
to brighten your end of the chain.
If you will relinquish the piece of land we have mentioned, our friendship will be strong.
You say you are not proud; neither are we.
Congress expects we are now settling the business with regularity;
we wish that both parties may have something to say in settling a peace.
At the time we requested a conference, we also requested that our friends, the Quakers,
should come forward, as they are promoters of peace,
and we wanted them to be witnesses to what took place; we wish to do nothing in private.
We have told you of the rusty part, which the file passed over without brightening it,
and we wish you to take up the file again, and rub it very hard; you told us,
if it would not do without, you would apply oil.

"`Brothers,--We the sachems, warriors and others, all depend on you; whatever is done,
we regard u final and permanent; we wish you to take it under consideration,
and give us an answer.

"`Colonel Pickering replied, If I understand you right,
your minds are easy excepting with respect to the strip of land between the two lakes.
He then recapitulated what Red Jacket had expressed,
which a the usual custom of the Indians in their answers;
reminding them why they decreased, and the white people increased,
and gave them advice in what manner they might increase also; observing,
that he did it as their friend, for he wished to see them rise and become a great people.
Here Red Jacket called out earnestly, in his language,
'`keep straight.`' The commissioner proceeded.

"`Brothers,--You say you are anxious for peace; so are the people of the United States,
anxious for peace with all the Indians on the whole island.
We do not speak it with our lips only, it is the language of our hearts.
You say, if we relinquish the four mile path from Cayuga to Buffalo-creek,
a lasting peace will take place.
The other day I gave you strong reasons why we could not give it up.
I told you, if I could not rub out the rusty spots, I would cover them over,
and I told you how I would cover this; alluding to the money offered as an equivalent.
You seem to be sensible that the United States
stand in need of a passage from lake to lake,
by land.
I therefore conclude, you would have no objection, if the land remains yours,
to our cutting a road, and if we do so, it will be very inconvenient,
unless we can have taverns to accommodate travellers, as the distance is great.
You know they have a road and accommodations on the opposite side of the river,
and as there can be no communication between the lakes, unless we have that privilege,
the United States will have the same necessity for a road on this side.

"`Brothers,--If you should travel it yourselves,
you would like to have a house to get a walking-staff; you justly observe,
the United States will want a harbor for their vessels on the lakes,
but they can have no benefit from a harbor,
unless they have the privilege of building houses and stores.
If this is all the difficulty between us,
I trust we shall not be long in coming to a conclusion.

"`Brothers,--When I came from Philadelphia,
it was not expected I would relinquish a hand`'s breadth of land;
but finding your villages on that part which I have offered to cede back,
I freely give it up.
I am growing impatient to conclude the business, and would be glad to know,
whether you will give me an answer, or take some time longer to consider of it.`"
As the Indians did not appear ready to give a final answer, he told them,
he observed it to be a tender point with them,
and proposed their taking it into consideration until tomorrow,
and that he wished to confer with some of the chiefs at his lodgings,
previous to their coming to council, which he thought would expedite the business.

"`It is a custom with the Indians, after the decease of one of their brethren,
to return to the donor any present which he had
received in his life-time as a mark of respect.
In conformity with this usage,
Red Jacket now returned to the commissioner a silver gorget,
belonging to one of their chiefs, who died last year,
which had been presented to him by the United States.
Farmer`'s Brother made a speech of condolence on the occasion,
and presented some strings of black wampum to the family of the deceased.
Clear Sky, then in a short speech, covered up the council fire.

"`3rd of the month.
Big Beard, Sonochle, Canundach, Canatounty, and a John Whitestripe, all Oneidas,
called at our lodgings.
Big Beard mentioned, that some Friends whom they had seen at New York,
requested them to make inquiry who were the original owners of the land about Hopewell,
and that if it could be ascertained,
it was probable a present would be made them by
the Friends who reside in that neighborhood.
He said, they had accordingly made the inquiry, and although, it was beyond a doubt,
that the original proprietors were incorporated with the Six Nations,
yet they were so mixed and intermarried among the different tribes,
that it would be difficult to point them out; they therefore apprehended,
it would be most equitable, to distribute it among the Six Nations at large.
No council was held today; a number of the chiefs being much intoxicated.
We were teased by them for liquor, and were, at last,
obliged to flee from their persecutions.

"`4th. Sagareesa and Captain William Printup, a chief and warrior of the Tuscaroras,
with an interpreter, visited us, to converse about the Hopewell lands,
appearing to have no doubt that the Tuscaroraa were the original proprietors.
Colonel Pickering came to our lodgings,
to read the proposed articles which were to conclude the treaty, the signing of which,
as witnesses, if we were called upon to do it, had, for several days,
been a subject of serious consideration with us.
We told him, on hearing what was proposed, that we apprehended for reasons given,
we could not be free to sign the treaty; which did not appear to be agreeable to him;
but we have not now to begin to learn to suffer at Indian treaties.
At two o`'clock, an Indian messenger from the council,
came to inform us they were assembled and waiting for us,
the Indians not being disposed to proceed in our absence: a great number were assembled,
and Red Jacket addressed the commissioner:

"`Brothers,--We, the sachems of the Six Nations, will now tell you our minds.
The business of the treaty is,
to brighten the chain of friendship between us and the fifteen fires.
We told you the other day,
it was but a very small piece which was the occasion of
the remaining rust in the chain of friendship.

"`Brothers,--Now we are conversing together, in order to make the chain bright.
When we told you what would give us satisfaction,
you proposed reserving the piece of land, between Cayuga and Buffalocreek,
for building houses, etc., but we apprehend, you would not only build houses, but towns.
You told us, these houses would be for the accommodation of travellers in winter,
as they cannot go by water in that season,
and that travellers would want a staff to help them along the road.
We have taken these matters into serious consideration.

"`Brothers,--We conclude that we do not understand this as the white people do;
if we consent to your proposals, we know it will injure us.
If these houses should be built,
they will tend to scatter us and make us fall in the streets, meaning,
by drinking to excess, instead of benefiting us: you want land to raise provisions, hay,
etc.; but as soon as the white people settle there, they would think the land theirs,
for this is the way of the white people.
You mentioned, that when you got possession of the garrisons,
you would want landing-places, stores, fields to plant on, etc.;
but we wish to be the sole owners of this land ourselves;
and when you settle with the British, the Great Spirit has made a road for you,
you can pass and repass by water; what you want to reserve is entirely in your own favor.

"`Brothers,--You told us, when you left Philadelphia,
it was not expected by the President you would release a foot of land.
We thank him for having left you at liberty to give up what you
please.--You have waited with patience at this council fire,
kindled by General Washington;
it is but a very small thing that keeps the chain from being brightened;
if you will consent to give up this small piece and have no houses on it,
the chain will be made bright.
As to harbors, the waters are between yon and the British; you must talk to them,
you are of the same color.
I see there are many of your people now here,
watching with their mouths open to take up this land: if you are a friend to us,
then disappoint them, our patience is spent; comply with our request; dismiss us,
and we will go home.
The commissioner then replied:

"`Brothers,--I wish your attention to a few words.--I thought you knew the
necessity the United States had for a road from Fort Schlosser to Buffalo-creek.
You appear sensible of it now, by referring to the road by water,
made by the Great Spirit;
you may see we can have no benefit of that without a passage by land.
You have forgotten what I said the other day,
respecting the treaty of Sir William Johnson,
by which he obtained a right to pass and repass through your country.
I then observed,
that what was granted to the King was transferred to the
United States by our treaty of peace with the British;
now since so small a piece is between us, to convince you that I am not difficult,
if you grant us but liberty to pass and repass, I will give up the rest.
You know there is a path already from Buffalo-creek to Niagara;
I only ask liberty to make a better path, to clear the stumps and logs out of the way.
I am sure, that about so small a matter you can make no difficulty;
I will sit down and wait your answer.
After a short space, Colonel Pickering observed,
he had forgot to inform them that the road should be opened
under the direction of the superintendent of the Six Nations,
Canadesago;
who would take care to have it done so as to be
as little injurious as possible to the Indians.

"`The sachems having consulted together about half an hour, Red Jacket replied:

"`General Washington, now listen;
we are going to brighten the chain of friendship
between the Six Nations and the Americans.
We thank you for complying with our request, in giving up the particular spot in dispute.
You mentioned that you wanted a road through our country; remember your old agreement,
that you were to pass along the lake by water;
we have made up our minds respecting your request to open a
road.`' Colonel Pickering writing what was said Red Jacket
would not proceed till he looked him in the face.

"`Brothers,--It costs the white people a great deal to make roads,
we wish not to put you to that great expense;
we don`'t want you to spend your money for that purpose.
We have a right understanding of your request,
and have agreed to grant you a road from Fort Schlosser to Buffalo-creek,
but not from Buffalo-creek down this way at all.
We have given you an answer; if, on considering it, you have any reply to make,
we will hear you.

"`Commissioner.--I confess, brothers, I expected you would have agreed to my proposal;
but as this is not the case, I will give it up,
only reserving the road from Fort Schlosser to Buffalo.
There has been a mutual condescension, which is the best way of settling business.
There are yet several matters to be attended to
before signing the articles of the treaty;
which I can best communicate to some of your chiefs,
as it would not be so convenient to discuss them among large numbers.
One matter is, how the goods and annuity had best be appropriated;
and as there are some bad people both amongst you and us,
it would be well to fix some modes of settling disputes,
when they arise between individuals of your nations and ours.
As soon as we have digested a plan, we will introduce it into the public council.
I therefore invite two sachems and two warriors of the Senecas,
and a sachem and a warrior of each of the other nations,
to take an early breakfast with me tomorrow morning.
I now cover the council fire.

"`5th of Eleventh month.
No council today--Colonel Pickering and some
chiefs busy in preparing the articles of treaty.

"`6th. An interpreter, with four other Indians,
came to have further conversation about the Hopewell land.
It does not appear probable, that the Conestogoes were the original owners.
We requested them to convene some sensible chiefs of each nation,
and we would meet them at General Chapin`'s, with a map of the United States,
and endeavor to settle the matter, if possible.
General Chapin is of opinion,
that the Tuscaroras are the original owners of the Virginia land.
No council in public, Colonel Pickering being engaged all day,
in conference on the articles of treaty;
new objections and dissatisfaction were started by several principal chiefs,
who are unwilling to relinquish Presque Isle.
They were surprised to find that Cornplanter, Little Billy, and others,
had received two thousand dollars worth of goods from Pennsylvania at Muskingum,
and two thousand dollars at Philadelphia.
Their minds being much disturbed, they broke up the conference;
this was a sad disappointment to us, who expected that all would be amicably settled,
and we should set off tomorrow.
General Chapin says, he hopes all will come right again,
but the Indians must have time to cool.
It is to no purpose to say you are tired of waiting, they will only tell you very calmly,
"`Brother, you have your way of doing business, and we have ours;
we desire you would sit easy on your seats.`"
Patience then becomes our only remedy.

"`7th. No business today; many of the chiefs being drunk.
Colonel Pickering spent the afternoon with us.
The idea he entertains respecting the lands ceded at Fort Stanwix, is,
that as the Indians did the United States a great deal of
injury by taking part with the British in the late war,
it was strictly just that they should make compensation by
giving up the lands which they relinquished at that time.
He instanced the case of an individual who had committed a trespass on another;
the law determines that the trespasser shall suffer either in person or property,
and this law is just.
Such is the reasoning of conquerors.

"`8th. The Indians were sober today.
General Chapin and the commissioner have determined to give them no more liquor,
until the treaty is over.
The chiefs and warriors were engaged till three o`'clock with the commissioner,
and agreed on all the articles of treaty to be engrossed on parchment,
and signed tomorrow.
At four o`'clock, we met Cornplanter, Red Jacket, Scanadoe, Nicholas, a Tuscarora,
Twenty Canoes, two ancient Conestogoes, Captain Printup, Sagareesu, Myers Paterson,
a half white man who lives with the Tuscaroras,
and several other chiefs at General Chapin`'s, to determine about the Hopewell land;
examined maps and conversed with them on the subject, which resulted in the opinion,
that the Conestogoes should quit claim to it; it appearing to those present,
that the original right was in the Tuscaroras; one of whom, an ancient man,
put his finger on the place in the map, saying, he had papers at home that would,
as he thought, confirm their claim to it.
We desired him to send them to General Chapin to examine,
and if he thought they contained anything worth notice,
he might forward them to us in Philadelphia.

"`First-day, the 9th. Several Friends in this part of the country came to the meeting;
one of them thirteen miles.
A number of other white people attended, and a large number of Indians.
It was a solid meeting; several, both of whites and Indians, were tender, and wept;
and after it was over, one man in a particular manner, confessed to the truth,
and prayed that the Lord might bless it to all who were present.
On my part, it was an affectionate farewell to the people hereaway.
We returned to our lodgings, and before we had finished our dinner,
a messenger came to inform us that the council was gathered, and waiting,
which we immediately attended.
Two large parchments, with the articles of the treaty engrossed, being ready for signing,
we were in hopes the business would now close; but to our surprise and disappointment,
we soon discovered some dissatisfaction among the Indians,
by their putting their heads down together and whispering.
After waiting impatiently for about an hour, not knowing what it meant,
Cornplanter rose and spoke, as follows:

"`Brothers,--I request your attention, while I inform you of my own mind as an individual.
I consider the conduct of the United States, since the war, to have been very bad.
I conceive they do not do justice.
I will mention what took place at New York at one particular time.
After the treaty of Fort Stanwix, I went to New York under an apprehension,
that the commissioners had not done right;
and I laid before Congress our grievances on
account of the loss of our lands at that treaty;
but the thirteen fires approved of what the commissioners had done,
and in confirmation of it, they held up the paper, with a piece of silver hanging to it;
(the treaty with the British.) Now, Colonel Pickering, you have told us at this treaty,
that what was given up by the British, was only the land around the forts.
I am very much dissatisfied that this was not communicated to us before.
There has already been too much blood spilt;
if this had been known at the close of the war,
it would have prevented any blood being shed.
I have, therefore, told our warriors not to sign this treaty.
The fifteen fires have deceived us; we are under the sachems,
and will listen to what they do.
Though we will not sign it, yet we shall abide by what they do, as long as they do right.
The United States and the Six Nations are now making a firm peace,
and we wish the fifteen fires may never deceive them, as they have done us warriors;
if they once deceive the sachems, it will be bad.
He then took his seat, and after a short pause, said,
I will put a patch upon what I have spoken;
I hope you will have no uneasiness at hearing the voice of the warriors;
you know it is very hard to be once deceived, so you must not make your minds uneasy.
Eel, the herald, then made a warm speech to the Indians,
exhorting them to abide by the decision of the sachems,
which was received with loud shouts of applause.
Entaw!
Entaw!
Entaw!

"`Colonel Pickering then addressed them as follows:
"`Brothers of the Six Nations and your associates,--I confess
I am greatly surprised at the speech of your head warrior,
after all the pains I have taken to make the articles of the treaty easy.
I endeavored to please both sachems and warriors,
they were both present when the articles were agreed on,
and there was not a word of objection.

"`Brothers,--The design of this treaty is, to bury all differences;
you know I candidly and explicitly disapproved of the
conduct of the commissioners at Fort Stanwix,
but as this treaty was to establish a firm friendship
between the Six Nations and the United States,
I did not wish to bring former transactions into view,
which was also the desire of your chief warrior;
now he brings up the old matters to make a division in your councils.

"`Brothers,--I wish for calmness and deliberation,
iis the subject is of importance to us, and of the utmost importance to you.
He expresses his dissatisfaction that our treaty
with the British was not explained before;
but this was done last year to the Western Indians,
when many of the Six Nations were present; I think many of the chiefs must remember it.
I will explain it again to prevent mistakes.
A certain line was drawn between the British and us;
what the British had obtained of the Indians on our side of that line before the peace,
was transferred by that treaty to the United States:
it was agreed that the British should not interfere
with the land on this side of that line,
nor were we to interfere with the land on their side of the line,

"`Brothers,--I am very sorry that these objections are
made now when we are just about to sign the treaty.
The chief warrior has called it the treaty of the sachems, and said,
that they only were to sign it; but the warriors, as well as the sachems,
were present when it was agreed on, and made no objection to it.
He says, they will abide by what the sachems do, as long as they do right.
Does he mean they will abide by them no longer than the warriors think them right?
If this be the case, we may as well let things remain as they are.
He says also, the United States and the sachems are now making a firm peace,
but I cannot consider it so, unless the sachems and warriors unite;
for unless this is the case, it will cause divisions among yourselves;
consider whether this will not be attended with dangerous consequences.
He speaks of the United States deceiving the sachems; as I represent the United States,
I have told you I will not deceive you;
I can add nothing on that head to what I have told you already.

"`Brothers,--I cannot consent to close the business in this manner,
after so much care and pains have been taken to make all things easy;
but wish you to consider of it until tomorrow, and give me an answer.
If the warriors expect to live in peace with the United States, as well as the sachems;
if they desire to brighten the chain of friendship;
if they wish to act for the advantage of themselves and their children,
I am sure they will sign this treaty.`"
Cornplanter then addressed the warriors in a short speech,
desiring they might be firm and steady to what they had agreed on.

"`10th. The warriors of the Six Nations met in council in the forenoon,
to consult respecting signing the articles, and came to a judgment.
In the afternoon they met again, expecting the commissioner and the sachems;
but several of the principal sachems being intoxicated, did not come,
so nothing was done.
A number of the chiefs and warriors of the Tuscaroras
came to pay us a visit respecting the Hopewell land.
Captain Printup spoke for them as follows:

"`Brothers,--We believe it was from motives of benevolence and good-will to us,
that you were induced to make inquiry after the original owners of some land in Virginia.

"`Brothers,--You have now found them,
and as you are a people that look up to the Great Spirit for direction,
we hope you will now make us some compensation:
we are in hopes the business may be accomplished at this time.

"`Brothers,--As the Friends on the land have long received the benefit of its produce,
and live at so great a distance,
it would be much more convenient to receive what they please to give, at one time,
than to have a small sum paid yearly.
We have been given to understand,
that whenever the former owners of the land could be discovered,
Friends stood ready to make them some compensation;
as we apprehend this has been sufficiently ascertained,
we are thankful to the Great Spirit,
that there is now a probability of receiving
something for the inheritance of our ancestors.

"`By the above speech, we found they had still some mistaken ideas,
which we endeavored to remove, by again stating to them the true reason of the inquiry,
and informing them we should represent to our brethren at home,
what now appeared to us to be the state of the case, as soon as we conveniently could.
This satisfied them,
and they requested to sign their names to General Chapin`'s testimony,
which most of them did in their usual manner.^
footnote:[Some time after, a number of these Indians came to Philadelphia,
for the purpose of examining more fully into the validity of
their claims to be the original proprietors of these lands.
Friends were very desirous of making a full compensation to
the natives for any lands on which they had settled;
and accordingly great pains were taken to adjust this business.
But, after a close investigation of all the circumstances,
and an examination of ancient maps and documents, by both Friends and Indians jointly,
it did not appear that the Tuscaroras had ever
been the possessors of the soil in question.
Yet as they had entertained strong expectations of receiving a donation,
rather than disappoint them, Friends raised a considerable sum of money,
and gave it as a present to them, with which they were highly gratified.]

"`11th. Had much conversation with several of the Indian chiefs.
In the afternoon, at two o`'clock, we were sent for to council,
where a great number were assembled.
The Eel, an Onondaga chief, spoke to the Indians in a pathetic manner;
which we understood to be an exhortation to unanimity
among the chiefs and warriors in closing the business.
Colonel Pickering then held up the two parchments containing the articles of the treaty,
and asked if we should proceed, which they assenting to,
he told them he would give one of the parchments to one of their friends to examine,
while he read the other.
I accordingly examined one, and informed them they were word for word alike.
They then agreed to sign, and pointed out the two head warriors, who,
though they were young men, were by some custom in their nation,
the persons who were to stand foremost in ratifying contracts; they signed,
and then the chiefs and warriors, some of the most eminent in each nation,
being in all upwards of fifty.

"`After the articles were signed, we desired Farmer`'s Brother and Cornplanter,
to collect as many chiefs of the different nations as they thought proper,
to go down to our lodgings; the interpreter was also requested to come with them:
accordingly, about forty came.
We smoked and conversed with them freely, on several subjects relating to their welfare,
gave them further information of our principles,
and expressed our good wishes for their prosperity.
We then hd our presents brought and spread upon two tables.
They did not choose to divide them themselves, but left it to the interpreter;
which being done, they were much pleased and satisfied with the division,
and the articles were very agreeable to them.
They soon after retired, informing us of their desire to see us tomorrow morning,
as they had something further to communicate.

"`12th. About thirty or forty of the sachems and chief warriors met at our lodgings,
and delivered the following speech, by Farmer`'s Brother, the chief sachem.

"`Brothers, the Quakers from Philadelphia!
I wish you would attend to what we who are now present are about to say.
We speak as one.

"`Brothers,--Yesterday,
after receiving your invitation to come and partake of your presents,
we agreed to meet here this morning to speak a few words, which we will now do.

"`Brothers,--We are very glad you have lengthened out your patience
to see the end of the business which is now brought to a close.
We thank the Great Spirit that he has preserved you in health,
from the time you left your seats +++[+++homes], until you arrived here,
and has continued to preserve you to this time.
We put you under the protection of the same Good Spirit on your return,
and shall be very happy to hear that you get safe home;
and hope you may find your friends and families well on your return:
it would be very acceptable to be informed of this, by letter to the chiefs now present.

"`Brothers,--We give hearty thanks to the descendants of Onas +++[+++William Penn],
that you so willingly rose from your seats to attend
this council fire according to our request;
here are the articles of treaty for you to look over,
in order to impress them on your minds,
that you may tell them to your brothers who are sitting on their seats at home.

"`Brothers,--You have attended this treaty a long time;
the articles which we have now signed, we hope you fully understand.
Now, as we have shown them to you, we would wish to know your opinion,
whether we have made a good peace or not; as we cannot read,
we are liable to be deceived; you have no doubt considered them;
we want to know your minds, whether there is any flaw or catch in them,
which may hereafter occasion uneasiness.

"`Brothers,--If you think that peace is now established on a good foundation,
we wish you would come forward and sign the articles:
as you are a people who are desirous of promoting peace,
and these writings are for that purpose, we hope you will have no objection,
but all come forward and put your names to them,
and this would he a great satisfaction to us.`"

Immediately after this speech, the treaty being concluded,
and the council having broken up, our friends took their leave and set out for home.
The following memorandum is the first which occurs respecting the journey:

"`13th. Rose at three o`'clock in the morning,
after a very poor night`'s rest in a cold open hut,
where it snowed in upon us as we laid.
The weather was very cold and the roads exceedingly had;
we had an uncomfortable ride of four hours,
during which John Parrish had his face bruised by a fall;
and such was the difficulty in part of the road,
that it appeared as though we travelled at the risk of our lives.
We at length arrived at a public house at the head of Canandaigua lake, thirteen miles,
where we got breakfast and refitted.
We then rode on seven miles, and put up for the night,
there being no stage ahead for twenty-two miles.

"`14th. Rose early and pursued our journey through bushes, swamps, and deep mud-holes;
the road so bad that, with hard pushing, we could make but three miles an hour.
In about three and a half hours,
we found the remains of a fire where some travellers had fed yesterday,
which was a pleasant sight; and having some oats with us,
we fed our horses and breakfasted upon hoe-cake, dried meat, and cheese.
We felt like poor, forlorn pilgrims, and mounted our horses again,
the path being as bad as it could be;
and the snow falling on us continually in passing among the bushes,
it made the travelling truly hard.
As it continued snowing very fast,
and there being but one house to stop at between Bath and the Painted Post,
we accepted the kind invitation of Captain
Williamson to lodge with him at the former place.
He is a very polite man, had been many years in the British service,
and entertained us elegantly; a great contrast to our last night`'s fare.

"`15th. By daylight we left Bath, it still continuing to snow very fast.
A most trying time it was to us,
but in about two hours we reached a house where they were able to give us some breakfast,
which was refreshing.
We arrived at the Painted Post about one o`'clock, got some corn for our horses,
and eat our bread and cheese; after which we rode eleven miles,
crossing the Tioga several times, and arrived at the widow Lindley`'s,
who kindly invited us to stay at her house, where we were entertained very hospitably.

"`16th. After breakfast went for our horses,
but the family were so friendly they would not receive any pay for their keeping.
We crossed the Tioga twice more,
and found the road so exceedingly fatiguing and the day unpleasant,
that we rode only about two and a half miles an hour,
and arrived at an ordinary about three o`'clock in the afternoon.
There being no house for about twenty-four miles ahead,
we were under the necessity of lodging in a poor hovel, where there were already a man,
his wife, and seven children.
We laid our blankets on a bark floor, and endeavored to get some rest,
but the cold pinched as to such a degree, that we had but little repose.
We were all affected with an addition to our colds; this is hard travelling and living,
and it is a mercy that we are preserved as well as we are.

"`17th. Rose between two and three o`'clock, intending to make forty-two miles,
as there is but one miserable house in the intermediate distance,
which we desired not to lodge at, but disappointments and vexations are to be ours,
and no doubt they are good for us.
The depth of the snow, which was continually balling under our horses`' feet,
and the excessive badness of the path,
it being little else but a continued succession of mud-holes, roots, and stones,
rendered our hopes of getting through quite abortive;
and from necessity we had to stop at the Block-house.
Our horses had to stand out all night without hay, which gave us the most concern;
as for ourselves, we procured a tolerable supper, and taking our lodging upon the floor,
got some sleep.
There being no chimney to the house, occasioned them to have but little roof,
that the smoke might have sufficient vent to pass off,
which gave us a pleasing view of the brilliancy of the stars,
it being the first clear night since we left Canandaigua.

"`18th. Rising very early, we rode over the Alleghany mountain,
which was covered with snow about ten inches deep.
There were abundance of tracks of deer, bear, wild cats, white rabbits, etc.
Near the top, a great bear raised up from the side of a log and frightened our horses.
We fed our horses,
and after eating some biscuit and dried beef at the foot of the mountain,
proceeded on our journey, getting to the widow Harris`'s to lodge that night.`"

A few days after this, they were permitted to reach home in safety and good health.
In closing the report of their proceedings,
they remark in substance--that during a sojourn of seven weeks with the Indians,
they bad frequent opportunities of observing with sorrow the melancholy and
demoralizing effects resulting from the supply of ardent spirits furnished them by
the whites--that the difficulties and hardships to which those poor people,
once a free and independent nation, are now subjected,
appeared to them loudly to claim the sympathies of Friends and others,
who have grown opulent in a land which was their former inheritance,
and that they believed a mode might be devised of promoting their comfort,
and rendering them more essential benefits than any which had yet been adopted.
They likewise remark that the engagement was one
involving trials of a peculiar and painful nature,
yet they had reason to hope that the objects
they had in view were in good degree answered,
and that they were thankful in being permitted to return with the reward of peace.

As the articles of the treaty confirmed the right of the United
States to large tracts of land which had been obtained by conquest,
without making the Indians what Friends deemed an adequate and just compensation for it,
they could not consent to the requests so frequently made to sign the treaty.

Soon after reaching home, this diligent laborer in the cause of his Lord and Master,
believed himself called to attend the Yearly Meeting of Friends in Virginia,
and some of the meetings composing it.
His esteemed friend, Thomas Stewardson, kindly consented to bear him company,
and they set out to perform the service in the Fifth month, 1795.
From some brief memoranda which he made, the following account of the journey is taken:

"`Left Philadelphia on Fifth-day morning, and rode hard in the heat to reach Elkton,
forty-eight miles; arrived about eight o`'clock, much fatigued.

"`8th. Got off by sunrise: the day was very hot,
but with diligent travelling we arrived at Baltimore, fifty-four miles.
Leaving this city in the morning, we got to dear Evan Thomas`'s to lodge,
being mutually glad to see each other.
On First-day, the 10th, accompanied by several Friends, we set off for Georgetown.
In our way, rode through the Federal city, then only in its incipient state,
but fast advancing, both as to buildings and population.
At Georgetown we put op at an inn; sent for doctor Thornton, and others,
to procure a meeting at three o`'clock in the afternoon.
He used great exertions, and the inhabitants being generally notified,
the meeting was held in a large new school-house.
It was much too small to contain the people, which at first made them somewhat uneasy,
but more stillness and composure taking place, the meeting was held to satisfaction.
Crossing the Potomac, we rode to Alexandria, and lodged.

"`Second-day, the 11th. It rained and thundered very much in the morning.
I however visited several Friends, and the weather becoming more favorable,
we went to Occoquan to dine, and reached Dumfries to lodge.
The house being full of Virginians attending the court; they were not a little noisy.

"`12th. Got to Fredericksburg to dinner, and from there to Bowling Green, and lodged,
being fifty miles, and the day very hot.

"`13th. Travelled very diligently, and made fifty-two miles today.
Having imprudently drunk cold water when very warm, I became considerably unwell.

"`14th. Expecting the Quarterly Meeting to be at White Oak Swamp,
we rode there after breakfast, but were disappointed, as no Friends had assembled.
We then went on, and soon met several Friends going to Wain Oak,
the Quarterly Meeting being held there, whose company we joined.
The Quarterly Meeting was a good one.

"`16th. Meeting for Sufferings was held,
after which we went to the meeting of ministers
and elders at three o`'clock in the afternoon.

"`First-day, the 17th. The morning meeting very large,
almost as many out of doors as within, and a favored time;
that in the afternoon was also large, and a mixed congregation, as in the morning,
and it was hoped was a profitable season.

"`18th. Meeting for worship was large, attended by many not Friends; it proved a hard,
laborious time, and a number of appearances in the ministry; after which,
the business began, and was well conducted.
Lodged at James Ladd`'s, with upwards of forty Friends.

"`19th. The meeting, today, was a solid refreshing time:
Richard Jordan`'s service was very acceptable, and I hope useful.

"`20th. Feeling a freedom to propose that the women and men should sit together,
before they proceeded to business; the shutters were opened,
and there was some service to satisfaction; then went to business, in which,
I thought Friends were favored.
About four o`'clock, the Yearly Meeting closed, and we returned to James Ladd`'s.

"`21st. A meeting being appointed at Black-creek, a number of Friends accompanying me,
with our valued Friend, Richard Jordan, of North Carolina,
we reached the widow Ellison`'s, where we waited until meeting time.
The company was large, considering the time for giving notice: many gay people attended,
and it was thought to be a favored meeting.
Richard Jordan was large in testimony, and in supplication.

"`23rd. Rode to Richmond.
E+++.+++ Maule and his brother have built a mill on the side of the canal,
and for the privilege of the water pay four hundred dollars a year.
This canal is an astonishing work, about twenty feet wide, dug through a solid rock;
in many places twenty-five feet deep on the upper side of the hill.
It runs about forty-five feet above the level of James river.

"`First-day, 24th. Arose with much fear and concern upon my mind,
lest truth should suffer by our having a meeting among a gay and libertine people,
many of them much hurt by Paine`'s '`Age of Reason,`'
which has been abundantly spread in Virginia.
How ever, at entering the capitol,
where Friends had almost universally been exceedingly tried in their labors,
I was favored with great composure.
My friend Richard Jordan opened the service, which was, to all appearance,
satisfactory and well received by the people.
Immediately after he sat down,
the way was clearly opened for me to stand up with the words,
'`Verily there is a reward for the righteous;
Verily He is a God that judges in the earth;`' to illustrate and enforce which,
the Lord was pleased to grant me both matter and
utterance to my own astonishment and thankfulness.
It proved such a time as I think I never experienced more than
once or twice in all my labor in the cause of truth.
A very numerous,
crowded audience were exceedingly still and attentive for about one hour and a half;
when,
though I did believe I felt sufficient matter
and concern to have supported me some hours,
as well as the closest attention in the audience, yet I thought it expedient to close;
with great thankfulness to our gracious Helper, who had been so marvellously with us.
Friends who were present from most of the meetings within thirty miles, said,
the truths of revelation rose triumphant over Deism and error,
and were never more cordially received in that place.
The Methodist minister having appointed to preach at Manchester at four o`'clock,
the time set by Friends for our meeting, we did not go to the meeting-house until five,
when his meeting being over, we took possession of the house,
and had a very large audience, many from Richmond.
The general tenor of my labor was much the same as in the morning.
This was also a solid and comfortable meeting.
Returned to Richmond, and went to bed, rejoicing that truth had triumphed today.`"

The account breaks off here, and the notes of his further service in this journey,
if he kept any, hare been lost.
From his companion we learn that on the 25th, they went to Goochland and held a meeting;
from there to Cedar-creek, and taking one or two meetings in their way,
reached home on the 4th of the Sixth month.
