== Chapter IV.

[.chapter-synopsis]
* Magdeburg
* Halberstadt
* Journey continued
* Reach Pyrmont
* Religious Meetings
* Again leave Pyrmont
* Rinteln
* Reconciliation between separated Friends
* Minden
* Uncourteous treatment at Ufeln
* Trials at Bilefield
* Lemgo
* Bad roads
* Return to Hanover
* Various religious services
* Leave for Amsterdam
* Disasters on the road
* Revisit Minden
* Religious Meetings
* Counsellor Borges and Consistoriul Rath
* Osnaburg
* Impositions upon travelers
* Bentheim
* Deventer
* Amsterdam
* Friends in Amsterdam
* Hague
* Rotterdam
* Religious reflections
* Meetings with the inhabitants
* Voyage to Sluys
* Proceed to Dunkirk
* Markets, etc.
* Journey to Paris
* Thomas Paine
* Irreligion in the city
* Journey to Congenies
* Origin and character of Friends at Congenies
* Religious services
* Minutes made in former years
* Affecting parting
* Journey renewed
* Gilles
* Character of the people and country
* Professors with Friends--Leaves Congenies

"`Seventh-day, 22nd. Reached Magdeburg before night;
the innkeeper and servants received us again with gladness.
The reason of our return to this city was to show ourselves to the school-master,
who had endeavored to do us much harm in Berlin, by his letter to Herman;
and generally to defend our principles, if he had spread anything to our prejudice.
We therefore desired he might be informed that we were returned,
and ready to answer for ourselves to him or any who
were willing to meet us with the Bible in their hands;
we also desired our being here again might be spread among our religious brethren.
Two religions men came to see us, whom we had not seen when here before;
one of them was full of the necessity of the supper, but yet in a loving frame of mind;
and though he endeavored to defend his doctrine,
he found himself more deficient than he had contemplated;--the other appeared to be
a solid man and in good measure united with Friends in principle.

"`First-day, 23rd. One of the men who was with us yesterday,
came with one of his friends, and attended our little meeting;
and something being said to them by way of ministry, they received it kindly.
In the afternoon, one of those men who had been deceived by the magician, came to see us,
and was glad in being released from the impositions of that person.
It appears that the poor Magdeburgers have often been deceived
by persons professing to have the philosopher`'s stone.
A meeting of a company of serious persons,
different from those we had been with when here before,
was to be at four o`'clock this afternoon; and though they invited us,
we felt some objection to going among them in the time of their singing;
they therefore concluded that we should come near five, when their service might be over.
We accordingly went, and found about fifty men and women;
one of them asked if we would be easy until he read two
letters from some religious people who lived near the Rhine,
at the seat of war;
they were very affecting accounts of the sufferings of the people by the French,
particularly at their taking possession of a city where one of the persons lived.
Being gathered into silence, the meeting opened by prayer;
after which considerable was said in the ministry.
The people were generally quiet, and several much tendered, though it was evident,
by the conduct of some of their principal men when we went in,
that their minds had been somewhat prejudiced,
and that they were not pleased with our keeping on our hats;
yet through renewed mercy Truth prevailed, and we parted in a tender affectionate manner,
with their prayers and good wishes for us.

"`24th. Left Magdeburg,
and not finding a convenient house for our accommodation in the town where we stopped,
were compelled to proceed to Halberstadt, where we put up at a poor inn.
Our landlord`'s son, a sensible agreeable young man, soon became acquainted with us,
being bred up for a minister.
He said he was sorry that he was destined for that station,
and would rather do anything for a living than to take orders,
because he did not think he was called to it.

"`25th. Two religious men came to see us,
who belonged to a little company that held conferences on
religious subjects with a view to each other`'s edification.
We proposed seeing them together this evening, which they gladly assented to;
one of them, whose name was Kein, took me to his house and was very kind.

"`Halberstadt is a very ancient town, and the houses are built in a singular manner.
It appears to have but little trade, and few of the inhabitants are rich;
it contains about two thousand houses,
has seven Roman Catholic cloisters for nuns and friars,
and the places of worship are very ancient; one is said to be eight hundred years old.
We went to Kein`'s house, and found but about ten persons gathered;
the service in general was close and searching,
and not so much openness felt as at some other places; yet some were tender;
on the Whole we were relieved by the opportunity,
and believe it will be blessed to some of them.
We afterwards heard there was a deist present, who appeared touched with the doctrines,
said he had never heard such before, and hoped he should improve by them.
Kein, and the young man educated for a priest, coming to our inn,
some suitable remarks were made to them, to which they assented.
The young man thought it an unhappiness that he had not
been brought up to some other means of getting a living;
said there was a great falling away from the primitive church;
that the priests were very mercenary,
and that he could not bear the thought of their
exacting money from the poorest class of the people,
when they took the sacrament, so called, which was the practice of most of them.
We gave him Barclay`'s Apology in Latin,
and are in hopes that oar observations will not be lost upon him.

"`26th. The young priest and a lad came to tale leave of us,
and at parting embraced us affectionately;
the family also all manifested their love for us on parting.
We passed through a fine country, thickly set with villages and large towns,
among which was Wolfenbuttle.
The people tell some extraordinary stories respecting what occurred to Luther,
while he was writing some of his works there.
We arrived before dark at Brunswick, being forty miles.
Doctor Neimire and Simon Lobenstine came and spent an hour with us,
and mentioning to them our thought of having a meeting before we left the town,
they cheerfully undertook to open the way for it.

"`27th. Finding that although the doctor had offered his house for the meeting,
yet from some cause had again declined it; but another person, a serious man,
opening his house cheerfully, we went there and found a small room full of men and women,
being such as met at times privately for the improvement of each other.
Our gracious Helper being near, it was an open satisfactory meeting;
they did not seem restless in the time of silence,
but were solid and attentive to what was offered.
Several were very tender, and after being with them nearly three hours,
they seemed reluctant to part, and embraced us affectionately.

"`28th. Our kind friend who had given up his house for our meeting,
came by sunrise with his wife to bid us farewell,
remarking they had wept together last night after we left them,
in considering how we had left all for Christ`'s sake,
and were travelling at our own expense, and they knew not how to administer to us,
though they felt willing according to their little ability.
This morning, however,
they thought they could not be easy without bringing us
some sausage of the woman`'s own making,
to the value of about half a dollar, as a token of their good-will;
it was made in such manner as to be eaten without warming,
and was very agreeable to take in our wagon.
There was something so simple-hearted and full of love in these dear people,
that their little present was enhanced to us a hundred fold,
and we parted with them in near unity, and in the love of Christ,
wishing one another`'s welfare here and forever.
The family at the inn parted with us again in much affection,
and passing through many villages and a fine country, we dined at Hildesheim;
then through a rich country with many crosses on the roadside, arrived at Oelsen,
a considerable town, but dirty and irregular.
Here we were taken to a large inn, where there were nearly thirty guests before us,
mostly of a low class of people, who had their music, card-playing, etc.,
the landlord an unpolished man, and the fare very mean.
David Sands being very poorly, we procured a pretty good bed for him;
the rest of us were but meanly accommodated.

"`29th. Got off early, and rode to Mila, where, as there was a good inn,
and David being unwell, we breakfasted.
Finding we were not likely to get to Pyrmont tonight, if we kept the common post-road,
and our postilion hot being allowed to go out of it,
we were so anxious to be with our friends, that we discharged him,
though we had paid the whole sum for the station he was to take us to.
We then agreed with our landlord for a certain sum to
take us over the mountains before night to Pyrmont.
Passed on a rough road, over very high mountains; the atmosphere being perfectly serene,
and descending from them we crossed the Weser in sight of Hameln in a boat,
a beautiful stream about one hundred yards wide.
Here we found a mean-looking town, and poor, dirty people--got very coarse fare,
and hastened on and arrived at Pyrmont, to the joy of ourselves and our friends,
before dark.
Here we found George Dillwyn, who had continued all the time of our absence,
having met with various matters among the little flock which engaged his care and labor.

"`First-day, 30th. At two meetings, which were satisfactory.
Before we arrived here, a letter had been brought from Major Marconnay of Berlin,
expressing in a grateful and thankful manner,
the goodness of the great Shepherd in sending us to Berlin;
that he hoped he should never forsake the Truth as it had now been discovered to him.
He had undertaken to open our way for an interview with
the king several days before we left Berlin,
being acquainted with the Prime Minister.
We waited as long as we thought necessary, and then left the city,
he having received no answer from the Minister.
The next day after, he was informed by him that the way was open,
and the king ready to see us.
Finding we were gone, the great men expressed regret,
and despatched a courier after us to Potsdam; but we had left that city also.
Thus by their needless delay,
their curiosity and our concern for an audience with the king, had been frustrated.
On the way back,
we frequently looked at it as the only thing we had left which caused us regret; however,
as there are many serious people in many places in Prussia,
we cannot doubt but other instruments will, in the Lord`'s time, be sent among them,
who may have the same concern laid upon them,
and which he may open a more effectual door to discharge.
We cannot charge ourselves with willful omission,
and therefore hope it will not be laid as matter of accusation against us.
The journey into that country, and the Divine mercy so evidently extended to them and us,
must remain as cause of reverent admiration and thankfulness as long as we live.
In the tour to and from Berlin, we travelled about six hundred miles,
and were out thirty-one days.

[.asterism]
'''

+++[+++Editor`'s Note: The Editors have obtained a copy of the above mentioned letter,
and apprehending it will be acceptable to their readers, they have inserted it below.
It furnishes evidence of a mind, in which the work of regeneration was carrying on,
struggling under religious concern,
and longing for a more full participation of that glorious
liberty which is the privilege of the sons of God.
It is delightful to observe how congenial minds, under the forming power of divine grace,
harmonize with each other in the unity of the one Spirit wherever they meet,
or however previously unknown.
Outward distinctions, whether of station, country, or profession,
seem to melt away and become lost,
in the aboundings of that love which flows in
their hearts as children of one heavenly Father,
and objects of the compassion and mercy of the same Redeemer and Saviour.
It is no less remarkable,
that in proportion as the heart-changing power of the Spirit of Truth is submitted to,
and the blessed realities of religion experienced,
the soul becomes increasingly sensible of the emptiness
and unsatisfying nature of outward forms and ceremonies,
and longs to partake more largely of the living substance.
The letter also serves to show the feelings of affection and fellowship,
excited in the minds of some they met with,
in the course of their laborious and painful journey;
and that though their speech and their preaching
was not in the words which man`'s wisdom teaches,
yet under the powerful influence of the Holy Spirit which accompanied,
it was instrumental in awakening not a few to a serious consideration
of the things which belong to their souls`' peace.

[.embedded-content-document.letter]
--

[.letter-heading]
A Translated Copy of a Letter from Major Marconnay to William Savery, David Sands, etc.

My last words to you, dear brethren,
were "`God be with you`"-- words that came from the fulness of my heart.
I love you with my soul.
I was never so soon inclined to unite with any men as I was to unite with you;
and never felt so soon a constraint to open my mind to any as I did to you.
I have opened this heart of mine into your loving souls;
but yet you are not wholly acquainted with my tried situation;
for there are feelings which cannot be expressed in words,
I seem as if I was forsaken of God, and yet I abhor this thought.
I have no desire to live or to die--for the pleasures of the world,
let them be what they may, I have neither taste, sense, nor feeling;
but who will believe, that notwithstanding this disgust of the world,
my heart remains shut up from higher and heavenly enjoyments.
The precious sense of the sonship with God; the assurance of faith,
and the consolations of the word; of all that I formerly enjoyed, tasted,
and felt of these gracious gifts, I have now scarcely remembrance.
My prayers are weak and powerless, as if I cried unto God from afar,
so that he cannot hear me.
This is also a thought I abhor.
Such, my dear brethren, are nearly the circumstances of my soul:
let your hearts now feel with painful compassion, how it is with me;
and fall down on your faces before the throne of the great and merciful Being,
and pray for your poor weak and wounded brother,
that Jesus Christ may again be formed in my heart,
and that I may again rightly fix my eyes upon him;-then
shall I be able to stand in this heavy exercise.
I shall then take from his hand the bitter cup and not murmur,
but wait for his help-then I shall be enabled in the end to exclaim, '`Lord, Lord God,
gracious and merciful,
you are great in your kindness and faithfulness;--who
was ever confounded that put his trust and hope in you?

Yesterday, the minister Howick sent for me,
and said he had just received a letter from the King,
who was very willing and ready to give you an audience;
and O! how gladly could I have called you back,
as I wished most heartily an interview between you and our good King.
I told the minister, it was possible you might have stayed over yesterday, the 21st,
at Potsdam; on which he immediately dispatched a chasseur to the General Bishosswerd,
notifying him that you might probably still be there;
whether the chasseur has met with you, I know not; but if it be according to my wishes,
you will have an audience with the King tomorrow morning at nine o`'clock.
And in this case, I desire you to give me, as soon as possible,
a circumstantial information of your conference;
for be persuaded I shall not make any bad use of what you may entrust me with.
Your letter to the King, the minister sent to him yesterday; but the books,
which the messenger could not take, were sent to the monarch today.

Now for the conclusion.
"`God be with you.`"--his light be your guide; his love and grace,
in and through Jesus Christ, your protection and defence in all danger:
be of good comfort, and filled with joyful hope.
He that is with you, is stronger than he that is against you.

Never shall your memory be effaced from my soul, I shall not cease to love you;
it will be a comfort to my weary soul,
if sometimes you will make me joyful by imparting a few lines of love,
and nothing but death will be able to prevent my answering your letters.
In love I embrace you in my heart, as

[.signed-section-closing]
Your ever loving brother,

[.signed-section-signature]
Marconnay.

[.signed-section-context-close]
Berlin, 22nd October, 1796.]

--

[.offset]
Returning now to the Journal:

"`31st. We have received several letters from Philadelphia, which were very acceptable,
though there was also some cause for exercise;
yet I must endeavor after resignation in all things, which has been my prayer this day.
This world and the fashion of it passes away.
O may we secure an inheritance through our Lord Jesus
Christ in an ever-abiding mansion in the world to come.
David Sands and I walked to Conrad Galla`'s, spent some time with the kind family,
and Charlotte Laaer, who had come to this place, and was glad to see us.
She was in a loving frame of mind,
and we hope the breach between her and befriends will be healed;
she appears to be an innocent, sincere young woman,
but through the influence of Brown has imbibed some opinions not congenial
with the harmony and unity of this little body of professors.

"`Eleventh month, 1st. Spent much of the day alone,
my mind discouraged and much exercised from a
fear lest we had hastened from Prussia too soon.
In the evening my friends perceiving my depression, endeavored to cheer me up,
but I retired to my chamber and obtained but little relief for body or mind.

"`Fourth-day, 2nd. The meeting was large,
nearly all the Friends residing here were present, and some from Hanover,
two of whom were a father and son, who had a strong desire to spend some time with us,
and came forty miles on foot: the son is a youth of a sweet innocent countenance,
and was much broken in the meeting on First-day and today;
thus the Lord is at work to bring sons from far,
and daughters from the ends of the earth.
The meeting was a solid good season; both my beloved brethren were engaged therein,
but my mind was not in a state to enjoy it as at other times.
I took an opportunity when my dear friends George
Dillwyn and David Sands were alone with me,
to mention what I thought was the principal cause of my depression;
not waiting at Berlin for an opportunity with the king lay heavy upon my mind,
and I thought I could do no less than stand resigned to go back again,
if it was the Lord`'s requiring.
They were led into sympathy with me, and in a little time George Dillwyn said,
what I had mentioned had taken so much hold upon his mind,
that he apprehended it was his duty to stand resigned to the
further openings of Truth with respect to going to Berlin,
if it should be called for at our hands--and the
concern now resting on the minds of my friends,
I felt more at liberty.

"`First-day,
6th. The meetings in the fore and afternoon were thought to be seasons of profit.

"`7th. The Monthly Meeting held near six hours:
we were all engaged in labor for the preservation of this little flock in love and unity,
and leading them into such order and discipline as was suited to their circumstances.
Several new members who had made application, were received into membership;
and on the whole, it was thought to be a solid, well-conducted meeting.

"`Fourth-day, 9th. We had a tender instructive parting from this dear little flock,
who are made very near to us.

"`Fifth-day we rose early, a number of the Friends coming to see us;
after a season of contrition we again took leave of them in many tears,
leaving George Dillwyn still at Pyrmont, with a hope to meet at Hanover,
if the Lord will.
Christopher Reckefus waiting upon us with his four horses to take us for a few days,
we put on and arrived at Rinteln; the roads being very rough,
our wagon was almost broken down, and we had but poor accommodation at the inn.
Rinteln is in the Landgrave of Hesse`'s dominions,
where several have been imprisoned for their religious principles, and others banished.
There appears much of the spirit of intolerance and great darkness among them;
yet there are a few awakened people, for whom we feel sympathy.
It contains, perhaps, five thousand inhabitants; is a poor dirty place,
and garrisoned by many soldiers.
Had a small meeting at a house, the owner of which, when near his end,
directed it should always be kept open for religious
meetings--there were but about eight people met,
yet through mercy it was made a time of refreshment and comfort;
most of them were acquainted with our principles, but being afraid of the priests,
had declined meeting together since the decease of the former owner of the house.
We encouraged them to a revival, and left them in much sweetness.

"`General Worms hearing we were from America, offered us a visit; he spoke some English,
and said he had seen David Sands when on Long Island--inquired
affectionately after several Friends there--appeared glad to see us,
and wished us a safe return to our families.
All the officers and soldiers who have been in America treat us with respect.

"`12th. After paying an exorbitant bill for very poor accommodations,
we passed through a fine country to Minden,
where the inns being much crowded on account of fair time,
it was difficult to get lodging; however, we at length met with a tolerable inn,
but were obliged to eat at the Table d`'Hote, which is not pleasant,
though the people behaved respectfully.

"`First-day, 13th. Had a meeting this afternoon about a mile out of town,
where about sixteen beside ourselves attended; it was rather a laborious time,
but ended well.
Some years past, there were upwards of sixty who used to meet on First-day,
being mostly separated from the public forms;
but Emanuel Brown and others have been the means of scattering them,
so that at present there appears to he but five or six families,
who meet once a week at this house, and hold their meetings mostly in silence,
acknowledge all our doctrines, and we hope are honestly seeking a right foundation.

"`14th. Yesterday we thought of leaving this place; but feeling a stop in our minds,
we now became more acquainted with the state of the little company professing with us,
and were enabled to account for the feelings we had in the meeting.
Three of the principal members being at variance among themselves,
we requested to see them all in our room,
when with tenderness and caution we labored with them to search out the cause;
and they being brought into a tender frame of mind,
opened things to us and to each other with great freedom;
the humbling power of Divine Grace attending, they freely forgave each other,
and desired that every tiling which had caused uneasiness might now be buried;
and we had the satisfaction of seeing them embrace one
another with much cordiality and brotherly affection.
After their reconciliation, we had a comfortable religious opportunity with them.

"`15th. We went to Frederick Smith`'s; breakfasted,
and took leave of the family and others who had come in, with much brotherly love.
Our dear Albinus was much broken at parting, having travelled about four weeks,
and upwards of three hundred miles with us, was very near to us in the love of Truth,
and it was a trial on both sides; he said he hoped he was now, through mercy,
favored to know the Truth, and bad faith to believe it would set him free.
We proceeded on to Henford, and in our way stopped to feed our horses at an inn,
where a number of the family were sitting down to a meal of potatoes, some salt,
and rye bread, which looked as coarse as if it had been made of bran;
yet they all had the appearance of health.
Thus vast numbers of the people of this country live; their houses are very dirty,
and pigs, goats, cows, geese, etc., mingle together with the family.
A young lad being ill with the cholera morbus, David Sands administered to him,
and the family appearing very thankful, would have made him some pecuniary compensation.
Our friend Christopher Reckefus still continued with us as our postilion;
and the country being everywhere crowded with Prussian soldiers,
feed for horses was very dear, so that we paid a Spanish dollar for a bushel of oats.

"`Fourth-day, 16th. We were much discouraged,
and doubted the propriety of staying to appoint a meeting; but as we waited in patience,
it appeared best that some inquiry should be made after religious people;
and meeting with some encouragement, we agreed to stay,
and appoint a meeting for this evening, at the house of +++_______+++ Bude, a town officer,
where our dear friend John Pemberton had had a meeting;
a few religious seeking people came to see us.
This town, like many others in this country, is dirty, the streets narrow,
and paved with pebble stones; the houses with the gable-ends towards the street,
have generally a mean appearance, the people poor, and few of respectable mien,
except the officers of the army.
It was crowded with soldiers, billeted on the inhabitants,
which is the case with all the adjacent towns and villages,
there being thirty thousand soldiers quartered in the neighborhood.
This place seems to be in a dead state as to religion.
The meeting was small; ability was given us to hold up our principles,
and the spirituality of true religion, and it ended to satisfaction.

"`17th. We set off for Kiepshagen, the place of abode of our friend Christopher Reckefus;
the roads so bad that we travelled only four and a half miles in two hours.
A meeting being appointed to be held at his house this afternoon,
about fifteen persons met us.
Christopher and his brother have thirty acres of land,
for which they pay about forty dollars a year to a nobleman;
they value their property in the whole at six hundred dollars;
but the various demands upon them of a public nature,
for some of which they suffer distraint, keeps them poor and bare;
yet they appear contented.

"`18th. After a religious opportunity with these families, we parted in much sympathy,
the two brothers accompanying us to Ufeln:
we passed through the finest piece of woodland we have seen in Germany,
the timber almost as tall as in America, which it is not common to see here.
Christopher took us to the house of a person whom John Pemberton mentions in his Journal.
This man`'s wife being a religious woman, and inclined to Friends,
had provided a dinner for us;
but her husband not being united with her in religious concern,
and having always treated Friends with indifference, and there being eight of us,
we thought it best not to stay, though the woman pressed us very kindly.
With considerable exertion we found a poor inn,
the people of the house not well disposed to receive us,
and there was no retirement or satisfaction to be obtained.
Officers and other light persons were crowding into the room,
and the residents of the inn cross and disobliging,
evidencing clearly that we were not welcome guests,
which we endeavored to bear with patience; but at length they told us what was to pay,
that we must discharge it and leave them.
This excited in us some admiration and disgust.
We went and dined at the house of the person before mentioned,
who treated us with kindness.
A young officer in the army offering his room for a meeting, we sat down together; he,
the woman of the house, and about five others, with eight of our company,
made up the number.
Upon the whole, it appeared to be a satisfactory season,
and we hope will have a tendency of uniting the
man of the house more fully to his tender,
religious wife,
and opening the way for Friends to be more kindly
received in this town than they have hitherto been;
the minds of both priests and people being very dark and prejudiced.
We were nowhere so much stared at, so ill-treated, nor so depressed in our minds.
After meeting, the affectionate woman got us a dish of coffee,
we took a kind leave of the family, and through Divine favor left them rejoicing.
Arrived at Hereford, and on the 19th got to Bilefield.
Though the appearance of the inn bespoke but poor accommodations,
yet the widow and her children who kept it,
seemed disposed to do as well as they knew how.
This town contains about eight thousand inhabitants,
who are chiefly employed in the linen manufacture; and it is filled with soldiers.

"`First-day, 20th. Several religious people stepped in to see us,
with whom we had a satisfactory time; one of them was a soldier,
had been with the King of Prussia against the French, and was in several battles,
but had never fired his gun.
One was a general engagement of the two armies; the night before it took place,
he being upon guard on the out-pickets,
and perceiving a general attack likely to come on in the morning,
felt great repugnance to shedding the blood of his fellow creatures,
and kneeled down and besought the Lord to preserve him through the coming day,
which was mercifully granted: his company were divided into five parts,
which were to follow each other as they were called out,
and those who remained alive after expending their ammunition,
to return and be succeeded by another.
He was first placed in the second division,
but afterward was providentially transferred to the last;
many of his comrades were killed, and the last division being called,
was prevented from getting into action by night coming on;
thus his prayers were answered.
There being several religious men in the regiment he belonged to,
and others in the same brigade,
during the campaign they frequently met together
to edify one another in the spiritual life:
so it appears that the Most High may be sought even in the midst of wars and armies.
He was a tender-spirited man, and desirous of finding the right way,
though under many discouragements and burdens,
in consequence of his employment as a soldier: we advised him to patience,
and encouraged him to look to the Lord for help.
In the evening we were invited to a meeting outside of the walls,
where Sarah Grubb and a company had had one to their satisfaction:
about thirty serious people attended; the Lord favored us together,
and Truth rose higher than I remember it to have done since we left Berlin;
so we parted and returned to our inn refreshed.

"`21st. Things appeared rather discouraging--no way opening for a meeting in the town.
David Sands, Lewis Seebohm and myself dined with C. Wellman, who,
with his wife and children, used us very kindly, were very free in conversation,
deeply acquainted with the mystic authors, high in reasoning,
and seemed much fixed in their strong-holds.
There are several families among those that are called rich,
much in the same circumstance; they do not attend at any public worship,
and plead that there is no necessity for meeting together,
but that each one may seek the Lord in private;
yet they would willingly attend a meeting if it was in a private way,
being afraid of the cross.
Some opportunities and close labor being had with them,
we hope the observations made may hereafter be blessed.

"`22nd. William Farrer and myself visited Charlotte Laaer at her father`'s house,
she having come here from Pyrmont;
her mother appeared very friendly and pleased to see us, but her father was not so kind,
though he used us more respectfully than we expected.
This poor young woman has much to try her faith and patience;
we felt great sympathy with her; she is of a loving, tender disposition,
and honestly laboring to be what she ought to be in the sight of her heavenly Father;
this leads her in a tribulated path--her family being people of distinction in the world.
Lewis Seebohm and myself took coffee with a merchant who had married Charlotte`'s sister;
she met us there; they were kind and appeared to be religious people.
In the evening had a meeting in our inn, where about thirty or forty people came,
many of them of the first rank; it held about three hours.
David Sands and myself were led to preach the Gospel,
during which much solemnity prevailed; it proved refreshing to us,
and we believe to several of them.

"`Fourth-day, 23rd. Had much conversation with C. Wellman and his family,
who appear to be drawing nearer to the spirit of Truth in themselves.
In the afternoon had an opportunity of more free
conversation with Charlotte Laaer`'s father and mother,
in which he seemed tender; and we parted friendly.
It has been a day of much exercise,
in which my mind has been more tried about the way of moving from hence,
than I have ever experienced before; and the same also with my companions:
indeed this has been a very trying place to us during the whole time of our being here.
The state of things among those called Separatists, who are ashamed of the cross,
has exercised us much;
yet there is a little remnant who are desirous of standing faithful,
whom we hope we have been made a means of strengthening.
To the flesh it looks pleasant to turn towards Amsterdam,
the days being very short and the roads exceedingly bad;
but our minds are not fully settled to proceed that way.

"`24th. After a time of waiting on the Lord under much concern to be rightly directed,
it appeared most safe to proceed to Lemgo.
We parted with several of our acquaintances and with the people of the inn,
in an affectionate manner;
our landlady and all her household have been very attentive and obliging,
which has been a relief to us during our stay in this exercising place.
Dear Charlotte Laaer, who has had our sympathy in her trials,
was much affected at parting.
The roads were bad, and we did not arrive at Lemgo until afternoon;
the landlady received us kindly, but the house was crowded with Prussian officers.
Lewis and myself visited an ancient man named Buckholz, who passes here for a Quaker,
has been brought under suffering several times for his testimony,
and is very near to us in principle; with him and a few others,
we had some religious service tending to their encouragement.
I was glad of the visit.
There are many precious souls scattered up and down in this country,
struggling with discouragements.
Lemgo is the Prince la Leppes`' dominions, believed to contain five thousand inhabitants.

"`25th. Undetermined which way to turn; these two weeks past have been very trying,
hardly able to see a day before us; thus there is need to pray for patience.
Being nearer to Amsterdam now than we have been before,
it seemed as though we might be permitted to turn that way,
but after solid consideration, all seemed closed for the present with respect to Holland,
and our minds were most easy to proceed in faith towards Hanover, directly back.
It was a trial to be thus kept in Germany.
Passed through several villages, and the roads so bad that our wagon stuck fast,
though all our company were out of it, and the horses were not able to move it;
our good driver, Christopher Reckefus,
was obliged to go back about three quarters of a mile to get a chain to draw it out,
which detained us an hour and a half in the cold.

"`26th. The roads continuing very bad,
I hired a horse and a man to bring him back from Hameln:
here we found three of the young Friends from Pyrmont,
who had come on foot twelve miles to meet with us;
showing the love these tender young people have for the company of Friends.
We took an affectionate leave of them and our attentive friend Christopher Reckefus,
who had continued with us eighteen days, and endeared himself to us.
We took post-horses and went on to Spring, the road being a turnpike,
it was a great relief to us, but there are few such in Germany,
as the princes are not willing to spend their money on roads,
and the people are too poor to improve them.

"`27th. Arriving at Hanover,
we found our dear friend George Dillwyn with his interpreter;
they had held a meeting in the morning and appointed another in the afternoon,
which we all attended, and it appeared a satisfactory time;
several of the religious people having evidently
gained ground and come nearer to Friends.
There are several here who have scruples respecting some parts
of the business on which they are dependent for a livelihood,
similar to that which was among Friends in the beginning,
and from which testimony many under our name are now departed:
and when we think of the occupations of many who have had an education among us,
and some who are in high stations in the church,
it has a painful influence upon our minds,
while we are endeavoring to cherish that which is of the right
birth in those who have not had the same advantages;
but Truth is the same in all places, and Wisdom is everywhere justified of her children.
David Sands and myself have had our minds turned to think of a
meeting in a more general way than has yet been in this place,
but no opening has hitherto presented;--there is need for more firmness and
boldness for the Truth among those who appear to have a love for it and its friends.

"`30th. Had a meeting at George Dillwyn`'s lodgings: about thirty attended,
among whom were two candidates for the priest`'s office; it was a humbling time,
and one of these young men was much broken, and all his former fabric destroyed;
he seemed like a man in amazement,
that he should have found the truth in so simple a way and so unlooked for,
and we endeavored to strengthen his exercised mind.

"`Twelfth month, 1st. A number of people coming in, we had another meeting in the evening.

"`First-day, 4th. A meeting being proposed at the house where George Dillwyn lodges,
outside of the gates, a number of people collected; the landlord,
who had heretofore cheerfully given us his commodious room, now refused,
being afraid of the magistrates,
and he turned away many of the people who were collecting; some of the most zealous,
however, persevered, and about thirty being assembled,
the Lord favored us with his presence and it proved a solid, contriting season.
The magistrate sent a civil officer to tell the
landlord he would be fined twenty dollars;
and his wife being in great passion at this,
I endeavored to pacify her by offering to go with the officer to the magistrate,
and to take all the consequences upon ourselves; but after some conversation with him,
I found he had no orders to take us there; and showing him the tenor of our passes,
he went away,
and afterwards came back to the inn and said he had
informed the magistrate what sort of people we were,
upon which he did not incline to send for us.
In the afternoon we held a meeting at the house of J. Buchner, who had freely offered it;
about sixty were collected, and many went away for lack of room;
two civil officers came in while we were speaking, but offered no interruption.
It was thought to be a meeting of the most information to them of any that had been held;
they expressed their thankfulness, and we parted with tenderness.

"`5th. The knowledge of our being in town being much spread,
many of various characters and ranks came to our lodgings throughout the day,
and a number sent their children for books,
so that all we had were presently disposed of, and if we had had a large number more,
they would not have been sufficient for the applications.
The school-masters in this place make it a practice to
tell their scholars any interesting matter that occurs,
and as several of them had been to see us,
the children got information that we were from America, a great way off,
and come to preach the true religion to the people of Germany,
without taking any pay for it.
This news the children communicated to their parents, and it thus spread fast,
and accounted for the city being so generally acquainted with it.
In a conference with some of the principal men who make profession with us,
we found a necessity to guard them against appearances
by way of ministry that were not duly authorized,
some instances without proper weight having been manifested among them.
Several said,
they desired rather to continue always in silent waiting than
to admit any ministry not from the right fountain,
as it would only scatter.
In half an hour after we returned to our inn,
we found ourselves surrounded by one hundred people, with whom we sat down in silence.
Emmanuel Brown being come to Hanover was also present;
David and myself were engaged in religious communication,
and the people were very quiet and serious,
and the meeting appeared to be owned to our humbling admiration;
hence we have cause to say continually, Good is the Lord,
and worthy to be served in all things.
Frederick Seebohm and two other Friends from Pyrmont being present,
we had a short opportunity with Emmanuel Brown, who appears like a Friend.
After a day of much labor, we retired to rest in the enjoyment of sweet peace.
The Lord has not raised such a remarkable inquiry in this place,
but with gracious design to bless it,
if those who have now been called remain faithful to him.

"`6th. Had another full opportunity with Emmanuel Brown, George Dillwyn being present;
he freely acknowledged the doctrines of Friends,
with respect to Christ`'s baptism being spiritual,
the non-necessity for those who had come fully
to enjoy the spiritual communion with Christ,
to partake of the ceremony of bread and wine;
and also the benefit and duty of meeting together for Divine worship.
He favored the doctrine of celibacy, believing it right for him to continue single,
but did not think it was obligatory upon all.
This man had been the means of sowing discord and leading off
many innocent persons in this land with his vain imaginations,
and his professions of love and attachment are not to be relied upon.
Many came and took an affectionate leave of us,
and we were renewedly convinced that the Lord has a precious seed in Hanover;
to him we must leave them at present, feeling now clear in our minds,
and humbly thankful to our great and gracious Lord,
who has been with us and granted strength to go through the various and
almost continual labors and exercises in this place to our own comfort,
the encouragement of the little honest-hearted flock,
and we hope not to the dishonor of the blessed cause we are engaged to promote.

"`Here we parted with dear George Dillwyn and his wife in near unity,
he proposing to stay a few days longer, and then to proceed towards Berlin:
as we now are likely to travel in contrary directions,
there is little prospect of meeting again on the continent,
Berlin and Amsterdam being near five hundred miles apart.
Our landlord and servants were very respectful and affected at parting;
a number of gay women having come to get a sight of us,
they waved their hands and wished us a happy journey,
as did also the people in the streets.
There appears great encouragement for Friends to visit
this place who may be rightly called to such a service.
We rode on about ten miles,
and our postilion having taken up a man and woman without our consent,
when we came to the house where the horses were to stop,
they called for drink and food which the landlord charged to us.
As it was an imposition we were not disposed to submit to, being of violent passions,
he stormed and swore we should pay it,
that it was the practice to charge all to the herrschaft and let the poor go free;
so for peace sake we were obliged to submit; he was in such a rage,
I heard him tell the postilion he would do right to overset us on the road,
which he fully executed about one and a half miles from the stopping-place.
It was extremely cold, windy and snowing, and near night, when we were overset;
my companions were bruised and much injured, I escaped with little damage,
but it was with great difficulty we could get the wagon up,
and were kept in the snow and wet a considerable time.
It being now dark, William Farrer and myself walked to the village,
not being easy to trust ourselves to this bad man again,
who we believe was in league with the innkeeper; the conduct and appearance of whom,
and of the people in his house and other circumstances,
convinced us that Satan reigned there.
The inn where we now arrived was a decent house:
the wounds of my friends were dressed as well as we could,
and the people being of more kind and accommodating
manners than is common in the villages in Germany,
we felt tolerably comfortable,
and retired to bed in thankfulness to a gracious and ever-watchful Providence,
who so preserved us that no limbs were broken nor lasting damage sustained;
thus we have daily fresh occasion to sing of his mercies.

"`7th. Our wagon being much damaged,
it was near mid-day before we could get it repaired so as to be fit to proceed:
rode on to a village eighteen miles, when it was near dark.
The place was very dirty, and the houses crowded with soldiers;
and though we offered high pay, yet no beds could be obtained fit to lie on,
and the rooms were so filthy as to be quite unsuitable to spread straw upon;
we were therefore obliged to go on to Minden, twelve miles in the night,
and where we were in great danger of being overset again.
We however got to our former quarters,
and were received by the landlord and family gladly.

"`9th. Had a meeting in the evening, which proved to be a tendering season:
several returned with us to our lodgings, and appeared comforted.

"`First-day, 11th. Attended the meeting of those professing with us,
held at Frederick Smith`'s; about fifteen persons were present,
and though it was mostly silent, yet it ended to our satisfaction.
In the evening we had a meeting in a chamber at the orphan house,
where two hundred at least attended, and behaved well.
Among them were people of note, and officers of the army; it was a solemn season,
and we parted in much tenderness, returning thanks to our gracious heavenly Helper,
who thus in an unlooked for manner made way for us.
It is not likely that such meetings were ever before held in Germany,
and we humbly hope that the cause of Truth has been promoted by them.
There was much expression of unity with us, and thankfulness for the opportunity.
O! what occasion we have to say, '`Good is the Lord, and worthy to be served.`'

"`12th. Not feeling ourselves at liberty to go forward,
we were visited by several who were at meeting last evening,
and informed us that many who had not been there
expressed a desire they might have such an opportunity;
after weighing it,
we concluded to put off the appointment of another meeting until tomorrow.
The little company of Friends in this place seemed much relieved by the public meeting,
and said they felt as though a great burden was taken off their shoulders.
We dined at counsellor Borges`'s;
his house and heart seemed to be opened in an unexpected manner,
and we had much religious conversation with him and his two daughters, we hope to profit.
This is the same man whom Sarah Grubb mentions,
and who being involved in a multitude of business pertaining to his office,
and much looked up to by the people, had not ventured to avow openly,
what no doubt he had been convinced of, and so appeared to have fallen back,
and not inclined to see us at our first visit to Minden.
He attended the meeting at the orphan-house, but stood in the entry.
It was said by his son-in-law, Lewis Seebohm,
that he never received Friends with so much openness before,
and manifested great attachment to us.

"`13th. We were informed that the Consistorial Rath,
who is a director of things relating to the church within his precincts,
as well as a priest of the first dignity,
had forbid any more meetings being held in the orphan-house,
and had said things which reflected upon us and our Society.
We felt most easy to appoint another meeting for this evening,
at such place as our Friends thought best; and with respect to the priest`'s reflections,
we thought we should not be clear in leaving Minden without paying him a visit,
lest it might tend to the discouragement of the little flock here.
David Sands and myself went and found him at home;
and on inquiring the cause of our being forbid the orphan-house,
he affected to be friendly,
and said we might freely have held meetings there as to his own particular sentiment,
but that the edict of the king of Prussia admitted of no
public religious assemblies in his Westphalian dominions,
but Lutherans, Calvinists, Roman Catholics, Moravians, Jews, and Menonists;
and therefore as the king`'s servant, he was obliged to forbid our public meeting;
but that we might meet more privately at our inn or any private house,
without interruption, for the edification of the people;
to which he was not at all opposed, but said we might do so in the Lord`'s name.
We told him we could not resort to secret places as some did, to hide their testimony,
or for fear of suffering;
and that we held our meetings open for all in the city of Berlin.
We also asked him,
if he did not believe liberty of conscience was the common right of all men?
To which he answered in the affirmative; but thought it was not abridged in this place.
We conceived it was; but not finding it necessary to go into much controversy with him,
turned to the other subject.
This confirms me in the expediency of encouraging those upon whom it may be laid,
to visit the king of Prussia; perhaps it may fall upon dear George Dillwyn.
For my own part, I feel my mind relieved from it at present.
With respect to the other subject (reflections upon the Society),
he appeared startled that it had come to our knowledge;
but was not able to tell his author, and said it was a matter of little consequence,
that we ought rather to rejoice when evil was falsely spoken
against us--it was what every true Christian might expect;
but for his own part, he did not believe there was the least foundation for it.
We replied,
that the character of ourselves and the Society was dearer to us than our lives,
and that we were bound to defend it; which he acknowledged was right,
and that if it was possible to find his author,
he would inform us before we left the city.
After making some general observations,
and placing the reflections cast upon us to the account
of the old root of bitterness in the priests,
we parted in a friendly manner, himself, his wife and daughters shaking hands with us,
and wishing us a good journey.
One of our Friends here not being free to bury his wife
in the manner of any of the religious societies,
buried her in his garden, for which the priests took from him six dollars as their fee.
Thus these poor people are under suffering many
ways for the testimony of a good conscience.

"`Made another visit to counsellor Borges and had some religious service,
which was a humbling time.
The old man embraced us affectionately,
and said he had not words to express the thankfulness he felt for our
visits--followed us to the gate and took a final farewell,
recommending us tp Divine protection and care, with the tears flowing down his cheeks.
We hope our interaction will remain with sweetness,
and be beneficial to our few sincere-hearted brethren who hold a meeting in this place;
this counsellor being a man of extensive influence.
Had a meeting this evening consisting of about sixty persons,
besides a number in the entry.
A man of genteel appearance came in, who was a Calvinist minister,
stayed the meeting through,
although our principles respecting true Gospel ministry and the freedom of it,
were largely treated upon.
It was a confirming time to most present, and a solemn parting with our dear Friends,
who came one after another in the most affectionate manner to take leave of us.
Some of these partings in Germany must remain with me as long as my memory.

"`14th. A cold damp day; the ground covered with snow and the roads deep and dangerous;
pur wagon being too high and top-heavy, we rode in fear;
but arrived in safety at a town where we stopped a short time and proceeded to Bomte,
having travelled six Dutch, or thirty-six English miles.

"`15th. Got to Osnaburg and dined at the Table d`'Hote with about twenty persons,
who treated us respectfully;
one of them expressed his surprise that we adopted in our writings, and otherwise,
a name that was given us in derision;
there being something inviting and consistent with the character of our Society,
in the appellation of Friends;
but foreigners must be at a loss for a reason why we continue the name of Quakers.
Such remarks have been frequently made in our travels;
and if the Society had not continued it,
it is very probable the name of Quaker would scarcely have been known at this day.

"`16th. Osnaburg is subject to the king of England,
and contains about ten thousand inhabitants.
There is a convent in this town, composed of young women of noble families.
It appears that the German nobility who have many daughters,
persuade some of them to go into nunneries,
to save the portions that are expected at the time of marriage.
At the Table d`'Hote,
it is very unpleasant to be obliged to hear the
music which is almost continually playing,
so that we can scarcely hear one another in conversation.
We expressed to the priests and the landlord our objections to it;
and some of the company finding us uneasy, took up the subject,
and an elderly man told the landlord,
he thought it a great imposition upon many to please a very few;
and although he had lodged there for some months,
if it was continued he should be under the necessity of shifting his quarters.
In the evening we had a meeting at a private house,
where about ten sober people convened, who behaved in a becoming manner,
and we hope the service will prove profitable.
Although they are separated from the public worship,
they are more like Moravians than Friends--they remember Sarah Grubb with respect.

"`17th. Proceeded to Rheine: the roads being very difficult and filled with snow and ice,
we thought it a mercy that we got on without being overset, as our wagon is so top-heavy.
Rheine is a small Roman Catholic town subject to the bishop of Munster;
the people in these parts appear to be very poor,
and the whole seems to be a country of darkness.

"`First-day, 18th. The people were crowding by day-light to matins,
with their beads and crosses: my feelings are heavy and unpleasant.
O! sweet liberty of conscience, you restorest men to their proper dignity,
if your blessings be used to the glory of God.
Passing on, we halted at a village, where the language, manners and cleanliness,
evidently indicated we were drawing near the borders of Holland.
Got to Bentheim, a considerable town on a rocky hill, with a strong castle.
This town being Protestant, and we finding a decent, clean house kept by the post-master,
took up our abode for the remainder of the day.
The rooms, beds, furniture and people,
are much more cleanly than we have met with for some time.
Had a satisfactory opportunity with the people of the house and some others,
in the evening, which left my mind easy and pleasant.
The Lord is good; and though trials inwardly and outwardly attend us,
yet he favors with times of refreshing from his presence,
which is an ample reward for all our toil and suffering.

"`19th. Left Bentheim, and the roads being difficult,
did not arrive at Delden till two hours after dark.
Our expenses at inns are extravagant; and all over this country,
travelers are fleeced in almost every way, especially foreigners;
and without submitting to multiplied impositions,
there is no getting along with any degree of comfort.
It is far more expensive travelling than in England;
their movements are slow and tedious, generally about three miles an hour,
and make great demands upon our patience.
The country is in general handsome and fertile;
many houses in the villages are of good brick and look well, though but one story high.
Their fires are made in grates, fixed in the chimneys, the fuel being turf and some wood,
which might do very well if there was enough of it.
With considerable danger we arrived at Deventer, a pretty large town; with clean streets,
many elegant houses and open squares.
A very spacious and ancient piece of architecture claimed our notice;
it had been used as a worship house for the Reformed, for centuries past,
bat is now totally in ruins inside, the French army having made a stable of it;
such are the effects of war!

"`Fourth-day, 21st. We travelled through a highly cultivated country, extensive meadows,
fine planted woods, houses, gardens,
and all around conveying an idea of great regularity and order.
The city of Deventer and its environs, the river Yssel,
with a handsome bridge upon boats, and the cleanliness of the people,
formed as agreeable a prospect as any we have seen on
the continent--the city may contain ten thousand people.
travelers become more numerous as we approach Amsterdam: we were taken for Hanoverians,
could understand but little they say, though they can readily comprehend us in German.
The Holland language appears to be a mixture of bad German, French, and English.
The roads being good, we made thirty miles today, travelling,
for the first time since we have been on the continent, at about six miles an hour.

"`Sixth-day, 23rd. Passing through a fine country, we arrived at Amsterdam;
the houses in the main streets of this great commercial city are generally large;
and although they are built with the gable-ends to the street,
and from three to five stories high, yet they have an appearance of grandeur.
The river Rhine empties into the Zuyder sea,
which a few centuries past was a valley filled with towns and villages;
but the ocean breaking the banks,
overflowed the country and drowned most of the inhabitants.
The public buildings are magnificent, and the whole city crowded with shops.
This is indeed a beautiful and populous city;
neatness is conspicuous through its borders, but the number of beggars is considerable.

"`First-day, 25th. We were at meeting in a room of John Vanderwarf`'s house;
a number of strangers came in, and through Divine favor it proved a good meeting.

"`26th. Held another meeting, and though the people, as is their practice,
were restless in time of silence, yet it was thought to be a serious opportunity.
The weather was very cold, and no fire in the meeting-room,
except in foot-stoves for the women.
In Holland, it is not customary for women to draw near or sit by a fire,
that being a privilege for men only; hence the women are furnished with wooden boxes,
with a bason of coals or turf in them to put under their feet.
It is so cold here that the hair of the men is frozen with their breath,
as they pass along the streets; and fuel being dear, chiefly turf,
with a few coals from Germany and England, or a little fine wood to kindle it,
they keep very small fires, and having few stoves,
the rooms are so cold that we had to keep on our thick overcoats most of the day.
Meat costs from about nine to twelve cents per pound, which is for the best kinds.
In almost everything they are the reverse of Germany; the furniture, etc.,
being kept very clean and nice; they drink a great deal of tea and coffee,
but do not use much sugar.

"`27th. We were examined by the Committee de Surveillance,
who treated us with much civility,
and recommended us to the French consul for a pass to go towards France.
The Stadt-house where they sit is i very large and noble building,
highly ornamented with marble sculpture.
All religious professors now bate liberty of conscience, and to meet openly for worship;
but private meetings are forbidden.
Their funerals are attended by men only; no bell rings,
nor do they wear mourning after the interment.
Our passes being certified by the American consul,
he advised us to go by the Hague to see the American and French ambassadors there.

"`First-day, 1st of First month, 1797.
Had two meetings; about fifty persons attended each, and we hope they were to some profit.

"`2nd. Our passes being endorsed by the French consul,
we exchanged our old wagon for a coach, which will be safer and warmer,
and we '`hope to travel with two, instead of four, horses.
Notwithstanding the beauty and opulence of Amsterdam in general,
travelers are beset every few paces with beggars.
In the Jews`' quarter especially, the misery, nakedness, and dirtiness,
exceed anything of the kind I have ever seen before.
In Berlin I was never asked for charity.
The neatness of everything in Amsterdam, its shops, streets, canals, bridges, etc.,
is very pleasing to strangers; yet the Jews`' quarter is an exception.
The vessels that trade up the Rhine are drawn by horses; are very capacious,
being about one hundred feet long, and hive several handsome rooms upon deck,
where the families of the captains reside.

"`First-day, 8th. Were at two meetings, the largest we have had;
there were six American captains present,
and these meetings were thought to be the most solid
and satisfactory of any since we came to this place:
many of the people were affected and parted with us affectionately;
thanks to our great and gracious Helper, who has not forsaken us in any place.
If any good remains on the minds of the people
in any of the cities and towns we have visited,
let the name of the Lord be magnified, and we humbled in the dust.

"`9th. Sat with the few Friends in what they call their Monthly Meeting.
Their principal business for several years,
appears to have been only to meet and make a minute that they did so; and once a year,
to transmit an account to Friends in London,
of the condition of the state of Friends here; as the house where John Vanderwarf lives,
and in which the meeting is held,
belongs in part to Friends of England and part to Friends of Holland;
there is also some other estate under their care.
The books for one hundred and thirty years back, the minutes of the Monthly Meeting,
records of births, burials and marriages, etc., are still preserved in very neat order.
By these it appears, that from about 1676 to 1720,
there was a considerable number of Friends here,
sixty or seventy signing their marriage certificates.
Since the last date, there appears to have been a gradual decline,
until it has come to what it now is;
two ancient Friends being all that keep up the Monthly Meeting,
who appeared concerned what might become of the property when they should be taken away.
After reading and minuting our certificates, the meeting concluded.
In the evening we had a religious opportunity with young John Vanderwarf and his wife,
which we believe was right, and hope it may have its use.

"`10th. Set out for the Hague; passed throngs Haarlaem, a large town,
and over a fine country, many beautiful villages, elegant country-seats, etc., to Leyden,
a large city, containing about sixty thousand inhabitants; the neatness, decency,
and size of the houses,
makes it rank among the first cities of this riek and populous country:
from there travelling through a country very pleasant and highly cultivated,
we arrived at the gates of the Hague, and took lodgings at a good inn.

"`11th. Visited the American ambassador, who received us very courteously,
endorsed our passes, and gave us such intelligence respecting our journey to France,
as was in his power.
We went also to the French ambassador, who treated us respectfully,
bat said he had no authority to give a pass to an Englishman;
but thought William Farrer would meet with no
interruption while he remained in our company,
engaged in the good work of promoting religion among the people; and remarked,
that he was satisfied we were what we appeared to be, without deception.
This beautiful city may contain forty thousand inhabitants,
and is said to be the handsomest town in Europe: the principal street,
which is magnificently built, and about three hundred feet wide,
has a promenade in the centre, of about one hundred feet wide,
shaded and ornamented by five rows of stately and beautiful trees;
the woods round the town, are also laid out in fine walks with seats at proper distances.
All the principal streets have trees on each side, and canals in the middle;
the trimming of those trees in the winter, serves for fuel for the poor.
The inhabitants appear civil, very neat in their houses and decent in their persons.

"`12th. Got to Rotterdam, and met with several Englishmen and some Americans:
we were received by those to whom we had letters, with great openness and friendship.

"`Sixth-day, 13th. Found an open reception at Cornelius Lloyd`'s,
who is of English descent,
and was the last person who contributed to support a Friend`'s meeting at this place.
Although there is something pleasant in meeting with so
many who can converse in our own language,
yet the general state of my mind for some days past has been far from joyous;
having travelled under daily exercise, though concealed by a cheerful countenance,
partaking in secret of copious draughts of the bitter waters of Marah,
from a consciousness of my natural disqualification for the work of Gospel ministry.
Travelling so far, through many outward difficulties,
for the promotion of the Redeemer`'s kingdom,
brings me into deep reflection on the degree of
redemption which I myself have experienced;
which alas!
I often have cause to acknowledge before the Searcher of hearts,
is far short of what I am persuaded the power of redeeming love is able to effect;
yet some consolation is afforded by the conviction,
that I most sincerely desire a higher degree of attainment,
even the state of a perfect man in Christ Jesus--that I
may be thoroughly washed in the laver of regeneration,
until I am prepared, through adorable mercy,
to be presented faultless before the throne of his glory with exceeding joy.
In passing through these European countries,
a secret sadness has frequently covered my soul, on viewing the pompous palaces,
the crowded cities, the vanity of the great, the avidity of the merchants,
the oppression and wretchedness of the poor,
and the depravity of many in all the different classes; that I am ready to cry out,
O! when shall the Son of righteousness arise with healing in his wings,
to recover mankind from the many maladies which encompass them!
A few there are, scattered over this continent, whom he has gathered,
and is gathering under the shadow of his wing; who have appeared to me,
though many of them are hidden in solitary places, to be like the salt of the earth,
which prevents the whole mass from sinking under its corruption.
With these my soul has rejoiced, and will rejoice;
they have been like stakes of confirmation to me, and with all the infirmities I feel,
I am satisfied that my lot has been cast hero for their sakes.
On taking a retrospect this morning of the five preceding months of wearisome travel,
labor and exercise, I feel the reward of sweet peace;
and the tribute of thanksgiving to the Beloved of my soul,
who has not forsaken me in the hour of trial, but mercifully preserved me, though faint,
yet pursuing the mark, for the prize of the glory of God in Christ Jesus, my Saviour,
whose service is perfect freedom.

"`14th. Visited the ancient place of meeting for Friends,
and it being now used as a carpenter`'s-shop,
we requested it might be cleared out and made ready for meeting tomorrow.
Rotterdam is about one-third the size and population of Amsterdam, lies nearer the sea,
and has fine canals running through it in different directions,
in which the largest merchant-ships may lie conveniently.
The number of English and Scotch people,
the appearance of sociability among the inhabitants,
and other advantages which it possesses,
would make it a more desirable place of residence than Amsterdam;
though it does not equal it in grandeur.
Many of the houses here, as well as all over Holland,
are built with the front from one to three feet from a perpendicular line,
the upper part of the walls having the gable-ends to the streets,
project over the footways, which they say, is to prevent the water that falls,
from running down the walls and windows.
The new houses project very little, and some not at all.
When a fire happens, as the streets are narrow,
these projections occasion a communication of the flame to those opposite.
There are people paid to put out fires,
and the citizens trouble themselves but little about it.
Pumps are fixed in the canals, and by means of leather pipes,
convey the water to the engines, so that they use but few buckets.
In the principal towns, the houses are almost universally occupied by shops below,
and the family sit up stairs.

"`First-day, 15th. About sixty persons attended the meeting, mostly respectable people,
and it was a solid good time.
Dined with Cornelius Lloyd, a merchant of considerable wealth:
his wife was so terrified at the noise of the cannon,
and the fear of the French army entering the city,
when Dumourier was on the opposite side of the Maase, that it deprived her of memory,
so that she cannot retain anything a minute at a time.
His mother, an ancient woman, was educated a Friend: on visiting her,
she appeared glad to see us; her faculties are good,
and she remembered William Brown being here on a religious visit;
her son has now the care of the meeting-house, which he rents out,
and has some stock in his hands to pay for cleaning it, finding candles, etc.,
when wanted; but the funds of Friends here,
have sunk by the failure of one of the descendants, who held them to a large amount.
In the afternoon, about one hundred and fifty attended the meeting, which,
through renewed mercy, proved a satisfactory season; many were tendered,
and it was a time of refreshment to ourselves.
Thanks be to the Author of every blessing.

"`16th. At the meeting in the evening,
it was thought that half the people who desired to be present, could not get in,
and the place being so crowded and warm, they were, for a time, rather restless; however,
through Divine mercy, Truth rose into dominion; they became solid,
and parted in tenderness.

"`17th. In the evening had a meeting at the Episcopal worship house, built by Queen Anne,
for the benefit of the English residing here; it is not large, but a decent,
plain building.
Many of the English and Scotch people having
gone away from Rotterdam in the heat of the war,
among whom was the priest, it has been shut up for some time;
the remaining part of the congregation, seeing that Friends`' house was too small,
offered it freely, but the construction of the room is such, as to produce a great echo,
so that we are informed many who sat in the centre, heard but partially; however,
they behaved remarkably well, and on the whole it was thought a profitable meeting;
the Lord is good to us poor unworthy creatures, from day to day.

"`18th. The inhabitants are civil and respectful;
the water here is better than in Amsterdam, where they drink little but rain-water,
here the canals ebb and flow with fresh water, which, at this season, is pretty good.
The canals render it dangerous walking in the evening, when the weather is foggy.
A few years since, in very thick weather,
there were said to be three hundred people drowned by falling into them; since which,
they have increased the number of lamps, and ropes are extended from tree to tree,
when there is danger of the like disaster.

"`First-day, 22nd. The meetings both in the fore and afternoon, were,
through the mercy of our heavenly Father, solemn seasons;
there are doubtless a number of seriously visited souls in Rotterdam,
and the prospect of Friends visiting this city on a religious
account is much more promising than in Amsterdam.
Though Friends are almost extinct as to supporting meetings,
yet I cannot but feel a prayer in my heart,
that the Lord might be pleased to send his servants into this part of the vineyard.

"`23rd. Expected to move towards France,
but our minds not being clear of the people in this place,
we concluded to tarry some time longer.

"`First-day, 29th. Have been unwell for several days.
A pass was procured for our going into France, except for William Farrer,
who could not obtain one on account of his being a British subject.
We had three meetings today, and through the renewing of Divine favor,
they were satisfactory; we took leave of the people in much tenderness and affection,
believing we might soon be at liberty to go.

"`30th. We hear many discouraging reports of the difficulty of travelling in France,
and are much exercised about the right way to proceed;
believing our religious concern in this place is now fulfilled.
We have none to lean upon but the Lord alone, who, blessed be his name,
has been hitherto excellent in counsel and wonderful in working for us,
more so than I feel myself worthy of.
We visited several of our friends here, who advised us to go to Sluys in Flanders,
by water, and our minds settled to turn that way.

31st. Went on board the packet: the commander was an honest-looking man,
and I made out to understand his half Low Dutch and half French.

"`1st of Second month.
Wind ahead, stormy and some rain; sailed about twenty miles, our cabin having no fire,
and the weather being very damp and cold and the beds small,
we did not feel very comfortable.

"`Fifth-day, 2nd. The wind was very high; lay to all day;
very cold and no prospect of getting on, added to which,
we understood we should be arrested on our
landing if we did not wear the national cockade,
which we could not comply with;
everything looked more gloomy than at any time since leaving my native shore;
a little hope and some confidence however remained,
and a humble trust in the Almighty Arm that has hitherto preserved,
which settled us in calmness.

"`4th. Got on pretty well, though the wind continued nearly ahead.
Passed by several handsome villages on the islands, which are in the province of Zealand.
The wind being very small and a thick fog, the anchor was dropped.

"`5th. Much detention on account of the fog, but it breaking away,
we sailed by the beautiful island on which are the cities of Middleburg and Flushing;
reached Sluys in Flanders, about dusk;
here we underwent an examination by the officers and also a search,
but all ended without long interruption.
The dampness of the vessel, and scarcely anything comfortable,
kept David Sands unwell most of the voyage, which was about one hundred miles;
I was also taken poorly, having got a heavy cold.
The merchants to whom we were recommended visited us.
Many exercises crowded in, so that it was a trying time.

"`6th. David Sands and myself both very unwell; the prospect of proceeding to Dunkirk is,
from a variety of circumstances, very discouraging; it we indeed a gloomy day,
faith and hope very low.
The two merchants to whom we had letters coming to see us,
did not encourage us to proceed to France,
supposing it to be impracticable without a national cockade,
which was also the sentiment of others.

"`7th. Weighing seriously what was best to be done in our trying situation,
and the various reports of difficulties that would interrupt our journey,
our minds being calm and composed, we concluded to pursue oar journey to Dunkirk,
in humble confidence on the Divine Arm,
that is alone the defence and preservation of them that love the Lord in sincerity.
We left Slurs in the afternoon, and arrived at "`Bruges before dark,
having passed through a poor country.
This city is thought to contain sixty thousand people,
but has a dark uncomfortable appearance,
the houses like prisons with iron bars across the windows.

"`8th. Hired a post-chaise to take us to Dunkirk, thirty-seven miles,
and passed through a flat fertile country; met with the American consul on this station,
an agreeable young man, who told us that with our passes we might go over all France;
this relieved as much from the anxiety we felt, both for our testimony and our safety,
and our hearts were lifted up with praises to our heavenly Benefactor,
who can at bis pleasure dispel the clouds and darkness that at times surround.
Riding on the side of the sea, we arrived at Dunkirk in the afternoon.
I put up at Judith Gardiner`'s, a Friend from Nantucket,
whose husband died at sea since their settling here, and she keeps a boarding-house.

"`9th. Unwell, the consequence of travelling so long in this damp foggy climate,
where we have not seen the sun for fourteen days, and but very little for six weeks.
Our landlady, who is a motherly woman, attended me kindly.

"`10th. This town is supposed to contain forty thousand inhabitants,
has a gloomy appearance, the houses being closely stowed; the people here,
as well as in Flanders, are mostly Roman Catholics.
The harbor, which is about a mile from the sea, is narrow, walled at the sides,
and almost bare at low water--two men who supped at the house being Deists,
I had to contend against them till near eleven o`'clock, yet we parted friendly.

"`11th. The poultry market is pretty good, and fifty per cent,
cheaper than in Philadelphia.
Though this place is in France, the people speak Flemish and French alternately;
their markets, as well as at almost every place where we have been in Europe,
are in the open air, without any shelter;
the buyers and sellers are for the most part women;
the articles are brought to market on the smallest species of asses that I have seen;
their loads being so very large that the poor animal is scarcely seen.

"`First-day, 12th. Had a good meeting at B. Hussey`'s, where about thirty attended,
among whom were some American captains, and several citizens of Dunkirk,
In the evening attended a large meeting, consisting of Americans, French,
and a number of Scotch and English.
The company were remarkably quiet, the doctrine delivered was much opposed to Deism,
with which it was believed some present were tinctured;
the labor was with tenderness in Christian love, and we hoped it had an effect on some.
Prayer and thanksgiving were offered to the Author of all our mercies;
the people parted in much kindness, and we felt an evidence that we are in our places,
though it was through many exercises we got here.

"`13th. The few Friends who remain here are respected by the inhabitants,
the magistrates, etc., through whose kindness they have been exempted from bearing arms,
and at the times of general illuminations they have been signally protected,
which must be esteemed a favor from Him who rules and disposes
the hearts of men to be kind to such as keep his testimonies.

"`14th. Owing to great industry and exertion in cultivating the land,
which is naturally poor and sandy, vegetables are abundant and very cheap;
potatoes and turnips may be bought for about twenty cents a bushel; apples are good,
and in greater plenty than in America at this season of the year.
The people are civil and respectful, especially to Americans.
In the evening the meeting was as large as the room could hold,
and the people very orderly, none appeared restless or went out until it concluded.
It was a favored time, much tenderness being evident in those assembled.
It is indeed cause of admiration to me, that in passing from one nation to another,
we find a tender-hearted people everywhere: the Lord has a precious people in this city.

"`15th. It appears as though we might soon be at liberty to leave Dunkirk for the present.
The people go to their chapels at any time of the day and perform their devotions,
thus at all hours they are going in and coming out;
I could not help feeling a love for them, though I cannot own their superstition,
believing they will be accepted according to the sincerity of their hearts,
when many who think themselves wise philosophers,
will have nothing to yield them consolation.
Got our passes endorsed by the American consul, who went with us to the municipality,
and at his request they gave us new passes, inserting in them that we were Friends,
called Quakers.

"`17th. Leaving Dunkirk, we passed through the city of Burgh,
and before dark arrived at Lille, where, with difficulty we procured a passage for Paris,
one hundred and fifty miles distant.
Lille is a large city, and may contain seventy thousand inhabitants.

"`18th, Proceeded in a cabriolet, which is a very heavy carriage,
takes a great deal of goods, and has eight horses, two postilions, and a director;
we had four passengers besides ourselves.

"`19th. Passed through a number of towns and villages,
and saw many of the people going to their mass houses,
over the doors of which is painted,
'`The French nation acknowledge the Supreme Being and
the immortality of the soul.`' Arrived at Paris.

"`20th. The country is populous, but we see much less travelling than about London.
The city of Paris is crowded with inhabitants,
the houses are of white stone like the plaster of paris; the streets are not kept clean,
and have no paved side-walks for foot-passengers.

"`22nd. We rode to the municipality, where they endorsed our passes;
and going into another apartment to have them sealed,
one of the principal men ordered us to take off our hats.
We told him we were of the people called Quakers, who did not use that compliment to any;
he appeared warm, and said it was no matter what we were,
no person could be admitted before them with their hats on, and came towards us,
as we supposed, to take them off, but one of his companions in office, observing to him,
that we made a religious scruple of it, he withdrew, and growing more mild,
said he always paid respect to religion, and had no more to say if that was the case.
He sealed and signed our passes, and we parted friendly.
A law of France,
which obliges all others to appear uncovered before the National Convention,
exempts Friends by a special clause--there were a number of
persons present waiting to do business with the municipality,
who appeared surprised at our thus bearing our testimony;
perhaps some may reflect on it to profit.

"`23rd. There seems no probability of much religious service in Paris,
except in conversation and distributing books;
and our minds have been much exercised both before and since arriving here,
under a sense of the difficulty of passing through this country at this time;
and laboring to keep to our righteous testimony among a gay and dissipated people,
many of whom make light of all religion.
Over their chapel-doors is placed the inscription before mentioned.
These places are frequented by many pious people,
and mass is performed by a priest who has taken an oath to the nation,
none else being allowed.
I do not doubt that with all the vices and infidelity which reigns in Paris,
there are many of Zion`'s true mourners there;
with such I was favored frequently to feel a secret sympathy.
May the great and universal Shepherd of the heavenly fold,
stretch forth his arm to this nation,
and gather many thousands to the standard of truth and righteousness,
where their tossed souls may lie down in safety and none be able to make them afraid.
In the evening, David Sands and myself fell in with Thomas Paine,
and spent about an hour and a half in conversation about his opinions and writings.
He made many assertions against Moses, the prophets, Jesus Christ, etc.,
which had much more the appearance of passionate railing than argument;
to all which we replied.
I felt zealously opposed to him,
and believe that nothing was said by my companion or
myself that gave him the least occasion to exult:
we bore our testimony against him firmly.

"`Our path on this continent has been through many trials of faith,
and contentions for the faith;
may they all end to the glory of the great Head of the church,
whom I honestly desire above all other things to serve, with my time, talents,
and substance.
This city contains almost everything to gratify the eyes of the curious,
the desires of the voluptuous, the talents of the learned,
and the dissipation of the gay and fashionable world;
but has little to satisfy the soul longing after celestial riches,
and but few in appearance are seeking after it.
The street called the Boulevards, is about two hundred feet wide,
encircles the whole of the city, and is, perhaps,
the most extraordinary street in Europe.
It contains a great number of shops and stalls for the sale of every, species of goods,
many places of vain amusement, and handsome walks with seats,
and is almost constantly crowded with passengers.
It is a great inconvenience to persons walking that there are no foot-ways,
or very few in any part of the city,
so that at the approach of carriages they run in crowds into the houses, shops, etc.,
adjacent.
There are many objects in this great city which excite astonishment,
but the mind grows weary with the iniquity which abounds,
and desires rather some quiet retreat even in the
interior of America than to dwell in such a city;
it made me feel sad and disgusted at the ever-lying vanities of a delusive,
uncertain world.
A passage offering to proceed towards the south,
we concluded to embrace it and leave Paris in the morning.

"`25th. Arrived at Fontainbleau, which has but few manufactures and little trade,
and may contain ten thousand inhabitants.
This morning for two leagues before we got here, there were neither houses nor farms,
but the road bordered by uncultivable mountains, consisting almost entirely of rocks,
or else by wood-land, the towns and villages on the road,
looked as poor as the country around them.

"`First-day, 26th. The weather has been very fine and serene,
the country though not rich was beautiful;
the villagers dressed in their best clothes appeared lively,
walking about in their wooden shoes, which they almost universally wear.
Some were attending their places of worship, but more diverting themselves in the fields,
and appear not to be deeply impressed with trouble for the miseries of war.
The people have many conjectures about us, sometimes supposing we are Spaniards,
Hollanders, Swiss, British or Germans, sometimes Italians, etc.;
We generally inform them soon after our arrival to quiet their minds,
that we are not in any of the characters they suppose us to be,
but Americans and of the people called Quakers,
travelling to see our brethren in the south of France;
this with a present of a few books sets them right, and they use us respectfully.
We endeavor to maintain a conduct void of offence; but are often much tried,
and it frequently appears to me as though I was travelling in
the midst of darkness and could see no light;
yet I greatly desire to be preserved from murmuring,
having had hitherto to acknowledge the mercy and goodness of God,
who has extended his care and protection in the course of the present arduous journey,
in many a trying hour.

"`27th. At Nogent.
It is the time of the carnival, an occasion of feasting and rejoicing all over France,
but the Catholic religion being at present at a low ebb,
this festival is not celebrated with as much pomp as it used to be.

"`28th. Passed through a handsome country, but many of the people live very hard.
The weather being raw and cold today, I pitied the poor shepherdesses,
who sit on the sides of the rocks and mountains, tending, perhaps, a few sheep, hogs,
asses, and goats, on very barren pasture.
They spin all day long, and follow their flocks;
and sometimes ride about the country on very small asses, two women on one,
one of the women looking one way, and the other another way;
but the habits and manners of this people baffle my powers of description.
The country appears to abound in wine, and little else is drunk,
it being generally a very light claret.

"`1st of Third month.
Being a remarkably fine morning, I set off alone before the carriage,
and after walking six miles along the side of the Loire, and passing two villages,
stopped for the voiture; the country was pleasant and hilly.
Passing on, we met about two hundred German prisoners, who had been taken at Mantua,
and were in a most deplorable situation, almost exhausted in every respect,
many of them having neither shoes, stockings, hats, nor shirts;
the miseries of war were very affectingly painted in this spectacle of wretchedness.

"`2nd. Arrived at Moulin in the afternoon; a considerable, but not a handsome city,
principally occupied in making muslins, which the women spin,
while walking in the streets.
Our cabriolet leaving us, we were obliged to take what they call a chariot de post,
which is nothing more than a small cart without sides, at each end a basket,
and in the middle a straw bed for the passengers to sit on, back to back,
with their legs in the basket; they carry four persons, have a little horse or mule,
and a postilion,
and these appear to be the only carriages that travelers can obtain in France,
except they travel in the national cabriolets with eight horses;
or have their own carriages, when they may obtain post-horses.
This was a very trying day to my mind; darkness seemed to cover my spirit.

"`3rd. Left Moulin in the disagreeable chariot de post or potache;
passed through a mountainous country, mostly covered with vines,
and got to Pallisee in the evening.
There are but two inns in this place, kept by father and son,
who were the only persons from whom we could obtain a convenience for travelling,
and they did not fail to take advantage of us, charging at least fifty per cent,
higher than the best inns and carriages in America.

"`4th. Finding no other way of travelling, we resumed our potache,
passed over a country more mountainous than any heretofore, until we arrived at Rouen,
situate on the side of the Loire, a city that may contain twenty thousand inhabitants.
At the Table d`'Hote, were a number of Frenchmen, who treated us politely,
and finding they had a desire for religious information, we gave them some books.

"`5th. The country, as yesterday, is covered with vines and mulberry trees;
arrived about dusk at a large town closely environed by mountains,
the inhabitants employed in manufactories of muslin and silk.
They were differently dressed from any we had yet seen, and remarkably friendly;
indeed the frankness of this nation does not
allow us to remain strangers more than an hour;
seeing but few strangers, especially from other nations,
they are curious in their inquiries.
We passed a very disagreeable night, and as soon as it was light,
were glad to rise and proceed on our journey.

"`6th. Arrived at Lyons in the afternoon, and pm up at an auberge,
perhaps the largest we have seen in Europe,
forming a hollow square about two hundred feet on each side:
this city contains about one hundred and forty thousand inhabitants;
one-third is built on a very steep mountain, on the side of the Rhone; many parts,
however, now lay in ruins, being battered during a long siege.
We are a spectacle to many; my mind is heavy and disconsolate:
the ways of the Lord are a great deep, but I dare not murmur,
he is good and worthy to be adored, both in suffering and reigning.

"`7th. Finding a boat that was to go off at eleven o`'clock for Avignon,
one hundred and thirty miles, we took our passage, there being about twenty of us ia all,
and sailed down the stream eight leagues.
The country, on each side, is very beautiful; arrived at a village in the evening,
where the keepers of the inns rushed down to the shore,
and almost compelled us to enter their houses,
and perhaps twenty girls and boys were waiting to take our baggage, and earn a few sows.
A genteel man, a merchant, who had a coach on board, took us under his protection,
and we got to tolerable lodgings.

"`8th. Proceeded early down the river and met a number of boats going up to Lyons,
loaded with wine, etc.
Three or four of these being fastened together, are drawn by horses,
as many as twenty being necessary to draw them up against the stream, which,
in some places, is rapid--the mountains are planted with vines to the tops,
but in some places interspersed with olive, almond, and mulberry trees.
The Alps, about eight miles distant, are covered with snow.
It being uncommonly low water in the Rhone, our boat got aground twice,
but having four stout horses in a smaller boat which they tow after them,
for the purpose of relieving them when aground,
after an hour`'s labor we got afloat again, and arrived at Valence in the evening, which,
like most of the cities in the south of France, is very ancient,
and may contain eighteen thousand inhabitants.

"`9th. Embarked early, but having a strong head wind could not proceed far.
We went on shore and walked to a city about a mile distant,
said to be built and fortified by Julius Caesar, and called Montlemar;
it has high strong walls, and bears all the marks of great antiquity,
has little riches or trade.
No auberges or taverns, within the walls, being permitted to lodge travelers,
we went to several outside, but could find no lodgings;
it being on the main road from the south to Lyons, they were filled with guests;
at last we got to a poor inn where they took five of us:
my state of body and mind rendered me more unfit to endure hardships than at other times.
Most of these ancient cities have more or less of Roman monuments yet remaining.

"`10th. The wind continuing very high and right ahead,
and the waters so low that our captain thought with
such a wind it would be impossible to proceed;
we accepted the kind invitation of our friend, the merchant of Circasson,
who had a coach that would take four and offered us places in it as far as Nismes;
so taking post-horses at Montlemar, we arrived at Point Esprit before dark.
This city is a very ancient, dark-looking place, may contain eight thousand inhabitants,
and was built by the Romans; the streets are so narrow generally,
that no wheel-carriages can pass; their fagots and other things are carried upon asses.
These ancient cities generally have a melancholy appearance,
so as to damp the spirits of the most animated stranger; the bridge at St. Esprit,
which crosses the Rhone, is a very ancient and handsome structure, more than a mile long.

"`11th. Went on about seven miles:
there is great danger in travelling on account
of robbers and assassins who infest the roads,
so that none care to travel after night.
The mail was robbed on a mountain which we crossed today,
and some travelers have been robbed and murdered lately in this vicinity,
which makes it a very trying time to travel in France.
We went to the municipality, who endorsed our passes and behaved friendly;
and some persons being desirous of information, we gave them several books.
Our kind friend, the merchant, inclining to stay here a few days,
we "`were obliged to take a potache for Nismes;
the people of the auberge taking us for priests, behaved respectfully.

"`First-day, 12th. I was very unwell, and the weather being misty and cold,
and the chariot de post open, with only a little straw to sit on,
and there being two women passengers besides us three, we were uncomfortably situated,
and travelled very slowly,
having only a little horse and a mule to carry us and our baggage.
The country is highly cultivated, covered with vines, almond, olive and mulberry trees.
We passed several crucifixes and images on the road,
but most of all within six miles of Nismes.
As we travelled only about three miles an hour,
we did not get to Nismes until candle-light, not quite thirty miles.

"`13th. Nismes contains about forty thousand inhabitants,
chiefly employed in silk manufacture;
it was the first place in France where we were questioned about the national cockade,
but our reasons satisfied them.
We hired a voiture to take us to Congenies, about three and a half leagues.
The country between Nismes and Congenies, though somewhat mountainous, is fine;
the people seemed pleased at seeing us, and immediately judged we were Friends,
having seen those who were here eight or nine years ago.
We went to Louis Majolier`'s to lodge, and several of the Friends being there,
they received us with strong marks of affection and joy.

"`14th. Our friends flocked to see us, and saluted us with tears of joy;
much mutual consolation was felt,
and they furnished us with the best provisions the village afforded.
In the evening about thirty-five of them being with us,
we desired them to retire into silence, for which they appeared prepared:
mercy and goodness were evident in covering us with a precious solemnity,
a few sentences being offered in much brokenness,
they received it like the thirsty ground; after which,
our friends Pierre Robinel and Magdalene Benezet,
both bore testimony to the continued goodness of the great Shepherd,
towards the few scattered sheep in this remote corner of France.
Our valued friend, Louis Majolier,
also added his grateful acknowledgments and confession of unworthiness of Divine mercy,
in much tenderness and with many tears.

"`15th. The weather is very fine, the almond and peach trees are in blossom,
and the olive, figs, etc., out in leaf.
I never was in a country where there was more unaffected simplicity than here.
Shepherds and shepherdesses, are scattered about tending their flocks,
and knitting or spinning at the same time; having very few cows or goats,
they milk the ewes, which affords them a sufficiency,
and they think the milk richer than cow`'s milk.
In the evening we had some conversation with them on their present state as to religion,
and from the information of +++_______+++ Robinel, an ancient man,
it appears that for sixty years at least,
there has been a number of religious people in this neighborhood,
who had separated from the common ways of worship, and were by some called Inspirants.
Their attention was first turned to Friends by information in the public papers,
of a young man who came to Paris and advertised that the owners of a vessel and cargo,
which was taken by the British in the war with America and France,
were requested to come forward and claim their
several proportions of the said vessel and cargo;
and that his father, who was part owner of the ship which took the French vessel,
was a Quaker, and did not desire to hold their property,
as it was inconsistent with his conscientious scruples.
They then made inquiry respecting the principles of Friends,
and found them much the same as their own.
After this, being visited by Sarah Grubb and company, and confirmed in their sentiments,
they continued to profess the principles of our religious Society,
and have passed through many trials lately, some having been imprisoned;
they were truly glad to see us, believing we had come in an acceptable time.

"`16th. We visited twelve of their families.
When speaking to Louis Majolier in imperfect French, he repeated it in better,
or rather in what they call the Padua language, which is bad French and Italian mixed,
and hard to be understood.
Dined with Jean Benezet, the husband of Magdalene;
being affectionately desirous to serve us, they provided a great variety of food:
the wine is of their own manufacture, such as is commonly drunk here,
being similar to the American cider, and not stronger.
In the evening we had the company of many of these Friends,
and hope it was a time of encouragement to them.
I could not but repeatedly contrast the circumstances of these persons,
with that of my dear friends at home and in England.
O! the sweet simplicity and innocence of this poor, industrious,
but apparently happy people.

"`17th. Taking a walk, on our return we were met by a number of our friends,
who took us into a house where they had spread a table with bread, butter,
and a variety of fruits, showing their assiduity to make us comfortable;
the innocence of their manners and their desire of improvement by our visit among them,
was so forcibly impressed upon me,
that I was constrained to turn aside and pour forth tears of gratitude and joy.

"`18th. Visited the remaining families, and find there are seventeen in all; the men,
women and children, are mostly employed in vineyards,
or cultivating olives and making oil of them, or raising sill;-worms;
though there are some weavers of silk,
and some of wool and linen for the use of the villagers.
They appear to have but little in the world, and yet are contented,
as much so as any people I have seen on the continent;
their dispositions and manners evidently
different from the other nations we have visited.
The village contains about one hundred and fifty
houses and six hundred and fifty inhabitants,
all of whom have been civil and respectful to us.
There does not appear to be any person of high character or riches among them,
but a remarkable equality reigns throughout the whole.

"`19th. Attended meeting in the usual place, where several not Friends were present;
the whole number supposed to be about eighty, and it proved to be a solid good time.
Having yesterday felt our minds turned to write our views and
feelings respecting the state of the Friends here,
and to add some admonition, encouragement, etc.,
Louis translated it and read it at the close of the meeting,
during which most of the assembly were much contrited.
We then separated under a thankful sense of the goodness and
mercy of the gracious Shepherd of the sheep.
Their usual practice being to hold but one meeting on First-day,
we appointed another to be at three o`'clock in the afternoon: before the time,
the room was filled, many coming from Fontanes and other villages not far off;
the opportunity was satisfactory,
and ended in prayer and thanks to Him whose is the power and the glory.
In the evening, about eight or ten men and five women, the most noted among them,
came to have a free conference with us respecting establishing some order and discipline,
and a Monthly Meeting, which has been dropped several years,
though there had been some little care of the poor,
and also over the moral conduct of the members; but as the time was short,
we separated without attempting anything.

"`20th. Walked to Calvisson, a village three miles distant,
containing three times the number of inhabitants of Congenies.
None appear to profess with Friends,
except the father of Louis Majolier and his sister-in-law,
who do not attend the meetings at present.
In this part of France, villagers and peasants seem to be the only inhabitants,
few or none of rank or wealth.
On a mountain by the way, we saw the Mediterranean sea,
and had a most extensive prospect of vineyards and olive-yards:
the air as fine and pure as France affords, or perhaps any other country.

"`21st. In the evening,
about forty men and women Friends assembled to revive their Monthly Meeting;
many of them lament the lack of proper discipline,
and are very desirous of adopting as much of our
order as may be suited to their circumstances.
Louis Majolier being chosen clerk,
it was agreed to procure books for entering fair minutes and for recording births,
marriages and burials: they then nominated two men and two women overseers;
some remarks were made and we gave them such information as appeared proper;
they then recorded our visit on their minutes,
and agreed to hold their Monthly Meeting at a stated time in future.

"`22nd. I looked over the old minutes of the Monthly Meeting,
where they had recorded some certificates and letters, etc.
It appeared that two men and two women had laid a concern
before them to visit the families of Friends at Gilles`'s,
which they performed;
that there were several marriages solemnized nearly in the same order as Friends;
that they had issued advice to be honest and punctual in their dealings,
and to walk in all respects consistent with their profession;
that they had dealt tenderly with some who walked disorderly,
and at length disowned one who would not be reclaimed; they also took care of the poor,
and recorded the certificates of our friends, George and Sarah Dillwyn,
Robert and Sarah Grubb, Mary Dudley, Adey Bellamy and John Elliott,
who visited them in the year 1788.
Upon the whole,
there was more consistency than I expected to find--and
as they now appear reanimated to commence again,
I feel a hope they will be supported; many of them are in a state of weakness,
and they know it, and are willing to receive counsel.
On inquiry, I find there are a number of families scattered in different villages,
who hold the same religious opinions, and at times attend their meetings.

"`23rd. Benjamin Johnson was very poorly, and but little medical aid could be obtained.
We deferred going to Gilles`'s, and our minds are closely exercised,
yet thanks be unto Him who in mercy has hitherto carried us through all;
I endeavor to cast my care upon Him in this sequestered corner of the world.
In all the village of Congenies I believe there is not
one shop for the vending any kind of goods,
yet the simple needs of the inhabitants seem to be supplied,
and they are continually bringing us various kinds of fruits, preserves, nuts, etc.;
no people need be more kind or sympathetic than they appear to be.
Their fuel is principally the trimmings of the grape-vines, olive, mulberry,
fig and almond trees,
and at times the wood of such trees as die or are blown up by the roots;
it is sold by weight.
I have not seen a forest of timber-trees, for two hundred miles.
The olive-yards endure a long time,
and do not arrive at their most fruitful state in less than fifteen years;
I have seen several from one hundred to one hundred and fifty years old,
which are highly esteemed--they trim them almost to the stump every year.

"`24th. Walked with Louis to a part of his ground where we planted some potatoes,
which are not much known or used here;
observed many men and women pruning their trees and vines;
they work diligently among their olives, almonds, mulberries, vines, etc.,
but do not appear to be as laborious people as the Germans,
yet they generally live better.

"`25th. Our friends Louis Majolier and Pierre Robinel accompanying us,
we rode out to a village about one and a half leagues from Oongenies,
and were met in the road by an ancient woman who goes under the name of a Friend;
much pleasure was pictured in her countenance,
and she conducted us to the house of one also professing as Friends;
they set before us some bread, honey, and wine, with a little cheese,
made that morning of ewes`' milk.
After waiting about one hour, eight of those called Friends came;
others being gone into the fields, we did not see them.
We sat down in religious retirement with this little company,
who appeared to be less conformed to our practice than those at Congenies,
yet were serious.
Something was given to express for their encouragement in
pursuing the way of Truth as it opened on their understandings,
and to meet together to wait upon God on First-days, and to visit,
as frequently as convenient, the meetings of Friends at Congenies;
after which we returned.
Though the roads in France are generally pretty good,
there is scarcely any such thing as travelling fast, their poor little horses, mules,
and asses, seldom going more than three miles an hour.

"`First-day, 26th. The meeting in the school-room,
which is at present their only meeting-place, collected about ten o`'clock;
the fore-part was somewhat interrupted by a number coming late, and the room was crowded,
but being at length gathered into stillness,
the great Master of assemblies favored with his presence:
a remarkable solemnity continued for near an hour, very refreshing to our spirits,
and we were persuaded to many of theirs also.
Feeling my mind at liberty,
I expressed a number of Scripture passages among them with some addition,
and thought I had never been so favored to express myself in French before;
great tenderness prevailed among both old and young: Louis made a very suitable addition,
and the people parted, we believe, through infinite condescension,
comforted--there were upwards of eighty present;
several professors came from the adjacent villages,
and shed tears of joy at meeting with us:
there were also some who had never been at a meeting of the kind before.--
Louis`'s religious father and mother-in-law from Fontanes dined with us.
In the afternoon, about the same number attended the meeting,
and the people who came from other villages
parted with us and their friends here in tears.
In the evening, had a conference with the overseers,
with those who speak in their meetings, and with some other leading members;
on their own motion it was agreed to hold henceforward two meetings on First-days,
and one in the middle of the week, if the next Monthly Meeting united with it;
this opportunity afforded us a free expression of
sentiment on subjects relating to their welfare.

"`27th. Louis, his wife, and myself, went to visit her parents and family at Fontanes;
the country is hilly, yet covered with vines, the soil very poor,
though there are delightful valleys among the mountains;
but I have seen neither cows nor oxen since leaving Nismes; but sheep and goats for milk.
Passed through a village where were several large and once elegant buildings, gardens,
etc., belonging to a cidevant nobleman, now totally ruined;
a cross and a crucifix of enormous size, lay in scattered fragments on the ground.
As we advanced towards Montpelier, I felt desirous of visiting it,
but it was not practicable.
Arrived at Fontanes,
where the good old people and family of Samuel Brunn were much pleased to see us;
the kindness, simplicity, and genuine hospitality of this house, was truly grateful;
after spending about three and a half hours with them, we took a most affectionate leave,
not expecting to see them again:
most of the family walked half a mile on the road with us, loading me with fruits, nuts,
etc., accompanied with their blessing and desire for my safe return home.
We got back to Congenies about dusk, and found Benjamin still very unwell.

"`28th. In the evening, accompanied by Louis, I visited seven families,
which appeared to be agreeable and reviving:
having found my mind concerned to leave with them in writing,
some further counsel respecting holding their meetings for worship and discipline,
with that solemnity becoming the occasion, I got it translated,
and concluded to have it read at their Monthly Meeting.
I believe these tender, good people, would find their meetings more useful,
if they were kept more in silence;
they have four persons who appear by way of ministry in their meetings,
three of them we cannot doubt have received gifts; yet one or more of these,
we hope may improve in weight and usefulness,
by an increasing disposition to wait all the Lord`'s appointed time,
to qualify them to administer to the greater edification of the church.
Our friends here have not yet banished that lively
activity of spirit and quickness of imagination,
so characteristic of their nation,
and may be in danger of carrying it into their most serious concerns;
they do not appear to have that visionary disposition
and desire of penetrating hidden mysteries,
so observable in the Germans; and indeed the two nations differ in almost everything.

"`30th. Our friends collecting at ten o`'clock, we sat down with them.
The silence was truly solemn and affecting,
and the thought of parting was deeply felt on both sides.
I took leave of them in the best French I could, Louis mending it in some places;
after which, David Sands concluded in prayer: we embraced them all with tenderness,
and parted in heart-felt sympathy and affection, with many tears and pious wishes.
We mounted, David on a bidet, I on a very poor little mule: Louis Majolier,
Pierre Kobinel, Pierre Marignol, and Pierre Benezet, having two asses between them,
accompanied us.
I rode about a league, when my mule kicked and flounced about,
and showed so many obstinate airs, that I was willing to exchange it for an ass,
but had not rode two leagues more, before the little animal stumbled on his knees,
and slipped me over his head, without damage, however.
I then remounted my mule,
but soon after arriving at a village where it had an inclination to stop, he kicked,
and refused very obstinately to go on; however, at length,
with the assistance of the spectators, I got through the village,
and he afterwards behaved with more decorum during the journey,
travelling at the rate of two and a half miles an hour.
Our whole business on this continent has one tendency, namely, to teach us patience;
and we shall be poor scholars, indeed,
if we return with as low a stock as when we came from home.

"`My mind feeling sweetly relieved, at parting with my dear friends at Congenies,
I passed along without complaining, the weather being fine,
and the country covered with blossoms and verdure.
I did not wish myself at any other place, nor in any other company, for the present,
believing we were moving in the way of our duty.
The country, in the vicinity of Gilles`'s, was more hilly, and the whole,
with a very few trees interspersed, was covered with vineyards,
the cultivation of grapes being almost the sole occupation of the people;
yet in the valleys they raise some wheat and rye.
There are very few cattle in this part of the country,
though as a rarity we saw two young oxen; horses are very scarce,
but they have excellent mules for their wagons.
We arrived safe at Gilles`'s in the evening,
the road being the nearest way from Congenies,
was in many places not practicable for carriages; the distance, said to be five leagues,
occupied six hours, without halting.
Our guides took us to the house of one professing with us, where we were received kindly,
and several of those, called Friends, came to see us, and supped with us.
Our landlord is an old man, and perhaps the richest of those, called Quakers, in France;
we were well accommodated, both as to provisions and lodging.

"`31st. Several of those called Friends came to see us,
and with some of them we walked about three quarters of a mile to the Rhone:
the land between the town and the river, was mostly sown with wheat and rye,
which looked well.
After we returned, there being several present and a good deal of conversation, David,
Louis, and myself, retired to our chamber.
It is not beneficial to enter too freely into conversation about things
which have little or no connection with our main business among this people,
and therefore we find it best sometimes to withdraw,
for they are a people very fond of talking.
In the evening, about forty attended our meeting and behaved orderly,
though we sat in silence about an hour,
when I thought it right to deliver a few expressions, to which they paid attention; yet,
except in a few instances,
there did not appear to be that preparation to receive the
word which was so evident in our friends at Congenies.
Louis afterwards urged the necessity of their adding more of
the works and fruits of the Spirit to their faith,
without which the good profession they had made to the world would neither
yield them peace nor be a light sufficient to guide others into the Truth.
There appeared some tenderness, all were quiet and seemed retired in their minds,
yet I thought it altogether a time of suffering,
and there was less of the cementing power and love of
Christ to be felt than in the meetings at Congenies.

"`Fourth month, 1st. From the top of the hill above the town,
there is a prospect of a fine extensive valley with a canal in the middle.
On the side next to the Rhone,
it appeared to be as handsome and rich a spot as I had seen in France;
but one of the Friends in company said it was not of more than half the value,
nor did it yield half the profit of the hills of gravel
that surrounded all the other side of the town,
extending several miles, and covered with vines,
but so poor that it appeared as though it would yield little or no grain or grass,
yet produced the finest wine in all Languedoc: the valley was too rich and damp for wine,
and two acres of it would be given for one of vineyard,
and the vineyard cost as little labor per acre as the grass or grain.
The grapes raised on rich land make the poorest and thinnest wine;
but the more dry and poor the land, if the vines will grow at all,
the stronger and more excellent the liquor; this is a fact established by experience.

"`This city contains six thousand inhabitants, a few of whom are Protestants.
Before the revolution, they had twenty-nine Catholic priests to support,
at present they have but one large and very ancient chapel remaining,
and but two priests;
the women appear to be going in and out of their chapel all day and seem devout,
but very few men pay any attention to religion.
It is a lively industrious place,
and has a considerable trade in wine and brandy up and
down the Rhone--they sell almost everything by weight,
as apples, nuts, oranges, etc; in the market they were weighing live eels,
and had much difficulty to keep them in the scales.
The Friend at whose house we are, has a large family of children,
and is a great cultivator of the vine, etc;
having about five hundred acres of land on rent, at from two to three guineas per acre;
another of the Friends has also about the same quantity,
and they appear to be men of the first rank in this place.
Those professing with us,
appear generally to be in more easy circumstances than at Congenies.
Dined at one of those Friend`'s who had a plentiful table and the finest fruits, raisins,
figs and grapes, almost as fresh as on the vines.
After dinner, sitting down with the family, a solemnity covered us,
in which David Sands and myself had something to offer.
Mary, the daughter of David Ventigole,
also bore a lively and tendering testimony in much humility.
I thought I had not heard the Gospel preached more in
the demonstration of the Spirit in France;
she has appeared a few times in their public meetings.
Going out to take a little walk alone before dark, one of the Friends came to me,
and I went back to his house and spent a few minutes
with him and his wife to much satisfaction,
they being a valuable couple who love the Truth.
The more we know the people here, the more our love increases toward them.
I was at the house of a lame man, a tailor, who appears to be a steady, religious person,
and says he never asks one price for his goods and takes another.

"`First-day, 2nd of fourth month.
At the meeting this morning in the house where we lodge, about sixty or more attended,
who behaved with remarkable decency and solidity.
About an hour passed in silence, then Pierre Robinel, Pierre Marignon,
Louis Majolier and myself had each a few words to offer; after which, Mary,
daughter of David Ventigole, bore her testimony, which was edifying and sound,
delivered in much humility, and had considerable effect on the audience.
After the meeting closed, Louis read the same writing that was read at Congenies;
the truths contained in it touched several of them sensibly:
we were satisfied with the meeting,
believing the great Master of assemblies favored with his presence.
In the afternoon, the meeting was attended by some Catholics and some Protestants,
and concluded in much brokenness,
and a humbling sense of the renewed love and mercy of our heavenly Father.
At seven o`'clock in the evening,
we had about ten men and four women of the principal persons in our room,
to propose for their consideration tue propriety of establishing an order and discipline;
some of them expressed their opinion of its fitness,
and we then left it under their consideration.

"`3rd. Dined at David Ventigole`'s; he told us he owned about eighteen hundred sheep,
seven hundred and fifty of which were milked by the shepherds and shepherdesses twice,
at noon and midnight, and do not afford quite a pint per day each;
he has also fifty-six oxen, fifty horses, seventeen mules, and ten asses,
and employs from one to two hundred persons, according to the season,
but seldom has much less than one hundred.
Our landlord has about the same amount of stock, and employs as many people,
but he has twenty-seven hundred sheep; the reason we have seen no oxen is,
that they keep them on the mountains.
Those professing with us here, who employ so many people,
have no small influence in the town and neighborhood:
they are very generous and hospitable,
but in general not quite so susceptible and tender as our Friends at Congenies.
Some of the young women wear crosses of gold;
one of them said that hers cost more than a louisdor,
but she and some others had taken them from their necks.
We had a free conference with those under our name about some matters in their dress,
etc., which they received in love, acknowledging their weakness.
The Society here, as well as at Congenies,
has been subsisting for sixty or more years under the name of Inspirants,
until they became acquainted with the principles, of Friends.
I believe if the Lord should put it into the hearts of
other more qualified brethren or sisters to visit them,
it would have both its use and reward, especially if they understood the language well.
In the evening, the meeting was attended by about forty,
and I thought it the most solid of any we had with them.
I believed it best to speak without the assistance of an interpreter,
and by attending to my concern and proceeding deliberately,
I found myself more relieved and satisfied than since I came into the south;
the meeting for worship concluded in prayer by David Sands.
Louis then read some of the thoughts I had written respecting worship,
and the solemnity in which all our meetings ought to be held;
then we had a free conference respecting the nature and necessity of church discipline,
and parted with serious impressions.

"`5th. This forenoon, after a short time of retirement with the family where we lodged,
and some others who came in, we parted in much love;
many were waiting without to take leave of us, which they did affectionately,
but many more not being present, I felt tried at leaving them.
We went on, however, accompanied by several of our friends,
some of whom went a mile or two on foot, and appeared affected at parting.
Proceeded to Nismes three leagues:
several persons came to offer us a conveyance to Paris,
but we thought we had better buy a carriage and take post-horses.
In Nismes, there are many curious Roman remains of great antiquity--an amphitheatre,
said to have been built before the birth of our Saviour,
capable of containing seventeen thousand persons; a temple of Diana,
and an extraordinary fountain and castle of the same age.
Having procured a carriage,
after dinner all our dear friends from Congenies and Gilles`'s, except three,
took a most affectionate leave of us,
such as I trust will not soon be forgotten by any of us.
