== Chapter V.

[.chapter-synopsis]
* Leaves Congenies
* Impositions
* Vienno
* Lyons
* Incidents of travel
* Poor quarters
* Robbery and its event
* Accident on the road
* Difficulty of religious labor
* Renewed imposition
* Mean fare
* Catholic chapel and ceremonies
* Arrival in Paris
* American consul
* Renewed difficulties
* Notice of Paris
* Ruins of Prince Conde estate
* Dunkirk
* Character of the French
* Rejoicing at the prospect of peace
* Difficulty of procuring passports
* Arrival in England
* Renewed religious engagements
* Printed sermons
* Isle of Wight
* Island of Jersey
* Descendants of Mary Dyer
* Guernsey
* Prisoners at York
* Liverpool
* Isle of Man
* Interesting interviews and meetings
* Swarthmore
* Services in the north of England
* Scotland
* Edinburgh
* Dunde
* Urie and Robert Barclay
* Aberdeen
* Penitent hearers
* Return to Edinburgh
* Glasgow
* Ireland
* Belfast
* Boarding-school
* Poverty of the people
* Romish funeral
* Dublin
* Distribution of alms

"`6th. Parting affectionately with our three friends from Congenies,
we passed through a number of villages, and arrived at Bagniol, took some refreshment,
and proceeded to Pierrelatte, having travelled nineteen leagues today.

"`7th. Leaving Pierrelatte we got to Montelemar, and while we were in the auberge,
a smith, without our order,
put a piece of iron round one of the wheels of
our carriage under a pretence of mending it,
and demanded three shillings sterling for his labor; but as we had not employed him,
we endeavored to show him the unreasonableness of
meddling with our carriage without consulting us;
and not without a great many words we obliged him to take it off,
as we saw it would rather injure than help the wheel.
The postilion also demanding an unconscionable fee, we were obliged to dispute it;
but many people gathering round, we felt unpleasant,
and to rid ourselves as well as we could, paid our money for the sake of peace.
It is not uncommon to have a host of importunate people to contend with in
France and other places where we have travelled on the continent,
which with other things, makes it very exercising for Friends to travel;
that we have need of a double supply of meekness and wisdom to
pass along and keep a conscience void of offence.
We got to Tain and lodged, being twenty-three leagues.

"`8th. Passed over a mountainous country.
I alighted from the carriage and walked through the city of Vienne,
on the side of the Rhone, with the Alps to the east.
It is very ancient, and has some remarkable places of worship, much defaced at present;
it is about a mile long, and crowded with inhabitants; after crossing a high mountain,
we arrived at St. Symphorien and put up at a poor inn.
The postilion seemed desirous of taking advantage of us as we were strangers,
and with some pecuniary sacrifice, I got him quieted.

"`Fourth month, 9th. Arrived at Lyons about twelve o`'clock.
Benjamin Johnson being much weakened with his late sickness, had now another attack,
and having a long journey before us, it was a time of discouragement and trial to us all,
yet not without a ray of faith an I hope in that mercy and goodness,
which has been our support and preservation through the
course of our journeying both by sea and land.
His company has been useful,
and the giving up his time and substance to
accompany one so unworthy as I often feel myself,
will I trust be recompensed to him by the gracious Dispenser of every blessing.
We travelled but four leagues today,
and had to pay double the usual rates for the last two,
it being established by law that the last post entering in,
and the first going out of Lyons, Paris, and other great cities,
travellers shall be subject to that additional price; the fixed rate in common,
being thirty sous for each horse for two leagues.
In our circumstance the law requires us to be
furnished with three horses and to pay for four,
but they generally incline to go with two and take pay for three and a half.
Having arrived at Lyons without deciding what auberge to put up at,
our postilion took us to a good one opposite the grand promenade.
The Rhone and the Seine pass by this city on opposite sides,
and meet a few miles below it.
Many of the shops were open, although it was First-day,
and many booths of goods were exhibited for sale.
It is very thickly inhabited, perhaps no city that we have seen, more so,
except London and Paris.
We were informed there was some worship today, both Protestant and Catholic,
but that the priests who had not taken the oath,
performed their devotions privately in chambers, etc.
The people are in an unsettled state respecting religion,
yet doubtless there are many pious souls all over France,
who lament the decay of religion among the people.
It appears to me that the all-wise Ruler of the universe,
is preparing a way for the Truth to be preached in this country.
We distributed some books and left Lyons about twelve o`'clock,
though my mind and also David`'s were not a little turned towards Geneva,
but on account of several circumstances,
we were upon the whole induced to move towards Paris.
At the end of the first stage,
we were again brought to some hesitation about going to Geneva,
yet concluded to proceed as far as Macon;
our way is strewed with circumstances unusual to Friends.

"`11th. Passed through fine roads, and a delightful country, nine leagues to Macon,
lodged at one of those immensely extensive inns
which are found in many places on this continent,
exceeding in size any I have seen in England or America.
The kitchen and other offices are so far off,
that it was with difficulty we could get what we had need of,
though the waiters seemed active and ready to oblige us when they knew our needs.
Here we were told there were thirty priests who would not take the oath,
and remained in confinement, assisted by the charity of the people;
there were also both Protestants and Roman Catholics who held open worship.
The people had their different opinions about us as heretofore,
not a few pleased themselves with the thoughts of our being priests in disguise.
Seeing the castle where the thirty priests were confined, about a mile distant,
I took a walk in company with a young man that way, but not being permitted an entrance,
and it being warm, stopped at a little cottage, where was only one person, a woman;
we asked for some water, which she got, and said she had something better for travellers,
and brought a fine bunch of half-dried grapes: said she had lost a son in the war,
and whether her husband was living, she did not know.
We observed to her that her`'s was a solitary life in a place so hidden;
she replied that she had some neighbors who wanted her to live with them,
but she had the company of the good God, who was better than ten husbands,
and all her children.
Macon is a considerable city: the Saone passes through it.

"`Fourth month, 12th. Left Macon, and proceeded through a delightful country,
which I thought might be called the garden of France; got to Sennez,
about nine and a half leagues; the women here work in the fields,
and appear to be a hardy race of people.

"`13th. Benjamin Johnson continuing very poorly,
and the people of the auberge being agreeable, we concluded to stay here all day.

"`14th. Passed on through Chalons; the stable for the post-horses and carriages,
a large building, was formerly a magnificent chapel,
some part of its ancient grandeur still remaining.
In the evening got to St. Emilian, a poor village, and as it was raining hard,
and near night, we were obliged to stop and take up our quarters at a very sorry inn.
After a poor supper, having occasion for something in our saddle-bags,
they were not to be found.
A number of people, apparently of bad character, being at the inn,
we made our loss known, searched in all the places we thought it probable they were,
but in vain, and we went to bed.
The rain came down on us through the thatched roof,
and the people were coming in and going out of our room frequently, which,
with the idea I had of their ill-character, and the probable loss of our bags,
kept me in such a situation as to allow of but little sleep.

"`15th. Rose early, went into several houses and informed of our loss;
I also inquired the character of our landlord,
and found they had little to say in his favor.
I then thought of going back to a town, about two leagues off,
in order to obtain advice and assistance, and had procured a horse for the purpose,
but a person sitting in the house, told me my going back would be quite useless,
that I might rest assured the valise was in the village.
I inquired for a magistrate, and the people of the inn denied any being there,
but a man somewhat more respectable than the rest, took me aside,
assured me there was one, and he would conduct me to him.
The magistrate appeared to be a man of integrity, and offered to assist us:
I gave him a description of our property,
and promised a reward to the person who should produce the valise;
he had a drum beat round the village to alarm the people, which succeeding,
a man in half an hour came to the auberge with the valise,
said he had found it in a stable, at some distance, covered with hay,
but his countenance was evidently marked with guilt and confusion.
We gave a reward of a louis, and prepared to leave a place we were heartily tired of.
The bag, besides clothing, contained a number of letters, papers, etc.,
and we did not perceive that anything was missing.
Passing along a fine country, and through Autun,
a handsome and beautifully situated city, we got to Chissey, a small village,
where we had some repairs done to our carriage, but had proceeded only about a mile,
when one of our springs breaking, we had to return.
The innkeeper had taken possession of an ancient castle of some cidevant nobleman,
which he converted into an auberge.

"`First-day, Fourth month, 16th. Passed through Salies, a considerable city,
and it being, what is called, easter, the people were dressed in their best clothes,
and collected in large companies, amusing themselves agreeably to the customs of France,
and appeared all activity and vivacity.
Arrived at a small city called Avalon: great numbers of people, of both sexes,
were on the promenade, which all the large towns have.
David and I walked through the place among them; they behaved respectfully,
but gazed much at us:
there can scarcely be a more exercising service than we are engaged in,
to minds like mine.
We frequently feel as though there were some
religious people in the places we pass through,
but are at a loss how to select them, or be of much use to them,
as none of us know the language sufficiently; we, however, at times converse freely,
and sometimes spread books.
I doubt not but the day draws nigh,
when the word of the Lord will be sounded under his own
authority to many who have hitherto sat in darkness.
At present we feel rather a spirit of heaviness and mourning than any
pointings of Truth to gather the people to the true standard;
probably the time is not now, and may we possess our souls in patience.

"`17th. Passed through Auxerre, Bassou, etc.;
this seemed to be a high day with the inhabitants: all the country was full of mirth,
and shall I say wantonness?
Arrived at Joigny, a large town,
where also the people were scattered like flocks all over this beautiful country,
round the city as well as in it, dancing, etc.
O! France, how dissolute and thoughtless are many of your inhabitants,
who have certainly not learned the things which belong to their peace,
though their chastisement has been heavy.

"`18th. This is a fine country of wheat, but few people at labor,
mostly engaged in diversions and sports: at Sens, a considerable city,
we had to stop to have our carriage mended,
the rough pavements of France being very destructive to carriages.
The people in this country seem to think it is
not improper to get all they can from travellers,
and therefore charge for their work,
about three times as much as would be a just compensation for their trouble.
The blacksmith charged us twelve shillings and six-pence sterling, for two hours`' work;
these continual impositions make our travelling amount to three and a half guineas a day,
though we have often no full meal but supper.
The charges for post-horses are high,
and we content ourselves almost all day with bread and cheese, some smoked herring,
apples, nuts, and some poor wine.
The chapel of the former bishop,
in which a priest was officiating to several hundreds of the people, mostly women,
was the largest and most magnificent I have seen in France; the paintings,
the multiplicity of ornaments outside, etc., bespoke it to be very ancient,
and were also a testimony to the unnecessary and inconsistent
manner in which these buildings were erected,
six or nine centuries past.
The people go in procession, near kindred and acquaintance, two and two, to the chapel,
with an infant to be baptized, and return with a drum and music before them,
and sit down to a feast.
In this chapel an invitation to all good Catholics was
pasted on the pillars to bring in their gifts liberally,
for the support of the priests and the altar,
that their holy religion might not fall to the ground.

"`19th. The country is thickly set with towns and villages as we draw nearer to Paris;
we passed through Chatelet, Melun, Charenton and many other towns,
and got to our former lodgings in Paris, and were received with pleasant countenances.
In the afternoon, went in search of the American consul, Skipwith,
but the office was shut.
A number of Americans have been in this city nearly a year,
seeking some indemnification for their property taken by the nation,
and have no prospect when they shall be at liberty to return.

"`20th Went again to the consul`'s office, but were told to come again or wait an hour;
we returned and after some time went back.
It is exceedingly trying to wait from time to time on men in
public stations before any business can be accomplished;
they only think fit to attend from about eleven o`'clock to three each day.
He used us courteously and appeared willing to oblige us,
but has little in his power at present,
as there is some disagreement between the French government and ours.
He told us that for about two month past,
all communication between England and France had been prohibited,
so that no passes could be obtained but for Hamburg or some other neutral port.
This was an additional affliction to us,
to think of travelling six or seven hundred miles from hence in our wearied state;
apprehending it was more than we could accomplish in
time for the Yearly Meeting in London.
Being much cast down,
I quietly reflected on the mercy and goodness of our heavenly Shepherd,
who has condescended from time to time, to '`make darkness light before us,
and crooked things straight;`' and then felt easy to leave the
business of procuring passes and forwarding them to us,
to the consul, and proceed to Dunkirk.
We then took post-horses for St. Dennis,
to go on a different road from that we came here upon.
Paris, for the licentious and men of pleasure,
is perhaps more fully calculated than any city in Europe;
there may be found everything to gratify their desire,
to feast their eyes and delight their imagination; but for persons of our character,
and engaged in the weighty business we are, it is altogether undesirable.
France is a country in which my mind has been much exercised and sunk,
and I think every hour long till we get out of it.
Our cabriolet needing some repair, while it was doing at the second stage,
a man arrived in his own cabriolet from Paris, and being an Englishman,
spoke to us in that language.
He was of genteel appearance; had been in France about ten years;
told us he lived at Chantilly, and would be glad to have us at his house tonight,
which we agreed to.
When we got to Chantilly, our carriage being badly broken,
we had to get it repaired again.
Our friend, the Englishman, whose name is Christopher Potter, sent a young man for us,
and received us with great frankness; he is a man of ability,
and having a genius for manufactures, has succeeded admirably;
says he gives bread to about six hundred people in his different establishments;
lives on part of the estate once belonging to the prince of Conde;
his wife and children continuing in England.

"`21st. Having breakfasted at Potter`'s,
he took us to view the former seat of the prince, which for magnificence and extent,
exceeds anything we have seen in Europe, belonging to a subject,
though at present its grandeur is defaced: the mansion-house, stables,
green-houses and other buildings, are in their extent and style,
such as I have no talent for describing; the gardens, fish-ponds, canals,
cascades and fountains, are said to have been, when in their best condition,
preferable to anything in Europe.
These ruined palaces,
once replete and surrounded with all that could please and
gratify the voluptuous inclinations of their inhabitants,
are some of the most striking monuments the world can exhibit,
of the instability and vanity of all earthly enjoyments, and bring with them, to a wise,
reflecting mind, an antidote against setting our hearts on any terrestrial thing;
and cast a melancholy shade over all human glory.--Lord,
teach us to aspire with increasing ardor,
after that glory which is celestial and eternal,
and those mansions of immutable felicity,
which you have prepared in the riches of your mercy,
for all those who love you and keep your commandments.
The prince and his family, who, it is said,
had above one thousand people who wore their livery,
are now wandering emigrants in foreign parts.
Potter is a very extraordinary person, as a man of this world,
and no doubt of great use in employing the poor in his neighborhood;
yet one thing is lacking, worth a thousand times more than all he can otherwise acquire;
a desire more ardent after the peace of God, which passes all understanding,
and those riches which will never perish.
We felt a desire to have a meeting among his people; he said,
he hoped the time might come, when he should forward such a proposal with pleasure,
but as they were a body of English people,
and were watched over with rather a jealous eye,
the object of the meeting might be misconstrued by evil-minded persons,
and bring them into suffering.
He returned with us to our inn, and we distributed nearly all our books among his people.
We parted from them in kindness,
and he pressed us to direct any of our friends who came that way, to call on him,
and he should always be glad to see them.

"`22nd. Passed on to Doulen.
The sheep here are kept pretty much under care of the shepherds`' dogs,
whose sagacity and attention is admirable.
There are very few hedges in France, and no fences except a few of stone,
where there are intervals of pasture on the sides of the road;
the dogs let the sheep feed along the borders of the grain,
continually watching them at all quarters; and if one or more transgress the bounds,
they immediately bring them to order.
The shepherds have so much confidence in them,
that they sit down on the side of a bank and work at making baskets,
or some other employment,
leaving the management of the flock very much to their faithful subordinate keepers.

"`24th. Having passed through several towns and some fine country,
we arrived at Dunkirk in the afternoon.

"`25th. Felt refreshed after a laborious journey.
We find, by computation, that we have rode fourteen hundred miles in France;
about fifty of which was over the same road twice,
so that we have had an opportunity of seeing and feeling the
state of the people in a religious sense and otherwise,
and my judgment is, that the French are an open-hearted, unsuspicious people;
we passed through them without any material interruption,
such as we frequently met with in Germany, as searching our baggage, inquiring our names,
characters, and business, etc.
They are generally civil and polite; the country pleasant, and in many places fertile,
abounding in corn, wine, and oil.
Though not remarkable for pasturage and cattle, yet the air is pure and serene,
the waters good, the necessaries and even luxuries of life plenty;
yet strangers travel at a great expense.
Their post-horses in general are better than I expected,
and they have a great number of asses and fine mules: many of the public-houses are good,
perhaps in size and convenience nowhere excelled; the beds good and clean,
and the provisions generally excellent, but their hills are enormous.
Travellers, if they use economy, and are in their own carriage,
cannot be accommodated for much less, for three persons, than four guineas a day.
As to their religious character, I am at a loss to describe it;
no doubt there are many in the higher ranks of life who are Deists;
but the great mass of the people, though at present turned out of their old channel,
remain attached and riveted to the religion of their education,
yet the superstition and extravagance of that has received so great a shock,
that it is scarcely probable it will ever rise again to
the same degree of influence as formerly.
There are many pious persons mourning in secret,
and desirous of seeing the depraved manners of the people reformed;
and I dare not entertain a doubt but He who rules in heaven and in the kingdoms of men,
will have a people gathered both from the superstitions and vanities,
that have heretofore abounded,
who will be a special and spiritual heritage unto himself--may
He cut short his work in righteousness and hasten that day!

"`For my own part, weak, feeble,
and unworthy as I feel of any employment in His holy hand, I see but little or nothing,
towards the promotion of this great work, that has been answered by my being among them;
yet, as I came here under a simple apprehension of duty, not to seek mine own things,
but the things which belong to Jesus Christ and his kingdom; after all my weak moments,
and several things in the course of this deeply exercising journey,
which had better have been omitted, or might have been better performed,
I submit all into the hands of my tender and merciful Father,
and ask nothing more than that he will spare me from
being followed by the arrows of condemnation,
and grant me such a portion of peace and assurance in Him, as in the riches of his love,
he may see fit, for in my best state, I am unworthy of the least of all his mercies,
and a poor, helpless, unprofitable servant.

"`26th. To be obliged to stay here much longer feels unpleasant,
but no way yet offers to get to England, the channel of communication being stopped,
and we shall have need of patience.
Accounts arrived of the preliminaries of peace having been signed,
and great rejoicings and an illumination took place,
but no insult was offered to our friends,
which is very different from England and America, to their great reproach.
Friends enjoy more freedom in France than in either of those countries.

"`27th. The people are still in a state of rejoicing, full of tumult and confusion;
but it appears to me that instead of this vain show,
it is matter of reverent thankfulness and secret gladness of heart,
to the merciful Author of every good work,
that he appears to be disposing the Powers who
have stained the earth with so much human blood,
to stay their hands.
But oh! how can their recompense the thousands of unhappy
widows and orphans who are mourning in secret places,
their irretrievable loss all over the nations where we have travelled.
Oh! when will men be wise--when will they allow the peaceable kingdom of the
Redeemer whom they profess to adore to come on earth as it is in heaven.--How have
the great of this world always resisted the coming of that glorious day,
for which they pretend to intercede in their prayers!

"`First-day, 30th. Had meetings morning and evening; at the latter,
through the condescension of the good Shepherd of the sheep,
it was a time of refreshment and comfort, I believe,
to both the laborers and the auditory: for my own part,
having felt for a number of days like a dry and withered branch,
I was rejoiced to feel again the circulation of that life and virtue,
by which alone all the branches of Christ, the true vine,
are nourished and supported to bring forth fruit to his praise.
The Truth as it is in Jesus,
appeared to rise into dominion--the erroneous and destructive opinions of Deism,
which are subtilely making their way into many minds, who will be robbed and spoiled,
whether they be of our Society or others that indulge it, of the most inestimable jewel,
the most powerful consolation to the soul, both in life and death, that ever a Being,
infinite in mercy and boundless in his compassion, conferred on mankind.
Oh! that He may protect and preserve our Society from drinking in
this deadly poison to the soul--that the watchmen on the walls may be
enabled faithfully to sound an alarm to the careless,
to whom it may be offered as a gilded bait, and the poor wounded receivers of it,
be left to lament their folly in that day when its
fatal consequences will be forever irretrievable.

"`Fifth month, 1st. This day is foolishly observed in France,
and spent in a riotous manner; troops of young women and girls were in different places,
dancing under garlands hung in the streets.
Feeling no call of duty resting upon my mind, to detain me in this place,
the time passes very heavily.

"`First-day, 7th. The meeting this morning was attended by about twenty persons,
and I hope it was profitable.
In the evening about fifty attended, mostly very respectable-looking people,
who behaved well,
and the opportunity ended in solemn supplication to the Father of mercies.
We were refreshed; our hopes of his continued care over us, revived;
and we humbly trust it was an edifying season to most present:
may the praise of all be rendered unto the Fountain of every blessing,
to whom alone it is due.

"`9th. The markets here are supplied with plenty of vegetables--sound, good apples,
at this season of the year, are sold three for less than a cent; eggs,
twelve sous for a quarter of a hundred; butter, about twelve cents a pound;
very good beef and veal, about eight cents a pound.
As we cannot leave here without our passes but by some deception,
which we cannot practise, though many others make use of this means,
we have to bear our detention with patience,
desiring that after laboring and travelling so much for the promotion of Truth,
we may do nothing on leaving the continent,
that will bring it into reproach--the eyes of the people being upon us.
Oh! that we may be preserved wise and harmless.
A proposal being made for our accepting a mode of passing under a deceptive cover,
we dare not receive it.
May we be kept wise and patient,
so that no blemish may be brought upon our holy profession;
the snares that are laid for our feet are many, and some very plausible.

"`13th. Having endeavored to keep a conscience void of offence,
I feel my mind free from condemnation; though I am weak, poor, and liable to err,
and may not in some instances have kept in the straight path of duty,
yet the Lord speaks peace to my soul.`"

After waiting in this place, from the 24th of Fourth month, to this day,
the mayor and municipality granted them passports.

"`First-day, 14th of Fifth month, 1797.
The meeting this morning was a solid favored time;
the people took leave of us affectionately, and we embarked in the afternoon.

"`15th. Being on the English coast, a thick fog obscured the land,
and it was thought we might get ashore, and proceed to London by land,
without being asked any questions,
but we were determined not to be smuggled into England;
and having travelled so far without wounding our testimony,
we hoped to continue so to the end.
A fishing-boat coming alongside, we agreed with them for four guineas,
to take us to Dover, about five leagues;
there being a penalty upon any captain that lands passengers from an enemy`'s country,
at any port except Dover, Southampton, Gravesend and two others;
but being detained by the fog,
we concluded to give them three guineas to land us at Margate.
When we got to the place, some young Friends came down and wanted us to land,
but the officer of the port coming and inquiring from where we came,
we honestly told him, from Dunkirk; he said it was not in his power to permit us to land,
and that the fisherman was liable to a fine of two hundred pounds for bringing us,
but as we had not landed, the penalty could not be exacted.
The officer seemed disposed to be kind,
and if we could have assumed the character of alien merchants,
we might have had the privilege, but we could not make use of such a plea.
Several Friends came, and appeared to regret our not being permitted to come ashore;
we however thought it best to push off,
and accordingly anchored a quarter of a mile distant.
Here several Friends came to us in a boat,
and thought no one would molest us if we landed,
but we chose to proceed up the Thames to Gravesend; the Friends were very kind,
and went on shore and brought us some acceptable refreshments.

"`16th. Having got up to Gravesend, the officers came on board,
and after making a search, permitted us to land.
We went on board a packet-boat for London;
there were several respectable people in the vessel,
but also some sailors and wicked women, who soon began to be troublesome.
An old man checked them for their discourse, at which one of the women pertly said,
she hoped we had no Quakers on board.
I told her, I had the honor to be a Quaker,
and David Sands united in the same acknowledgment: after some time,
the passengers mostly collecting in a large room below deck, these women came down also,
and David Sands began to speak to them; the people behaved soberly,
and the two women became much broken.
A young man, a Baptist, seconded him in a feeling manner; and I made some addition.
One of the women in particular was bathed in tears,
and I cannot but hope it may produce some good effect.
When we landed, I went to seek for a coach, and was met by two of my dear friends,
making ready to meet us.
In London, we met with our dear friend, George Dillwyn,
he having got here about eight weeks past.

"`17th. I attended week-day meeting, at Gracechurch street,
and was permitted to pass it in silence, in thankful remembrance of the Lord`'s mercies,
and secretly to praise his great and worthy name.

"`First-day, 21st. Was at the Park-meeting, and in the evening, at Westminster.

"`28th. Deborah Darby, Rebecca Young and myself,
appointed a meeting at Wandsworth in the evening, which was large, and proved,
through renewed mercy, a favored time.

"`Sixth month, 1st. The public-meeting began to collect in the women`'s meetinghouse,
but Friends apprehending it would not hold the people, the men`'s house was opened,
and it was supposed twelve hundred people assembled in it,
and through Divine condescension, was a time of renewed encouragement.
Deborah Darby, Mary Dudley, Samuel Alexander and myself, were engaged in the ministry.

"`Sixth month, 6th. We appointed a meeting at Deptford, for this evening,
and as the meetinghouse was too small,
it was held in a part of a maltster`'s buildings and yard; it was very large,
and dear Deborah Darby was singularly favored: we left the people with much sweetness,
many of them soliciting another opportunity.

"`9th. Had an appointed public-meeting this evening, at Tottenham,
in which we were permitted again to rejoice in the Lord, our helper.
At the house of a Friend,
I found three books said to be sermons preached by me last year;
and on looking over them, observed they were full of errors,
both in language and doctrine, with which I was greatly exercised,
and visited the man who had undertaken to publish them.
I found he was a poor shoemaker, who had got some knowledge of short-hand,
but was very illiterate, and if he had taken them down correctly,
could hardly put them into common sense;
the erroneous language and doctrines were such as I never uttered, nor even conceived;
and there were, also, many gross absurdities.

"`First-day, sixth month, 11th. At six o`'clock in the evening,
under as much discouragement as ever I remember,
attended a meeting appointed for other professors: it was large and crowded;
through renewed mercy, I felt my mind much enlarged,
and have never felt more sweet peace in my labor, since leaving home.
Going out of the meetinghouse, a Turk, who had been at a meeting before, waited for me,
and said he felt his heart made better; that God was good to all nations,
and that those who served him, were the same in Turkey as in England;
he took my hands in both his, and pressed them to his breast affectionately.
I now felt my mind relieved, and at liberty to leave London shortly.

"`17th. Left London, and rode to Portsmouth, and from there proceeded in an open boat,
to Newport, on the isle of Wight, and got a person to clean the meetinghouse,
formerly occupied by Friends.

"`First-day, 18th. As we gave no notice of any meeting,
the gathering in the morning was small; at the close of it,
I felt strength to appoint a public meeting, at six o`'clock this evening;
which was crowded, and I hope satisfactory; the people behaved becomingly,
and appeared glad at our being there.

"`19th. The town is full of soldiers,
and the pious inhabitants lament the great change taking place,
from the simplicity and innocent manners which formerly distinguished the people,
to more luxury, dress and licentious conduct.
I went to the meeting at six o`'clock this evening,
though much oppressed with a cold and hoarseness; the house was soon crowded,
and the people being still, I was enabled to extend my voice sufficiently to be heard;
and Friends thought it a profitable time, for which favor the Lord alone be thanked.

"`20th. Went three miles to have a meeting at a farm-house; the man of the house,
being necessarily from home, his wife had notified the few scattering neighbors,
and about thirty simple-hearted, honest people came,
and I thought it was a time of as much love and favor, as I had experienced in England.
The young man, the master of the house, arrived just at the breaking up of the meeting,
and expressed his sorrow at not being at it.

"`21st. A Methodist minister, at the close of their meeting,
had given notice of our meeting to be held this evening,
at the house of some pious people of the Methodist connection:
the woman of the house seemed to be universally esteemed,
she held meetings in their cottage and frequently preached to the people.
More persons came to our meeting, than the house would hold;
and it was owned by our gracious Head and High Priest--the
language of encouragement flowed freely to an honest,
simple-hearted people, such as I have rarely met with.
This woman preaching with such general acceptance,
seems to be an advance towards Friends, both in her and others,
who approve of her ministry, which is uncommon among people of other societies.
I felt easy to appoint a meeting a few miles off, for tomorrow evening.
The bishop of Winchester came here to confirm the people of their church,
who had not undergone that ceremony: it was said,
he had not been to visit this part of his flock for fourteen years.
None under the age of fourteen, were admitted, and not then,
without a certificate granted by their pastor,
certifying that the party had undergone an examination and was approved by him,
for confirmation; but it appeared that some had not even seen him on the occasion,
and had only sent for their tickets.
Our landlady`'s daughter was much affected when she understood the
weakness and absurdity that appeared in this pretence of religion;
having never been examined, and knowing little of their confession of faith,
she went heavily to the chapel.
Some of the clergy have brought themselves into contempt, not only here,
but in many parts of the kingdom, by their irregular lives;
and my mind was affected on account of the young
people who were training up in such formality,
and under such miserable shepherds.

"`22nd. This afternoon,
I went to the place where the meeting was to be held in a Methodist meetinghouse; which,
though it rained much, was filled; the people conducted to our satisfaction,
many were humbled into tears, and we parted with their desires for another.
May the Lord be praised for his goodness, and we humbled in the dust,
for no good thing dwells with us, except it be given of God.

"`First-day, 25th. The meeting this morning was very large,
and remarkably solid and favored; great part of the audience much humbled, and in tears;
for which I felt thankful to the Author of all our mercies,
to whom alone all praise is due.
Feeling comfortably relieved, and at liberty, I took an affectionate leave of them.
Had a parting, sitting with the family, who had shown us great kindness,
and went to Cowes.
The minister of the dissenting congregation offering his meetinghouse,
we had a very crowded gathering at six o`'clock in the evening;
he standing at the door all the time, directing the people to seats, and keeping order.
The people were light and gay, and the labor was hard,
but towards the close great solemnity appeared, and it ended to much satisfaction,
the people acknowledging the truth of what was delivered; and the minister also said,
he should pray for me, that the Lord might continue to strengthen me for the work.
Several who had attended our meetings accompanied us to the water-edge,
and parted in great brokenness, especially our kind hostess.
We left, through mercy, an open door for any who may hereafter be sent to this island,
where there is a considerable number, almost, if not altogether,
convinced of the doctrines of Friends.
I had nine meetings among them, and they were made very near to me.
We were rowed in an open boat over to Southampton, about thirteen miles,
and it was about eleven o`'clock at night when we got on shore.

"`27th. Appointed a public meeting at Ringwood, for this evening,
which was large and satisfactory.

"`Seventh month, 1st. Have had satisfactory meetings at Pool, Lymington, and Wareham;
went to Weymouth, and from there by the packet, to Guernsey,
and had a very trying passage.

"`4th. Had an appointed meeting this evening, in the upper part of a spacious store;
a large number attended, and through the kindness of our heavenly Shepherd, it was solid;
the people expressing their satisfaction,
and as we went to our lodgings several inquired
of us when there would be another meeting.

"`6th. Took passage for the island of Jersey;
the wind was so high that we could not make a landing where we intended,
but were driven many miles, and there being two ships of war near,
they obliged our captain to come on board.
The wind continued very boisterous, and the shore all round was rocky.
While the captain was absent, our vessel dragged her anchor,
and our people became much alarmed,
as we must have been driven by the violence of the wind on to the French coast,
if we were not permitted to go into harbor,
which the captain of the man-of-war gave us liberty to do,
but required us to stay on board for the orders of the prince, before we landed.
These delays, and the serious danger we were in, were very trying, having,
taken no refreshment all day.
After much toil and difficulty, the wind blowing directly towards the coast of France,
we anchored within two hundred yards of land;
our letters and my passport were sent on shore to the prince,
and after considerable detention, we were permitted to land,
and sent under guard five miles to the principal town, St. Helier,
where we arrived about eight o`'clock in the evening, very weary, and almost sick,
for lack of proper refreshment.
Being taken before several officers and examined,
we were told that this island was so circumstanced,
that it would be very improper to preach against war at present;
the last officer manifested a kind disposition towards us, and we were dismissed.
The inn being taken up with guests, chiefly officers,
I was taken to the house of two middle-aged women,
between eleven and twelve o`'clock at night.
Looking back on the fatigues and dangers of the day, my soul was made afresh,
thankful for the continued mercies of my heavenly Father,
and deeply sensible of my own unworthiness to be thus
cared for and preserved from one place to another,
in a strange land.

"`7th. The two women Friends who thus provided me with accommodation,
appear to be pious persons; and though separated from the benefits of religious society,
they with their niece sit down together on First and other days, in silence,
for the performance of Divine worship; they are esteemed by the people as Friends,
and well spoken of.
They gave me an account of the manner in which Claude Gay, who formerly lived here,
was treated by the people, and at length banished the island;
whereupon he went and laid his situation before the king,
who ordered his officers to receive him again and to treat Friends in a different manner.
The father of these Friends had been deceased now for a number of years,
and they remained the only professors with us on
the island--there were a number of Methodists,
but as they could not join in their meetings, they sat down alone.
At about eleven o`'clock, we sat with them,
and after a time of silence and much solemnity, I felt some encouragement to them,
and the baptizing power of Truth uniting us, it was a season, I hope,
of much comfort to us all.
In the evening, they collected a few religious people in the house,
and we had a satisfactory meeting.
An elderly woman, who speaks at times among the Methodists,
said she thought Friends ought not to go from this island so quickly as they had done,
none having stayed more than two days, and hoped we would stay longer,
and she believed the Lord would bless our coming.

"`The Methodists thought we might hold our meetings tomorrow,
at a time when those of other societies were not collected,
supposing we should have many more persons.
This at first appeared plausible, but upon weighing it,
I was most easy to propose two meetings; one at ten and the other at six o`'clock.
Our friends, with the man of the house, went to seek a proper place,
and a suitable room presenting, it was hired for the purpose.
Some of our Methodist acquaintances thought we
had better publish our meeting through the town,
by a public crier, or get hand-bills printed and distributed, to inform the people,
neither of which I could be easy to do, but let the notice spread as it might,
without taking much pains about it.
The place being filled with soldiery and appearances of war,
made me feel very low in my mind,
with a discouraging prospect of having meetings with them.
I feel very much at times for Friends who accompany ministers
in these exercising labors among other professors,
being well convinced it is often a mortifying business to go from house to house,
with invitations to our meetings,
and am therefore inclined to lighten their burdens whenever I can,
and at this time feel thankful for the company of my kind and suitable companions here.

"`First-day, Seventh month 9th. The meeting at ten o`'clock,
was attended by about two hundred people,
and the heavenly Shepherd condescending to grant us his presence,
in which only there is life, we had a solid, open, satisfactory meeting in the hall-room,
and appointed another to be at six in the evening.
Retired to my chamber: it seems to me improper, before these large public-meetings,
to continue in company and conversation until they come on--my place at least,
appears to be to retire and endeavor to have my mind gathered to the Divine Fountain,
where strength and qualification to hold them to the honor of Truth, can alone be found;
and after all, I think I always have entered them with fear and trembling,
lest the blessed cause should by any means suffer.
At six in the evening, many people collected and thronged the house;
a rude drunken man coming in, tended to unsettle the meeting;
many showed great displeasure at his conduct, and though he was a man of property,
the soldiers present attempted to turn him out;
all which with the continual thronging of the people,
and the room being exceedingly warm, made it trying to us,
and the more sober part of the company.
My friends and some of the respectable inhabitants,
spoke to the people to bring about some order.
I stood up, and for a time hoped that stillness might have come over us,
but the heat and throng were so great, that I found it best to tell them,
I did not conceive the meeting could be held so as to answer my concern,
and wished them quietly to withdraw; which but few seemed inclined to do,
and said it was very hard they should be deprived of the meeting,
by the restless behavior of a few;--however, it still appearing best to Friends,
we passed through the crowd, and the rest followed.
We went to the house of our women Friends,
where about twenty or thirty serious people following us,
we were favored with a precious religious opportunity.
One thing which probably added to the unsettlement in the large gathering was,
that many of the people did not understand what was said in English,
to induce them to more quiet.

"`10th. Went to St. Owen`'s bay, about eight miles from St. Helier,
and had a meeting with the people; a large collection of whom attended,
but scarcely any understood English; much quiet prevailing,
and what I said being interpreted, it was a solid, comfortable meeting,
the people being as remarkable for their simple rural manners,
as in any place I have been at.
Had religious conversation afterwards with a number, gave them some books,
and parted in much tenderness.
Appointed another meeting in the evening at St. Aubins.
A sergeant in one of the regiments sat with us and had some serious conversation;
he appeared to be a religious-minded man, weary of his situation as a soldier,
and said there were a number of religious men in that rogriment,
and in another then on the island: his situation excited our sympathy.
An elderly woman, whose two daughters had been at the meeting at St. Helier,
desiring to see us, we went to the house; she said she was granddaughter to Mary Dyer,
who was put to death at Boston,
and that there were several other of her descendants on the island.
The meeting was not large; for a time it felt very heavy,
but at length it proved through renewed mercy, a strengthening time to a number present.
After meeting, a pious man, who sometimes exhorts among the Methodists,
came and took me in his arms, and was very tender; he was soon to leave the Island,
being banished for twelve months for refusing to bear arms,
and would have to leave a wife and two children behind,
who kept a little shop for their maintenance,
which occasioned us to feel much sympathy for him.

"`Returned to St. Helier, and on the 11th had a meeting at the Assembly-room, which,
through mercy, was satisfactory; but my mind not being yet relieved,
I appointed another to be at six o`'clock in the evening, which was large,
and several of the officers of the regiment came in,
one of whom did not seem inclined to behave well, nor to allow others to be so;
but after some time, being more quiet, I was, through Divine assistance,
favored to relieve my mind, and take an affectionate leave of the people.
Our elderly women Friends, who have so kindly accommodated us,
feel their lonely situation as Friends, on this island;
but have been mercifully preserved and helped.

"`13th. Returned to Guernsey, and attended a meeting there in the evening,
which ended to satisfaction;
but my mind was not relieved without having a more general public meeting.

"`First-day, 16th. The meeting, this forenoon, was to good satisfaction;
and in the afternoon, went to one appointed at a place called the Forest;
where about one hundred and fifty people attended, and through Divine help,
it was an open time; many of those present were Methodists,
and were tender and respectful.

"`17th. Having obtained from the trustees and the
principal members of the Episcopal place of worship,
called Bethel, the liberty of holding a meeting in it this evening,
notice was accordingly given; but about the time appointed, the parson sent for the key:
the Friend who had it would not give it up.
He then met the Friend on the way to the house,
and insisted upon our declining holding the meeting, which we were not disposed to do,
neither would his own people consent to it, saying,
he was only their servant whom they paid,
and they would do what they pleased with the house.
He then went off, and we entered the house, which was soon filled;
many of the audience being the principal people of the island.
After some time, they became still,
and though it did not appear to be as much favored as some meetings,
yet I was helped to open several important doctrines,
and passages of Holy Scripture readily and pertinently presented for their support.
My mind became relieved, and I hope the cause of Truth lost nothing;
the people parted with us respectfully,
not at all pleased with the attempt of the parson to prevent the meeting.
One of the principal contributors was much displeased with his conduct,
and said the doctrine he had heard was true and very liberal.

"`18th. A number of the people desired to know when we would have another meeting,
but we not inclining to stir up contention between them and their minister,
did not think it proper to hold any more in that house.
In the afternoon, I went out about five miles,
and had a meeting at the house of a person who is a member with the Methodists;
at which about eighty of his neighbors attended an honest, simple-hearted people;
it was thought by Friends to be as favored as any we had in Guernsey,
for which I was thankful; all praise is due to the heavenly Shepherd.
In the evening the meetinghouse was full, and it proved, through mercy, a solid,
relieving time to my mind; the people took leave of us in much affection.
The captain of the packet telling us we must be on board by ten o`'clock:
on full consideration, I felt now quite easy,
and concluded to go--had some disagreeable company on board.

"`20th. A French vessel bearing down upon us, our captain hoisted more sail,
and getting on faster than the other,
though she was within three quarters of a mile of us,
we providentially escaped going to France, and arrived at Weymouth in the afternoon.
Went to Bristol; and on First-day, the 23rd, attended their meeting in the morning,
and appointed one for other professors in the evening.
The meetinghouse is said to contain fourteen hundred persons,
but it was not sufficient for the people that came.
I was, through renewed mercy, favored to relieve my mind,
and we separated in a tender frame.

"`26th. Got to Ackworth; attended the meeting with the children, which,
through Divine condescension, proved a solid, satisfactory season.
At the close,
I believed it right to appoint a meeting at six
o`'clock the next evening for the neighbors.

"`27th. The meeting was large and solid;
to the Lord be the praise and glory of his own works.

"`29th. At York; visited several places, and went to the castle where seven
Friends are confined for their religious testimony against tithes.
The buildings are airy and handsome;
those Friends have a large room to themselves in the daytime,
where they employ their time in handicraft labor.
In a religious opportunity with them, the good Master favored with his presence;
they were much tendered, and we parted affectionately.
The poor curate, who belonged to the parish they mostly came from,
about ten days past came to York to enter a complaint to the archbishop,
against the priest who put Friends into prison,
because he would not pay him for preaching;
he made three visits to those imprisoned Friends,
and they said he was more affected at seeing them than any who
had visited their apartment since they were confined.
The curates, who do the drudgery for the priests for about thirty or forty pounds a-year,
in many parts of England, are badly paid by their profligate superiors.

"`First-day, 30th. At Ackworth;
and notice having been given to the neighbors not professing with us,
the meeting was large, and, through the continued mercy of our heavenly Father,
was a very contriting season, remarkably so to the dear children.
A meeting being appointed at Leeds, for six o`'clock in the evening,
the house was well filled, and I hope it was a profitable season.

"`Eighth month, 2nd. Got to Liverpool,
and on the 3rd appointed a public-meeting for tomorrow evening.

"`4th. The meeting was large and satisfactory.
Had a meeting at Warrington in the evening of the 6th, which was crowded,
and Friends thought Truth rose over all,
though to myself it felt more laborious than any I had attended for some time.

"`7th. Friends proposed that another might be held this evening,
as many of the people were desirous of it, but after weighing the matter,
I was most easy to return to Liverpool.

"`First-day, 13th. Meeting in the morning at Chester,
with the few Friends who live there, and about sixty others;
it was a time of much brokenness, and another was appointed for the evening,
which was large, and held to good satisfaction;
the people expressing their approbation of the doctrines they heard.
This city has many marks of great antiquity,
and is built on a plan different from any other
I have ever seen.--Went back to Liverpool,
satisfied with my visit to Chester.

"`15th. Was at the Monthly Meeting of Hardshaw, and a number of the neighbors coming in,
it was large;
my mind more than at any other time in England was exercised for our own professors,
and through renewed mercy, I was favored to relieve it to my comfort.

"`16th. Was at a marriage; many other professors attended the meeting,
and some of considerable note; one who had written much,
and was intimate with the prime minister, Pitt, said after meeting,
he did not know how it would be taken by Friends,
but he could scarcely refrain from standing up, and enforcing by his testimony,
to those of his own profession present,
the excellent and charitable doctrines they had heard.

"`First-day, 20th of Eighth month.
The meeting appointed for this evening was large,
several ministers of different congregations attending;
my gracious heavenly Helper did not forsake me,
and I was favored to relieve my mind and feel more clear of Liverpool than ever before;
many came up after meeting, expressing desires for my preservation by sea and by land.
My daily feeling of incapacity for any good word or work of myself,
through the power of Divine grace, keeps me from any exaltation of spirit:
may the Lord be with me and keep me to the end from dishonoring the Truth.

"`24th. Having waited a considerable time for a favorable wind,
for the packet to go to the Isle of Man--while we were at the week-day meeting,
a messenger came and informed us the vessel was about sailing;
I therefore took leave of Friends in a few words, and went on board.

"`25th. Landed on the island: there being a large shed on the shore,
and several people offering their assistance, some of our friends went with a joiner,
to fit it up for a meeting on First-day,
the 27th. We held a meeting there in the forenoon, attended as was supposed,
by about five hundred persons,
among whom were several of the most respectable inhabitants; the people behaved well,
and the opportunity was to much satisfaction.
Appointed another for the evening, and notwithstanding it rained much,
the place was filled; it was thought there were about six or seven hundred:
this was also a satisfactory time, and ended in prayer.
Apprehending I was not yet quite clear, appointed another for tomorrow evening;
but after coming out,
some of the town`'s people thought that ten o`'clock in the morning would be better;
I submitted to their judgment, and they made it known.

"`The next day we went to the meeting-place,
but the people being confused about the time, only about one hundred came; it proved,
however, through Divine goodness, a refreshing time, both to us and the people.
Another was appointed for five o`'clock in the evening.
While at dinner, a respectable man of the island,
brought me a letter from Alexander Shaw, lieutenant-governor, under the duke of Athol,
inviting me and my friends to Castletown, where he resided;
and offering the use of his chariot and servant while we stayed on the island,
they being now in Douglas (the town): we accordingly accepted his offer.
The inhabitants showed us great respect,
and the poor fishermen regretted they could not be at the meeting,
as they fish all night, and put out to sea early in the afternoon.
Nearly one hundred boats sailed out of this port,
and they said the others belonging to the island,
which were between four and five hundred in all, would meet them at the fishing place,
for they always fished together, under the direction of an admiral or commander,
and had strict rules to prevent one having greater advantages than another.
When they were drawn out a little way from the pier into the sea,
they all took off their hats and said a short prayer: considering their occupation,
they generally appear to be sober, considerate men.

"`In the evening, the meeting assembled; most of the respectable inhabitants came,
and in the whole, six or seven hundred;
it was the most solid and satisfactory of any we have had here,
for which I was truly thankful to the Father of mercies.
An officer, who sat by me, kneeled down with me at the time of prayer,
and seemed much affected, as was also Major Wallop, brother of the earl of Portsmouth,
who had sat by me in every meeting.
The people were tender, and hoped we would have more meetings before we left the island,
a serious soldier followed me in the street, and expressed with much tenderness,
his satisfaction,
and told me it was a great grievance to him and several of his comrades,
that their captain drew them out on parade, on First-day mornings,
and hindered them from attending public worship as they desired.

"`Next day, left Douglas--conveyed to Castletown in the governor`'s carriage;
he was walking on the parade, and invited us to dine with him at three o`'clock.
We took up our lodgings at the hotel, and in the afternoon went to the governor`'s,
and several of his acquaintance being present, we dined with them in the castle.
The room we sat in, had walls nine feet thick, and was a very ancient fabric;
the governor and his wife treated us with great friendship,
and on our mentioning the desire of having a meeting tomorrow,
he proposed twelve o`'clock.

"`Eighth month, 30th. Held our meeting in the ballroom, which was very much crowded.
The governor and family, and most of the principal people of Castletown attended;
it was to good satisfaction,
and at the close I signified my intention of another at six o`'clock in the evening.
The governor stood up and told the audience that
the church would be opened for the purpose,
as it was evident no other place would contain the people;
he also sent his servant round the town to give notice.
Castletown may contain three or four hundred houses.
In the evening, the assembly gathered in the place mentioned,
and was supposed to be seven hundred.
I felt low and poor at entering it; the people`'s expectations seemed raised,
which always depresses me.
I was, however, made truly thankful to the Author of mercies,
who condescended to cover the assembly with his presence,
and it ended in prayer and praises to him, our heavenly Father.
The governor, and a man of high rank in the island, going with us to our lodgings,
I showed them my certificate, which they seemed pleased with,
and expressed unity with me, etc.

"`31st. Took the governor`'s carriage and servant, and arrived at Peel,
another considerable town of about four hundred houses;
the majority of the people fishermen.
We delivered the governor`'s letter to the high bailiff,
who said he would exert himself to forward our views,
and offered a school-house or the guard-house, for a meeting.

"`Ninth month, 1st. At meeting in the guard-room,
the soldiers having seated it with planks.
The high bailiff, and several others who had interested themselves for us, attended.
After I had been on my feet about half an hour,
the people crowded the house and round it so, those without striving to get in,
and it raining, that I perceived it would not do to continue the meeting.
The high bailiff remonstrated with them, and I sat down a few minutes,
but the throng was too great to hold the meeting through,
in that solemnity which had at first attended;
not that the people were inclined to be rude, but quite otherwise;
yet so many being anxious to get in and hear, kept the meeting in an uneasy state;
so after sitting a short time, we broke up, the people regretting it.
We told them if we could have a more convenient place,
we inclined to hold another meeting at five o`'clock,
and left it to them to provide for us.
In about a quarter of an hour,
a person came to tell us that the Methodists would be
obliged to us if we would accept their meetinghouse,
which we accordingly did.
It was near the sea-side, and the weather very stormy with hard rain,
yet as many came as filled the house, being about five hundred;
and a good meeting it was: thanks be to Him, who is ever worthy.
After the meeting was over, the fishermen who had been out to sea,
finding the storm increasing, were returning into harbor,
but through the violence of the tempest,
several of their boats were dashed to pieces on the rocks, but no lives lost.
This disaster, added to their continued disappointment of catching fish this season,
made the people seem much distressed.
Having a sum of money from a benevolent Friend for the poor,
I distributed some of it among them, for which they were thankful;
they generally appear to be a very civil, quiet people, and religious in their way,
live poor, and are now much discouraged.

"`Ninth month, 2nd. Proceeded to Ramsey, eighteen miles from Peel.
This island being exposed to high winds from the sea, trees do not thrive in it,
yet in some spots they do better.
A person who had lived in Philadelphia came to see us, and also the curate,
who kindly offered us a large school-house for a meeting, which we accepted;--the judge,
and high bailiff, also offered their service.

"`First-day, 3rd of Ninth month.
At meeting this morning, two priests and the curate attended;
the house held about three hundred, but it was thought many more were crowded into it,
and many others could not get in; it was a satisfactory season,
and another was appointed at five o`'clock this evening, in the same place;
the garden was also opened, and many stood there: it was estimated that, inside and out,
there were more than five hundred persons; a great number for so small a town.
It felt to me as much owned, and as great solemnity prevailed,
as at any we had on the island, and concluded with much brokenness among the people;
thanks be to Him that is forever worthy, and nothing to us but abasement.
The people pressed for another meeting tomorrow,
and the judge thought if I would submit to have another, as many as could afford it,
would be there, and inclined to make a very handsome collection,
and as he knew I would not receive it, he was sure it would be a gratification to me,
to see it distributed among the poor who were distressed by the failure of the fishery.
I assured him I could never admit of anything of that kind,
but was willing to subscribe myself to their necessities, out of meeting;
he heard my reasons and was satisfied.

"`Went on second-day to Kirkmichael, and found that a meeting would be agreeable,
but the landlord undertaking to give notice, and making it to be in the afternoon,
and we having fixed to be at Peel, at a meeting at five o`'clock,
we could not stay their time, at which some of the people were sorry and blamed him:
I left the place rather heavy at the disappointment.
Had a meeting at Peel at the time mentioned; the house was filled, and it proved a solid,
relieving time: thanks to the Author of all good.

"`Ninth month, 5th. Went to Douglas, twelve miles; and it being a stormy evening,
and the fishermen not disposed to go out,
I appointed a meeting principally on their account.
About three hundred of them attended, and many of the other inhabitants,
and through mercy, it was a solid, favored opportunity:
I was then easy to leave the island.
We were informed the governor had expressed his sorrow
that we should be at any expense on the island,
saying it was a reproach to the Isle of Man, to let us be at expense,
while we were engaged for the people`'s good.
Major Wallop came and took a kind leave of us;
and all things being ready for leaving in the morning,
I wrote a letter to the governor in acknowledgment of his kindness,
and retired to rest under a thankful sense of the manifold mercies of my heavenly Father,
who had condescended to conduct me peacefully through my concern for this island; which,
and all his kindness to me, ought ever to be remembered with gratitude.
'`The Lord is good unto all;
his mercies are over all his works--his works shall praise him,
and all his saints shall bless him; they shall speak of the greatness of his power,
they shall talk of his kingdom, for his kingdom is an everlasting kingdom,
and his dominion throughout all generations.`'

"`Ninth month, 7th. Arrived at Whitehaven in the afternoon,
and went to the widow Jane Pearson`'s, who took us in kindly;
most of the ground on which the town stands, is on rent payable to lord Lonsdale.

"`First-day, 10th. The meeting was large and to good satisfaction;
the evening meeting was soon exceedingly crowded, and great numbers out of doors,
supposed in the whole to be one thousand people; the house having small windows,
was so warm and oppressive, that it was very trying and exhausted me much.
I did not think it as open a time as in the morning, but it closed well;
and I proposed another for tomorrow evening,
not feeling easy to leave the place without it.

"`11th. The meeting this evening, appeared to be solid from the first sitting down,
and was, through renewed condescension, a precious relieving time to me:
on retiring to bed and looking back upon the day,
I felt as much sweet peace as I remember to have experienced for a long time past:
thanks be to Him who is ever worthy.
Some time back I had a desire to get home this autumn,
but my prospect of Ireland and Scotland not admitting of it,
I was now favored with a good degree of resignation to bear the disappointment.

"`13th. Attended the week-day meeting at Swarthmore, one mile from Ulverstone,
where the members of society chiefly reside; about forty Friends came to it,
and perhaps twelve of other societies;
and it was held in comfortable and refreshing silence.
I mentioned my prospect of a meeting with the
inhabitants at five o`'clock in the evening,
and a Methodist minister who was present, stood up and offered their meetinghouse,
which he thought would suit us better, as it was in the town:
Friends acknowledged his kindness, but after he and the others were gone,
they seemed to have some strait about it,
and at length concluded that it should be at Swarthmore;
thinking the people would come out, which I doubted,
and had no scruple of accepting the offer.
The meetinghouse at Swarthmore, is now in good repair,
and may hold when the chamber and back part is open, about five hundred persons;
at the entrance next the moor, is a covered door-way of stone, with an inscription,
signifying the time of its building, and G. F. at the end of it;
there are also two large arm-chairs very heavily made, altogether of wood,
and carved on the back; one was for George Fox, and the other for his wife, to sit in:
there is also an ebony bedstead, which George Fox left for Friends who were travelling,
to lodge on.
The meetinghouse stands high,
and commands a beautiful prospect of the country and town of Ulverstone.
Swarthmore Hall is a large pile of antique building, with an avenue into the yard,
where Margaret Fox`'s carriage used to enter by
a gateway of rough stone arched on the top.
The house, as well as the farm, is at present the property of some person not a Friend,
and rented: the rooms are large, particularly that where the meeting used to be held:
it is paved with stone downstairs; up stairs, the wainscoting round the room is carved,^
footnote:[This ornamental work was no doubt performed in judge Fell`'s time.]
as well as the wood-work over the chimnies,
with some representations of Scripture passages.
Margaret Fox lies buried about a mile from there,
where Friends buried their dead at that time.
We walked to town by the paved way on which the family used to walk,
which is mostly shaded with trees.
There are about twelve families of Friends, who keep up the meeting.
Going over these grounds caused me to feel serious, but not superstitious.

"`At Elijah Salthouse`'s,
he showed me their ancient Monthly Meeting book in the days of George Fox,
which was curious; and also an old folio bible printed in 1541, in old English text,
with rough plates; it has a chain and small padlock to it,
by which it was formerly chained to the wall in the meetinghouse;
it is in pretty good keeping for its age.
The reason alleged for its being chained in the meetinghouse is, that in that day,
cavillers at the doctrine, delivered were sometimes present,
and Friends referred to the text to satisfy them,
and also to show to the world that the calumny thrown on Friends of rejecting the bible,
was false.
It was likewise made use of by poor Friends who came from a distance to meeting,
and would be there before the time,
who employed themselves in reading it;--a far more consistent and becoming
employment than many now are in the practice of before meetings begin,
such as conversing about news, trade, politics, etc.
The weather being stormy, and the meeting so far from Ulverstone,
only about two hundred attended; many of whom being religious people,
it was held to satisfaction, yet I did not feel myself relieved.

"`14th. The minister of the Independent congregation,
sent to know if we inclined to accept of their house this evening,
which he should cheerfully make ready for us if we thought proper.
Believing I should not feel clear without his offer was accepted, we did so,
and the meeting was large; the people conducted well,
and through the condescension of our heavenly Father, it was a refreshing time to me,
believing that Truth was much in dominion; and I retired to rest,
easy to proceed in the morning.

"`15th. Got to Kendall, to George Stewardson`'s;
was much oppressed with a cold:--the weather so wet;
they said there had not been a dry day for a month past,
which had much injured the harvest, the wheat growing in the shock,
and a great deal of hay being nearly rotten.

"`First-day, 17th. The meeting was larger than any I have seen,
except London and Bristol; and an appointed one this evening was very large and crowded;
it was supposed there were fourteen hundred persons within doors, and many out;
the Author of all good was mercifully pleased to be with us,
and it concluded in thanksgiving.

"`19th. Attended their week-day meeting, wherein I was silent:
appointed one to be held at six o`'clock this evening, for all who inclined to attend;
which, though it rained very hard, was large, consisting of about one thousand people,
who behaved becomingly.
My cold and hoarseness made it trying to me to speak, yet it closed comfortably:
the minister of a dissenting congregation was much affected,
and took leave of me with expressions of unity,
and prayers for my preservation and return, to my friends in peace.
A number of our female ministers are travelling in Scotland,
and these northern parts of England; but no man Friend,
except Thomas Scattergood and myself; David Sands is in Wales.
What has or does hinder them, but the too great attachment to the pursuits of this world?
O! what a pity, in such an abundant field of labor as this country affords!
Lord, loosen our Society more and more,
that they may be ready to enter the field you are opening in Europe.

"`21st. At Cockermouth; where there are about twenty families of Friends,
who keep up the meeting.
The wages of labouring people here are very low; men twenty-one pence per day,
and find themselves;--most of the people, men, women and children, wear clogs,
made of leather above and wood and iron for the soles,
which seems to be general in the north of England,
except for such as are of considerable property.

"`22nd. Appointed a meeting for six o`'clock this evening;
a number of Friends came in from the country, among whom was John Hall, of Broughton,
a minister; the meeting was large and satisfactory.

"`First-day, 24th. Attended their forenoon meeting at Wigton,
at which were Mary Watson and Mary Sterry; the former had good service.
I did not think myself authorized to appear by way of ministry,
as indeed I seldom do among Friends.
The members of society in Cumberland and Westmoreland, appear to be a plain,
honest people.
Arrived at Carlisle in the evening, and a meeting being appointed at six o`'clock,
it was large; several of the clergy attended;
and through the condescension of our heavenly Father, it was a solid, satisfactory time.
Appointed another meeting for tomorrow evening.
There are about thirty-two families of Friends here,
and there may be fifteen thousand inhabitants in this city.
Many Friends came in from the country to the meeting;
and also some people of note in the town, and some of the clergy:
the people were remarkably still,
and the Lord favoured us with a truly consolating meeting; my mind felt quite relieved,
and I had an affectionate parting with many of the people.

"`27th. Lodged at Hawick, forty-four miles from Carlisle.
The labourers on their farms, live generally in a cluster of twenty or thirty houses;
are meanly accommodated in small mud cottages with thatched roofs, almost like stables;
the children and most of the women without shoes--turf is the common firing,
and their bread of oatmeal.
Arrived at Kelso a little past eleven o`'clock,
and finding that the widow Margaret Anderson and two daughters were gone to meeting,
we went and sat down with them; they and one man, not an acknowledged member,
composed the whole meeting;
some others who are descendants of Friends join them on first-days.
Their lonely situation affected me,
and I could not but reflect on my dear native city and the meetings there,
where there are so many to encourage and strengthen one another.
Oh! what advantages do Friends in such places enjoy, and how thankful ought they to be!
May the sight of many poor and solitary ones be remembered by me,
if the Lord spare me to get home,
and be a perpetual incitement to walk worthy of his manifold mercies.
There was something solid and precious attended us, and we were glad we had sat with them.
I proposed a meeting for the people of the place;
but it being thought the notice would be too short for this evening,
it was appointed for ten o`'clock tomorrow forenoon.
The lands being farmed out in large tracts, the poor can get none;
and the farmers who employ them, feed them with skim, or as they call it,
blue milk and oatmeal, made into crouder or hasty-pudding, potatoes, turnips, kale, etc.,
but very little meat.
The river is well stored with salmon, but none are permitted to take them,
but such as purchase that privilege of the Duke of Roxborough.
Notwithstanding their plenty, they are six-pence sterling per pound,
so the poor must taste them but seldom.

"`29th. Very little notice being given, the meeting was small;
at the close of which I appointed another at six o`'clock in the evening.
I felt much discouraged at having a meeting here;
the minds of the people not appearing open towards Friends;
but about two hundred attended.
I thought Truth did not reign, and to me it was a low, and I feared a fruitless season;
yet the people said they hoped we would stay over First-day;
it was however still and quiet throughout.

"`30th. "`Went on--passed through a large town called Dalkeith,
and arrived at Edinburgh in the evening.

"`First-day, Tenth month 1st. Friends have built a new meetinghouse in a retired place,
which will contain about five hundred persons.
There are about twelve families of respectable Friends residing here;
and we went to the meeting, in expectation of seeing our members alone;
but the people came in until there were three hundred, who appeared becomingly,
and it was on the whole to satisfaction.
Appointed another meeting at six o`'clock in the evening,
at which about five hundred attended, among whom were many high professors,
who behaved well; it was thought to be a favored meeting,
and I left it peaceful and easy, and appointed another for Third-day evening.
This city is said to contain one hundred thousand inhabitants,
though it does not cover a great deal of ground.
The houses are in general higher than in any city in Europe, from five to ten stories;
the ground being very costly, it is almost covered with building, and scarcely any yards.
In the new city, the houses are large,
plain and substantial--they generally have stone
stair-cases in one quarter of the building,
which ascend to the top of the house;
and frequently the several stories are occupied by different families,
and have from four to eight chambers each:
these families may be from six to eight or more in one house,
mostly unacquainted with each other.
The space between the joists and ceilings and floors,
is filled with a composition of saw-dust, etc.,
which prevents the communication of sound,
and the families are more conveniently accommodated than might be expected.
At present there are no American students north of Virginia at the college.
Our friends say, they do not desire to see Friends`' children sent here from America,
it being generally destructive of their morals and religious principles.

"`Tenth month, 3rd. The meeting this evening was large and comfortable;
a number of men of science attended,
and it closed in reverent thankfulness to the Author of all our mercies.
Yesterday evening our friend Phoebe Speakman,
with her companions Ann Crowley and J. Birkbeck, came in from their journey to the north.

"`5th. At the week-day meeting this forenoon,
about forty Friends and a few others attended.
Phoebe Speakman had good service, to the comfort of all;
her call seems altogether to our own members.
At the close of the meeting, finding my mind not yet relieved,
I proposed a public meeting at six o`'clock.
Our Friends here set a good example, by shutting up their shops while they go to meeting.
The meeting in the evening was very large and crowded, many men of letters attending,
and I entered it in fear and trembling for the precious cause, which is often my case.
I think I can say, I seek not mine own honor, but above all,
the exaltation of Truth and its testimony.
The people behaved in a solid manner from the beginning, and it proved,
through Divine condescension, a relieving meeting,
and I took leave of the people with much tenderness.
After meeting, some pious persons expressed themselves in an affectionate manner.
I hope the kind expressions of some after meetings will only have a tendency
to make me more humble and sensible that to me belongs nothing,
but all to Him, whose is the kingdom, the power, and the glory,
and all the praise of his own works forever:
our rejoicing is the testimony of our consciences, not the well-done of the people.

"`7th. Rode to Leith, and took passage in a pinnace across the water to Kinghorn;
then taking post-chaise, we passed through the town of Kircaldy and several leaser towns,
and got to Dundee in the morning of the 8th. Two respectable men,
Alexander Webster and William Smith, visited us,
who appear to be convinced of our principles and very friendly.
Some notice having been given, and a large hall well seated,
we went to the meeting with expectation of seeing very few,
as it was the time that all the different places of worship began,
and the people are very exact in this country in attending their places of worship,
and keeping the First-day religiously in their way.
However, about four hundred came, mostly men, and after a few minutes, behaved well.
It was thought to be a comfortable meeting,
and I appointed another at six o`'clock in the evening.
Having at the meeting in the morning used some expressions,
inviting such as were not satisfied with the doctrine,
to call on me and express their minds, three respectable citizens of the place,
but of Deistical principles, joined our friends in the street,
professing a desire for an interview with me,
which I thought had best be deferred until after our meeting in the evening.
The convenience of the hall being enlarged by a different arrangement of the seats,
and opening two rooms adjoining,
the whole were so closely stowed that I had very little expectation
we should be able to hold the meeting to satisfaction,
and expressed my fears to the people.
They endeavored, however, to be still, became very solid and attentive,
and I saw scarcely any uneasiness.
The meeting closed solemnly in prayer,
after which it was some time before we could get the people to move,
so that we could get through, and numbers followed us to the inn door.
It was thought there were one thousand or more assembled;
and it was said many hundreds went away who could not get in.
The three men aforementioned came to the inn; we found them strong in their opinions;
one seemed to be what is termed a Fatalist,
and thought that Judas could not have done anything but what he did,
nor any man else from the beginning of the world.
They appeared to be men of good education, and the points were argued with coolness,
and they parted in a very friendly disposition.
We don`'t know that much was gained; but we all concluded nothing was lost,
as they were driven to their shifts, and willing to drop the argument,
and said they wished there was a body of Friends settled at Dundee.
I retired to rest, thankful for the merciful preservation and help through the day.

"`9th. The town of Dundee stands on the river Tay, about eight miles from the sea,
and as well as almost every village and town in England and Scotland,
has many soldiers in it.
Dined at our friend Alexander Webster`'s, who is under convincement; his wife,
who continues with the Baptists, was pleased with our visit to Dundee, was very kind,
and I hope preparing to be of one mind with her husband.
Another meeting being appointed for this evening, the people hired a man,
as they did yesterday, to preserve order and keep the rude boys out of the house.
Although we went before six o`'clock, the house was nearly full and became very crowded.
I was led to speak plainly against the doctrine of Deism--the
people behaved quietly and some were much tendered;
and though I did not think Truth triumphed so much as last evening,
yet it was a relieving time to me, and the meeting broke up in solemnity.
William Smith`'s wife was at it, with which he was rejoiced,
and she confessed feelingly to the truths she heard.

"`10th. Parted affectionately with William Smith and Alexander Webster,
who said they were strengthened by our visit; but a young woman,
who is also under convincement, and lives with a rigid aunt,
was not permitted to come to any of our meetings, nor to see us;
which was a grief to those two men, and to her also.
They meet together at times like Friends,
and I cannot but hope Truth will one day be more
prosperous in Dundee than it is at present,
though the absurd doctrine of unconditional election and reprobation,
so rigidly held by many, must first be renounced.
Our landlord acknowledged he was much edified by our meetings,
and parted with us with many good wishes.
Rode through a fine grain country, pretty much in sight of the sea, and got to Montrose,
and visited a widow Milne and daughter, the only Friends at that town,
and had a religious opportunity with them to our satisfaction.

"`11th. Went to Urie, the place of Robert Barclay`'s birth and death.
The present possessor is lately come to the estate: he is a young man of eighteen,
named Robert, and was out hunting;--the likeness of Friends seems quite extinguished;
the father of this young man retained a regard
for our profession in the early part of his life,
but went off, got to be a member of parliament, and died about two years past.
The young man`'s preceptor told us, he knew Mr. Barclay would have been glad to see us;
and asked us to stay until he returned from hunting,
and to dine there about four o`'clock, which we declined,
having determined to be at Aberdeen in the evening.
The library room, which is small,
is the place where Robert Barclay is said to have written his
works;--there are a great many ancient Friends`' books,
all Robert Barclay`'s writings, and nearly all the pieces in opposition to him,
and many other books of more modern date on different subjects.
The meetinghouse, which has not been made use of for a number of years,
stands within a few yards of the dwelling--the
ministers`' gallery and some other seats remaining;
but it now appears to be a place for broken furniture and lumber.
The preceptor took us about half a mile from the dwelling, to the top of a little mount,
the highest land in the neighborhood, which was the burying-place of Friends;
the family are buried together, and now enclosed by a house built over them,
at the expense of David Barclay of London; they consist of seven graves:
it is probable that several of the family died in other places.
We left the former residence of the excellent apologist and defender of our faith,
with heaviness of mind,
and with reflections upon the impossibility of the best of men
conferring grace and virtue upon their descendants.
The country from Uric to Aberdeen was very poor; the distance about fourteen miles.

"`12th. Passing through a poor country and with hard riding we got to
Old Meldrum--some of the Friends had gone to their meeting;
but our friend John Elmslie meeting us in the street, took us to his house;
and after a little refreshment, we also went to meeting,
where there were only two men and eight women--it was held in silence; and at the close,
I appointed one for the people of the town, at six o`'clock in the evening; which,
though not large was thought satisfactory.
The town is small, and the people generally in low circumstances.

"`13th. Went on to our ancient friend George Cruikshnnk`'s, who lives with his son John,
who married a daughter of John Wigham`'s. This family
appear exemplary in their house and manner of living,
and may be gifted for service in the church.
Our friend George Cruikshank`'s daughter was very ill;
she bears her lingering painful disorder with great patience and resignation,
and we had a comfortable religious opportunity in her room.
At six o clock went to a meeting appointed at Inverary, a village about two miles off;
the house held about three hundred people, was well filled,
the people quiet in the time of silence, serious, tender and attentive.
I thought them more like thirsty ground than in
any other place we had been at in Scotland,
and the Lord favored us with a memorable time, to our great comfort;
the praise of all was rendered to Him, whose due it is: the people were very thankful,
and expressed much desire for another meeting.
O! my dear friends of Philadelphia--how gladly would these,
and many more in desolate places as to vital religion,
receive the crumbs that fall from your spiritual tables almost untasted.

"`14th. Our ancient Friend went with us to Kinmuck, four miles,
to the family of John Wigham, who are settled on land which they have improved,
being managed by his eldest son, a hopeful young man.
The village of Kinmuck is about half a mile distant, quite small,
but has several families of Friends and a meetinghouse.
Rode to Aberdeen about fourteen miles.
A letter being received from Philadelphia,
mentioning that symptoms of the yellow fever had again appeared there,
it was affecting to me; but having left all is obedience to my apprehended duty,
I commit all to Him whose power is sufficient to control and stay the hand of disease,
when and where he pleases.

"`First-day, 15th. Notice having been given to other professors,
the meeting was held in Friends meetinghouse, which was comfortably filled:
there are but six families of Friends belonging to it.
After a little time the people behaved orderly and were very attentive;
it grew more and more solid, and ended to satisfaction.
Appointed another for six o`'clock tomorrow evening.
This town stands upon the river Dec; the land round it is not rich,
and the people are employed in knitting worsted, woollen, cotton and raw silk stockings;
also spinning the yarn for them and for linens: there are many rows of good houses,
the streets well paved,
and in general more cleanly than the other towns we have passed through in Scotland;
the city is supposed to contain twenty-five thousand inhabitants.

"`16th. The meeting this evening was very crowded;
it was thought that four hundred got in,
and a vast many went away for lack of room--all the avenues for air being stopped,
it became very warm and trying.
Although many had to stand, they presently got quiet, and a solemnity prevailing,
the people continued attentive and were tendered.
We believed it was a season not soon to be forgotten;
the Lord`'s good presence having been thankfully witnessed,
all the praise was rendered to him, who is now and forever worthy.
After meeting, a sensible man came to our lodgings,
and told us he had for several years been a seeker
after Truth--was thankful for what he had now heard,
and wished us to stay longer in Aberdeen,
having no doubt he could obtain a place for a meeting
that would hold one thousand or fifteen hundred people,
who he thought would come if we had another; but feeling my mind clear,
I did not think it laid upon me.
Agreed to breakfast with this man tomorrow, and I retired to bed,
thankful for the help and preservation through the day.

"`17th. Went accordingly to see John Melles and his wife and children;
who appeared to be people of good circumstances, and were very open and friendly.
They said many people marvelled that I spoke as I did last night, without notes,
as all the preachers in Scotland use them, and supposed I had been bred to the ministry,
etc.; so little idea have many in the present day, of the nature of our ministry.
We left Aberdeen, and after passing through much poor country, chiefly in oats,
arrived at a village called Lawrence Kirk in the evening.

"`18th. Rainy and cold; instead of proceeding direct for Glasgow,
as I was in hopes of doing, I found my mind turned to go by Dundee again.
We were well accommodated at the inn,
and had good wheat bread on the table as well as oat cakes;
but the latter is the bread of the poor.
The people in the country appear to be poor,
many of the women and children were without shoe or stocking, though it was quite cold,
and the highland mountains on our right covered with snow on the tops.
Considerable oats and barley yet to cut, and much more to get in and stack.
They have little fuel, and the bleakness and exposure of the country to cold winds,
require a hardy race of people to endure; which they certainly are.
My two travelling companions, George Miller and William Farrer,
made some remarks on Americans using the word '`thee`' instead
of '`thou,`' where the latter would be most proper;
they were of the mind that it was a departure from our testimony,
and had crept in from a desire of pleasing others by a soft accommodating form of speech,
and was inconsistent with the practice of our ancient Friends.
I never thought it proceeded from a desire to evade our testimony,
but through custom had prevailed in many from ignorance of grammar rules;--we are,
however, recommended by an apostle, to hold fast the form of sound words.
Arrived at Dundee in the evening.
Our two convinced friends, Alexander Webster and William Smith, called upon us,
and appear to have gained strength to avow the
principles of Friends more openly than heretofore,
and to sit down together on first-days in silence,
with such who incline to sit with them.
The accounts they gave us, and the comfortable feeling of our minds,
induced us to believe we had been rightly directed to visit this town again

"`19th. The Tradesmen`'s Hall was again seated, though not so conveniently as before,
we being placed in the middle, and the people not inclining to go to the far end,
they blocked up the door-way, and prevented many from getting in;
had it been otherwise arranged, we believed it would have been filled.
About five hundred attended, chiefly of the most respectable inhabitants.
My mind was in a remarkable manner tenderly affected towards them,
and through the gracious condescension of our heavenly Father,
the opportunity was to our great comfort and thankfulness.
After meeting,
two religious men and a woman who had an uncommon knowledge in the Scriptures,
and were of a tender spirit, visited us.
They expressed their convictions in all the foregoing meetings, as well as this,
though they had never heard a Friend before,
and were united with the doctrines they had heard,
and were only come to have further information
as to some points in which they still had doubts,
particularly whether water baptism and the sacrament so called,
were not enjoined for Christians to observe as a standing ordinance of Christ.
We had much freedom in exchanging sentiments with these tender people,
who had read some parts of Barclay`'s Apology,
lent to them by Alexander Webster since we were first there;
they said they had never heard those matters so clearly stated as in this opportunity,
and could say they now thought there was not anything essential in them:
we parted in much affection.
A man also came into our room while we were thus conversing, and opened his mind to us:
he said he had been at all our meetings, and ever since the first,
was under strong convictions for his past bad conduct, but was comforted in hope,
by the doctrines we held,
of the universal grace and free pardoning mercy of the
Almighty to returning and repenting sinners,
which was very contrary to what he had been used to hear,
of absolute and unconditional election and reprobation.
He appeared like a prodigal son returning to the
arms of the Father of mercies--was much broken,
and thought that through Divine grace he should renounce all his former evil practices:
I endeavoured to encourage and strengthen him in his good resolutions,
and he left us in tears; his state affected me much and remained on my mind,
with strong desire for his preservation.
Retired to rest with a comfortable evidence of being in our places--the Lord be praised.

"`20th. Our two friends, Alexander Webster and William Smith, with several others,
were disappointed and affected on hearing we proposed leaving them without
another meeting;-- the people appeared to draw hard to detain us longer,
but feeling that things were comfortably left,
and the minds of many stirred up to further inquiry,
we concluded to send them some books from Edinburgh;
and the two Friends crossing the river with us, we had a tender parting from them,
and rode on to the county town, (Cooper,) where we lodged.

"`21st. Set off in the rain and cold, rode through the towns of Kircaldy, Kinghorn,
etc. and arrived at the ferry opposite Leith: it blew very hard,
yet thirty of us passengers went in a sloop, and had a rough, wet time,
and poor accommodations, but arrived safely.
A young man under convincement, and Anthony Wigham, were waiting for us on the quay;
we took a seat in the coach which goes every half-hour for Edinburgh,
and soon got to George Miller`'s, where we were kindly received.

"`First-day, 22nd. The meetinghouse was nearly filled in the morning,
and the people solid and attentive.
At six o`'clock in the evening it was much crowded, and the Lord was rich in mercy to us;
the people parted in a kind and tender frame,
and I was in hopes I might now pass away from this city,
so famous for its learning and science,
that it is said there are seldom fewer than one thousand young
men attending the University from England,
Ireland and foreign parts; more than forty Americans being here at present.

"`24th. A young man who was at some of our meetings on the Isle of Man,
being now here attending the medical lectures, frequently visited us,
and expressed a fear lest while endeavoring to obtain worldly knowledge,
he should unhappily lose rather than gain in the
knowledge of God and of our Lord Jesus Christ,
which he was convinced many of his fellow students had done;
and feelingly expressed his desire to keep, through God`'s grace,
free from the pollution of sentiments and manners so unhappily
prevalent among the professors and pupils in this place.

"`25th. Attended their week-day meeting, and appointed one for six o`'clock this evening,
requesting that the notice might be particularly
communicated to such who were considered seeking,
religious people.
The evening was remarkable for storm and rain,
so that even some women Friends who attempted it,
thought they were obliged to give out and return home;
yet from two hundred and fifty to three hundred came, nearly one half of whom were women,
supposed to be such as I most wanted to see:
it was the most confirming and solid meeting of any we attended in Edinburgh;
and after taking an affectionate leave of them,
I felt perfectly clear and easy to leave the city.
On the next day we parted with several Friends, and also with our kind,
hospitable landlady, Ann Miller and family, with much tender feeling.
Passed through a pretty country, surrounded with high hills,
and having several handsome seats of noblemen in sight of the road;
arrived at Glasgow in the evening,
and put up at one of the largest inns I have seen in Europe,
having about one hundred rooms.

"`27th. Breakfasted and dined with a worthy man and his wife,
who are convinced of our religious principles;
they with two or three other sober persons,
sit down and hold meetings for worship in the manner of Friends.
Appointed a meeting to be held at six o`'clock this evening;
when about four hundred attended, and behaved well.
I then appointed another at the same hour tomorrow evening,
and lodged at the house of a young Friend from Manchester.
Glasgow is well laid out and built; contains many large and handsome public buildings,
and the private houses are not inferior to any place I have seen--the streets wide,
straight, well lighted by lamps, and has excellent footways,
superior to most we have passed through in Europe.
The city and adjacent villages are extensively in the manufacture of fine cotton stuffs,
muslins, fine linen, etc., and is said to contain sixty thousand inhabitants.
The meeting in the evening was attended by about the same number as the one last night,
did not hold so long as common, feeling that those I most wanted to see were not present,
and I marvelled that there were no more than we had before;
but was informed that the Presbyterians and the seceders from them,
accounted the most rigid to their faith of any in Scotland,
had no unity with the Methodists, and our having the meeting in their house,
kept many away.
I appointed the meeting for tomorrow forenoon at the Tradesmen`'s Hall.

"`29th. The meeting in the Hall was comfortably
filled with many people of the first rank,
and was satisfactory; appointed another at six o`'clock this evening,
which was crowded as well inside as round the door and on the stairs.
Through Divine favour, a solemnity soon spread over us; and though I seldom have entered,
or stood up in, these great meetings with more fear and even trembling, than in this,
yet the good Shepherd and everlasting Helper of those who put
their trust in I was mercifully pleased to bear me through,
beyond anything I had experienced in Scotland, and indeed to my own reverent humiliation.
The pernicious doctrine of Deism,
and the Pharisaical righteousness of some professors of Christianity,
were principally what I had to open to the audience, who were so still,
that some afterwards said, they heard distinctly outside the Hall;
and I have seen but few in all my travels equal to it--it
closed in humble thankfulness to the Author of every mercy:
after which I took leave of the people,
apprehending I might now be at liberty to leave them;
many came up very tenderly and respectfully,
and hoped we would not go away without another meeting,
which I told them I would consider as well as I was capable of.
We endeavoured to get out,
but the audience seemed not inclined to move until we went foremost,
through an opening they made for us; several asking for another meeting,
and many followed us almost to our quarters.
I can scarcely express the thankfulness I feel to the Author of all our mercies,
who has been pleased to carry me so peacefully through my visit to Scotland.

"`30th. Notwithstanding the importunity of the people,
I did not feel the propriety of another public meeting at the Hall,
having reason to hope, as it closed well last night,
the way will be open for future fellow travellers; yet weighing what was best to be done,
was easy to propose a meeting in the house of John Robertson, at six o`'clock,
for those who appeared most inclined to Friends`' meetings;
and such being accordingly invited, about sixty came.
The time of silence was solemn,
and proved a prelude to the continuance of Divine favour throughout.
Several were much humbled, particularly two gay young women, sisters,
who had been at all the meetings and were of considerable rank in the world;
they stayed with us after meeting,
and one of them acknowledged she had never received so
much benefit as in the meetings of Friends.
We told them of the few who sat down together on
first and fifth days at John Robertson`'s house,
where they hoped they should be strengthened to attend.

"`31st. Put forward on our journey through a country the soil of which is naturally poor,
but being manured with lime, sea-weed, etc.,
is made to produce good crops of oats and barley: passed through several towns,
and for a number of miles in sight of the sea; and at night, Eleventh month 1st,
arrived at Port Patrick, and with difficulty procured lodging at a private house,
the inns being crowded.
The wind blowing hard and directly ahead, we were obliged to stay here.
There are abundance of poor-looking people almost naked,
who come here from Ireland to beg.
The town contains about two hundred huts and houses, surrounded by high barren mountains,
and not above four houses in the place that can be called tolerably good; the women,
lads and girls go barefoot, and some of them were sliding so on the ice.
Mutton costs here four pence, and beef six pence per pound, and much of it very poor.

"`4th. The wind coming out more fair,
we went on board the packet and arrived at Donagadee, in Ireland, in the evening.

"`First-day,
the 5th. Sat down with the family and a few others who commonly attend with them,
and at the close of the sitting I proposed a meeting at Newton this evening,
of which our friend T. Bradshaw gave notice in the town.
At six o`'clock, though very wet and discouraging,
yet about four hundred came together and behaved well,
and through renewed mercy it proved an open time.
--Appointed another for tomorrow evening.

"`6th. Went to Newton Ards, where a number of officers and soldiers attended the meeting;
but I thought it not so open and satisfactory as the last.

"`8th. Was at Belfast; the streets of which are very dirty, the poor people very much so,
and without shoes or stockings; the women and children go through the mud,
now in the Eleventh month.
Went on to Antrim, and were kindly received by the family of Gervas Johnson,
who is now on a religious visit to Friends in America.
An appointed meeting at six o`'clock in the evening, was solid and satisfactory,
as was another at the same hour next evening--the house was filled,
and the Presbyterian minister attended both this and the last;
it was quiet and ended to our satisfaction.

"`11th. Took a post-chaise for Lisburn, accompanied by several Friends,
and passed through a fertile country, but the huts of the poor peasants were miserable:
the town we passed through today had been much injured a few days before by some rioters,
and the windows and some doors broken;
the sufferers were such as are called United Irishmen.
This part of Ireland has been long famous for rioting.
With the help of lanterns we walked out to the boarding-school of Friends,
for the province of Ulster, which consisted of about fifty scholars, boys and girls;
their supper was potatoes and milk--they looked healthy and were decently dressed;
having some little religious communication, many of them were tendered,
and I was glad we were there.

"`First-day, 12th. Attended their meeting.
The custom of Friends in this town,
is to have a second meeting after the rising of the first,
and not to dine until after the last;
but feeling a concern to have a meeting for the people at large in the evening,
the afternoon meeting was put off.
The public meeting at six o`'clock was large,
and except some interruption from rude boys, was held in much quiet.
Although the people behaved well in general, I did not think it so open as many others.^
footnote:[It is not strange that our dear friend found so little openness,
as he had to treat upon that divinely authorized passage of the apostle,
"`This is a faithful saying and worthy of all acceptation,
that Jesus Christ came into the world to save sinners,`" etc.; for it is well known,
that through the subtlety of the serpent,
Deism and a disregard of the Holy Scriptures had gained
considerable hold in many parts of that country.]
Some appeared much affected, and an elderly man reached out his hand,
and said it was the Gospel that had been preached, and he wished me well.

"`13th. Visited the boarding-school again; the situation is fine,
and commands a beautiful prospect.
Large additions have been made to it since the decease of John Gough,
who formerly kept it: it has forty acres of land on a long lease.
The National Meeting subscribed four thousand pounds,
and the province of Ulster raises annually about three hundred pounds for its support;
this with some little income beside, enables the institution to board,
educate and clothe fifty-six children, from eight to fifteen years of age,
at three pounds per annum; they bringing with them one good suit,
and also a common one:--the whole expense for one scholar,
is about thirteen pounds Irish, per annum.
Went to Hillsborough and had a meeting in the evening, which was quiet and satisfactory;
then accompanied Louisa Conran, wife of John Conran a minister,
to their house about two miles; he was out from home on religious service.
The poor people in this part of the country, are busily engaged in sowing wheat,
digging potatoes, etc.; the women and children everywhere without shoes and stockings.
Potatoes, with a little oatmeal, sometimes milk, and now and then a bit of meat,
make up their principal food.
I visited a number of the poor in their cottages, the women spin and the men weave linen,
muslin, etc., but are very poorly clad, indeed almost naked; their houses very cold,
with little light but what comes in at the door; the walls of mud and straw,
roofs thatched, floors of earth, and small fires of turf,
for which they pay dear to the landholders; a straw bed or two, with some stools,
a table, a few bowls, etc. make up their furniture.
How would a sight of these poor oppressed people, make many,
even of the poor in Pennsylvania, thankful for their blessings!
We distributed a little money among them, and they returned many blessings.

"`15th. Attended the week-day meeting at Ballindery, the roads were bad;
met by the way with a blind man, who had his mother, aged eighty-six,
on his back in a sack, led by a faithful dog.
Post-chaise one shilling per Irish mile.

"`16th. Attended the Monthly Meeting at Lisburn: unexpectedly to myself,
and contrary to my usual lot in Friends`' meetings,
there was a necessity laid upon me to appear in the ministry--the labor proved hard,
and more laborious than among other people; after which I felt peaceful and easy.
There was much consistency in their appearance as to our profession,
but more weight in answering their queries, and conducting their business,
would have been proper.

"`17th. Went with our friend Louisa Conran two miles to dine,
after which proceeded to Lurgan, about eight Irish miles, through a populous country;
the people on the way-side dwell in wretched hovels of mud and straw,
many children almost naked, and this in the midst of a fertile country,
abounding in the produce of the earth; but the poor live very poorly indeed,
perhaps in every way more distressed than in any country I have seen;
and the rich lamentably oppressive.
It being market-day when we arrived, the market-people were packing up their stockings,
linen, yarn, etc.; many of whom were intoxicated with strong drink,
which is said to be a common case on market days.
The houses are all white, being overcast with lime,
which is much the case in this country.

"`First-day, 19th. Though unwell I went to meeting at Moyallen,
and through Infinite condescension it was thought to be a favored time.
Attended the evening meeting at Lurgan,
though quite poorly with the cold I had taken--the
house was supposed to contain seven hundred persons,
and was filled: it appeared as open a time as I have had in Ireland.

"`21st. Was at William Pike`'s, with whom we went to Dungannon, a considerable town,
and visited T. Greer`'s, jr., and his family.
About eighteen months past they removed to this town,
having before lived at a beautiful farm some miles off, but were obliged to leave it,
in consequence of being in much danger from rioters.
One evening, seven persons came with their faces blacked and otherwise disguised,
armed with pistols, etc., under pretence of searching for guns, but abused the family,
robbed them of two watches and above one hundred guineas;
which had such an effect on his wife, that she has not yet got over it.
Had a public meeting, at which, though a wet evening,
there were about seven hundred present,
and it proved a favored season--many soldiers and officers attended,
several of whom were much affected.

"`24th. Attended a public meeting at Rich-hill, the house pretty full;
I thought it a laborious time.
A drunken priest who attended was held up to the people in such a manner,
that they thought he could not have been so described
if I had not received some previous information;
but they were satisfied their conjecture was wrong, and were glad he had been so handled.
I knew not that there was any in his station present until after meeting.

"`Appointed a meeting to be on First-day morning, the 26th, at Newry.
The Methodists offering their house, and we not seeing any better, accepted it:
they took much pains to accommodate the people,
and though the house contained about seven hundred, it was too small;
yet the meeting was very quiet, and through renewed mercy a favored opportunity.
We had a public meeting in the Presbyterian meetinghouse at six o`'clock in the evening;
the house was large, yet it was much crowded, and many did not get in.
It was said that fifteen hundred persons were present:
the meeting concluded in prayer and praises to our heavenly Helper,
who had been mercifully with us through the day.
The minister of the congregation said at the close,
that we might have the house again whenever we saw fit to use it,
and thanked us for our service.

"`27th. We left the town,
but had not gone far before we saw about one hundred
and fifty persons kneeling on the wet ground,
both men and women--found it was a Romish funeral; the priest dressed in his white robes,
and a corpse in the middle, over which he was making prayers,
and performing some ceremonies.
We stopped,
and had an opportunity of seeing some of their gross superstitious ceremonies,
and the making a bowl of holy water,
which he did by muttering over it a few Latin prayers, and putting in a handful of salt;
he then sprinkled the coffin; the people arose, and were likewise sprinkled,
which the poor women seemed eager to catch, and returned him a courtesy.

"`28th. Reached Dublin, and on the 30th went with two Friends to visit the poor,
principally in those parts called the Liberties,
where the most distressing scenes of human misery presented themselves in abundance,
such as my eyes had never seen before, neither is it in my power fully to describe.
We went through the different apartments of fifty or sixty houses,
with scarcely any glass in the windows, the ground floors of earth,
and everywhere filled with almost all kinds of filth;--in some rooms two, three,
to nine or ten women and children, and some men,
many of them sick and with very few rags to cover them,
sitting round two or three little pieces of turf, and many without any fire at all,
lying about on a little dirty straw in the corners of the room--they had no bed-clothes,
and were almost perished; complaining of having nothing to do and nothing to eat,
some for twenty-four hours or more.
The dampness and dirtiness of their houses, and the filthiness of their persons,
must remain undescribed:--they greedily seized sixpences and shillings,
as if their miserable existence depended on them, and returned us many blessings,
some in very singular language.
A large number surrounding us in the street,
we went to a baker`'s shop and distributed among them fifty loaves of bread.
Dined by candle-light, wet and weary, at R. Clibborn`'s.

"`Twelfth month, 1st. Visited a charity school,
of which Friends had been considerable promoters;
it consisted of about eighty boys and girls; they appeared ragged,
and many without shoes or stockings, yet kept in pretty good order.
The institution is supported by subscriptions made annually.
At six o`'clock attended an appointed meeting for the people generally:
although the evening was very wet, yet the house was nearly filled,
and the people were quiet; but not feeling my mind relieved,
I appointed another at Sycamore alley, on First-day evening.
Spent much of the 2nd in visiting the poor near Summer Hill,
particularly at a spot called Mud Island, where there may be one hundred poor houses,
many of which are of mud, and many miserable inhabitants, some without any fire,
the day cold and damp, and the floors of earth quite wet;
they appeared to have no other beds than straw, and were miserably provided with that.
I distributed a number of guineas among these almost naked people,
and visited about one hundred families.
In returning to our friends we purchased about one hundred loaves of bread,
for which we soon had numerous customers, giving only one to each person.

"`First-day, 3rd. Attended the meeting in the forenoon at Meath street, which was large.
I had a heavy cold by going so much among the poor in the wet.
Went to the appointed evening meeting, which was exceedingly crowded,
and it was said that many hundreds went away; the meeting was quiet and ended well.
Appointed another in the same house to be on Third-day evening:
truly these engagements are not desirable to the flesh.
I long for a release in the Lord`'s time;
may I be enabled to keep the word of his patience.

"`On the 4th, went with two young men on another visit to the poor,
and relieved many miserable human beings.
The memory of these visits cannot soon be effaced from my mind.
May they teach me to be humble and thankful for the blessings I enjoy.
O my dear country folks! could many of you who live in ease and abundance,
far removed from these affecting scenes of wretchedness, behold them,
profitable impressions might be made for life.
To see a mother and daughter, the youngest of them sixty years, almost naked,
without fire, on a damp earthen floor, lying upon a little straw,
only a few tattered rags for covering, and very little to eat,
how must every feeling heart be touched!
In another place there were two widows with seven children,
two of them blind and nearly naked, and one of the mothers racked with rheumatic pains;
they had no fire, and not two ounces of bread in the house.
They have no laws here to oblige the parishes to take care of the poor,
and more than twenty thousand in Dublin are in deep distress,
many through their own folly and wickedness, but not a few for lack of employment.
Walked a mile and a half to a Friend`'s house through the wet,
(for it rains every day.) where we received shocking accounts
of the murders and plunder of the United Irishmen in the south,
within a few days past.

"`5th. Went with Deborah Darby and Rebecca Young to the public meeting this evening:
it was a very respectable congregation, one Romish and several other priests present,
and I thought it the most open and favored opportunity I had been at in Ireland;
the people behaved well,
and at the close were very inquisitive when there was to be another meeting.
I was thankful for the renewed mercies of the day.

"`7th. Visited a blind boy about eleven years old, who appears to be a prodigy,
and has a memory so tenacious that he can retain almost all he hears,
and repeat a large portion of several books, etc.; it is so surprising,
that all who have seen him acknowledge it to be an extraordinary gift.

"`9th. A number of invitations were sent to me by Friends,
but it was not possible for all to be complied with; indeed,
I desire to have much more retirement than I can obtain.
Friends do not enough consider poor travellers who stop among them,
or probably they would not crowd upon them so much as they do;
they mean it as a kindness, but it often amounts to oppression.

"`First-day, 10th. It was concluded to open both meetinghouses,
neither being capable of containing the people that would probably come.
I attended at Sycamore alley, and they were both thought to be favoured.
In the evening the public meeting at that place was soon filled;
the mayor of the city and some principal persons came,
among whom there were eight or nine priests of different congregations and many officers.
My mind was opened in an unusual manner, and after speaking some time,
some pieces of coal were thrown in at the end windows,
which alarmed the women and many of them rose:
two of the officers of the army immediately went out to find the disturbers,
and drew their swords.
I sat down for three or four minutes, when they returned, and the people becoming quiet,
I rose and proceeded, and it proved to be a truly comforting, tendering time;
thanks be unto Him who is ever worthy of all praise:--the meeting ending in
awful prayer and praises -- the people parted from us in much love,
and I felt my mind relieved of public meetings in Dublin.

"`11th. Spent the forenoon in visiting the poor,
and distributed about eight guineas that were put under my care,
to a very wretched company.
