== Chapter VII

[.blurb]
=== Testimony Of the Monthly Meeting of Friends of Philadelphia for the Northern District,
concerning William Savery.

It appears that he was born in the city of Philadelphia, in the year 1750,
and educated in the principles of the Christian religion as professed by us;
and was placed with a Friend in the country, to learn the trade of a tanner.
On his return to the city in 1771, being naturally of a lively and social disposition,
he soon joined with those who, being themselves the votaries of folly and vanity,
encouraged him in a departure from the simplicity of truth; which,
aided by his own propensities,
drew him into many deviations from the religious principles of his education.
In this situation he was arrested by the powerfully
convictive evidence of the Spirit of Truth;
and in the year 1778, at a meeting held at Merion after an interment, was much affected,
and lasting impressions were made on his mind by that solemn scene,
and the testimonies then delivered.

In the autumn of that year he married in Chester county,
and settled within the limits of our Monthly Meeting--
spent much of his time in retirement at home,
and in the thirtieth year of his age, first opened his mouth in a public testimony;
and dwelling inward with those gifts and qualifications with which he was favored,
he became an able advocate for the cause in which he had embarked;
and by faithful attention thereto, his labors were blessed to the benefit of numbers,
especially amongst the youth, to many of whom he was an eminent instrument of good.

He was engaged to travel much on this Continent in the service of Truth,
being several months in each year, from 1789 to 1795 inclusive,
absent from home on Gospel errands; and by accounts received,
his labors of love were to the satisfaction of those among whom his lot was cast.

Having had his mind drawn into near sympathy with the Friends at
Pyrmont in Germany--with the entire unity of his brethren at home,
on the 18th of the Fifth month, 1796, he embarked for Liverpool,
and from there soon proceeded to London, and then to Pyrmont.
After paying an acceptable visit to the comfort and strengthening of Friends there,
and in some other parts of Germany, he went to Nismes in the south of France,
visiting a mall company of such as professed with us, in that neighborhood,
much to his own comfort and peace.--Then returning to England,
he visited many of the principal towns and places in that nation, Ireland and Scotland,
and had large public meetings with those not of our Society.
Having thus discharged his religious duty in those parts,
he returned to his family and friends in the Tenth month, 1798.

He labored diligently in his temporal business for the support of his family,
as well as for the relief of the poor and distressed,
to whose needs his liberal mind was ever ready to administer according to his ability;
yet this did not interrupt his steady attention to other religious duties,
being diligent in the attendance of meetings,
and in various services to which he was called and appointed,
for the benefit of society and the promotion of the cause of truth and righteousness.

In 1802, the neighborhood in which he lived was visited with a pestilential disease,
which carried many off in a short time.
Not being easy to leave this scene of woe and misery,
he voluntarily resigned himself to visit those in distress, both Friends and others,
with advice and counsel, in the love of the Gospel,
to the great consolation and comfort of many.
A like affliction befalling that and other parts of the city and neighborhood,
in the following year he was again engaged in the same manner, freely devoting himself,
both night and day, to relieve the distresses of others,
with which his feeling mind was deeply affected.

In the early part of his sickness he was borne up above complaining,
or admitting that he was much out of health, until the disease,
which proved to be a dropsy, had made such progress, that it was visible to his friends.
He continued to attend to his outward concerns and religious duties;
and in some of the meetings which he last attended,
was led to open a prospect that his time here would not be long; but,
in an animating view of a blessed immortality, signified it was no matter how short,
provided this were attained.

He was remarkable for punctuality and uprightness in his dealings;
and not long before his decease, said to a friend who often visited him,
"`It is necessary to look to our outward concerns,
there are so many reproachful failures;`" and
appeared desirous once more to get to meeting,
that he might have an opportunity to warn such of the
elderly part of society who had got into the earth,
and of the youth who had got into the air.
"`I thought,`" said he, "`I was once strong for the work, but now I am a child,
brought back to my horn-book,
and have nothing to trust to but the mercy of God through Christ my Saviour.`"
Thus reverently depending,
he was preserved to the last in great resignation and composure of mind.

He was mostly confined from the 26th of the Third month,
except frequently riding out for the benefit of air and exercise,
till the 18th day of the Sixth month, 1804,
in the evening of which he was considerably worse, continuing ill through the night,
and on the 19th in the morning, about six o`'clock,
closed his useful life in the fifty-fourth year of his age.
On the following day, his corpse,
attended by a great number of his friends and neighbors,
was interred in Friends`' burial-ground in this city.
