== Preface

In perusing so interesting a narrative as is presented in the account
of the Christian labors of this worthy minister of the gospel,
the inquiry may arise,
why it has been permitted to lie so long unprepared for the public eye?
In reply to this,
it may be remarked that some of his papers were for a long time mislaid,
and when collected,
they were placed in the hands of several persons to examine and arrange,
neither of whom made an essay for accomplishing the task.
They were voluminous,
and a variety of engagements arising out of the peculiar state into which the
religious Society of Friends here has been thrown within the last fifteen years,
seemed then to preclude the practicability of undertaking the work.
But from the conviction that there was much in
the papers to interest and instruct the seeking,
religious mind, I was induced to transcribe those parts,
and to endeavor to arrange the whole so as to
form a regular account of his life and labors,
so far as materials could be obtained.
In the course of his travels,
he was much more particular in the memoranda he made
than has been customary for Friends in his station;
giving a cursory description of the country, its produce, the value of it,
and the habits of the people where he travelled.
This peculiarity is accounted for by the fact,
that his notes were made for the information and gratification of his near connections;
and it would seem, without any prospect of their publication.
Some of those details, which may be found in other works, have been abridged,
though there is more of this description still retained
than is common in most journals of Friends,
but which will probably be interesting to many readers,
and render the work more acceptable to them.

I was intimately acquainted with William Savery, and esteemed him as a brother beloved.
His affable disposition, his catholic spirit, and his truly Christian principles,
endeared him to those who knew him,
and peculiarly qualified him as an instrument in the
Divine hand to draw others into the love of truth,
and into an obedience to the convictions of the Holy Spirit.
His ministry was generally more of a doctrinal nature than that of many other Friends,
accompanied with a fervent engagement that his audience might be
brought to an heartfelt experience of the unspeakable love of God,
in sending his dear Son, our Lord Jesus Christ, into the world to save sinners;
of the efficacy of his propitiatory sacrifice
and the sanctifying power of his Holy Spirit,
who hath by his own blood obtained eternal redemption
for all that come unto Him in true faith:
at times declaring with much solemnity and reverence,
that he would rather lose all he had in the world,
than be robbed of his faith in the divinity of Christ.

His submission to the power of Divine love in his own heart,
by which he was brought out of sin and corruption,
and his indefatigable devotion to the cause of Christ, present an instructive example,
calculated to invite old and young to diligence
and faithfulness in the path of manifested duty,
that they may become lights in the world, and through Divine mercy,
be partakers of that salvation which is only obtained through our Lord Jesus Christ.

[.signed-section-signature]
Jonathan Evans.

[.signed-section-context-close]
Philadelphia, Seventh month, 1837.
