== Chapter I.

[.chapter-synopsis]
* Early religious visitations
* Reflections made in after life
* Marriage
* Renewed exercises and their effects
* First appearance in the ministry
* Religious visits from 1781 to 1789
* Visit to S. Carolina and Georgia
* Deputation to the Indians of the N. West
* Address by Friends to the Indians
* Journey to meet the Indians
* Voyage up Niagara River and Lake Erie
* Drunken Indians
* Detroit
* Religious Meetings
* Kindness of the Officers to Friends
* Gathering and appearance of the Indians
* Interview with a Wyandot Chief
* Great heat of weather
* Horrors of Indian Wars
* Repeated Disappointments
* Indian Slaves
* Leaves Detroit
* Joins the Commissioners in Camp
* Continued detention
* Dangers from the Indians
* Meetings on the Frontiers
* Sickness
* Indians decline receiving the Commissioners
* Address from Friends sent to the Council
* Indians refuse the terms offered by Government
* Start for home
* Party divides
* Voyage down the St. Lawrence
* Terrible Storm and suffering Night
* Montreal
* St. Johns
* Voyage down Lake Champlain
* Sickness and Suffering
* Whitehall
* Journey through New York State
* Albany
* Yellow Fever in Philadelphia
* Voyage down the Hudson
* Arrival in Philadelphia
* Reward for the Sacrifices made
* Interest of Friends in the Indians

William Savery was born in the city of Philadelphia, in the year 1750;
received an education in the principles of the Christian religion,
and was placed with a Friend in the country to learn the tanning business.
Returning to the city after the expiration of his apprenticeship,
he associated with those, who, like himself, were much inclined to vanity and folly;
and seeking the enjoyment of ease and pleasure in a
course of life far remote from true happiness,
he became less susceptible of tender impressions,
and gradually much estranged to the voice and
heavenly care of the great Shepherd of the sheep.
In this situation it pleased Divine Goodness, by the powerful reproofs of his Spirit,
so to break in upon his wandering mind,
as frequently to bring him to an awful sense of
the bondage of corruption wherein he was held,
to some glimpse of the peace and comfort consequent upon a life of piety and virtue,
and the necessity of laboring to become a participant in that redemption, which,
through our Lord and Saviour Jesus Christ,
is graciously extended to the sincere penitent of every name and nation.

In a review of the benighted condition in which he had been involved,
and of the extension of Divine mercy in plucking him as a brand out of the burning,
he says,--

"`I may acknowledge,
that notwithstanding my revolt and turning aside from the paths of purity and peace,
the Lord has been graciously near me all my life long,
and has watched over me as a tender Father for good,
smitten me by his Spirit when I have been rebelling
against his holy law written in my heart,
making merry over the Divine witness there;
and has reached to me and tendered me in the midst of mirth and jollity.
He often followed me to my chamber,
and upon my pillow has drawn tears of sorrow and contrition from me,
when none have been privy to it but his All-seeing Eye:
so that my days of joy and laughter have often produced nights of sorrow and weeping.
Still I continued sinning and repenting and turning the
grace of God into wantonness for a number of years,
being at times favored to see, in part, the beauty there is in holiness,
but fearful of incurring the scoff and scorn of the
world`'s deluded votaries should I turn my back upon it.
Activity of spirits, loose discourse and noisy mirth,
were my sad refuge to drown serious reflection: yet the worm that never dieth,
a wounded conscience, often embittered my sweetest draughts of pleasure.
In this state I was inclined sometimes in a serious hour to read a pious author, which,
I think, by the assistance of the gracious Helper, was made serviceable to me,
being roused to more serious thought than ever before.

"`I now saw the iniquity of misspending my precious time,
and refrained from frequenting taverns and places of diversion.
I struggled hard to break myself off from my fondness for much company,
seeing the snare there was in it;
being apt to relate adventures and tales to provoke mirth,
and often for the embellishment of them to strain beyond the
truth--I was much concerned to watch over myself in this,
which is both dishonorable and sinful.
Oh the folly of thus misspending our precious time! how
watchful! how careful ought we to be of our words and actions;
always remembering,
that the sacred eye of an all-seeing God pervades the
most secret chambers we can retire to,
and his ear is ever open to hear both the evil and the good.
Yea, many of the present day have known,
when the terrors of the Lord have overtaken them for sin,
and they have had to taste of the spirit of judgment and of burning,
that every secret thing has been brought to light,
and all the hidden works of darkness have been made manifest;
that even for idle words they have had to render an account.

"`When we have long wandered, and got far and wide from the pure path,
in which the Lord`'s ransomed children have to walk,
though it may seem to have been in small things, yet they make close trying work for us;
and many deep baptisms we have to pass through,
before we can witness our sins to be wiped away and cast, as it were,
into the depth of the sea.
When this is experienced,
such have indeed cause to acknowledge with great humility of soul,
that it is of the mere mercy of Him whose mercies are,
(blessed be his great name,) over all his works.
Some, who with myself, have been rescued as from the very jaws of the devourer,
can praise his holy name with songs of gratitude and joy, knowing,
that in the midst of judgment he does still remember mercy.`"

In the year 1778, attending a meeting at Merion, held after an interment,
he was on that solemn occasion, deeply impressed with serious thoughtfulness.
Being married that year, he settled in business in Philadelphia.
The state of his mind about this time is described by himself nearly as follows;

"`I had been employed in bringing myself to a more circumspect life,
being pretty careful in my conduct and conversation, and just in my dealings among men,
and was willing to believe I had attained to great matters,
and that I might now take up my rest; for by my own strength,
abilities and contrivance, I could not only keep up a fair upright character among men,
and make my life happy and myself respected; but also, (Oh,
the deceitful workings of Satan!
Oh, the mystery of iniquity!) that it would, at the close of time here,
gain me an inheritance in the regions of purity and peace,
among all those that are sanctified.
But, how can I sufficiently adore my great and good Master,
for his continued regard and care over me,
in that he did not suffer me to remain long in this state of delusion and error.
He disturbed my false rest, and made me at times exceedingly uneasy with it,
and gave me at length to see,
that notwithstanding my regularity of behavior and all my boasted attainments,
I fell far short of that purity, which all the vessels in the Lord`'s house must come to;
and that I was yet under the law, which cannot make the comers thereunto perfect,
not having passed under the flaming sword, nor felt the day of the Lord to be come,
which burns as an oven.

"`This brought great distress and anxiety of mind over me,
and sometimes I was ready to doubt the truth of these divine revelations;
and was exceedingly desirous to find, if possible, an easier way to peace and happiness,
than by submitting myself to the cross, of which I had as yet experienced but little.
I was much tossed and distressed, as one who was in a dark and howling wilderness,
where I could see no way out, either to the right hand or to the left.
But at length, the Lord, who indeed watched over me continually for good,
blessed and praised forever be his name, brought me into some degree of composure.
The strong impression then made on my mind, its application to the state I was in,
and the instruction it conveyed to me,
left me no room to doubt its being divinely intended for my good.
My eyes became more clearly opened to discern where I was,
and that all the righteousness of my own putting on, was as filthy rags,
of which I must be stripped,
before I could experience a putting on of that purity and righteousness,
which is the fine linen of the saints.
In great distress and anxiety I saw nothing for me to lean upon,
but to dwell alone and keep my eye open and my spiritual ear attentive to Him,
who is the unchangeable High-Priest of his people,
and with whom are all the treasures of wisdom and knowledge,
who knows the states of all his children, and when and where He leads them,
graciously affords ability to follow, to the praise of his ever adorable name.

"`It pleased Him to lead me as into the wilderness,
and to give me a sight of my former disobedience and folly.
Oh! the bitterness and distress that covered me when I was alone or in meetings.
I experienced but few pleasant draughts of his love, my meat was gall and wormwood,
and my drink of the bitter waters of Marah.
This was not unfelt by some sympathizing Friends,
who were anxious that I might know an establishment upon the Rock immoveable.
Thus I continued, but was still preserved desirous to know the Master`'s will,
and in measure made willing to obey, though under the cross;
yet the way to the kingdom was for some months much darkened,
and a sense of my sinful conduct often brought me almost to
despair of ever finding forgiveness with an offended God:
and my burden in meetings was almost insupportable.

"`Oh! these were times of baptism never to be forgotten in mutability.
One evening, sitting in my house alone, great horror and trouble seized me--I wept aloud,
and after a short time went to bed; but my distress was so great,
that it almost overcame me, and I thought I tasted of the misery of fallen spirits.
Not being able to contain myself, I arose and walked the room.
My spirits at length being nearly exhausted, I threw myself on the bed again,
but had not lain long, before I grew cold like one near death, a clammy sweat covered me,
and I was to appearance stupid.
In this state I was, through adorable mercy,
released from the horror that before surrounded me,
and was comforted with a sight and feeling of a state of inexpressible happiness and joy;
and when so far come to myself as to have utterance given me, I cried aloud on this wise,
Oh! now I know that my Redeemer liveth.

"`Oh! the sweetness I then felt,
in being favored with such an evidence of the goodness and mercy of God!
It far surpassed everything I had ever before experienced,
and was such that I hope to bear it in remembrance as long as I have a being here.
Tears of joy ran freely down my cheeks,
insomuch that I could not restrain them nor
scarcely utter a word for a considerable time;
and my dear partner, who shared with me in my affliction,
was also made a partaker with me in my exceeding great joy.
Blessed forever be the name of the Lord,
though He sees meet for our refinement to try us even to an hair`'s breadth,
yet in our utmost extremity his all-powerful arm is made bare for our deliverance.`"

Being thus, in infinite mercy,
brought to a living experience of the unfathomable love of God towards his poor fallen,
helpless creatures, and the extension of his power for their redemption,
through our Lord Jesus Christ; he was concerned to abide under his purifying baptism,
that he might really know the communion of saints,
and have fellowship with the Father and with his Son Jesus Christ.
Having felt the terrors of the Lord for sin, it led to close watchfulness and fear,
lest the enemy, through his subtlety,
should draw his mind away from a steady subjection to the cross;
and when disengaged from his outward avocations,
he spent much of his time at home in retirement.

In the year 1779,
he accompanied a Friend on a visit to the meetings of Friends in Virginia and Carolina,
and as far as appears,
it was about this time that he was engaged to speak a few words in meetings,
by way of Gospel ministry.
To a mind sincerely desirous of advancing in the way and work of salvation,
this journey must have furnished many instructive lessons, which, carefully treasured up,
would be lastingly beneficial.
Some circumstances seem to have made such deep impression on his feelings,
as occasioned him to notice them with much concern.
A Friend had been drafted to serve in the army,
but being conscientiously scrupulous against bearing arms,
could not comply with the requisition.
He was therefore tried by a court martial, sentenced to be whipped,
and received forty lashes on his bare back with a whip of nine cords.
Although he had no friend to sympathize with or to encourage him in a
faithful testimony to the peaceable kingdom and government of Christ,
he meekly and patiently suffered his flesh to be thus barbarously
mangled in the presence of some thousands of persons.
William says, "`Great endeavors were afterwards used, both by threats and persuasions,
to induce him to comply with some service in the military establishment,
such as waiting upon the sick, or in some other employ that they might take hold of,
so as to answer their purpose: but remaining steadily fixed,
he could have no freedom to countenance their measures,
let the consequence be what it might.
I think it is worthy of remark,
that his prudent wife appeared to be more concerned on account of an
evil report that her husband had been brought to a compliance,
than for all his suffering, or all they were worth in the world.
After the time had expired, for which he had been drafted, he returned home.
Here, I may mention the reasons offered by a certain Major Roberts in the American army,
why the Friends ought not to suffer; he said, the Quakers had not deceived them,
they had borne their testimony from the beginning,
and were never known to bear arms on any occasion; they also paid taxes,
which were three-fold more than their proportion;
those treble taxes were in consequence of their not uniting in warlike measures.
It may also not be improper to take notice of a remark
made by a great woman of the church of England,
that she observed some of the Quakers`' children had departed from the plainness of
their profession and got about half-way into the fashions of the world,
which rendered them ridiculous in the eyes of
others and a reproach to their own Society.

His appearances in the ministry being approved,
he was acknowledged as a minister in the year 1781; and in 1785,
with the concurrence of his Monthly Meeting visited the Yearly Meeting held in Baltimore,
and some other meetings in Maryland.
In 1787, he attended the Yearly Meetings of New York and Rhode Island,
and visited several other meetings within the states of New York and New England;
and in 1789,
was again engaged in paying a religious visit to
some meetings in Maryland and Pennsylvania.

In 1791,
the Monthly Meeting uniting with his prospect of
religious duty to visit the city of Charleston,
South Carolina, and other places of the Southern States,
he took his passage in a vessel bound for Charleston in the fourth month,
and arrived there on the 22nd.

He says, "`24th being First-day, was at two meetings:
they were attended by more people not professing with us, than Friends,
who do not appear to be more than fifteen members in the place;
but the meetinghouse was too small to answer my concern of seeing the inhabitants.
Second-day being a time generally allotted for recreation and amusement,
the negroes appeared in their best trim and many of them cheerful,
yet the great numbers of them, and the reflections consequent on their abject condition,
gave everything a melancholy tinge with me.
Appointed a meeting to be held in the Methodist
meetinghouse in the evening of the 26th. The house was filled,
and it was said that several hundreds could not get in.
Some fundamental truths were opened, showing that the work of righteousness is peace,
and the effect thereof, quietness and assurance forever.
The Lord was pleased to favor with ability to my humbling admiration;
the meeting was still and solid, and I went to my lodgings in peace.

"`Colonel Laurens having obtained the privilege of the Baptist meetinghouse,
I agreed to have a meeting there in the evening of the first of fifth month.
It being First-day, I was at Friends`' meeting in the morning, which was large;
that in the evening was also large and satisfactory.
Left the city and got to T. Lewis`'s the 5th, about fifty-four miles.
Here are about seven families, who have built a small meetinghouse,
being convinced mostly without instrumental means; they meet in the manner of Friends,
twice a week, and appear to be an innocent people.
Our landlord has freed ten negroes, several of whom cost fifty guineas each;
he and his wife are united in this,
that they never found peace of mind until they had so done.
On our road we met between thirty and forty negroes, of both sexes, almost naked,
some of them lame and decrepit, travelling to Ashley bridge, a considerable distance off;
there to be put up and sold at vendue.
This made our hearts sad, and caused the reflection;
certainly there is a righteous and omniscient
Judge that commiserates the poor and oppressed,
and takes cognizance of the actions of hard-hearted and merciless oppressors,
and by terrible things in righteousness will
sooner or later plead the cause of the afflicted.
It is sorrowful, that because judgment against an evil work is not speedily executed,
the hearts of men are set to do evil.

"`Rode upwards of one hundred miles, and got to Bush-river meeting the 8th;
appointed one to be held at four o`'clock in the afternoon, which was large,
being attended by many professors.

"`The 9th, had a meeting at Rocky Spring; many Baptists and others attending,
it was very large, and through mercy strength was given to labor,
but I fear little good was done.
Proceeded to Cane creek and had a meeting; though the people appeared very raw,
yet it was to pretty good satisfaction.
The next meeting was at Paget`'s creek: a variety of religious professors were present,
and near the close the people were much tendered.
Had meetings at Raybor`'s creek, Mud-lick, and Allwood,
and on the 15th was at Cambridge or Ninety-six.
Had a meeting in the Courthouse, with a mixed multitude: it was large,
and thought to be open and satisfactory.
In the afternoon had another meeting in a large unfinished building; many attended,
and we thought it was well we were there.
Got to Wrightsborough, in Georgia,
and attended their week-day meeting on the 18th. The neighbors being invited,
it was a large gathering, and ended well.

"`The 19th, had a meeting at Mendenhall`'s:
a large number of Methodists and Baptists attended.
Two women fell on their knees, and trembled, and shook, and prayed, and exhorted.
I could scarcely account for such an extraordinary appearance,
as they continued in these agitations some time after meeting broke up.
Several wept, and most of the people appeared serious.
I stepped in among them again, and advised the women to stillness;
and then thought I had a more favorable opportunity to speak to the people than before;
upon the whole I felt easy when it was over.
As we were riding through the woods on the 20th, the road being narrow,
the iron of the swingletree breaking,
it fell on the mare`'s legs and set her to running and kicking in a frightful manner.
I expected nothing but to be dashed against the trees every moment,
for I had not power to stop her, nor any possibility of jumping out,
without imminent danger; but through the singular interposition of divine Providence,
who has watched over me with the tenderness of a father all my life,
the creature suddenly stopped and trembled exceedingly, when all my efforts were in vain.
A few yards further might, in all probability, have terminated the scene,
and I was accordingly endeavoring to be collected in my mind.
Such a marvellous escape was greatly to my humiliation,
and presented an impressive lesson to me.
What shall I render to thee, O Lord, for all thy unmerited mercies,
and to what end hast thou so often been gracious to me,
but that I might more fervently seek and serve thee, the remainder of my days.
Lord grant me strength so to do!

"`The 22nd being first-day, had a meeting at Wrightsborough:
the people of different professions and ranks came in great numbers;
it was thought to be a solid, tendering time; but not feeling quite easy,
I appointed another at four o`'clock in the afternoon,
the people continuing in the woods.
This was truly a relieving time,
and we thought we had never witnessed so much brokenness throughout:
they were loath to part with us, and many tears were shed on both sides.
I endeavored as soon as possible to retreat, but they stopped the sulkey^
footnote:[A light, two-wheeled carriage drawn by a horse.]
frequently, and seemed reluctant to let us go.
Accompanied by several Friends, we passed on to Augusta,
and proposed a meeting at four o`'clock in the afternoon of next day;
but the people being thoughtless and dissipated, were so taken up with their diversion,
that we did not obtain the company of more than twenty.
We proposed another at ten o`'clock, in the forenoon of the following day.
As they can scarcely tolerate us on account of our abhorrence of slavery,
this was truly a trying place to lodge in another night.
Near the time appointed, the bell was rung, and about one hundred collected;
many of them appeared to be people of some note, and being favored with utterance,
I cleared my mind, and before we parted,
gave them a charge to be more cautious of discouraging
disinterested religious visits in future.

"`On the 28th we got to Savannah.
The next day being First-day,
the parson came and offered his meetinghouse
for a meeting at five o`'clock in the evening,
which was large; several of the clergy, and many people of note, attended;
they appeared to be total strangers to us, and were at first light and airy,
but became more serious, and were mostly very attentive.
The Lord was near, and I trust was mouth and wisdom.
I left them easy and comforted in mind, being glad I gave up to go there,
though in the cross.
Crossed Savannah river, and lodged at +++_______+++ Blunt`'s,
who is a hard-hearted slaveholder.
One of his lads, about fourteen, coming in from the field at dark,
was ordered to go and milk the cows; and falling asleep through weariness,
the master called out and ordered him a flogging.
I asked him what he meant by a flogging.
He replied, the way we serve them here is, we cut their backs till they are raw all over,
and then salt them.
Upon this, my feelings were roused, I told him that was too bad,
and queried if it were possible; he replied it was, with many curses upon the blacks.
It disturbed us much, but I hoped his orders would not be obeyed.
We went to supper, and this unfeeling wretch craved a blessing,
which I considered to be equally abhorrent to the Divine Being as his curses.

"`31st. Rose in the morning, and whilst at the door musing,
I heard someone begging for mercy, and also the lashes of a whip.
Not knowing whence the sound came, I ran,
and presently found the poor boy tied up to a post,
his toes scarcely touching the ground, and a negro whipper,
with five or six hazel rods lying by him.
He had already cut him in an unmerciful manner, and the blood ran to his heels.
I stepped in between them, and ordered him untied immediately,
which with some reluctance and astonishment was done.
Returning to the house, I saw the landlord, who then showed himself in his true colors,
the most abominably wicked man I ever met with,
full of horrid execrations and threatenings upon all the Northern people;
but I did not spare him,
which occasioned a bystander to express with an oath that I should be '`popped over.`'

"`We left them, distressed in mind,
and having a lonesome wood of twelve miles to pass through,
were in full expectation of their waylaying or coming after us,
to put their wicked threats in execution; but the Lord restrained them.
This was a day of heaviness and sorrowful reflection,
and the next house we stopped at we found the same wicked spirit.
We rode through many rice swamps, where the blacks are very numerous,
great droves of these poor slaves working up to the middle in water,
men and women nearly naked: a peck of corn is their miserable subsistence for a week.
A gloomy sadness covered them, so as scarcely to admit of the interchange of a sentiment.
O Christianity and humanity, how are ye disgraced!
Where will such astonishing horrible conduct end?

"`Sixth month, 2nd, got to Charleston.
On First-day, the 5th, attended Friends`' meeting in the morning,
and had a public meeting in the evening at the Baptist meetinghouse,
which was large and a relieving time to my mind.

"`The 23rd was at Cane creek, North Carolina; it being their week-day meeting.
It was pretty large, many came to it directly out of their harvest fields,
and our good Master was with us.
Had meetings at several places to a good degree of satisfaction, and got to Petersburg,
in Virginia, the 2nd of Seventh month.
On First-day, the 3rd, had a public meeting at four o`'clock in the afternoon,
which was very large, the people of other religious denominations attending,
the house could not contain them all; but it ended well.`"^
footnote:[The reader will observe that there is
a considerable interval between these dates;
no memoranda appear to have been made,
and the information requisite to fill the chasms which
are left by the writer cannot now be obtained.]

[.asterism]
'''

In the year 1792 he visited the meetings of Friends in Virginia,
attended their Yearly Meeting,
and appears to have been favored with strength to fulfill the service required of him,
with peace to his own mind.

The condition of the Indian natives in this country had for some
years engaged the attention of the Yearly Meeting of Philadelphia,
and its representative body, the Meeting for Sufferings;
and in the recollection of the kindness shown by those original proprietors
of the soil to the Friends who first landed on these shores,
and the friendship which subsisted between them,
the Society had endeavored to cherish that bond of union,
and to evince their gratitude and love by such aid as it was in their power to bestow.

These acts of benevolence, however, had been interrupted by war,
devastating the frontier settlements, and staining the land with blood.
Deeply affected with the horrors attendant on this cruel contest,
the Meeting for Sufferings, in the Eleventh month, 1792,
was engaged to prepare a respectful memorial to
the President and Congress of the United States,
recommending the adoption of such pacific and just measures
toward the natives as might arrest this savage warfare,
and establish peace upon a firm basis.
In the Second month following,
the meeting was informed that a treaty was likely to be
held at Sandusky (now in the State of Ohio),
and by messages received through Captain Hendricks and his brothers,
two Indian messengers recently from the Western country, and also a letter from Hopackon,
a sachem of the Delaware nation,
it appeared that the Indians were very solicitous some Friends should attend it,
and as a confirmation of the message and a token of their continued friendship,
they sent three strings of white wampum.

Several Friends, of whom William Savery was one,
feeling their minds religiously engaged to visit the
Indian country about the time the treaty was to be held,
and producing to the Meeting for Sufferings in the Fourth month, 1793, minutes,
expressing the unity of their respective Monthly Meetings,
and the approbation of President Washington having been obtained,
they were deputed in its behalf to attend the said treaty,
and present to the natives the following address, viz:

[.embedded-content-document.address]
--

[.letter-heading]
To the
Indians living on the North-Western and Western borders of the United States,
and all others whom this writing may concern:

[.salutation]
Brothers,

Hearken to the speech which your friends called Quakers, assembled in Philadelphia,
from several parts of Pennsylvania, New Jersey, etc., now send to you by their brethren,
John Parrish, William Savery, John Elliott, Jacob Lindley, Joseph Moore,
and William Hartshorne.

Brothers,--When our grandfathers came with Onas +++[+++William Penn]^
footnote:["`Onas`" is the Native American word for feather or quill.
Having written (with the white man`'s feather pen) and
honored several treaties with the Native Americans,
William Penn was given the name Brother Onas by the
Native Americans who had come to love and respect him.]
over the great waters to settle in this land, more than one hundred years ago,
they kindled a large council fire with your grandfathers,
and sat together around it in much good-will and friendship,
smoking the calumet pipe together;
and they told your grandfathers that they were men of peace,
and desired to live among you in peace and love,
and that their children might also be careful
always to live in the same love one with another,
as brothers of the same family.

This council fire was kept burning with a clear flame many years,
which gave a good light to all around the country,
and the chain of friendship which was made at the same time,
was kept clean from rust by our fathers and your fathers; until about forty years ago,
an evil spirit whispered bad stories in the ears of
some of your people and of some of the white people,
so that the light of the ancient council fire was almost put out,
and the old chain of friendship was made dull and rusty.

Brothers,--Our grandfathers told your grandfathers,
that the Great and Good Spirit who made them and all people,
with a design that they might live on this earth for a few years,
in love and good-will one toward another, had placed his law in the hearts of all men,
and if they carefully attended to its inward voice,
it would keep them in love and friendship,
and teach them to shun everything that would
occasion them to trouble and hurt one another.

Brothers,--Do you not find that after you have been angry and quarrelsome,
or done any bad action, you are made uneasy and sorrowful;
and that when you are sober and serious, and do good actions, your minds feel pleasant,
easy, and comfortable?
It is the law from the Good Spirit, who is all love, and who placed it in your hearts,
which gives you such peace and comfort when you do well, but when you do evil things,
it reproves you and makes you feel uneasy and sad.

Brothers,--We wish you to consider and remember,
that the Great Spirit sees and knows all the thoughts of your hearts,
and of the hearts of all mankind, and all their actions.
And when their bodies die, such men of all colors and all nations, who have loved,
served and obeyed the holy law of the Good Spirit, placed in their hearts,
He will receive their souls, which are never to die,
and they will live with Him in joy and peace forever:
but the souls of bad men who have lived wickedly in this world, must live,
after their bodies die, with the bad Spirit in a state of distress and misery.

Brothers,--We make profession of the same principles with our grandfathers,
which teach us to love you and all men;
and in that love we feel our minds drawn to send you this speech,
with a great desire for your good.--We were made glad when we heard that the sober,
good people among you were disposed to promote
peace and brighten the old chain of friendship,
with the white people of the United States;
and that many of you have a desire that you may be instructed in tilling the ground,
and to live after the manner of the white people,
which we believe you will find to be more comfortable for you and your families,
than to live only by hunting;
and we think it will also be good for your young people to be learned to read and write,
and that sober, honest, good men should be sent among you for teachers.

Brothers,--We have often told some of your chiefs when we have
had the opportunity of taking them by the hand in this city,
that we are not concerned in the management of the affairs of government,
which are under the direction of the President of the United States, and his counsellors,
but that we should, at all times,
be willing to do anything in our power to promote love and peace.

Brothers,--We greatly desire that the commissioners who are now sent by the President,
and also your counsellors and chiefs,
may look up to the Great Spirit for his wisdom and help,
that you may all be made wise and strong to light up the council fire,
and brighten the chain of old friendship, that all things may be settled to satisfaction,
and a lasting peace established,
so that there may be no more difference or war between
your people and the inhabitants of these States.

We desire you may receive our friends, by whom we send this writing, in love,
as brothers who are disposed to encourage you in all good things.--And,
in the ancient love which our grandfathers felt for each other, we salute you,
wishing you happiness in this life, and that which is to come,
and remain your friends and brothers.

[.signed-section-signature]
Signed by forty-four Friends.

[.signed-section-context-close]
Philadelphia, fourth month 19th, 1793.

--

Of this journey, which proved to be one of great exposure and personal suffering,
William Savery has preserved memorandums; from which it appears,
that they left Philadelphia in the Fifth month, 1793, and on arriving at New York,
met with John Heckewelder, a Moravian missionary, who had lived among the Indians,
and was going to attend the treaty.
On First-day, the 5th of the month, they attended two meetings in the city,
and appointed one at seven o`'clock in the evening,
which was largely attended by professors of several denominations: it was solid,
and ended to satisfaction.
They left New York that evening, and got to Albany the 8th.

William says, "`our stores having arrived with general Lincoln,
they were nearly all put on board of eight batteaux,^
footnote:[Small flat-bottomed boats, similar in appearance to a canoe.]
built for the purpose; two of these were covered in the centre with painted canvas,
about nine feet in length, surrounded with curtains, and had each a table in the middle.
Embarking the 9th, our little fleet attracted the attention of the inhabitants,
who were civil, and I believe wished us well.
It was truly a novel scene to most of the passengers.
The Mohawk has a strong current, frequently rapid,
and so shallow that the bottoms of our boats often rubbed the bed of the river;
this made hard work for the boatmen.

"`The 13th, all our boats and baggage being transported to the landing, above the falls,
we went on board, and arrived at fort Herkimer, making only seven miles today.

"`14th. John Heckewelder, Jacob Lindley, and myself, being with general Lincoln,
we became engaged in religious conversation with much kindness and charity;
the General expressed many just and valuable sentiments
on the weighty subjects under discussion.
Arrived at fort Schuyler in the evening.

"`17th. The boats and stores being yesterday taken over
from fort Stanwix to Wood creek landing,
we set off about eight o`'clock in the morning,
but as the creek was only about six inches deep,
were obliged to take about two tons out of our large boats and carry it in wagons,
to the junction of Canada creek; after this,
having the aid of the waters of a mill-dam at the head of the creek,
the boats readily floated.
Most of the passengers walked this distance, which was about seven miles.
At three o`'clock we embarked again, and made about sixteen miles today;
here we encamped, and next day got to the mouth of Oneida lake.
About three o`'clock got through the lake to fort Brewington,
at the mouth of Onondaga river.

"`19th. After breakfast sailed down a beautiful stream twelve miles, to Oswego falls.
Some Onondaga Indians followed us in a bark canoe,
and caught some fine salmon and other fish for us.
We encamped and lodged comfortably, being about eighty in company.

"`20th. After drawing our boats by hand on rollers, about one hundred yards,
we launched them below the main falls, and again embarking,
went down a rapid rocky current to Oswego fort, twelve miles.
It is a strong British garrison, commanded by Captain Wickham,
who sent his servant to invite us to his quarters, and treated us respectfully.
After being hospitably entertained, we left the fort and embarked on lake Ontario;
rowed hard to a harbor fifteen miles,
which we reached about nine o`'clock in the evening, and encamped.
Made twenty-nine miles on the 21st. As the wind was high next day,
we lay at the harbor until afternoon, then sailed seven miles, and encamped on the beach.

"`The 25th, got to Niagara fort, and stayed until about four o`'clock;
then crossed the river, which is about half a mile wide,
and took possession of two rooms in an unfinished house,
which the commissioners had prepared for us, having our own provisions and mattresses.

"`26th. Waited on the governor at his request, and were treated respectfully;
dined at our lodgings upon wild pigeons, which the Indians shot flying,
with their bows and arrows.
The town consists of about fifty houses: it is laid out in half-acre lots, and is likely,
from the extensive navigation and increase of population,
to be a place of considerable trade in a few years.

"`27th. Packed up our bedding and proceeded with
all the batteaux and stores to the landing-place,
seven miles up the river; pitched our tents on the bank of a green meadow,
and at the invitation of Captain Smith and other officers,
several of us dined with them at the mess-house.
Here are large barracks, with three or four hundred men, in a low unhealthy spot,
many of them very sickly, and a number die almost daily.

"`30th. Were visited by the governor, Timothy Pickering, and others.
The governor offered his house, at this place, for our accommodation;
but its low situation occasioned us to decline accepting it.

"`31st. Several of us went down in our boat to Navy Hall,
and spent several hours with the commissioners: we got passes from Governor Simcoe,
to go on to Detroit, by the first king`'s vessel from Fort Erie.

"`First-day, 2nd of Sixth month, a meeting being appointed to be held in a barn,
about four miles from our encampment; Friends, and some people from the landing,
attended.
It was larger than we expected, being composed of a variety of professors,
among whom were eight or ten Friends, who are settled in the neighborhood.
No regular place of worship being kept up for many miles,
the opportunity of assembling for that purpose appeared to be very acceptable;
the meeting was solid, and we hope may be useful.

"`3rd. Struck our tents,
and packed up as many stores as were thought
necessary--a wagon being prepared to take them,
and one of our large boats mounted on a carriage, we set off for Chippeway,
the landing place above the falls, where we lodged at a tolerably good house.

"`4th. Proceeded early up Niagara river, against a strong current,
which was rather unpleasant, for had we been driven down half a mile,
every effort must have been unavailing to rescue
us from descending the tremendous cataract.
Arrived at a farm-house, where being supplied with milk and butter, we breakfasted;
dined at a tavern four miles below Fort Erie,
where we found a large number of farmers convened from a considerable distance,
in order to render an account of their improvements and property;
several of whom were Friends and Menonists from Pennsylvania.
Reached Fort Erie about four o`'clock, and finding three British vessels,
we took our passage, but the wind being unfavorable, could not sail.

"`Fourth-day, the 5th, the wind still unfavorable.
The land between Niagara and this place, is generally rich and well timbered,
and is settling fast by people who are mostly from the United States,
and among them a greater number of members of our Society, than I had expected to find.
While at dinner the wind becoming fair,
a gun was fired to hasten the Indians and other passengers on board.
We sailed pleasantly, at the rate of about four miles an hour,
having on board about ninety persons, forty-five of whom were Mohawks, Messasauges,
Stockbridge, and Cayuga Indians.

"`Fifth-day, the wind pretty fair; sailed pleasantly in much harmony,
the time spent agreeably and usefully.
We conversed with the Indians and made them some small presents,
with which they were much pleased.
Towards evening the wind abating,
the vessel rolled so much as to cause many of the passengers to be sick,
myself among the number.
A storm of rain, with thunder and lightning, coming on in the night,
some of us got but little rest, and having a large quantity of powder on board,
our situation was awful, but Divine Goodness preserved us through it,
for which I desire to remain thankful, and increasingly studious in my inquiry,
'`What shall I render Him for all his mercies?`'

"`Sixth-day, the wind unfavorable.
Seventh-day, sailed perhaps thirty or forty miles.

"`First-day, the 9th, about noon came in sight of the Bass islands,
near which are abundance of fine fish;--continued heaving the lead from
about eleven o`'clock to three--the water near those islands being shoal.
Held a meeting in the cabin, at which were present our cabin passengers,
and some of those in the steerage, Captain Hendricks and his Indians, Captain John,
and as many of his as could find room--they all behaved soberly,
and it was satisfactory to us.
Several of the Indians expressed the same;
and Captain John informed the captain of the vessel,
he should be glad if he could have had what was said in writing,
and was more familiar and friendly ever after.
Arrived at nine o`'clock at the mouth of the river Detroit.

"`Second-day, weighed anchor with a fair wind, but a strong current against us;
the morning being fine, it afforded us a beautiful prospect of continued houses, farms,
wind-mills, luxuriant meadows and orchards, which had a very pleasing effect,
having seen nothing like it since we left the Mohawk river.
Arrived at Detroit about eight o`'clock, and after breakfasting on board,
went on shore to procure lodgings,
but finding the rent of two rooms to be four dollars per day,
we gave up the idea of finding our own provisions,
and took up our boarding at a house where we have a good table,
and sleep upon our own mattresses:
all kinds of foreign articles are about three-fold more than in Philadelphia.
Veal, one shilling, beef, fifteen pence per pound, fowls, four shillings a couple,
butter, two shillings and sixpence, etc.

"`Third-day, the 11th, the weather was very warm:
walked round the town and found the number of
houses and inhabitants to exceed my expectation.
We computed the houses, exclusive of the barracks, at two hundred; some of them good,
especially along the bank of the river.
There is only one place of worship, which is a Romish chapel.
Lieutenant-colonel England commands the regiment quartered in this place;
he is a very respectable man: the officers are civil and polite,
and possess a good opinion of Friends.

"`Fourth-day, the 12th, many Indians came to see us, but most of them being intoxicated,
we had little conversation with them.
The people seemed astonished to see Quakers;
and some of the officers calling to visit us, treated us respectfully.

"`Fifth-day, had a serious conference with Captain John, and other chiefs of the Mohawks,
to our satisfaction; they expressed themselves friendly,
and much approved of our attending the treaty.

"`14th. Almost wearied out with the importunities of the Indians for rum,
we however put them off.
Some of the Chippeways having arrived last evening from Michilimackinac,
and encamped outside the picquets, we paid them a visit,
but they had drunk much rum before we went, were very rude, called us ill names,
and appeared very angry.
All the Indians I had ever seen were far short of these
in their extraordinary terrifying painting,
and the appendages of their dress; any description I am capable of giving,
must afford a very faint idea of the ferocious appearance of this nation.
On leaving them, one followed and took hold of the arm of one of us, crying very harshly,
'`come back, come back.`' A ship-carpenter who was near, and understood their language,
said he believed if we had returned to them, they would certainly have killed us,
which most likely they would;
this made us more cautious of going into their company afterwards,
especially when heated with strong drink.
A number of Indians frightfully painted, passed through the town, dancing the war dance,
some of whom having knowledge of us, came to our lodging to pay us a compliment;
but I wish to be excused from a compliment of the like kind in future.
The frightful painting of their faces and bodies,
which are almost naked on such occasions, their terrifying whoops and yells,
their ferocious countenances and actions,
together with the tomahawks and scalping knives in their hands, form so horrid a scene,
that every truly Christian mind must recoil from it with disgust and sadness.
Sorrowful indeed it is to reflect, that such is the depravity of many,
under the dignified character of Christians,
whose conduct towards these poor creatures ought to have been marked with a pacific
desire of inspiring them with the mild and blessed doctrines of the Gospel,
that they are, alas! taking delight in encouraging them to this exercise,
and stimulate them with large potations of strong liquor, until they become frantic.

"`Dined by invitation at the officers`' mess-house; their respectful,
polite behavior to Friends, marked their character as gentlemen,
and merited our acknowledgment; they permitted us to use great freedom with them,
and I hope we kept our places.

Seventh-day,
after informing the colonel of our intention to hold a meeting here tomorrow,
to which he cordially assented, we viewed two places which were offered for the purpose;
but they being somewhat inconvenient, the king`'s ship-builder offered his boathouse,
which being large, and in a fine airy place on the side of the river, we accepted it.
Being much troubled with the continual visits of the Indians,
begging for rum and other things, we were obliged to retire up stairs to avoid them.

"`First-day, 16th of Sixth month, attended the meeting at ten o`'clock forenoon.
The colonel having dispensed with the accustomed military exercise,
which is practised at that hour,
a large number of soldiers and most of the officers were present,
besides a considerable collection of the inhabitants of the place of both sexes;
and as the house was in a large open lot, great numbers stood out of doors.
This being doubtless the first meeting of our Society at Detroit,
curiosity was greatly excited; their behavior at first, as might be expected,
was a little restless, talking, taking snuff, etc.,
but upon one of our company endeavoring to set
before them the nature of our mode of worship,
with a request they would join in our manner, they were very attentive and became still;
some of them, especially among the poor soldiers, were reverent and thoughtful.
The service, which was considerable, appeared to be received with openness,
and I believe the opportunity ended to mutual satisfaction.
There is no Protestant place of worship, that I can hear of,
within a long way from this place: all that has the shadow of worship,
except the Roman Catholic, is the reading of prayers and church service by an officer,
sometimes on First-days, at which the Protestant inhabitants attend.
After dinner the colonel`'s boat being prepared,
about twelve or fifteen of us proceeded down the river
to attend a meeting appointed at four o`'clock,
six miles off.
Several other boats set off in company, but the wind being high,
one of them put back--there were a number of Menonists with long beards present,
some French people, and the farmers in the neighborhood:--I hope the meeting ended well.
Returned to Detroit,
thankful to the Author of mercies for his unmerited kindness during the day.

"`Second-day,
17th. We have need to ask for both faith and
patience to support us under our long detention,
and the continual alarming reports of the disposition of the Indians,
who are collecting for the treaty.
Most of those who pass this place are said to go prepared for war,
if the commissioners do not comply with their wishes: they are in a haughty spirit,
being elated with their successes.
There are many among the inhabitants here kindly disposed towards us,
who appear to be very doubtful for our personal safety at Sandusky,
and seem rather to desire we would not venture.
We are thankful in being preserved so far in quietness and confidence,
trusting in the Omnipotent arm for preservation.
We cannot admit a doubt of the propriety of our coming,
nor of the motives which led to it; yet I may say,
it is the most trying situation I was ever brought into.
May the Lord preserve the little band,
'`wise as serpents and harmless as doves.`' At four o`'clock several of our company
dined at Colonel England`'s. The state of my mind made me wish to be excused,
but thought it improper to slight so respectful an invitation to us poor strangers.
The colonel is a man of great openness of manners, quite a soldier,
and his wife an amiable woman.
Five of the officers of the regiment being present,
we sat down to a table spread in all the elegance of a populous city.
After travelling several hundred miles of wilderness,
and encamping on the ground like poor pilgrims,
it was really marvellous to find plenty and elegance,
at least equal to the most fashionable houses in our city.
He did everything to make our visit agreeable,
which has also been the disposition of all the officers since we arrived.

"`Fourth-day, a boat coming for us from the neighborhood of the Menonists,
which arrangement had been made on the First-day preceding, all the Friends,
except myself, went down in it.
Having a pain in my head and bones, and being apprehensive it was the prelude of a fever,
I took some medicine and confined myself all day.
Towards evening was much relieved,
but the prospect of a fit of sickness so far from home put my
resignation to the will of an all-wise Providence to the proof,
and I found, as I have often before, that it is one of the highest degrees of attainment,
to say with sincerity, '`Thy will be done.`' Fifth-day evening,
at the request of the officers, I spent an hour or two with four of them,
and conversed on the nature of our business with the Indians.
They expressed a belief that much respect would be paid to the sentiments of Friends,
and assured me that the discouraging sentiments we had heard respecting our
personal safety at the treaty need not occasion us a moment`'s concern,
for it was not strange that such insinuations should drop from
those who were interested in the continuance of hostilities.
Some remarks on the difference of our pursuits and profession
produced the expression of a prospect which some of them had,
that before very long they would exchange the sword for the ploughshare.

"`Sixth-day, 21st, a number of Indians arrived from many hundred miles to the North-west.
They were frightfully painted; their dress more singular than any I have yet seen,
and generally large muscular men.
It is amazing to reflect on the vast distance they travel in their canoes
along the continued chain of lakes and rivers in this part of America.
We are now fourteen or fifteen hundred miles by the
water communication from the sea at Louisbourg,
and the trade is carried on, it is said, for two thousand miles beyond this,
from whence none but the costliest furs, as beaver, marten, etc., are worth bringing.
Schooners go about six hundred miles beyond Detroit;
thus the trade in furs is brought to this place
far beyond what I could ever have imagined.
A vast country, which may in time become an extensive empire,
remains unsettled in the British territories,
in which are large bodies of excellent land: that which lies along the river Le French,
about fifty or sixty miles above this, is fast settling,
and two hundred acres to a family are given gratis.
Good fish are plenty in these waters,
but no eels have ever been found above the falls of Niagara, nor rats on the land.

"`First-day, 23rd, we held a meeting in a large sail loft,
but not having given notice to the colonel of our intention,
the soldiers were out on parade.
The gathering was pretty large, many coming in from the country;
and the doctrine appeared to be closer than some present could bear.
A serious call was sounded,
to examine the foundation of a hope of salvation through Christ,
while men remain under the dominion of a long
catalogue of sinful indulgences and profanity;
and inculcating the necessity of having our
conversation such as becometh the Gospel of Christ,
in order to obtain an inheritance in his kingdom.
The labor was painful, and tended to our mortification, but this is good for us;
indeed it would be a vain expectation for us to think to reign,
where Truth so evidently suffers:
may we be favored with an increase of resignation to the Divine will.
In the afternoon I had some painful reflections on the state of the people,
and the prospect of some weeks longer continuance among them.
The upright intention of our hearts in coming on this
fatiguing and exercising journey being recurred to,
I went to bed somewhat revived, in humble confidence in the Divine arm for support;
and remembering the gracious promise, '`Lo!
I am with you always.`'

"`Second-day, 24th, Joseph Moore and myself went down to the river La Rouge,
and proceeded five miles up it to a new grist-mill, where we dined.
The people settled on the sides of the river are mostly French and Germans;
the land flat and wet.
We had conversation with several Germans,
who appeared to have a great desire for us to hold a meeting;
one man kindly offering to send horses for us whenever we gave them notice.

"`25th. J. Heckewelder returned yesterday from the Moravian town, on the river Le French,
and brought with him Gabriel Senseman, a missionary, and six or seven Indians,
among whom was John Killbuck, and his son, who had been educated at Princeton College,
but has again resumed Indian habits and manners.
These poor Indians, who do not go to war, have been driven about, from place to place,
and much distressed.
Governor Simcoe has now granted them ten miles square of land,
which they are beginning to cultivate;
but at present their situation was represented to be very distressing,
for want of provisions, having scarcely anything to subsist on, but roots,
until their corn grows.
Heckewelder and Senseman requesting our attention to them,
Friends took it into consideration, and no other resources appearing,
we thought it right to procure corn and flour for them,
to the amount of one hundred dollars;
part of which they immediately took off in their canoes.
Dined at William Forsythe`'s, on the river side,
and wrote an epistle to the Moravian Indians.

"`27th. Spent most of the day at our lodgings; a Shawnese chief, who, we were informed,
had come from the council at the Miami Rapids, desiring to see us,
we had some conversation with him through an interpreter,
but could not obtain his sentiments respecting the issue of the treaty:
he appeared to be a quiet, cautious man,
and thought the treaty would not be over before frost.
We are almost ready, at times, to apprehend that our patience will be exhausted,
yet cannot doubt but our unforeseen detention in this remote and libertine place,
will have its use.
I am thankful that our little band is preserved in good health,
and favored with unity of prospect and concern;
and hope our conversation has in good measure been such as becometh our profession.
It has, however, been peculiarly trying to me today,
to look forward to so long a separation from my precious home and dear friends, which,
with the sentiments we daily hear expressed,
of the danger of losing our lives at the treaty,
if the Indians should not be gratified in their demands,
causes us to be serious and thoughtful,
and to search for that foundation where we may
stand unshaken in every trial that yet awaits us.
Some evenings past, two Indians being intoxicated, quarrelled outside the garrison,
and one killed the other; of which I do not hear that any notice has been taken;
but probably the survivor will ere long be killed by
some friend or relative of the deceased,
according to Indian custom.
No Indian is suffered to stay inside the gates of the garrison, after the drum beats;
nor more than thirty to be within at once in the daytime; and these all disarmed.

"`28th. Visited Captain Labourne, who granted us the use of his library,
and we spent most of the forenoon in reading.
Captain Drake giving us his company,
related many curious observations he had made
during four years`' employment on these lakes,
having arrived a few days past from Michilimackinac,
about one hundred and thirty leagues distant, at the further end of lake Huron.
He informed us that many hundred men are employed by the North-West company,
who are constantly travelling to a very great distance,
trading with the Northern Indians for the richest peltry,
which is mostly brought from high Northern latitudes.
They are generally French Canadians,
and continue a number of years without coming into the settlements of the whites;
living principally on fish and game without salt--they are remarkably healthy.
All accounts agree that the most distant Indians
yet discovered are peaceable and harmless.
Many of those here are, on the contrary, fierce, artful,
and much prejudiced against the inhabitants of the United States.
This we experienced, before they knew anything of us,
by their angry looks and drawing away their hands when
we offered ours--calling us Shomochoman or long knives,
by which they distinguish all who are citizens of the United States.
Yet when we have an opportunity of informing who we are, and our motives in coming here,
they become kind, and do not use those epithets.
Much, I conceive, may be done with these poor people, by persuasion, kindness,
and honest dealing; but little by compulsion.

"`29th. Visited by a Wyandot chief,
who said he remembered some long and broad belts
that were given to Friends in former treaties,
which were intended to bind us together by the hands and arms,
so that no small accident in future should be able to make a separation;
and notwithstanding all that had happened,
the Wyandots felt some of the old affection to remain.
We assured him, we had the same love and friendship for them that our forefathers had,
and that our principles had always restrained us from war;
but believing our government was disposed to
make peace with them on principles of justice,
we were made willing to leave our families and take this long journey,
to endeavor to promote it, and to be present at the conclusion of so good a work.
He replied, he knew long ago that our Society did not fight,
that he was glad to see us here on so good a work;
and that as we had come a long journey, and were all preserved in health, as he saw us,
it was evident the Great Spirit was pleased with our journey,
and he hoped some good would be done,
and that the Great Spirit would bring us home in health and safety.

"`30th. A blind chief, of the Wyandot nation, visited us with some of his relations.
The meeting for worship in the sail-loft was large and solid, considering the company;
held another at five o`'clock in the afternoon, which was large, as before,
and to good satisfaction; the citizens, officers and soldiers, all quiet,
though a very warm day.

"`Seventh month, 3rd. Very warm.
The Ottaway having arrived from Fort Erie, we fully expected the commissioners,
or at least some letters from home, but were disappointed of both;
a fresh occasion for the exercise of patience and resignation was thus afforded.
Eighteen Oneida Indians came in the Ottaway, with sixty of other nations,
intending for the Grand Council at the Rapids, where the vessel touched,
and all but these were landed with Colonel Butler;
but these Indians being esteemed in the American interest,
and the chief unpopular with the war chiefs of other tribes,
the colonel was of opinion their lives would be in danger,
and therefore he sent them here to go forward with us to Sandusky.
This day the thermometer was at ninety-six.

"`Fifth-day, 4th of the month,
were informed the thermometer was at one hundred degrees in the shade,
and one hundred and twenty in the sun.
5th of the month.
We desire to be preserved from murmuring at our confinement in this place,
but many considerations conspire to prompt the wish to be released.
Our ears are constantly assailed with multiplied
instances of Indian perfidy and cruelty in their wars;
several fresh cases related this morning by one, who,
with her husband and some others now in this place, were prisoners.
About three hundred and ninety-five of them had fled into forts, for protection,
near the close of the war with Great Britain, consisting of men, women, and children,
inhabitants of Kentucky. They capitulated to a body of British troops and Indians,
on the condition that their lives were to be spared; but after a march of a day or two,
a number being aged and infirm, they were tomahawked;
after which each nation of Indians claiming a proportion of the prisoners;
husband and wife, parents and children, were separated,
and thus involved in the deepest distress.
The family of our informant, with many others, were brought to this place.
After some time, receiving intelligence that one of their children was with the Shawnese,
about two days`' journey hence, and that a day was appointed to burn him,
the father went off immediately, and with the interest of some traders,
and at the expense of one hundred pounds, obtained his child.
They were now in a thriving way, but had not yet fully discharged the debt.
Numerous well-authenticated instances equally distressing, we daily hear,
showing the horrors of Indian war--burning prisoners in
a slow fire of one or two days`' duration,
with shocking tortures of different kinds,
too much even to relate without the most painful feelings to
every mind not callous to the sensibilities of humanity.
O ye professors of the benign and heavenly doctrines of the Gospel,
that breathes nothing but peace and good-will to men,
how will ye appear in the awful day of retribution,
when our Divine Master shall come to judge the world in righteousness,
if any of you have been promoters of the great devastation, wretchedness, and misery,
which mark the footsteps of war?
In justice to the humane and generous officers of this garrison, we may say,
that their efforts have been numerous, and mostly successful,
in alleviating the miseries of the poor captives,
many of whom they have purchased at a great price:
some have cost near one hundred pounds;
and they have also relieved and clothed many who have escaped,
besides furnishing them with provisions to return home.
This, however, they are instructed by government to do;
yet their acts of private benevolence are very extensive,
this post being a door of communication to all the Indian country,
objects are continually offering.

"`Intelligence from the council, at the Rapids, informs us, that two chiefs,
from every nation there assembled,
had embarked for Niagara to inquire of the commissioners the extent of their powers;
and if they should find that they may lead to a reconciliation,
they are requested to abide till all the Indians are collected at Sandusky,
being determined,
that unless the commissioners agree to give up all the lands west of the Ohio,
they will not make peace; and if any terms short of this should be offered,
it is the opinion here, that the Indians will sacrifice all the Americans on the spot.
One of the two Shawnese that arrived here,
says he was daily an ear-witness to their counsels,
and assures us we may depend on his words as truth.
He says they want neither presents nor purchase-money, but their hunting-grounds;
without which they cannot subsist; and for their recovery they will risk their lives.
He further added,
what he had at times heard from old men concerning the first coming of the white people.
The wise men among the Indians, at that time, foresaw what has now happened,
and warned their brothers not to countenance each other
in receiving gifts from the white people;
saying, that the Great Spirit had made the land over the great lake for white people,
and this island for the yellow people.
They then refused to drink rum, and told the whites,
the Indians did not want the bitter water; that it was only drink for white people,
and that the Great Spirit had given the brooks
and springs to the Indians for their drink;
and foretold the consequence of Indians receiving that, and knives and hatchets,
which would be the ruin of them.
He remarked, that now several of those original tribes were extinct,
and yet the Indians had not adverted to the advice,
but had continued parting with their lands for these things,
until they were almost driven to where the sun set.
Happy would it have been if these poor Indians had
continued to refuse the bitter water to this day.
This day the thermometer was one hundred and two in the shade.

"`6th. Not quite so hot as yesterday:
spent the morning in reading and conversing with some visitors.
A vessel arriving,
confirms the account of deputies having gone down to the commissioners;
if their motives are such as we have heard, probably we may be at the end of our journey.

"`First-day, the 7th; meeting in the morning, in the sail-loft.
A large number of the officers and soldiers attended, and it was a solid meeting.
In the afternoon went six miles to the river Rouge, and had a meeting in a mill,
among the new settlers on the river; it was as large as we expected,
being composed of Germans, French, and English, and was a satisfactory time:
the people attend with gladness,
being willing to go far in these back countries where opportunities seldom offer.
Here are no places for worship established but Roman Catholic.
One woman told us, she would be glad to attend our meetings diligently,
even though she might have thirty miles to come, and did not understand much English.
O happy Philadelphia, what privileges thy inhabitants enjoy!
Mercies unthankfully received or unimproved, will increase condemnation.

"`Second-day, 8th. Received a letter from Captain Hendricks, an Indian, at the Rapids,
complaining of short allowance of provisions.
We sent them a barrel of flour, some pork, five dollars in money, tobacco, etc.,
and wrote an answer.
He appears to have some hopes of peace being accomplished;
but if we attend to the various opinions and sentiments we hear,
we are likely to be kept in continual fluctuation.
Persons who appear very friendly, and men of information,
advise us by no means to attend the treaty, that our lives are in the utmost danger.
It is grateful to find the people at large solicitous for our welfare;
but our principal business in this time of suffering and exercise,
is to labor to experience that '`quiet habitation,`' where we may be
preserved from being tossed off the foundation by the many voices we hear.
I endeavor after the resignation of all, even my life, to the Divine disposal;
yet hope we shall be conducted by prudence in our movements,
not rushing hastily or presumptuously into danger.
Saw a burial procession, in the pageantry and superstition of the Roman Catholic Church;
the deceased was said to be one hundred and fifteen years old.

"`Third-day, 9th, had an interview with the famous war chief Blue Jacket, a Shawnese;
he was reserved, saying he had given his sentiments at the council.

"`10th. Had a fuller opportunity with Blue Jacket,
who appears to be a man of understanding, but still reserved.
Reports state, that the Chippeways and Sioux of the Woods, who are near Lake Superior,
have had a battle, wherein many of the latter were killed, at which some people rejoice.
Visited by several Indians, some of whom understand a little English,
and appeared pleased with our views in coming here.
The Shawnese, Wyandots, and Delawares,
all appear to have more or less knowledge of Friends,
and acknowledge that they have confidence in the Society,
because we are peaceable and just.
We have seen some of almost every nation, which are collected at the council,
and have been more or less conversant with them every day since we arrived.
A vessel arriving this afternoon,
we were in great expectation of receiving letters from home,
and some directions from the commissioners, but are proved with repeated disappointments,
and must be longer exercised in the school of patience, yet dare not murmur.
We were informed that the commissioners were coming on,
and would encamp at the mouth of the river Detroit, until the treaty commenced;
but we apprehend the deputed Indians would arrive in time to prevent their coming.

"`11th. Dined at James Abbott`'s,
who being much acquainted with Indian affairs for thirty years,
expressed his opinion that no treaty would take place at present; or if it did,
no peace would be obtained; with which our two interpreters joined;
all agreeing that the Indians must first be chastised and humbled.
Friends urged their pacific sentiments towards the natives, and that kind,
lenient measures, accompanied with justice, would prove more effectual than the sword;
but without much effect.
Men who are in the spirit of war, we have found in many instances in this place,
cannot possibly see as we see.
A long and truly afflicting recital of Indian cruelty and perfidy was brought into view,
of which we have been obliged to hear enough before to fill a large volume.
I could, several times, have been glad to have stopped my ears from hearing of blood,
as I am confirmed in opinion that it has a tendency gradually
to eradicate the tenderest feelings of humanity.

"`12th. Embarked with all the family of our landlord, for his place, down the river;
walked several miles below, and rested at a French-house; felt the want of the language,
as I have often done before in this journey.
A vessel arriving from Fort Erie, we were informed that the commissioners,
after waiting five days for a fair wind, being met by the deputation of Indians,
had returned back to the governor`'s. With this disappointment,
and that of having no letter for us, our patience was almost exhausted.

"`13th. A custom is still retained here, that whenever there is a sale of lands,
it is to be public, and at the church door; and if a plantation is sold,
even twice in a year, one-ninth of the purchase-money goes, by an old French law,
to the church;
this has enriched some parishes in Lower Canada to an almost incredible degree.
By this great imposition they are enabled to support
the superstitious ceremonies of that church,
with great pomp and pageantry; but the people entertain a hope,
that it will not continue long.
Of all the land in Upper Canada, which is granted, and now granting,
two-sevenths are reserved in every township, one-for the king,
and the other for the priests.
The French interest in the legislature has hitherto overbalanced the English.
The arrival of letters from our friends and relations, at home,
was truly refreshing in our tried situation,
and tended to animate us to patience and perseverance.

"`First-day, 14th; meeting at ten o`'clock; was large and satisfactory.

"`15th. Our friend, Captain Elliott, arrived from the Rapids,
and brings no additional information to encourage the hope of a treaty taking place;
he says there are deputies from the Cherokee nation, who are at war.

"`16th. On further conference with Captain Elliott,
as to the best mode of promoting the concern of our Friends at home,
with which we remain unitedly exercised, it terminated in this,
that there was neither propriety nor safety in going to their council at the Rapids,
and that if the result of the meeting of the commissioners and
Indians at Niagara should prove unfavorable,
and prevent the treaty, the Indians, on such intelligence, would immediately disperse.
It was, therefore, deemed most advisable to write to Colonel M`'Kee +++[+++a British officer],
enclose him the address of Friends, and request him to deliver it to the Indians,
if no treaty was likely to be held.

"`17th. Wrote letters, one to Colonel M`'Kee, at the Rapids,
and one to the Indians assembled there in council; which, with the address of Friends,
were enclosed, as before stated, and forwarded by Captain Elliott.
Horrid instances of Indian barbarity related,
and many of them too well authenticated to occasion a doubt of their foundation.

"`18th. A false rumor of a vessel being arrived in the river,--our hope of
release from this dark and wicked place is thus frequently baffled.
Further information makes us almost despair of any treaty at this time,
or if it should take place, that the desirable object of peace will be obtained;
hence we feel our situation increasingly trying,
yet hope we shall be preserved in patience to the end.

"`19th. Being informed by a merchant, that the Indians had latterly mixed the sugar,
of which they bring considerable quantities to this place, with sand--when told of it,
they replied, You learned us by mixing water with your rum.
Thus Christians, so called, are their instructors in many vices.
An old Indian who paid a visit to the white people a few years past, and who,
on account of his residence far in the North West, had seldom ever seen any before,
being inquired of respecting the country in that remote region,
which had been but little explored, replied, '`that he was old,
but his sons had travelled very far,
and told him some extraordinary things;`' upon which he was asked,
'`whether his sons had not told him lies?`' '`Lies!`' said he, in amazement, '`No,
that is impossible,
for they have never yet seen a European.`' Friends retiring into the colonel`'s garden,
spent the time in serious consideration of the present
distressed circumstances of the poor Indians,
and the various matters that have contributed to occasion it;
which opened to us the great obligation laid upon rulers,
in order to promote the general welfare of mankind, that they do justly, and love mercy;
without which there can be no solid basis for a hope of enjoying peace, harmony,
and concord: a blessing to nations, and individuals,
infinitely more valuable than the most heroic conquests of war,
the accumulation of riches, or the extension of territory.

"`20th. Visited by Indians of different nations,
daily--we thus become acquainted with their customs and dispositions,
which we hope will some time turn to profit.
Saw another Roman Catholic funeral, giving us a greater opportunity than heretofore,
of being acquainted with their superstitious ceremonies and empty parade:
we could not behold it without secret pity. The Chippeway
Indians being at continual war with the Pawnee nation,
of whom they take many prisoners, men, women, and children,
they bring them into this settlement, and sell them at from ten, to one hundred pounds,
each;
and it is computed that at present there are here about
three hundred of these poor creatures in slavery.
This trade commenced about twenty-five years ago, before which time, we are informed,
the Chippeways put all their prisoners to death,
being determined to extirpate the nation.

"`First-day, 21st, had a large meeting in the sail-loft, which was thought to be a solid,
favored time; that in the afternoon not quite so large.
As this was likely to be a parting meeting with the people here,
many of whom had constantly attended and shown themselves very affectionate to us,
the congregation was unusually serious, and we were favored to take leave of them,
under a solemn sense of Divine mercy and goodness being with us;
which I believe will not soon be forgotten by them or us.
Many took leave of us with expressions of gratitude that
Divine Providence had permitted our being among them,
and prayers for our return home in peace.
Divers of the soldiers were tender.

"`22nd. A vessel arriving last evening, brought us intelligence that the commissioners,
several interpreters, etc., had landed at the mouth of the river,
eighteen miles from hence,
where they wait the invitation from the Indians to go to Sandusky,
and they request us to come to them when this vessel is ready to take us.
This reanimated us with hope that a treaty would yet take place,
and our long detention here would soon terminate.
Every countenance expressed the relief it gave us.
The interview between the commissioners and the Indian
chiefs concluded more favorably than we expected.
Such is our interest in the affections and good
wishes of many of the people of this place,
that I believe it would make them unhappy to hear of any injury being done to us.

"`23rd. The vessel not being likely to sail for some days,
the commandant and Captain Robinson called on us,
and consistent with his usual generosity and attention,
desired to know our wishes respecting our departure,
that he might order things accordingly; if we wished to go before the vessel sailed,
his barge well manned should be at our command; for which, and for all his former favors,
we thanked him, but concluded to stay for the vessel.

"`25th. After taking an affectionate leave of many kind friends,
who appeared much interested in our preservation and welfare,
being accompanied by their good wishes, we went on board with Colonel England,
Adjutant O`'Brien, and Lieutenant Hendricks, and several women,
who had been captives with the Indians, and were desirous of returning home with us.
We sailed pleasantly for two hours, when the wind falling, the colonel, officers,
and three of us Friends, got into a large covered barge,
and were rowed down to the commissioners, at the mouth of the river.
They and we were glad to see each other, after our long separation.

"`26th. Having pitched our tents on a fine green,
making a wing to a long row before erected, we slept comfortably.
The commissioners were well accommodated in Captain Elliott`'s house,
which is large and convenient.
Fourteen tents, pitched on a beautiful green bank before the door,
are occupied by Friends, the interpreters, two British officers, General Chapin, etc.
A number of Indians encamped along side of us.
The day was spent agreeably, and the colonel and officers from Detroit returned.

"`27th. About one o`'clock in the morning came on a tremendous thunder storm,
which continued two hours, raining most of the time very hard,
with continual flashes of lightning, and heavy peals of thunder.
The ground of our encampment being very flat,
we were soon deluged with water over our mattresses,
and retreating promiscuously into the house, we got no more sleep.
It being necessary for some of us to return to Detroit,
Joseph Moore and myself went off in a batteau about ten o`'clock, being rowed by Indians.
The day was hot, with the wind and current against us,
which made the voyage tedious and unpleasant.
Arrived at Detroit about sunset, where many of the inhabitants were glad to see us.

"`28th. First-day morning I was unwell,
probably the effect of our being so wet the night before last.
Several of our acquaintances came to see us,
and others sent to inquire whether there was to be a meeting at ten o`'clock;
but being poorly, and feeling weak without our friends, we declined it.
Afternoon, not being satisfied at spending the day idly,
we determined that it would be best to hold a meeting at five o`'clock.
Accordingly, upon our intention being known, many people assembled,
and through renewed mercy, it proved a very tendering season,
both to them and us--we thought more so than at any other time in Detroit.
The colonel, with his usual kindness, invited me to dine with him;
but I desired to be excused from dining out on First-day.

"`29th. Captain Freeman, Lieutenant Broadhead, and myself, breakfasted at Freeman`'s,
at five o`'clock in the morning; and the colonel`'s barge, manned by eight soldiers,
took us down to our encampment, about twelve o`'clock, where they dined,
and spent the day with us.
Joseph Moore stayed behind to finish some business at Detroit, and to come on tomorrow.

"`30th. A deputation of twenty-five or thirty Indians, accompanied by Captain Elliott,
Thomas M`'Kee, Simon Girty, and one Smith, an interpreter,
having arrived last evening from the Rapids, and encamped on an island opposite to us,
delivered their message this morning to the commissioners.
The purport of it was,
that they had not fully delivered the message from the
grand council to the commissioners at Niagara,
and were now sent to be more explicit, and to put the question,
Whether the United States were willing to make the Ohio the boundary line?
This they now brought in writing, and required an explicit answer;
and that if the United States agreed to this,
it was expected they would immediately remove all the
inhabitants off the land on the west side of the river.
Our commissioners informed them, that they would take their message into consideration,
and give them an answer when they were ready.
After this they separated, and conversed with us.
Among them were representatives of ten nations,
and several of them great men among the Delawares and Shawnese.

"`The Shawnese, Delawares, and Wyandots, as usual, said they knew Friends,
and were acquainted with our motives in coming.
I presented five of the principal men with neat tobacco-boxes filled with tobacco,
which they said, when they looked upon, they should think of Friends.
They departed in the afternoon, and slept upon the island.
Their demand occasioned us to feel discouraged as to being able to effect a peace,
and we retired to bed with heavy hearts.
A number of Indians who were encamped very near us, joined by some white people,
were dancing, singing, and yelling most of the night, accompanied with some Indian music,
which, though not what they style the war-dance, was very disagreeable to us,
and we got but little rest.
This kind of disturbance we have before been, and no doubt shall continue to be,
afflicted with.
Our situation, at present, is very painful on several accounts;
our family consists of about forty, including the servants,
several of them very loose in their principles;
and we are sorry to find that open debauchery is
too generally practised on the frontiers;
and so common has it become,
that white men of the first rank do not appear ashamed of it.
Three young women, Indian captives, designing to go home with us,
went in the vessel to Fort Erie, to wait our coming.

"`31st. The Indians came over to us after breakfast,
and stayed smoking their pipes and conversing with us until five o`'clock in the evening,
when the council fire was again kindled,
and the commissioners requested their patient attention to their answer, which,
as the subject was of the highest importance, they could not comprise in a few words.
It occupied several sheets of paper,
to explain the reasons why they thought it impossible to make the Ohio the boundary line;
but were still desirous of meeting them in full council, where, they could not doubt,
from the amplitude of their powers,
and the disposition of the United States to do them strict justice,
and settle large annual payments upon the Indians for such lands as
should be agreed to be confirmed to us at the general council,
that the business would yet end in peace, to the satisfaction of both parties.
The speech was then delivered to them in writing, and they withdrew to the island,
with their interpreters and agents, saying they would give us an answer tomorrow.
Three British officers from Detroit, who visited and dined with us today, were present.

"`Eighth month, 1st. At nine o`'clock in the morning the Indians returned;
and after the fire was kindled,
and they and we had smoked our pipes on the benches under the trees, as before,
they delivered an answer;
and remarked principally on that part of the speech which
mentioned the impossibility of removing the white inhabitants
off the lands which had cost so much to improve them,
and said, it was equally hard for them to give up their land;
that they should now return and inform their warriors what we had said,
and that we might also return and tell our chief Washington.
This last sentence was not approved by Captain Elliott; and some of the Indians,
after the council had risen, taking the speaker aside,
informed him that what he had said,
was not intended to have been offered--upon which they returned,
and told us they would now go to the great council, and lay our speech before them,
and would send us an account of their result,
and requested us to continue here till we heard from them.

"`The business now appeared to most of us to be near a conclusion;
and not knowing whether we might ever see them together, we sent our address,
and a letter from ourselves,
to the care and attention of Colonel M`'Kee and Captain Elliott to deliver,
and have interpreted to them.
Friends consulted together on the propriety of some of
our number going with these chiefs to the council.
The concern and fervent engagement of our minds that the poor
Indians might be wisely directed in the present juncture,
produced a resignation in my mind to be one,
though it appeared to me there would be some risk of our lives;
but upon laying it before the commissioners, Captain Bunbury and Thomas M`'Kee,
they were not easy we should attempt it,
as the Indians had positively forbid any American citizen to come on the ground,
while the grand-council held; we therefore declined it.

"`Eighth month,
2nd. The morning passed in reading and conversation upon the trying situation we were in,
and the necessity of asking for fresh supplies
of wisdom and patience to enable us to answer,
as much as in us lay, the objects of our journey.
In the evening had conversation with the most libertine part of the company,
who glory in their debaucheries; but it was like casting pearls before swine,
they turn again and rend you.

"`3rd. The vessel called Detroit, bound to Fort Erie, appearing in sight,
I wrote a hasty letter home.--Appointed a meeting to be held at Simon Girty`'s, tomorrow,
at ten o`'clock.

"`4th. First-day morning.
Very rainy, and much wet in my tent; rose about three o`'clock, bundled up my mattress,
and tied it in a painted cloth, and sat upon it till sunrise.
The rain continuing, three of us went to Simon Girty`'s, but finding none met,
except the family, returned.
Captain Hamilton, an amiable man, and an officer in the fifth regiment, dined with us.
The Chippeway, a vessel bound from Fort Erie to Detroit,
brought one hundred and eighty Indians, and landed them at the Miami river.
The afternoon being pleasant, had a meeting at Simon Girty`'s,
about one and a half miles from our camp, at which a number of Indians were present,
and behaved soberly.
General Lincoln, General Chapin, Captain Hamilton, Lieutenant Gwans, and several seamen,
also attended; I believe it was to satisfaction.
The few scattered white people in this Indian country,
many of whom have been prisoners of war, have no opportunity of public worship;
yet some of them are glad of our meetings; among whom was the wife of Simon Girty,
who also had been a prisoner among the Indians.
Several of the Indians who were encamped near us, having got too much drink,
were very abusive and unruly, and some serious consequences were apprehended;
but they were restrained.

"`5th. Spent the morning in serious conference with Friends,
and with some Wyandot Indians;
they think it unsafe for us to pay them a visit in the present state of things.
This night was very uncomfortable, owing to swarms of mosquitoes;
and notwithstanding every effort to avoid them, I did not sleep one hour,
and many of our company walked the green most of the night.

"`6th. Were afflicted with disagreeable conversation after dinner,
which we are subject to have imposed upon us daily by the libertine part of our company.
One of Captain Elliott`'s Pawnee slaves, who has been unwell since our first arrival,
died while we were at dinner, and was buried the same evening;
many of our company attended, and a number of Indians, etc.
Joseph Moore spoke at the grave, which appeared satisfactory.

"`8th. Twelve Indians called on us, being on their way home from the council,
which they left with impressions that a peace would be made;
but they said there still remained an opposition, principally from the Shawnese,
Delawares, and Pottawattomies; and also a few of several other nations.
They said the council had held too long for them, being tired,
and their clothes worn out, but they had left the principal chiefs of their nations,
Chippeway, and Munceys, at the Rapids.
In the evening, two Indian canoes having come down from Detroit,
each having a keg of rum, some of our new visitors (Indians) got drunk,
and came into our camp, just as we were going to bed, making a great noise,
and going from tent to tent.
Much persuasion being used,
I at length prevailed on the worst one to let me lead him away some distance:
he frequently called me brother, and seemed pleased with my attention;
but after I returned, it appeared to me to have been a very dangerous undertaking,
as he had a long knife at his side,
which he had before drawn out and brandished in our camp; but Providence preserved me.
They still kept at the distance of about a quarter of a mile from us,
yelling and whooping; several of our company offered to be watchmen,
which we thought prudent; and an uneasy night it was,
as they passed frequently backward and forward by our camp;
but no mischief was done to any.
Early in the morning I was awakened by one of them,
who had gotten into the middle of our encampment almost naked, very frantic and noisy,
with his knife drawn, which he vapored in the air, and beat on his breast.
Some of the servants and others would have seized him, but this would have been imprudent.
After troubling us about half an hour, an old Indian, who was sober,
came and led him away.

"`9th. Most of the day, at intervals,
we looked with anxiety towards a point of land in the lake,
expecting a deputation from the Indians to invite us from this place,
of which we are all weary, to the council; but no boats appearing,
we must be longer trained in the school of patience.

"`10th. Complaints were re-echoed from side to side of the
camp against the dilatory proceedings of the Indians,
and their squandering away the whole summer without coming to treaty:
indeed it has been the most trying situation I ever
experienced.--We were fully supplied today with poultry,
butter, eggs, sheep, and pork, from Gross Isle, but at a very high rate;
yet it is a mercy we can have such a plentiful supply at any rate.

"`11th. First-day.
The Ottaway from Fort Erie passed us; a number of passengers were on board,
some of whom landed; among them was Jasper Parrish, an interpreter,
who brought letters for us from Philadelphia, which was agreeable.
The commissioners also received papers and other intelligence.
Took an early dinner, and being accommodated with a boat and four hands,
all the Friends but W. H. attended a meeting at Gross Isle at three o`'clock,
where I believe several received us gladly, and all heard patiently.
Although the weather was hot,
and we had nearly four miles to walk from the place where the boat landed us,
yet I was glad I attended.
These poor frontier people have very seldom any
opportunity of assembling for religious worship;
and though many of them in their dress and manners, as well as their information,
are very little above the Indians;
yet they esteem it a favor to have the benefit of a free ministry,
travelling far on foot to attend meetings.
Some are rude and restless at times, but others appear like thirsty ground,
which I trust the great Lord of the harvest will in his own time water.
Returned to our camp, and passed a painful night with the tooth-ache and swelled face,
from which, with the addition of swarms of mosquitoes, I slept very little.

"`12th. At break of day was seized with a chill.
I arose, and, as well as I could, put on my clothes.
Joseph Moore rising at the same time, we went to the house and knocked them up,
being advised to take something by way of medicine.
I continued very sick, with shivering and chill.
After some time a fever succeeded, which continued very hot for about six hours,
with pain in my head and limbs.
Towards evening, with the doctor`'s advice I took an emetic, which operated violently;
and being much fatigued, and falling asleep for a few minutes,
I awoke in such a profuse perspiration,
that by day-break my clothes and the blankets were wet, and I left extremely weak.
This was a very trying scene to me,
so far from my dearest connections and beloved relations;
not knowing but it might be the Lord`'s will now to put a period to my stay on earth.
I labored earnestly to be enabled to say,
'`Thy will be done,`' and did not perceive much cloud in the way,
but saw it to be an awful thing to die.--It is a
very sickly time among the inhabitants here,
and many of the Indians have been carried off with a few days`' illness;
some of whom I knew.--I had my mattress removed into the shade of the tents of Friends,
and laid there most of the day, taking little nourishment.
My friends the commissioners and their companions were kind and attentive:
at the same time several of our retinue were unwell;
Jasper Parrish was thought to be dangerously ill.

"`13th. Very languid and weak, with pain in my head and face.
Captain Wilbank, who came with the Cherokee Indians to council,
and eight other white people from Detroit and parts adjacent,
dined with the commissioners.
A gloomy depressing day with me, my mind frequently turned towards home,
yet dare not wish to be there, believing we are in our right allotment,
whatever may be the issue.
Towards evening I was somewhat better,
and a hope revived of being favored to see my dear wife and friends again.
The Lord grant I may be preserved without a stain on my profession.

"`14th. The servants and others sat up most of the night and were noisy,
with music and dancing, which, with the abundance of mosquitoes,
caused me to sleep very little until day-light; after which I got some quiet rest,
and rose much refreshed and thankful, and was enabled to go and sit with Jasper Parrish,
who remains in a high fever, is low in his spirits, and doubtful of recovery.
I walked a little about and felt myself mending, yet my face continued much swelled.
About noon, three Indians came from the Wyandot town with intelligence,
that an Indian who had left the council had arrived there yesterday morning,
and says that a deputation was agreed to be sent, inviting us to the treaty;
but that the wind being unfair, they could not be expected suddenly.
He also says, that disputes have run high among themselves,
whether we should be sent for or not,
as the commissioners had declared they could not make the Ohio the boundary line;
but at length it was agreed to hear what the commissioners had to offer.
All this appeared not to be so fully authenticated as we could wish.
We are, however, often looking towards the point, twenty miles distance,
with a spy-glass, desirous of discovering a boat,
but are baffled by the canoes of the neighboring Indians,
who are daily fishing along the opposite shore.
Our commissioners, becoming almost impatient at the delay,
dispatched two swift Indian runners to the Rapids, about forty miles by land,
for information.
I felt much recovered, and slept tolerably.

"`15th. My stock of patience was somewhat renewed,
and we sat down with the company to breakfast,
where we were obliged to explain many things respecting our principles,
which were but little understood;
this has indeed been our almost daily employment to one or another,
and frequently to many at once.
I hope nothing has ever suffered by our defence, though we often feel ourselves weak,
especially as there are among us several men of consideration and understanding,
as well as others, who make light of almost all religion.
The weather being fine in the afternoon,
our company spent much of the time in walking up or down the river.
As our camp was thus rendered quiet, I passed the time in reading.

"`16th. Colonel Pickering being desirous of giving me
more information than I had yet received,
of the treaties held by the United States with the Indians,
and the nature of their uneasiness, I cheerfully sat with him in his room till breakfast,
and was pleased with the knowledge obtained;
being also sensible of the confidence he reposed in me,
by showing me the commissioners`' books and papers.
About four o`'clock in the afternoon a canoe was
discovered coming from a point a few miles distant,
manned by two Indians, who proved to be deputies from the council;
they brought a definite message in writing,
importing that the council had considered the answer of
the commissioners to the former deputies,
and objected to several parts of it, viz.:

They did not acknowledge the right of pre-emption to
their lands as vested in the United States;
but that they (the Indians) had a right to sell them to whom they pleased.

That all the lands west of the Ohio were theirs;
and that as we had told them of a large sum of money which we
would give them to confirm the sale of those lands to us,
they advised the commissioners to give it to the poor people who occupied them,
and remove them away; and that unless this was acceded to, a meeting was unnecessary.

"`As these terms were inadmissible, the commissioners answered by a line or two,
and immediately began to strike some of the tents,
and to take part of the baggage aboard.
About nine o`'clock at night our two runners arrived, bringing no intelligence,
as they said the Six Nations were not admitted into the private councils,
and they knew not but that the message of the two Wyandots had been to ask us to council.
As the Six Nations are in the interest of the United States,
the other nations did not condescend to transmit any answer.
Passed a painful night,
under the prospect that the desirable end of our embassy would not be answered,
and that great devastation and bloodshed would be the consequence.
The writing was signed by the Creeks, Cherokees, and all the nations present,
except the Six Nations.

"`17th. Struck the remainder of the tents, and got all our baggage, sheep, fowls, ducks,
etc., on board the Dunmore, by eleven o`'clock.
We were about sixty souls on board, including the commissioners`' retinue, sailors,
marines, prisoners returning home, etc.
The wind not being fair, we waited some time,
when it became rather more favorable--we sailed easily away,
and reached the Bass islands, forty miles, by seven in the morning.

"`18th. First-day, judging it proper to hold a meeting, we sat down in the cabin,
being joined by General Lincoln, and several others; the remainder were above,
round the cabin door.
It was a solid time, several testimonies were borne,
and the meeting concluded in supplication and thanksgiving to the Father of mercies,
who had preserved and sustained us in the present arduous journey.

"`19th. The servants and seamen having quarrelled,
one of the marines was ordered to walk the deck with his sword,
and to be relieved by the others, alternately, during the voyage.

"`22nd. The wind being high and fair, we sailed rapidly,
and arrived at Fort Erie about twelve o`'clock at night.

"`23rd. Wind so high all day, that it appeared imprudent to attempt landing;
but in the afternoon, Captain Bunbury left us for Niagara,
to engage a vessel going to Kingston, for our accommodation, when we should arrive.

"`24th. In the afternoon,
Jacob Lindley being furnished with a spare horse by the commissioners, and John Parrish,
John Elliott, and Joseph Moore, having their horses sent to them, they took leave of us,
intending to spend a day or two with a few Friends in the neighborhood,
and wait the recovery of Parrish, the interpreter,
who lay sick at a house a few miles off,
as he was to be their guide through the wilderness.
I felt heavy at parting with them; but seeing no alternative, wrote by Jacob Lindley,
informing my wife of my intention to return by Montreal.
Colonel Pickering, Governor Randolph, and their servants, with all the interpreters,
also left us, with intention to proceed on different routes,
and to spread information of the issue of the treaty,
as it was apprehended that the Indians were already dispersed and doing mischief.
Five women, who had been prisoners, also went off with General
Chapin.
Our company having now become small,
we felt lonesome at parting with those who had been the companions of our trials.
Five o`'clock in the afternoon, a number of Canada Indians, accompanied by J. Launier,
a Frenchman and interpreter, came on board to see us, conversed pleasantly with us,
and invited our company on shore to a dance; many from on board accordingly went;
but I had no inclination to behold what I had already seen too much of.

"`25th. Captain Pratt sent us two batteaux, one of them large, for our baggage,
the other for the passengers.
Taking breakfast once more on board the Dunmore, we left her about nine o`'clock,
the sailors and marines parting from us with many good wishes.
The boats being well manned with soldiers, we got on, and put in at Winternut`'s tavern,
where Jasper Parrish, the interpreter, was confined, and still very weak.
Here we again met with our friend, John Elliott, and soon after arrived at Chippeway.
Captain Hamilton being the commandant of the fort, he met us at the shore,
and took us to his apartment,
where we were entertained with great frankness and generosity.
About four o`'clock in the afternoon, the general, doctor, secretary, Lieutenant Gwanz,
and myself, proceeded in a wagon for Queenstown,
stopping a few minutes on our way at the falls of Niagara;
and got to our inn about seven o`'clock in the evening.
The farmers who live near the falls,
would be subject to the loss of their geese and ducks,
by their being carried down with the rapidity of the current,
and dashed over this mighty cataract,
were it not for an expedient which they have discovered as a preventive.
They pluck the feathers entirely off their breasts, about the size of a dollar,
and keep it constantly bare.
The water so affects them in this part, that they stay in it but a few minutes;
otherwise they would continue in their favorite element, and be destroyed,
as many hundreds have already been.
We were informed, that some years past,
a sergeant and four men attempting to cross the river too near the falls,
were all carried down and perished;
those on shore not being able to render them any relief.

"`28th. Got to Navy Hall, where we lodged.

"`30th. Sailed about three o`'clock in the morning, in a small sloop,
and having a fine wind, made about one hundred and thirty miles;
and as there were several islands ahead,
the captain concluded to stand off and on all night.

"`31st. Arrived at Kingston, a garrison formerly built by the French;
now occupied by the British.
A batteau being ready to receive us, we embarked for Lachine,
and got on about twenty-five miles before dark.
No houses appearing, the general orders were to lap ourselves in our blankets,
and sleep in the boat; which we did as well as we could,
having nine passengers and four Frenchmen on board,
one or other of whom steered the boat all night.

"`First-day, the 1st of Ninth month, sailed down the river St. Lawrence,
and passed a fort on the American side, and also two Indian towns,
one of them on an island.
In the evening,
after passing through the greatest number of islands I ever saw in a river,
which are called the Thousand Islands, and also through a long rapid,
we arrived at lake St. Francis.
The wind being fresh, it was doubtful whether we could cross it or not in the night;
but our Canadians concluding to venture on, we all laid down as in the preceding night.
The lake is about fifteen miles long and six broad.
I slept none; the clouds appeared wild and threatening for a night voyage.
About ten o`'clock, the helmsman seeing a gust rising, roused all up;
and in a few minutes a terrible hurricane came on, with tremendous lightning and thunder,
and very dark; but by the flashes of the lightning,
we judged we were about a mile or a mile and a half from shore.
The rain poured down in torrents,
and it appeared almost a hopeless attempt to reach the shore; but some of our company,
possessing considerable fortitude and skill,
were active in directing and encouraging the men to
persevere in rowing--notwithstanding all which,
such was the impetuosity of the waves and violence of the winds,
added to a deluge of rain and perpetual thunder and lightning,
that one of our best hands threw down his oar, and cried out in French,
'`We shall all perish,--we shall all perish!`' But Providence,
whose tender mercies were over us, had more gracious designs concerning us,
and at length brought us safe to shore, which happily proved to be sandy,
or we might still have been dashed to pieces.
Having a piece of painted cloth on board, as many of us as could got under it,
as it continued to rain very hard.
About twelve o`'clock it cleared away, and, being very cold, we concluded to go on shore,
and walk about to warm ourselves, being thoroughly wet, and shivering with the cold.
It was thought impossible to kindle a fire, as everything was so wet;
but one of our Friends striking to light our pipes, we were enabled to kindle one,
which was a great relief to us, and, sitting round it till daylight,
were enabled to prepare something for breakfast, and set sail again.
I believe all of us were thankful for our deliverance.
The man who was most intimidated had a consecrated
wafer about his neck to preserve him from drowning,
but his faith failed him in the hour of trial.

"`Ninth month, 2nd, with a fair breeze we soon reached the far end of the lake,
and got to a large new tavern,
with a view of warming ourselves and procuring some refreshment;
but there being no other fire than a little in an out-shed,
we departed and sailed down the rapids, nine miles in thirty-five minutes;
and a little further on came to another rapid, also said to be several miles long,
which we passed in about four minutes,
and arrived at Lachine about three o`'clock in the afternoon.
Feeling myself very unwell, I went to bed early, and had a restless night.

"`3rd. Having provided carts for our baggage,
and each pair of us a calash (a kind of open carriage), and a French driver,
we set off for Montreal, which, though unwell,
and a great part of the road extremely bad, we reached about ten o`'clock.
This town is populous, and carries on a great trade.
The chapels are open all day, and seldom without persons in them paying their devotions.
Some we saw on their knees; and as we did not interrupt them,
they continued thus engaged, and retired as they got through their performances.
Here are several nunneries richly endowed;
the sisters employ themselves in acts of benevolence, visiting the sick,
relieving the poor, and at times in needle-work and in making images:
several of them were passing to and fro in the streets,
clothed in long black robes and hoods.
The law which gives the church one-ninth of the purchase-money
of all lands sold by public sale at the church door,
has enriched this church to a degree that is almost incredible.
The market, which is said to be one of the cheapest in America,
is attended by a number of little cars about twice the size of a wheelbarrow,
in which they bring vegetables, fruit, etc., and are drawn by two large dogs,
which appear to be well kept and in comfortable condition.

"`4th. The commanding officer at Montreal having sent orders
to the farmers to find us two carts for our baggage,
and four calashes for ourselves to convey us to St. Johns,
they attended about six o`'clock in the morning,
being obliged to submit to such arbitrary commands,
however much engaged in their husbandry, which was the case at this time,
it being their harvest of oats and flax.
Such are the effects of military government.--Breakfasting at Chambly,
and riding through a beautiful country about twenty-seven miles, we arrived at St. Johns.
I continued unwell, having a high fever on me,
which was also the case with Captain Scott, and several others of our company.
Fifteen of us embarked after dinner-time in a small boat,
but there being scarcely any wind, and no current,
we had to put in at a very undesirable place, the character of which was bad, and,
we had reason to believe, in part at least, justly so.
I retired to obtain some rest, but a company of rude people,
who had got to the house before us, made such a continual noise,
that I was kept awake until towards morning, when I got a little sleep.

"`6th. Passed several garrisons, and proceeding with a fair wind,
stopped at an American custom-house on the New York side:
here we were obliged to leave the master of our boat,
who was so ill he could go on no further.
We had now none to steer or manage the boat, but a boy of about sixteen,
who knew the lake; but the wind being fine and we anxious to proceed,
William Hartshorne took command of the vessel, and we sailed pleasantly till evening.
We aimed to harbor at Gills`'s creek, where we might go on shore and sleep;
but it being after dark before we arrived there,
and none of us being acquainted with the entrance, we ran upon shoals and rocks,
and the sea and winds being high,
our little bark thumped as though the bottom would have been beaten out.
In great danger we continued on the shoals near an hour; at length, with much difficulty,
we got off, and anchoring in sufficient depth of water,
were obliged to lay here the remainder of the night, and a painful one it was to me;
it being rainy and a high wind, and no light to find our blankets.
I laid down on some casks and trunks, but slept none,
and my disorder returned upon me with double force in the morning.

"`7th. Sailed about eight miles to a pretty good house to breakfast;
but I ate none and could scarcely walk from the vessel,
in order to get upon a bed until the company were ready to depart.
Went on all day without stopping again,
and arrived at a small house with poor accommodations.
I wanted nothing but a bed, and although there was but one,
and our company consisted of the passengers of three vessels,
yet they kindly gave that up to me, and I got a little sleep the forepart of the night.

"`First-day, the 8th, arrived at Skeensborough or Whitehall, about ten in the forenoon,
where I soon went to bed, as did likewise Captain Scott and others.
In the evening I walked out a little, but had a very poor night,
with high fever and much parched with thirst.
My indisposition was now so serious, as to induce the fear that I must be left behind;
yet I had a great desire to reach home, if practicable.

"`9th. Friends encouraged me to proceed, though in great suffering,
and we got to Fort Ann, after riding about eight miles over an exceedingly rough road.
Here I took a little nourishment and laid down to rest;
from thence we went to Fort Edward, and in the evening arrived at Saratoga:
though the roads were somewhat better this afternoon, yet it was a very trying day to me.

"`10th. After a tolerable night`'s rest, we put on and breakfasted at Still-water,
having passed through a beautiful country, though at one time the seat of war,
where General Burgoyne was captured.
General Lincoln having been on the spot at the time,
informed us of many particulars connected with that memorable event.
We rode through a very pleasant country, and reached Albany in the evening.

"`11th. Remained here all day, had a very poor night,
and my fever coming on about three o`'clock in the morning,
I seemed almost ready to die with thirst.

"`12th. Went on board a sloop for New York.--I was still very unwell,
and my spirits increasingly depressed by receiving a
confirmation of a report which we had heard at Saratoga,
that my beloved city, (Philadelphia,) was in an alarming condition,
from the prevalence of a very contagious and mortal fever--that the stages and all
other means of communication between New York and it were stopped--that the vast
numbers which died daily occasioned the common rites of burial to be intermitted,
and a variety of other affecting accounts.
After sailing about three miles, the vessel being heavily loaded, got aground,
and though great exertions were made in the night, at high water, to set us afloat,
they were without effect.
Our passengers kindly gave me a berth,
but my fit of illness coming on as usual about one o`'clock in the morning,
I passed a distressing time.

"`13th. The Captain ordered a considerable part of our deck-load,
which consisted of boards, to be rafted and to meet us a few miles below;
this lightened the vessel, and she was with much labor got off;
but the wind having left us, we made little way.
In the morning, before day-light,
I was attacked with the most violent chill I had ever experienced, followed by fever.

"`14th, 15th and 16th, the wind being unfavorable, we made slow progress.`"

[.asterism]
'''

He gradually recovered from the chills and fever, and was able, in a short time,
to return to his family, who were in the vicinity of Philadelphia.
The yellow fever then prevailing in the city,
his sympathetic mind was deeply affected with the great affliction
and sufferings under which the inhabitants were laboring,
in consequence of the awful pestilence then permitted to overspread that place.

Although Friends had not the satisfaction of seeing a general treaty of amity concluded,
owing as was apprehended,
to the interference of some evilly disposed and interested persons,
yet the opportunities afforded for amicable intercourse with the Indians,
for religious service among the frontier inhabitants,
and for mingling with the families of Friends
then newly settled in the parts they visited,
together with the peaceful evidence that they were in the way of their duty,
sustained them under the trials and privations they met with,
and compensated for the sacrifices which they made in leaving home.

In rendering to the Meeting for Sufferings an account of the engagement, they remarked:
that notwithstanding the desirable object of peace was not obtained,
they had not a doubt of the rectitude of submitting to
go on the arduous and exercising journey,
believing that their company had tended to renew
the ancient friendship with the Indian natives;
many of whom, particularly the Wyandots, Shawnese, and Delawares,
appeared to appreciate their motives in going,
and some of those nations travelled sixty or seventy miles,
in order to have the company of Friends--that they had been
favored to travel together in much unity and harmony,
and to return in peace.

The Society continued to feel a deep interest in the welfare of the natives,
and to cherish toward them the obligations of justice and Christian benevolence.
They commiserated their situation as an untutored race,
liable from their ignorance to be easily imposed upon,
and subject to the dominion of ferocious passions when excited.
In their intercourse with them, therefore,
they endeavored not only to satisfy the claims of justice to the fullest extent,
but by kind and liberal treatment, to convince them of the sincerity of their friendship,
and that they were actuated by the desire to promote their comfort and happiness.
This course of procedure had procured for the Society a
place in their confidence and affections,
and an influence over them, which was often beneficially exerted in their councils,
when deliberating on the most important subjects.
When treaties were about to be negotiated,
the Indians generally solicited the attendance of some Friends to advise and assist them;
and after consulting the President of the United States, and obtaining his consent,
which was always cheerfully accorded,
the Society mostly deputed a few of its members to be present on such occasions,
in the hope that they might be instrumental in calming the minds of the natives,
and inducing both parties to accede to such reasonable propositions
as might facilitate the settlement of the subjects in dispute,
stay the effusion of blood, and restore those amicable relations,
which it was so desirable should subsist between the United
States and the aboriginal proprietors of our country.
