== Chapter III.

[.chapter-synopsis]
* Concern to visit Europe
* Journal of the Voyage
* Leave-taking
* Banks of Newfoundland
* Hard weather
* Meetings on Shipboard
* French Privateer
* Arrival at Liverpool
* Appointed Meetings
* London
* Sails for Bremen with George Dillwyn and David Sands, etc.
* Notice of Voyage
* Reach Bremen
* Wine Cellar
* Religious Citizens
* Continues Journey
* Hamburg and Altona
* Religious Services
* Travelling through Germany
* Zell
* Habits of the People
* Pious Pastor
* Hanover
* Visits to several religious characters
* Hammelin
* Pyrmont
* Grave of John Pemberton
* Professors with Friends
* Separatists
* Religious Engagements
* Remarkable reuniting Meeting with both Parties
* Affecting Parting
* Leaves Pyrmont with David Sands, etc.
* Visits the Dutchess of Brunswick
* Helmstead
* Character of the Country
* Magdeburg
* Religious Service
* Detects an Impostor
* Brandenburg
* Religious Meeting
* Potsdam
* Notice of the City--Berlin
* Discouragements
* Size, etc., of the City
* Interviews with religious Persons
* Meetings held
* Visit to Freyenwalde
* Return to Berlin
* Disliked by the Clergy
* Various Engagements
* Kindness of many
* Leave-taking
* Start for Magdeburg

The mind of William Savery being expanded by Gospel love,
and an ardent desire for the salvation of his fellow creatures, he was made willing,
freely, to give up his beloved home and connections, and his temporal concerns,
when he believed himself called to go forth as an ambassador for Christ,
to publish the glad tidings of redemption to a fallen race,
through a crucified and risen Saviour.
For a considerable time he had been under a concern to
pay a religious visit to Friends and others,
in some parts of Europe,
and opening it to the respective meetings of which he was a member,
his prospect of duty was united with,
and the requisite certificates of the approbation of Friends were granted him.

His notes of this engagement, are introduced, as follows:

"`Journal on board the Sussex, on a voyage from New Castle to Liverpool,
from the 18th of Fifth month, 1796, in company with several ministers, viz: Samuel Emlen,
Deborah Darby, Rebecca Young, Sarah Talbot, and Phebe Speakman.

"`Fourth-day, 18th. All the Friends intending to embark in the Sussex, met at New Castle,
a public meeting being appointed to be held in the courthouse.
It was large; more persons attending than could be accommodated within the walls.
Our own members were desired to give place to the towns-people; they generally did so,
and our dear Samuel Emlen continued at the inn with them,
and was engaged in distributing spiritual bread as occasion offered.
The court, then sitting at New Castle, adjourned to give us an opportunity in the house.
Judge Basset, with several magistrates, lawyers, etc., were present.
We believed that the great Bishop of souls granted us his presence,
and directed the laborers to invite the congregation to an attentive waiting upon Him,
the Leader and Teacher of his people,
as the only sure means of obtaining heavenly knowledge;
and they were feelingly put in remembrance, that if they died in their sins,
whither Christ was gone, they could not come.
A clear and decided testimony was also borne against holding our fellow-men in slavery;
and the meeting closed in solemn supplication,
prayer and praises to the universal Parent and gracious Preserver of men.
We returned to the inn, and after dinner,
the large room and balcony being furnished with seats,
Friends who accompanied the voyagers hither, sat down,
in number about one hundred and forty; and some of the towns-people hearing of it,
also came in.
The great Lord of the family was evidently with us,
and favored with a precious solemnity; under which, our endeared friends,
Deborah Darby and Rebecca Young, through the tendering influence of Gospel love,
were again qualified to water the plants of our heavenly Father`'s planting,
and affectionately to bid them farewell in the Lord.
Two of the Friends who were going abroad in truth`'s service,
were also exercised in the expression of heartfelt concern for
the preservation of themselves in the love and life of Truth,
and also of their long-endeared brethren and sisters whom they were about to leave.
Holy fellowship and Gospel love being refreshingly and encouragingly felt among us,
we were once more united in lifting up our hearts in prayer and praises;
committing each other to the merciful and all-wise disposal of the everlasting Shepherd.
This prepared the way for many near and tender friends and connections to part,
in the mutual experience of that love which is without dissimulation,
and in which the world`'s votaries are not privileged to rejoice:
may it ever continue and increase throughout all the churches of Christ.
About six in the evening, we went aboard the Sussex, at anchor before New Castle.

"`Fifth-day, the 19th. The vessel having hoisted anchor and sailed in the night,
we found ourselves this morning at Reedy island,
where we waited for some addition to our poultry.
The forenoon was rainy, with high wind and rough water--several of the passengers sick.
The weather clearing away in the afternoon) we again
set sail until about eleven o`'clock at night,
then dropped anchor; the pilot not being willing to go out of the capes that night.

"`20th. Setting sail about day-break with a smart fair breeze,
we came in sight of the lighthouse,
and a boat coming off for our pilot sooner than
we expected hurried us much with our letters.
We were out of sight of land by four o`'clock in the afternoon;
all the passengers as well as could be expected.

"`21st. A desire prevails among us to comfort and strengthen one another,
and especially that the younger part of the company may manifest our duty to the elder,
by every necessary attention.
Our friend Phebe Speakman is weak with disease,
but supported under it with instructive resignation and
patience--our dear friend Samuel Emlen,
better in health than when on shore, and with his usual animation,
enlivens us in our watery prison with frequent recitals of interesting occurrences,
and instances of Providential care and support,
drawn from a long course of observation and experience.
We feel as much at home on the ocean as we can possibly expect to do,
in this trying separation from the tenderest ties of
nature.--May the Lord increase in us and them,
resignation to his holy will,
until it shall be his good pleasure to restore us to each other again.

"`First-day, 22nd. Fine weather, sea smooth and wind favorable.
At ten o`'clock Friends sat down quietly in the cabin;
the promise to the two or three was comfortably fulfilled,
and we hope the bond of Christian union strengthened,
and something of a renewed confirmation afforded, that a wisdom superior to human,
directed both us that are leaving our native country,
and our beloved sisters who are returning home,
in casting our lots together in this ship.
Dined on deck.
Retiring to the cabin at four o`'clock,
we informed our kind captain that his company and that
of as many of the seamen as inclined to sit with us,
would be agreeable; upon which he came down with the mate and six others.
After a considerable time of silence, some counsel and encouragement being dropped,
they received it with attention and behaved with respect.
We were glad of their company, and the meeting closed to satisfaction.
Our dear friends at home have laid in a great abundance of good things for us;
a testimony of their care and love, though we, the objects of their benevolence,
could have been contented with less,
especially when we call to mind (as was the case this day at
our bountiful table,) how many of our brethren by creation,
and objects of the same redeeming love, are scarcely furnished with mere necessaries:
the lamentable situation of the poor Africans in the
slave-ships was sympathetically brought into view.

"`27th. A clear morning and tolerable breeze.
Retired to the cabin to hold our week-day meeting;
circumstances not permitting it the two preceding days, and were favored,
through much mercy, with a refreshing time, for which we all had occasion to be thankful.

"`28th. Perceiving a sail making towards us, she proved to be from Liverpool,
bound to New York.
Both vessels backed topsails until several short
letters were written and sent by our yawl,
ours enclosed to E. Pryor of New York;
and taking charge of theirs to their friends at Liverpool,
we wished good passages on both sides.
It is a pleasure to meet vessels at sea,
and this opportunity of writing to our dear friends at home rejoiced us much.

"`29th. Wind fair; at ten o`'clock held our meeting to mutual comfort:
all the Friends well but Rebecca Young, who was not out of her room today.

"`31st. Cold and rainy:
at ten o`'clock perceived we were coming on the fishing banks of Newfoundland.
We could not see more than two hundred yards,
but heard the fishing vessels sounding their conch-shells, which we also did,
agreeably to custom on these banks,
where there are probably from two to four hundred
English and American vessels fishing for cod.
As it is generally foggy and rainy weather, they keep a frequent blowing,
to apprize each other of their approach and to prevent running foul.
These banks are extensive--from east to west perhaps one hundred and fifty miles,
and from north to south about two hundred miles;
the soundings from thirty to sixty fathoms deep.
Our captain estimates that we are now about two
hundred and fifty miles from the nearest land,
which is the island of Newfoundland.
The number of cod annually taken here is astonishing.
They fish for them with lines forty or sixty fathoms long,
with heavy leads and two hooks; several of these being kept out at a time.
Some tend them, and others on board split and salt down the fish in bulk,
until they are loaded, when they return home and dry them.
We threw out a line, and soon took seven of from ten to twelve pounds weight.

"`Fourth-day, 1st of Sixth month.
Very wet, cold and uncomfortable, but the wind fair; we held our meeting in much quietude

"`Fifth-day, 2nd. Still wet and cold,
and we were scarcely able to keep ourselves warm with our great coats on.
A mountain of ice being directly ahead, we were obliged to change our course;
it appeared to move southward,
and was judged to be about two hundred yards in length and forty feet above water.

"`Sixth-day.
Little wind and a high sea; the vessel rolled much,
and several of the passengers passed an uneasy night--the weather so cold
and uncomfortable that we had this afternoon a fire made in the cabin.

"`First-day, the 5th. Friends generally sick;
we had slept little for the last twenty-four hours,
which have been more trying to us than any heretofore;
yet we are sensible we have much to be thankful for,
especially that we are mercifully kept in near unity and sympathy with each other.

"`6th. The wind and sea were boisterous and appeared awful, so that faith,
hope and patience were deeply tried at such seasons.
Those who venture to cross the ocean,
need be well convinced that they do it upon a good foundation;
such may humbly rest in confidence upon Him who gathers the winds in his fist.
Our captain thinks he never before was in so hard a gale at this season of the year:
the sea continually breaking over both the main and quarter deck,
injuring our livestock and washing away several necessary articles.
Friends almost all sick.
At night the wind and sea somewhat abated, and the wind being fair,
we have gained one hundred and ninety miles towards our
port during the last twenty-four hours.

"`7th. A rolling sea, wind ahead, and so cold that we had a fire in the cabin.
Thanks be to that Power Divine that unites us in the blessed harmony of the truth.
Gained little on our way, and the wind and seas being very high,
occasioned an afflicting night to most of the passengers.
The ship tossed very much,
and we have had very little refreshing sleep for several nights;
yet we are sensible that the benefits and afflictions permitted by Divine Providence,
are more equally distributed than we sometimes imagine.

"`8th. Wind and rain.
This is the tenth day since we have had fair weather and a comfortable sea;
may we be favored to possess our souls in patience: have gained very little today.

"`10th. Held our week-day meeting,
which the wind and sickness has not permitted us to do for more than a week past:
an hour and a half was spent in soul-refreshing silence,
and at the close an acknowledgment was made of Divine favor.
Our poultry and other livestock have been much
injured during the late high seas and winds.
Such is the suffering of these creatures in general on board ship,
that several of us agreed in sentiment,
it would be better to be deprived of the satisfaction
of abounding in fresh provisions on sea voyages,
than to gratify the appetite at the expense of so great oppression.

"`First-day, 12th. Our meeting today was a favored time; hope and faith revived;
thanks be to Him who is ever worthy, for this and every other mercy we enjoy.

"`13th. Cool as usual;
have had very little pleasant weather since a few days after leaving our capes;
the main deck always wet with seas breaking over it,
and frequently the quarter deck also.

"`15th. Our meeting for worship was a quiet, comfortable time.
The captain apprehending we were on soundings, cast the lead,
but found no bottom at one hundred and twenty fathoms.
At five o`'clock a large ship hove in sight,
which soon altered her course toward us--our captain hoisted
American colors and backened sail to wait for her.
Coming along under our stern, they hailed,
which we returned with information that ours was an American vessel from Philadelphia.
The other was a French privateer of twenty guns, and appeared to have two hundred men;
said they belonged to Brest, and had been cruising twelve days, was called L`'Esperance.
Finding who we were,
they wished us a good voyage and went in pursuit of a brig we had passed,
and which was still in sight.
While she was bearing down upon us, the minds of Friends were unpleasantly affected,
not only because it was uncertain what those sons of rapine might be permitted to do,
but more so, on reflecting to what a sorrowful state of darkness men must arrive,
before they can engage in the wretched business of privateering.
Sounding again, found bottom at seventy fathoms.

"`16th. At ten o`'clock discovered the coast of Ireland, not far from Cork.
Friends were mostly upon deck,
and pleased with the hope of seeing Liverpool tomorrow evening.

"`18th. The pilot came on board--met a number of vessels outward bound,
ten of which were going to Guinea for slaves;
the thoughts of which brought a gloom over all our pleasant
reflections on approaching Liverpool and our kind friends there.
Surely worse than midnight darkness awaits those who, with horrid presumption,
dare thus trample upon the most sacred decrees of heaven.
About nine in the evening a revenue boat with two custom-house officers came on board,
and by them we were landed near the dwelling of our
hospitable and worthy friends Robert and Sarah Benson,
who received us with real cordiality.

Mercy and goodness having been abundantly evident towards us in crossing the sea,
favoring with many uniting and confirming seasons together,
may we ever acknowledge it with thankfulness to the Father of mercies.

"`First-day, Sixth month 19th, 1796.
At two meetings in Liverpool,
my American companions were all exercised in testimony acceptably,
and dear Rebecca Young in prayer in the forenoon.
I felt no necessity to be heard in the ministry.

"`21st, Attended the Monthly Meeting at Manchester, to which Friends of Liverpool belong;
the business was conducted with dispatch, and in a little different manner from ours.

"`23rd. A number not professing with us attended the meeting on account of a marriage.
I ventured, for the first time since my arrival, to say a few words in testimony;
and feeling most easy to mention my prospect of
having an evening meeting with the inhabitants,
it was accordingly appointed.
Went after dinner to Richard Routh`'s, and retired to my chamber.
In the evening went to the meeting, which I entered in much fear, even to trembling;
but came out with thankfulness of heart:
a large number of the people gave us their company; and through Divine mercy,
it proved a solid, comfortable meeting.

"`First day, 26th. At Liverpool, the morning meeting was large for this place;
dear Samuel Emlen and our two American women Friends
were engaged in Gospel labor to my satisfaction,
and I hope to profit: my mind was kept still and quiet,
having felt no concern since landing to appear in testimony among Friends here.
Towards the close of the meeting,
I mentioned my prospect of a meeting with the inhabitants of Liverpool in the evening,
which was agreed to.
The meetinghouse was nearly filled, and the people behaved in a decent orderly manner;
and it ended to our comfort; praised be the Lord.

"`Having appointed a meeting to be held the 30th,
for young unmarried Friends above ten years of age, it proved,
through renewed condescension, a time of watering.
At the close,
I proposed another meeting with the people of other professions at six in the evening,
which was larger than the first, and thought by Friends to be a time of favor:
at the conclusion many of the people came to us,
acknowledging their thankfulness for the opportunity.
Samuel Emlen appointed another meeting of the like kind, to be held on First-day evening,
which coincided with a prospect I previously had.

"`Seventh month, 3rd. The meeting in the evening was very large;
it was said there were two hundred in the yard, and we had renewed occasion to say,
Good is the Lord, and worthy to be served; for He crowned us with his presence,
and made us joyful in the house of prayer.
It was to me an affecting parting with the people for the present,
my mind now feeling easy to leave them.

"`7th. At Birmingham;
and feeling my mind engaged to have a meeting with the people of this place,
I proposed it to Friends, who readily made way for it, to be at six in the evening.
Notwithstanding the notice was short, it was crowded;
several ministers of different denominations were present,
and there was an open door to receive what was delivered.

"`First-day, the 10th. In London.
Went to the meetings at Devonshire-house.
They were large, both in the fore and afternoon.
I was silent.
A meeting being appointed by another Friend to be held in the evening at Westminster,
I went to it.
It was large and thought to be favored:
many of the people acknowledged their thankfulness.

"`11th. Attended an examination of the boys`' and girls`' charity school at Clerkenwell,
a well-regulated school and boarding-house: the children were all dressed alike.

"`14th. At Tottenham week-day meeting, and silent as usual with me.
At the close, feeling my mind engaged to have a meeting with the inhabitants at large,
I proposed it, and Nicholas Wain, Thomas Scattergood, and other Friends uniting with it,
one was accordingly appointed, to be at six in the evening.
Not many Friends came to it, being afraid of taking the room of others;
it was pretty large, and through renewed mercy a solid time, my mind feeling peaceful.

"`First-day, 17th. Was at Devonshire morning meeting;
George Dillwyn and some others had good service.
I was silent, but appointed a public meeting at six in the evening,
in the house where the men`'s Yearly Meeting is held; which was very large,
and an open satisfactory time,
for which myself and friends were thankful to the Author of every good.

"`19th. At Devonshire-house meeting, but could not be easy, though trying to nature,
without appointing another meeting for other professors, at six o`'clock this evening,
which appeared to end well.

"`21st. Went with David Sands and Benjamin Johnson to
the American Ambassador for a passport to the continent,
which he readily granted; from thence we went to the Duke of Portland`'s office,
who is the Secretary of State, and obtained a permit from him.

"`24th. At an appointed meeting in the evening at Westminster, exceedingly crowded,
yet thought to be a favored season; thanks be to the God of all grace.

"`25th. Went with several Friends on board a vessel intended for Bremen,
and agreed to take passage in her.

"`27th. Was at Greenwich Hospital, where were above two thousand pensioners,
old men clothed in blue from head to foot, being ancient and disabled sailors;
they looked well and were lodged comfortably,
in places built like large state-rooms in a ship.

"`First-day, 31st. Was at a large and good public meeting at Clerkenwell,
and in the evening had a meeting at Horseley-down, over the market-house,
in a room supposed to hold eighteen hundred people;
all could not get in by some hundreds; and though very crowded and warm,
it was a quiet good time.
There being but one small stairway up to the room,
sufficient only to admit one person at a time,
it was more than half an hour before it was empty;
and in the throng two or three women fainted.

"`Fifth-day, the 4th of Eighth month.
After a solid parting with my friends, Joseph Savory and family of London,
George Dillwyn and myself went to Joseph Smith`'s,
where the Friends intending for Germany were, viz: David Sands, William Farrer,
and Benjamin Johnson, and a number of our kind brethren and sisters,
who were desirous to take leave of us.
We had a time of comfortable retirement,
under a feeling of the strengthening influence of the love of Christ; after which,
accompanied by Joseph Savory and wife, David Bacon, George Stacey and wife,
and Joseph Smith and wife, we rode to Blackwall, and went on board the ship Victoria,
Johann Borgis, master, for Bremen.
Took an affectionate leave of our friends, and immediately weighed anchor.

"`5th. With a fair wind we sailed by a pleasant country,
interspersed with handsome villages and farms;
a large number of vessels were in sight all day,
and we passed by many of the large ships of war at the Nore, one of which,
called the Ville de Paris, of one hundred and twenty guns, was like an enormous castle.
At dusk our pilot left us.

"`6th. A smart breeze and fair, with short seas; and the passengers nearly all sick:
our captain and seamen behave respectfully; the accommodations are none of the best;
yet we feel contented and easy, believing all is right.

"`7th. The latter part of this day we were in sight of land, being the coast of Oldenburg.
At night slacked sail, and stood off until daylight, then entered the river Weser,
and the tide being rapid, we lay seven hours at anchor,
during which we went on shore in Oldenburg, which is governed by Prince Etienne,
whose secretary was kind and courteous, inviting us to some refreshment.
As he could speak French, he commenced his conversation in that language,
but finding I could speak German, he seemed pleased, and was communicative.
We took a friendly leave of him, and walking towards the ship,
were sent for by the secretary`'s mother, a woman of good countenance,
with whom we walked in the garden, and found her to be a pious person,
towards whom we felt much love.
Parting in much tenderness, we returned to the ship with her good wishes.

"`9th. Sailed along between the countries of Hanover and Oldenburg to Bruck,
twenty-four English miles from Bremen, and dropped anchor;
here the vessels unload and send their cargoes to Bremen.
Bruck is a small village, and not very pleasant: we lodged on board,
and had a solid religious opportunity in the evening with the sailors.

"`10th. In the morning, having hired a lighter to take us and our baggage to Fraisack,
half-way to Bremen, we went on board, taking with us five poor passengers,
without expense to them.
The tide leaving us, we went ashore at a village, where poverty,
the effect of arbitrary power,
appeared in a striking point of view to Americans--the people,
with their horses and cows, living under the same roof, and all very meanly;
the land poor, and the people very laborious, especially the women.
Arrived at Negesak in the evening, and went on shore to a large and good inn, where,
after undergoing what we must expect to meet with in this journey,
the gaze and observations of many, who doubtless look upon us as a strange,
outlandish people, we had a good supper and retired to rest;
but previously had some agreeable and religious
conversation with our placid-looking landlady,
and gave her some books.

"`11th. After breakfast took passage in a lighter for Bremen,
about twelve miles up the river, against the current,
for which we paid fourteen shillings sterling.
Reached Bremen in four hours, and took quarters at a public house at Walfish,
outside the gates, where we were received kindly, and furnished with tolerable lodgings, etc.
A man coming in, told us there were in the town some who were called Quakers,
and who met at each other`'s houses for religious purposes.

"`12th. George Dillwyn, William Farrer, and myself, visited Mooyer and Topkin,
merchants in the town, to whom we were recommended.
Topkin having been some time in London, spoke English,
and gave us information respecting the money, mode of travelling, etc., in Germany.
We then went to Cassell and Trobis,
and found that Cassell had just returned from Pyrraont: he speaks some English,
and lives in high style.
An agreeable young man, who was employed in their counting-house,
and understood the English language pretty well, walked with us round the town,
showed us the public buildings and wine-cellar, which contained a vast quantity of wine,
chiefly Rhenish, the trade in which is carried on for the public benefit.
In this cellar there are many large tuns,
containing from forty to one hundred hogsheads each,
with the date of the vintage on them--some upwards of one hundred years old;
this they pride themselves in, and they can only be tapped by consent of the magistrates.
We returned to our lodgings with heaviness of heart,
observing no openness for religious service; we however gave books to several persons.
George Dillwyn, William Farrer, and myself, took a walk, and went into two houses,
where we were kindly received, had some conversation and gave them a few books,
for which they thanked us.
In the evening,
hearing of a religious woman who kept a school and was a kind of separatist,
Benjamin Johnson and William Farrer went to see her.
She received them gladly,
and said there were about twenty or thirty of them who met together to edify each other,
being all people seeking God.
This revived our drooping minds, that have been much exercised,
feeling something towards the people,
but not knowing which way to proceed to obtain relief:
hoping the Lord was working for us, we rejoiced and retired to rest.

"`13th. Had an opportunity of conversation with the religious woman,
who said she found by the book our friends had given her yesterday,
that they were not quite the same in opinion with us, for we went beyond them.
After sitting awhile with her, she sent a lad to show us the house of Albert Hoyer,
one of their number, with whom we had much religious freedom, to our mutual satisfaction.
We parted with him and an ancient woman, who appeared to be united with him in sentiment,
and with us in the general; she making some remarks,
which showed her to be one earnest for the right way.
We then went to the house of an ancient man who, with his wife, a woman of a comely,
meek appearance, received us pleasantly, and spent a little time,
opening to each other our minds on religious subjects.
He said the people called them Quakers,
and sometimes pointed at them as they walked the streets,
but that ought not to move them,
for he knew there was nothing better to be expected from people while
they continued under the dominion of the world`'s spirit,
as they did not understand the things of God.
We took leave of them in tenderness.
There is no doubt these are an enlightened people,
desirous of an establishment on the right foundation;
but they have many outward discouragements to hinder them,
as I apprehend is the case throughout Germany.
They appear to have little or no dependence on outward forms or ceremonies,
and confess freely, that none can be the children of God,
but those who are led by his spirit;
and that it is not putting away the filth of the flesh by any outward washings,
but the answer of a good conscience towards God,
through the regenerating power of his spirit, that is the saving baptism:
but they still comply with the ceremony of water baptism with respect to their children;
and they also attend the public worship.
That which principally distinguishes their little company from others,
is the circumspection of their lives and manners,
and their frequent meetings together to strengthen and build one another up.
I returned to my lodgings comforted with the interview.

"`First-day, 14th. Friends sat down together in our chamber,
and through Divine mercy were favored with an uniting, strengthening season,
which afresh animated our spirits to pursue as ability may be given,
our weighty engagements in this land.
The afternoon proved distressing to us,
on account of the people making it a time of merriment; drinking, singing,
playing at bowls, etc., which appears to be the general practice.
They attend their places of worship twice before two o`'clock,
that the afternoon may be devoted to lightness and foolish pastimes.
I said in my heart, what will become of the careless shepherds of this people;
who do not seem addicted to gross wickedness as in some other places,
yet are reconciled by custom to this abuse of the First-day:
and we are told the pastors do not discourage it or tell them of its impropriety.
Our landlady and her children kept the house as quiet as they could, on our account.

"`15th. George Dillwyn and myself visited Albert Hoyer,
two others of the same religious people being present;
we spent an hour or more with them to good satisfaction; they did not appear puffed up,
but desirous of improvement, and were open and loving.
We gave them some books,
and recommended their close attention to the further manifestation of the true Light,
which they had acknowledged for their guide and teacher;
and to hear their testimony faithfully: thus would the Lord prosper them,
and make them in his holy hand, as eyes to the blind, and as a city set upon a hill:
all which they took kindly, and hoped they should treasure up our observations,
and improve by them.
Then embracing us tenderly,
they expressed their desires that the Lord might
preserve us and bless his work in our hands.
We left them, comforted in a belief we had not been sent to Bremen for nought.

"`After dinner, Christian Bacher came to see us,
having just heard there were Friends come to Bremen.
He appeared to be a man of good understanding, acquainted with the Divine Light,
and separated from the public worship, with its forms and ordinances.
He said there were a number in Bremen that we have not seen,
who would be glad of our company, and who are seeking the truth.
Being acquainted with many parts of Germany,
he told us of religious people in Berlin and other places, who,
though weak in many of their opinions, are honest-hearted.
Some call them Mystics, and other names;
and they appear to have taken many of their
opinions of the inward life from Jacob Behmen,
Lady Guion, and other writers of like kind.
This man is acquainted with Friends at Pyrmont,
and acknowledges himself to be one with us; but we thought he was too talkative,
and one of those who think there is no need of uniting as a visible church,
or establishing an order of discipline,
which appears to be the opinion of many of the pious people in this country;
and this makes them shy of Friends at first, as they know us to be a gathered people:
this continually adds to the weight of exercise which
Friends must experience in visiting Germany.
We gave him Barclay`'s Apology, and several other books,
to lend or give to inquiring people,
which he seemed pleased with an opportunity of doing.
He gave us some directions for finding a serious people in Hamburg and Altona.

"`16th. Set off in an uncomfortable extra post-wagon for Hamburg, and dined at Ottenburg,
eighteen English miles,
travelling about three or three and a half miles an hour--and
there seems no inducing a German driver to exceed that gait:
the roads are very crooked, the country level and clear,
so that objects are seen at a great distance.
We proceeded to Tastoss, and were completely jolted and fatigued in their awkward,
clumsy wagons.

"`17th. Rose early: the post-horses being kept at an inn,
they were in haste to have us off before it grew very warm.
We were all loaded again in the same kind of wagon,
which is the best that can be procured for travellers in this country,
except they purchase one, and take post-horses from town to town.
Indeed, the best carriages we have seen here are heavy and inconvenient.
Travelled over a very poor country, as yesterday, one-third of which is a heath,
where they keep boys and girls to tend cattle, and the miserable sheep we see everywhere,
as we pass along.
Some of the land is sown with rye, barley, oats, buckwheat, and some wheat.
Hundreds of the poor peasants were employed in mowing and hauling in;
the women bearing an equal share of the burden with the men.
The grain was poor, compared with England or America.
The villages, generally, have a miserable appearance, being composed of clay huts,
without chimneys.
They use turf for fuel, and the people are very laborious, living hard; coarse,
black rye bread, milk, and some vegetables, being their principal diet.
Their horses, cows, etc., live under the same thatched roof with the family.
There are but few good houses between Bremen and Harburg, sixty-six miles, where we dined.
We are still in the Hanoverian dominions: the people are shamefully fleeced,
both by the government and the priests, beyond anything I have ever heard of.
At our inn they were civil and cleanly; a good house, and tolerable beds.

"`18th. George Dillwyn and myself went in a boat for Hamburg,
about six miles across the Elbe.
There were about forty passengers, several of whom were from the interior of Germany,
and intending for America.
After passing by many small islands, we arrived in about two hours,
and landed in this great and populous city, entire strangers; but knowing the language,
we soon found the London and American coffee-house; breakfasted there,
and then waited on Roosen, a merchant,
to when we had letters of introduction from London.
He appeared to be a high man, his countenance bespeaking little kindness to us: however,
he sent his barber to conduct us in a search for lodgings, but finding none we liked,
we took coach, and went to Altona, having a letter to Vandersmissen and Sons,
men of extensive trade, who received us with much kindness,
and appear to be religious men.
In Altona we were also unsuccessful in finding suitable lodgings for our whole company.
Returned to Hamburg, and took three rooms at one dollar and a half per day.
Coming again into this busy city, our minds were brought under exercise,
and abundant discouragement presented; seeing few or none who appeared religious.

"`Having heard of a person in Altona called a Quaker, I went with two of our company,
and after a great deal of walking in the heat, found him: he was an old man,
named Heltman, who had separated many years past from the common forms,
and met with some others at times in Altona and Hamburg of like religious opinions,
and was a preacher among them.
With him and his wife we had an hour`'s religious conversation.
After I had opened our principles a little to him,
and told him my motive for leaving my own country, he embraced me,
acknowledging he was one with me in faith,
He recommended us to two sugar refiners in Hamburg.
Having walked several miles in the dust and heat,
we returned to our lodgings fatigued yet satisfied with our visit.--'`Through many
tribulations we must enter the kingdom of God.`'

"`20th. George Dillwyn and I went to see the two men we heard of yesterday.
Upon entering into conversation,
one of them showed some surprise at our coming so far from home on a religious account,
and thought there was enough for every child of God to do at home,
and that the Lord could make way for the instruction of the people in all places.
Finding him a well-inclined man,
we endeavored to convince him of the possibility of a
Divine call to travel with the Gospel message now,
as well as in the apostles`' days, which he did not dispute;
but said that some had travelled under an apprehension they were called,
who had hurt themselves and did no good to others.
At length he appeared satisfied with our motives,
and believed we were right in making such a sacrifice.
We spent two hours in conversation on religious subjects,
in which he appeared to be an enlightened man, but too full of his own opinions,
as having no need, or not feeling any, of anything but what he already knew.
We gave them some books, and they were kind and loving at parting,
and expressed a hope that we would not take it amiss
that they seemed backward at first about our call.

"`First-day, 21st. Four men came to see us: one of them gave me a book he had written,
as an exposition of some of the predictions of the prophets and of our Saviour, etc.
This man appeared too full of himself and of talk;
he had suffered imprisonment at Nuremburg,
on account of his not attending the public worship and conforming to the ordinances.
On being brought before the magistrates and priests,
he was enabled to give such reasons for his faith and practice as silenced them,
and procured his discharge.
The rest of these men were more solid and humble,
so that we marvelled to find the clearness of sight they were favored with,
and the readiness with which they brought forth
Scripture to confirm their and our sentiments:
on the whole, the interview was satisfactory.
Stillness and more of the child`'s state is much wanting,
but the sincerity of heart which they appear to possess will, no doubt,
draw down the Divine blessing.
After giving them some books, we walked to Altona,
and dined with Henry and Jacob Vandersmissen.
They are Menonists, but having been nine months in England, and boarded with Friends,
they retain a love for the Society.
They sat in silence, both before and after eating, in a reverent posture.
We had some instructive religious conversation with them, and left them in much love.
J+++.+++ F. Reichart came to take us to his house,
where we had appointed to meet some of the separatists.
Twelve persons, besides ourselves, met; we advised them to get into silence, which,
after some time, they did.
A comfortable feeling attending,
I ventured to preach Christ as the light of the world and the life of men,
the bread from heaven, etc.,
and was more favored with expression in the German than I could have expected.
David Sands then requested me to interpret for him, which I undertook in fear,
but hope nothing suffered.
George Dillwyn also desiring my assistance, I gave it as well as I could,
though I feel myself not competent to such a work,
and less qualified to interpret for others, than to speak my own feelings.
Our communications were received and acknowledged as the truth,
and Christ Jesus as the only foundation.
If these people could see more clearly the necessity of silence, and love to abide in it,
they would be made a shining light; some of them, we had no doubt,
were drawing nearer and nearer to the '`quiet habitation.`'
They embraced and parted with us in great tenderness.
The space between Hamburg and Altona having some shady walks, swarmed with people, who,
according to the inconsistent custom of the country,
were diverting themselves in a variety of ways, with music, singing, dancing, gaming,
and drinking; we passed through them without molestation.

"`Second-day, 22nd. Two of the men who were at meeting yesterday, came to see us,
and in a tender frame of mind said, they felt that God was with us,
and had sent us thither;
were convinced of the necessity of inward silent waiting upon God,
who alone can open and none can shut, and who shuts and none can open;
and hoped our coming would not be in vain to them: they were very loving,
and at parting expressed much desire for our preservation,
and their own improvement in the true and living way.
One of them, J. Abenau,
appears to be the most solid and enlightened man that we have found among them;
though both these men and some others, we thought were not far from the kingdom.

"`The city of Hamburg is said to contain one hundred and fifty thousand inhabitants;
ten thousand of these are French emigrants.
Owing to its being a neutral city and free port,
there is abundance of shipping in the harbor from almost all nations.
It is governed by its own magistrates, but pays some tribute to the Emperor.
The people enjoy the free exercise of religious opinions,
yet few appear much concerned about it in any form; their places of worship,
though chiefly Lutheran and Calvinist, are furnished with crucifixes,
likenesses of saints, etc.; we found, however, some pious people among them,
to whom we felt much love.
The people in a general way, dress as their ancestors did several ages past,
the Dutch not being given to change.
The streets are narrow, have few foot-ways, and being everywhere paved with pebbles,
it makes walking tiresome.
Altona contains about forty thousand inhabitants, and is, of the two, the pleasanter city.

"`Fourth-day, 24th. Our friends the Vandersmissens having sent their coach,
some of us paid them a visit, and drank coffee, though it was but about eleven o`'clock.
The Germans think that coffee can never come out of season.
David Sands and myself had another opportunity with our friend Heltman;
he and his wife are loving, solid people, but low in the world,
yet we hoped were near the kingdom; he embraced and parted with us in tears,
recommending us to continue faithful unto God to the end;
and said his days were drawing near to a close, but he lived in the hope,
that through the Lord`'s mercy he should leave the world in peace.
Our landlady imposed upon us by an unjust charge,
which for peace sake we were obliged to pay, though it was contrary to our agreement.
This is a land of impositions on strangers.
We hired a boat to take us and our wagon to Harburg, six English miles, for six dollars;
dined in that place, at the house where we had lodged before;
the people looked pleased to see us and hoped to
have our company again before we left Germany.
We took four post-horses, and leaving Harburg travelled through a poor, Darren country,
the roads sandy and houses mean, and arrived at Walley, a village of about six houses.

"`Eighth month,
26th. We were obliged to stop on the road for our postilion to take his bread, herring,
and milk, which they do in the middle of every station, for which,
and the feed of the horses, passengers must freely pay, or be used worse than they are.
The horses eat the same bread as the drivers.
We arrived at the gates of Zell about nine o`'clock at night,
where an officer stopped us and took our names.

"`27th. Having agreed for four small rooms and beds,
George Dillwyn and I went into the city,
like solitary pilgrims in the midst of a strange people.
It is not easy to conceive the state of mind and mortification
that poor travellers have to pass through daily,
but more especially on entering large cities and towns, where, at first view,
all appear to be minding their own things, and where the manners, religion,
and pursuits of the people are so entirely different from ours,
and not a single inhabitant known to us; yet by patient waiting,
the Lord hath hitherto manifested to our comfort,
that five or ten upright-hearted souls are yet to be found in every place;
this hope comforted our tribulated spirits in passing through the streets of Zell,
as spectacles to the people.
Having a letter to a merchant whose name was Helmleck, we went to his house,
and were received with much civility and respect.
He said, he knew a person of our religion in town, whose name was Dietrich,
to whose house he took us; be proved to be a Moravian, but a kind, courteous man,
and appeared to be desirous of having some books,
that he might become better acquainted with our principles.
On conversing with a man at our lodgings, he expressed some surprise that I,
who was born in America, should be as white as a German: such is the ignorance of many.
The son of a Calvinist minister, hearing our conversation, informed his father of us,
who sent me an invitation to come to his house, and feeling no hesitation, I did so.
I found him to be a man of about thirty-five; we conversed without restraint,
on religious subjects, about an hour, he being of a candid, liberal mind,
freely confessed that our simple manners, peaceable principles,
and refusing to take oaths,
were consistent with the Gospel and his own private sentiments,
and frequently gave me his hand as a testimony of unity.
He called his eldest son, a pretty lad, about twelve years old, whom I saw at our inn,
and told him to take notice what I said, that I was one of the people called Quakers,
from America, that I did not think it right to pull off my hat in honor to any man,
but did it only in reverence to the Divine Being;
that I and my brethren never went to war, nor took an oath, our yea being yea,
and our nay, nay.
The lad was sober and attentive,
and remarked that he had read in the Scriptures a command concerning the last.
We parted lovingly, both the pastor and his wife pressing me to come tomorrow.

"`First-day, 28th. Several of our little band were unwell, owing, as we supposed,
to the manner of living in this country.
Sour wine, sour beer, bread, meat and vegetables, form the principal articles of diet;
the meat cooked till it is ready to fall to pieces.
Coffee, which the Germans make to perfection and drink it several times in a day,
seems to be almost the only good thing at their tables.
Meat is mostly poor, and the veal killed when it is about a week old.
The pastor and Captain Kirchner came to see us, with whom we had some conversation,
we hoped profitably.
In the afternoon, William Farrer and I drank coffee with them and Professor Rock,
a French Calvinist minister, who preaches in his own language to a congregation,
descendants of the Huguenots, who fled here from France, in the time of the persecutions:
he did not appear to be much concerned about religion.
This town, unlike those we had before been in on this day of the week,
was everywhere exceedingly still and orderly;
few people being in the streets or on the public walks, which was very agreeable to us,
and what we did not expect.
Spending some time with the pastor at his house, in serious conversation, I endeavored,
as well as I was qualified, to open to him the nature of our doctrines and practices;
he agreed, that no man could be a Christian,
but by the operation of the spirit of Christ; yet his idea appeared to be,
that this spirit was so mixed and blended with the natural faculties of the soul,
as not to be distinguishable from them,
but that it wrought our conversion and purification in an imperceptible manner.
I mentioned to him several passages of Scripture in opposition to this opinion;
and at length he confessed he had never read of, or heard the subject so treated before,
nor so much to his satisfaction.
He said the sprinkling of infants could avail them nothing,
and that what he did in that respect, was in conformity to the opinions of others,
and not his own; for if he could believe any water baptism essential,
he should embrace the opinions of those who administered it at mature age;
and with respect to the supper, he said,
he did not conceive it was intended to be of perpetual obligation in the church,
for that would have been perpetuating the Passover, which our Lord was then eating,
but that this and other Jewish rites he came to fulfill and put an end to.
He believed no more was meant by our Lord`'s injunction, than that his disciples,
as often as they sat down to meat, should remember him, their Lord and Master,
who was now sat down to table with them for the last time before he was offered up.
Clear it was, he said, that it had no effect on the souls of those who observed it,
who remained from year to year in their general conduct forgetful of God.
Many people, however, who took it from pious motives,
he did not doubt might feel themselves refreshed.
He kindly expressed the satisfaction he had felt, and near unity with me,
adding with much tenderness, that it was one thing to acknowledge sound doctrines,
and another to practise them.
I returned to my companions peaceful,
and in the hope that Truth had not suffered in the interview.

"`29th. Walked through the principal streets of Zell, which is a fortified city,
surrounded by mounds of earth, a wide ditch, gates, etc., and guarded by soldiers.
The promenades around it are very fine, lined with trees, and gravelled.
At this time they are suspicious of strangers,
and in addition to taking our names at entering the gates,
every innkeeper is obliged to return the names
of his lodgers every morning to the burgomaster.
The people are quiet and respectful to us; there is little appearance of trade,
and the market is poor.
The suburbs and city may contain twenty thousand inhabitants.
As we walked along, a man looking pleasantly on us, we turned about and spoke to him,
with which he seemed glad, and took us into his house.
He soon opened his mind, and we found he was a great admirer of Jacob Behmen,
and had a strong testimony against the priests, but very fearful of them and the people,
and therefore kept himself very hidden; which is the case of hundreds in this country.
He thought we were one in sentiment on religion; but on coming to see us in the evening,
we presently found he was full of visions:
though he confessed freely to the truth of our doctrines, and was tender and loving,
yet he spoke of having found God in minerals, and that he was to be found in everything;
had been made acquainted either by vision or dream with the nature of the Divine Being,
of angels and of men, etc.
He said he had been long separated from the common form of worship,
and had but two or three acquaintances in Zell
to whom he could speak his sentiments freely,
and these he would bring to see us in the morning.
We gave him some books, and such advice as we were favored with, which he took kindly,
and left us in tears.
Spent another hour with the pastor, Johann Frederick Krietsch, to much satisfaction.

"`30th. Took leave of my friend Krietsch and his family,
with much affection on both sides.
We gave him several books.
His wife said,
he had never seen a stranger that he discovered so much affection for since she knew him,
which he confirmed, and much desired we might return through Zell;
but be that as it might, he observed,
he should ever remember with thankfulness a kind Providence sending us there.
He was a tender man, and I hope the Divine blessing will rest upon him.
We also took leave of the family at the inn with their good wishes.
An agreeable young woman, of a religious mind, who waited on us during our stay,
took our attention at parting, and pressed our return if it were possible,
saying she would be glad to go with us to America.
The Moravian minister paid us a visit as we were about to go off;
having been out of town for some days and just returned,
he expressed his sorrow at the shortness of the interview.
We rode through a poor country to Hanover, and put up without the city gates,
where we had tolerable accommodations: the landlord was a baptized Jew.

"`31st. George Dillwyn and I walked through the
town and delivered our letters of recommendation.
The city has the appearance of considerable trade, chiefly carried on by land,
the river being only navigable for flat boats in freshes.
It is fortified, has many soldiers and about thirty thousand inhabitants;
the religion generally Lutheran, but there is one Calvinist meetinghouse,
and some Moravians who meet privately.
About their places of worship and burying-grounds are many relics of popery,
some monuments and imagery six hundred years old, or perhaps more.
Afternoon,
William Farrer and I walked about a mile and a half to
see the steward to the commissary of the port-office.
He and his wife received us kindly,
and appeared much like Friends in principle and practice.
He had been separated for some years from the common forms of religion,
and was a man of solid countenance and demeanor.
We spent about an hour with them to satisfaction.
He gave us the names of several more separatists, persons of religious character.

"`Ninth month 1st. Our friend Shaffer visited us:
the cross seems much in the way of the few serious minds in Hanover,
and they acknowledge they feel themselves too weak to stand forth faithfully.
A person to whom we had letters came to see us, and some of us being unwell,
occasioned as we thought by our manner of living,
he told us that dysentery was very common here in the autumn,
and many are removed suddenly,
and advised some remedy to correct the acidity of the
drinks and food which are commonly used in this country.
He appears to be a kind man and disposed to be of use to us.
The Lord makes way for us in every place.
Johann Buchner visited us: he was many years a musician in the army,
and had been in many battles; but growing uneasy with his profession, dropped it,
and is now gardener to the king`'s physician.
He has been in England, and there got acquainted with Friends and with the Methodists,
and speaks English a little.
He gave us an account of many exercises he had passed through,
and of his present state and opinions,
which I did not discover to be much different from ours.
He is no doubt a religious man, and is separated from the outward forms used here,
and more bold in maintaining his testimony than his companions.

"`2nd. David Sands and George Dillwyn not being able to converse in the language,
much of the labor falls upon me, and people frequently calling upon us,
I am kept pretty busy; for by the time we are two or three days in a place,
we begin to find out the religious characters, and they us.
We went to see a shoemaker, a tender, seeking man, and his wife;
both of whom were made very near to my spirit.
They had left other professors and kept much retired at home.
He said the people were vain, and it hurt him to mix with them,
and that he was desirous of following the inward Preacher, who would not deceive,
as many of the wise and learned preachers in the world did.
Then we went to an old man, who was spoken of as being a Quaker; he received us kindly,
but we soon found he was not got beyond the use of water baptism,
and was one of the principal men of the few Moravians who meet here in a covert manner,
and yet continue publicly to meet the Lutherans.
By letters received from the brethren in America,
he had understood that Friends had supplied the Indian
brethren under the care of D. Seisberger with corn,
in a time of scarcity.
I told him I was one of the Friends concerned in that business, which made him more open,
and he seemed pleased with our company.
In the evening we had a comfortable sitting by ourselves;
and have found it very strengthening frequently to retire in
this manner and seek for counsel in this trying field of labor,
where we feel the need of putting on the whole armor,
so that nothing may suffer by or through us.

"`3rd. George Dillwyn, David Sands and myself,
paid another visit to the aforesaid shoemaker, at his request,
and he appeared glad of the visit.
My companions going to our inn, I called to see Henry Wertsig, a woman`'s habit-maker;
and after spending some time with him, he accompanied me to our lodgings.
On our way we met a German nobleman, who, after passing a few steps,
turned back to speak to us; and said he had been in poor health for some time,
had tried physicians, the mineral waters and travelling, but all to little purpose;
a dejection spread over his countenance, and he seemed in a serious frame of mind.
My friend informed him I was from America, on a visit to the children of God in Germany.
He expressed a wish for my preservation and success.
I told him there was one Physician near at hand to whom he might yet successfully apply,
who, if it were not consistent with his wisdom to restore him to health,
could bless the affliction to him, and prepare him for a better inheritance;
to which he assented, and parted with us in a very friendly manner.
I can but admire at the clear and decisive manner in which many of these seeking
people speak of their convincement of the fundamental doctrines of Friends,
and the sense they have of their own weakness in
not more boldly and openly maintaining them;
but that time must come, I solidly believe, to many in this land.

"`First-day, 4th. Though very rainy, yet eight of the friendly people, and two Moravians,
came and sat down with us in silence at our inn.
Some religious communication taking place, they received it in much stillness;
and when it appeared about time to break up, we desired,
if there had been anything said which they did not unite with or understand,
they might take the freedom to mention it; to which the old man (Moravian) replied,
it was entirely consistent with Scripture,
and what he had found in his own mind for forty-five years.
They parted with us in much tenderness and with reluctance, desiring our preservation,
and hoped we would visit them again.

"`A great fair of horses, cattle, hogs, merchandise, etc., is to commence after dinner;
and this occasioned our getting away as soon as we could,
the people beginning to collect largely about our inn.
The landlord expressed his sorrow that we could not stay in his house with satisfaction,
as dancing, music, and all kinds of rioting would soon begin, and continue for two days;
he also said that he thought it a blessing to have such people in his house.

"`5th. Moved on to Hammeln;
the country we passed through was more fertile than heretofore, the road paved,
the mountains round us covered with beech and other timber,
the valleys clothed with verdure, and very pleasant.
Having taken some cold from riding through the rain,
I was more unwell when we arrived at Hammeln, than all the journey before.
This is a fortified town, and may contain about fifteen thousand inhabitants;
it is now full of soldiers, and said to be the strong hold of the Hanoverian dominions;
its handsome gardens and valleys of grass land, with a water course through it,
give it a pretty appearance.

"`6th. Feeling poorly, and but little prospect of religious service in Hammeln,
we set out for Pyrmont, travelling through a handsome, hilly,
and well cultivated country,
thickly settled with villages--the people were gathering in their harvest.
Arrived at Pyrmont, and alighted at our friend Frederick Seebohm`'s,
and were provided with accommodations.
Lewis Seebohm, and several of the friendly people, coming to see us,
we had a comfortable religious opportunity with them, in which Lewis interpreted.

"`7th. This being their week-day meeting, about twenty men and women attended,
and it was a solid baptizing time.
The people stayed with us some time after the meeting was over,
and seemed much pleased to see us.
We concluded to have our dinner ready cooked from an inn, and a young woman,
named Lena Spannagle, who had been with George Dillwyn and Sarah Grubb,
and also with John Pemberton, until he died, having heard of our coming,
walked twelve miles to offer us her services, which we freely accepted.

"`8th. Walked out to Lewis Seebohm`'s, about one and a half miles.
The valley which he occupies, was given him, about four years past,
by the prince of Waldeck, to erect a manufactory of edge tools,
which he has accomplished, and improved the place very much, for the time.
He has a pretty good library, and is a man of good talents,
acquainted with the English and French languages.

"`10th. Visited the family of Lewis Heydorn, consisting of his wife and six children.
Being obliged to act as interpreter, I did it in much fear,
lest I should make some mistake; sensible that we have daily need of Divine help,
that we may keep a conscience void of offence: we hoped the opportunity was profitable.

"`Went to see a person, named Galla, whose family consists of himself, wife,
and two journeymen.
The language of '`peace be to this house,`' went forth freely;
the spring of everlasting love and life being mercifully opened,
we rejoiced together in the feeling of near unity and affection for each other.
One of the young men was especially made near to us, as one who, if he kept faithful,
would be made an instrument of good to others.
At the burying ground we saw the grave of dear John Pemberton.
When I think of this brother being brought, in so singular a manner,
to lay down his life among this handful of professors,
who are like the first fruits in Germany, that saying mostly occurs,
'`the blood of the martyrs is the seed of the church.`'
He is remembered here with much sweetness.

"`First-day morning, 11th. About forty Friends^
footnote:[These people, though professing our principles,
are not accounted strictly in membership with our religious Society.]
attended the meeting, which was a solid, profitable season.
A woman who happened to be at the meeting at Hanover, last First-day,
walked with her brother-in-law six miles to the meeting, over a high mountain.
She is the wife of Huber, at Hanover, dined with us, was very tender,
and said the Friends at Hanover sent their love to us,
and hoped we would visit them again--she thought
the Lord had brought us there for their sakes.
Afternoon--some notice being given of the meeting, about sixty attended,
some of whom were of those who had separated from the little society here;
the Lord was pleased to be with us in a remarkable manner,
and most present were broken into tears.
It held three hours, and ended in solemn prayer and praises to God;
several persons continued with us, until nearly ten o`'clock,
conversing on religious affairs.

"`12th. In the afternoon, visited the family of Herman Shutamire, who had separated.
We asked him some questions concerning his separation,
which he answered in a good frame of mind;
and after recommending him to dwell near the Fountain of love,
that would reconcile and unite all the children of our heavenly Father together,
we parted in much tenderness.

"`13th. Visited several families,
which service was attended with much openness and satisfaction.
The valley where the Factory is, they call Friedenstall or Peace-dale; it is a quiet,
sequestered fertile spot,
and I believe that great harmony prevails among the inhabitants, who are four families,
chiefly connected with Friends.

"`16th. Herman Shutamire visited us, and brought three papers, one from himself,
one from Henry Munthang, and one from Anthony Shonning;
being a vindication of their conduct in separating from Friends.
On reading and considering the contents,
we agreed to request the principal Friends who remained united as a body,
to meet us tomorrow.

"`17th. The Friends having drawn up the causes
of their disunity with those who had separated,
we found it was likely to prove a very exercising affair to us,
and were much discouraged, feeling but little hope of a reunion.

"`18th. First-day: held a meeting at nine o`'clock, which ended solidly.
In the afternoon meeting about fifty were present, two of whom were Jews,
and it was thought to be a favored time.
The young women who are in families, and work either in or out doors,
as occasion requires, and very hard at times, are paid about seven dollars a year:
and a young man, a Friend of good capacity, says, if he makes his pair of shoes per day,
he earns about two shillings and sixpence our money, a week,
and is found board and washing; yet he keeps himself decent,
and is dressed like a Friend of our country.
Provisions and clothing are about two-thirds of the price in America;
but they make but little clothing and mean diet do.
Several of them express their desire to go to America,
but we dare not encourage or unsettle them.
Our concern for the right ordering of things among this little society,
keeps our minds closely exercised,
as well as for the restoration of those who are scattered--the
eyes of the people are much upon them and us,
some for evil, and some for good.
Having had my mind especially turned to this place, I feel at home for the present,
and desirous of bearing my part of the burden while we stay.

"`19th. Anthony Shonning, a sensible old man, who was separated,
brought a paper he had drawn up, containing a large sheet closely written,
which he said he could not be easy to omit.
We made such remarks as occurred to us,
and afterwards David Sands and myself visited him and Henry Munthang at their home;
they were loving, and evidenced a strong desire to be reconciled upon a right ground.
We proposed a meeting at six o`'clock, with all that had gone off, and Friends together,
and desired them to seek for a preparation of love and charity,
that they might meet each other in a state that the Lord would condescend to bless.
Most of the men Friends, and three women, met in the meeting-room.
Henry Munthang, Herman Shutamire, Henry Land, his son, and Margaret Wint,
being the heads of the families of those who had gone out from Friends, came also.
After a season of silence, David Sands was drawn to prayer; then we, the visitants,
expressed our minds to them fully;
setting forth the opportunity it gave the enemies of Truth to triumph,
seeing them at variance,
and the importance of their mutually laying down their prejudices against each other,
and seeking after a spirit that would bring about a reconciliation without many words.
The three principal separatists then expressed
themselves in great brokenness and humility,
and in a spirit of forgiveness of those who they thought had dealt hardly with them,
and caused the separation.
I marvelled at the clearness with which they expressed themselves.
The Lord graciously condescending to favor, in a remarkable manner,
with his blessed presence--all hearts were humbled,
the high untoward will of man was brought down, and the spirit that loves contention,
and delights to have the superiority, was cast out, and through mercy, the meek,
teachable state of little children appeared to predominate in most present.
Our minds being deeply baptized with an undoubted feeling of the Lord`'s goodness,
we were opened with clearness to set before them the nature of our holy profession,
the love of Christ, the good Shepherd to us all,
and the necessity of dwelling in that charity, which,
instead of magnifying each other`'s weakness,
and entertaining groundless jealousies and surmises of each other,
would cast a mantle of love over them, remembering that we also were weak,
and liable to be tempted.
A truly contriting and heart-tendering time it was,
and most of the company were melted into tears,
under an extraordinary sense of the Lord`'s compassion to us.

"`It was then proposed,
as it appeared that in a time of weakness many
things had been said and done on both sides,
that did not savor of that Divine love and charity in which
all the children of our heavenly Father ought to dwell,
that all present should now, under the humbling visitation of God`'s power,
without bringing up the occasion of offence, or going into many words,
forgive one another, and cast all that they had counted offences,
as into the depths of the sea, never more to be brought up again.
Both sides freely, and in great tenderness, confessing their readiness so to do,
and to begin again under the direction of the heavenly Master-builder,
in an united labor for the edification and
building one another up in the most holy faith.
They rose,
embraced and saluted each other with manifest tokens of unfeigned
love and thankfulness to the great Searcher and softener of hearts,
who,
in an unexpected time and manner had revealed his power to the uniting of
brethren who had been seven months in a state of separation,
after having for some years walked in harmony and suffered together
for his name`'s sake.--The meeting then concluded in heartfelt
praise and supplications to the Fountain of love and mercy,
who had in so remarkable a manner blessed the labor and exercise of the evening,
and crowned us with gladness, when we parted at almost eleven o`'clock.
For my own part, I thought myself amply paid for all my exercise,
the long journey and voyage, and the trying separation from my dearest natural ties,
by being made a witness to the love of God poured forth, I thought,
as in the beginning among Friends.
We went to rest, sweetly refreshed in spirit,
and I did not marvel that my mind had been so
remarkably turned to this place before I left home.

"`20th. Made several visits to the different classes;
many told us in brokenness of spirit,
that they had never before witnessed so much of the love of God shed abroad,
as was manifested last evening.
It appears that these people, in a time of weakness,
had been scattered through the influence of one Brown,
with whom John Pemberton had labored because of his erroneous opinions.

"`21st. A large meeting, most of the Friends and professors,
with the families of those who had not been at meeting for more than six months,
attended; it was a solemn tendering time,
and we were favored to relieve our minds in loving counsel, caution and encouragement,
to hold fast the profession of their faith in a good conscience and love unfeigned.
It was like completing the bonds of union;
we rejoiced together and gave thanks to the Author of every mercy.
In a conference with all those who were accounted members,
we were made acquainted with the business of their Monthly Meeting,
in which they had hitherto kept no minutes, but had visited and received some as members,
and in a book for the purpose, had recorded their births and burials,
and raised a small stock for the uses of society.
We recommended several matters to their attention and care,
and the necessity of promoting the school education of their children,
for which purpose our dear friend John Pemberton had left them thirty pounds sterling,
and another Friend had given them five pounds.
Our advice was received kindly,
as they had long felt the necessity of a regular established discipline.
The meeting concluded in much harmony.
Thus we are favored, through Divine help, to get along step by step to our comfort.

"`Fifth-day, 22nd. Visited a family consisting of a man, his wife and four children;
they appeared to be the lowest in the world of any we have visited.
A number of persons who were near the house at their work, both men and women,
hearing our voices, drew near,
and it proved a time of distinguished mercy and encouragement,
both to the family and those that came in, who were not Friends.
The man is a day-laborer, about the Factory,
and has to maintain his family with about one shilling a day, Pennsylvania currency.

"`23rd. Visited Henry Munthang and family; consisting of his wife, Anthony Shonning,
an old Friend removed from Rinteln, and six children; we hoped it was a uniting time,
both to visitors and visited.
In the afternoon called upon Klapp, the governor of the town, who received us kindly.

"`24th. Friends sat down quietly together,
and apprehending we were nearly clear of Pyrmont,
I expressed my prospect of going to Berlin.

"`25th. The morning meeting was the largest we have had,
though there were but three or four who did not profess with us; yet,
with the addition of the families lately re-united, they made a respectable appearance:
three Friends from near Minden, and two from Boetter were present.
It proved, through mercy, a solid favored meeting.
Afternoon had a meeting at Leibsen, a village one mile and a quarter from Pyrmont,
in the same valley as the Factory;
most of the Friends and a pretty large company of others attended;
we were considerably exercised, and it was thought to be a season of profit.

"`26th. Sat down together to seek for best counsel.
I mentioned my prospect of Berlin, which still continued with me.
David Sands expressed his unity with it and thought we should go together.
George Dillwyn thought he was not yet clear of Pyrmont.
The governor having sent an invitation, I went with some of our company,
and had much conversation with him; he spoke well of Friends,
and I hope he is a friend to them.
The people who saw us with him with our hats on, appeared astonished,
for the great men in Germany are approached with much servility.
In the evening being quietly together,
Lewis Seebohm thought it his duty to offer himself as a
companion to David Sands and myself to Berlin,
which was a trial to George Dillwyn.
Christopher Reckefus, and the Friends who had been here some days from Minden,
came to see us, as we expected soon to leave.
He has passed through many trials for his testimony,
and lately had a child taken up out of its grave, in his garden, by the priest,
after it had been buried nearly six months.
The priest had it interred in their burying-ground,
and then seized upon Christopher`'s property for his dues.

"`A number of our friends having come to see us,
the house was so full that all could not sit down; a solemn covering prevailing,
Friends were made near to each other in the love of Christ.
It is a special day of renewed visitation to many, both youth and others:
indeed we are bound to them and kept here in a singular manner.
After the opportunity, some young women had a conference with a few of us,
as to the means of giving them employment in spinning, weaving, etc.,
that would afford them a more decent living and less exposure in the fields.
Women in this country are obliged to labor very hard, both in and out of doors,
for about one shilling a day, Pennsylvania currency,
and about three shillings if they find themselves.
The men get about two shillings and six-pence per week, and their diet and lodging,
both which in a general way are very poor,
and do not probably cost more than half a dollar.

"`27th. Sat with the company of Friends in the capacity of a Monthly Meeting,
which held four hours, was a solid time, and I hope our being with them was of some use.

"`28th. Attended their week-day meeting, which was large,
and through renewed mercy a tendering parting season.

"`29th. Almost all the Friends came to take leave of us.
We sat down with them about an hour, and it proved a favored contriting season;
having been nearly united to them,
it was one of the most affectionate partings I ever experienced;
many of the dear young people held us by the hand, and would scarcely let us go,
and testified their affection by many tears.
We reached Mela about dusk and had entertainment at a good inn;
this is the territory of the bishop of Hildesheim, mostly Roman Catholics.

"`30th. Got to Hildesheim to breakfast;
gave to the landlady and her son (Protestants) some books.
Hildesheim is a considerable city, surrounded by ramparts,
is the residence and capital of the bishop`'s dominions,
in which the Lutherans are tolerated and have one place of worship:
the city may contain fifteen thousand inhabitants.
Rode to Brunswick, forty-two miles, and lodged at an inn where we had good accommodations.
The country we passed through is thickly set with villages,
the land excellent and the roads good,
with many crosses and crucifixes on the sides of them.

"`Tenth month 1st. The Duke has built a noble orphan-house here;
the city may contain thirty thousand inhabitants,
and abundance of trade is carried on during the fairs.
The Duke not being at home, we had a desire to see the Duchess.
The palace is large, in the form of a square, with one side open.
After waiting some time,
we were ushered into a large room;--she seemed pleased to see us,
conversed freely on various subjects,
told us our people were as much attached to her brother, the king of England,
as any of his subjects; and if all were like us,
there would be no troubles or wars in the world.
We told her our business in Germany,
and she asked if we found people of our profession there?
We mentioned our friends at Pyrmont,
and that we found religious and awakened people in almost every place.
As we were going to Berlin,
we asked if it were probable we could have an interview with
the king (of Prussia,) whether he was a man easy of access?
She said yes; but he was opposed to them on political principles.
We told her our religious concern for the people was, that they might come unto Christ,
and find rest in him.
Presented her with Penn`'s No Cross, No Crown, in French, which she received kindly,
and wanted to know the meaning of the title,
as she supposed no person could pass through life without their crosses.
We told her the saying of Christ, '`If any man will be my disciple,`' etc.,
and that the cross here spoken of was not anything outward,
or the common disappointments of life, neither such as were made of wood,
stone or costly metals, but an inward and daily cross to our corrupt inclinations;
a being crucified to sin and worldly vanities.
She said she now understood the title of the book, and would read it with pleasure.
Before we parted, I mentioned the words of our Saviour to a beloved female.
'`Mary hath chosen the good part,`' etc.,
that crowns and dignities were perishing and transitory things;
but if those who wore them were concerned to rule well
and fill up their duty as good stewards,
they would receive a crown of unfading glory in the world to come.
She thanked me, wished us a good journey, and we parted with satisfaction of mind.
Afterwards we visited some religious people, and gave them some books:
they appeared to be measurably enlightened men.
Passing through a fine country, a city called Kings-Lutter, several villages,
etc. we arrived at Helmstead.

"`First-day, Tenth month 2nd. Walked round the town,--the people gazed much at us;
and when we asked what place of worship they were flocking to in such numbers,
they told us the Lutheran; but supposing us to be Catholics,
said our Church was outside the gates.
Some asked if we were Brabanters: when we told them we were not, nor Frenchmen,
nor Catholics, nor Lutherans, but of a different religion, and came from America,
they looked surprised, and said it was very far off.
Waited on professor Beireis, who is esteemed a very learned man.
We gave him Barclay`'s Apology in Latin, which he received respectfully,
said he read everything, and was visited by kings and princes,
whom he should now have an opportunity of informing of our principles.
He remarked, that he was glad to have the company of religious people,
and willing to do us any service in his power;
but said there were no separatists in Helmstead.
Finding this to be the case, we took an early dinner, left some books at the inn,
and went off for Magdeburg, thirty-six miles,
Passed through a very fine country and many villages:
three-fourths of the ground was covered with wheat and rye stubble, the roads good,
and horses excellent.
It is the greatest grain country which any of us have ever seen,
and the people raise great numbers of sheep and geese.
Arrived after dark at the gates of Magdeburg, where we were examined,
and all our trunks and packages searched.
A little further on, an officer stopped us, took our names and places of residence,
and sent a soldier to conduct us to the inn;
here again the landlord took our names and places of abode,
in a book kept for the purpose,
where the names of all strangers that have lodged here for several years are to be seen.
The landlord and waiters were obliging, and the accommodations good.

"`Tenth month, 3rd. Walked round the town, which is handsome, cleaner,
and better built than most we have passed through in Germany,
and is well lighted with lamps.
We excited the curiosity of the people, who looked at us as far as they could see us,
yet there was nothing like scoffing or ridicule.
We were informed of a number of religious people, who met in companies once a week,
in different parts of the city, to sing, tell their religious experiences, etc.;
and one of the companies being to meet this evening,
we inquired whether we could be admitted to sit with them, which they agreed to,
and appointed to meet at six o`'clock.
We found about twenty-five men, but no women.
We kept our hats on, giving them our reasons,
with which they appeared satisfied--they had a short
hymn at this time on account of our being present,
after which the tutor made a prayer.
David Sands then spoke, and was enlarged on many subjects; during which, many coming in,
the room was crowded, and in the entry there were many women;
in the whole there were about sixty or seventy persons.
My mind being drawn to prayer, they all kneeled, and it appeared to be a solemn time;
they seemed to be filled with love toward us, and expressed their thankfulness.
We mentioned our desire to have a more general collection of the seeking people,
in Madgeburg, both men and women, as we felt much love in our hearts to them.
They said their situation required such a matter to be well considered,
and to be moved in with much caution and wisdom,
on account of the jealousy of the priests and government.
Poor creatures, they are like so many Nicodemuses,
and therefore much sympathy is due to them, when all things are considered.
On parting with them, they embraced us with many prayers for our preservation,
and thanks to the Author of all good, who had sent us among them.
They do not appear to have any idea of our Society,
and perhaps have never heard of the name of Quaker; indeed,
we seem now to be beyond where our religious Society is known,
and on this account I feel some hesitation in handing them books
which hold up a name given us only in derision by our enemies,
and not our acknowledged title.
The river Elbe affords a communication between
this city and Hamburg by flat-bottom boats:
in the river are a number of curious grist-mills, that float upon large boats,
and are worked by the stream.

"`An honest-hearted simple friend, who was with us yesterday,
and who had a very high conceit of a man that had made
these people believe he possessed extraordinary powers,
came to see us,
reflected on what we said in the meeting, and appears now to be much changed.
Some of us accompanied him home, where this wonderful man was,
and also another person who had visited us yesterday.
The magician put on an air of consequence,
and with great rapidity went over a number of incoherent expressions, without any sense,
which his two disciples seemed to catch with great eagerness,
and thought he was very deep, because they could not understand him.
After slipping in a few expressions, which was hard to do,
Lewis Seebohm told him we were in much doubt about his schemes,
and that if he was possessed of the power he pretended to,
he would not have occasion to live at the expense of other people, for several months,
as he had done.
Finally, we told the people that the things he had promised them,
would never be brought to pass, they were only deceiving themselves with a golden dream.
This touched him to the quick, and he flew out of the door of the room instantly.
Lewis called to him, but he did not return;
so the false prophet was manifested before several witnesses,
and they convinced of the delusion; their hopes of receiving a quantity of gold,
which he had said the angels were to bring him, and in which they were to be sharers,
were at an end.
They thought it was worth while for us to come to Magdeburg,
if it were only to break up this delusion, for he had many disciples upon whom he lived,
and had so done for a long time.
I notice the occurrence, as an instance how far the credulity of people is carried,
especially in Germany.
Those two persons were simple, well-meaning, religious men,
and one of them had separated from all outward forms of worship, for several years.

"`We visited a few families to satisfaction;
the people look upon us with very friendly countenances in this city, and speak kindly;
and there is something more courteous and engaging in their manners,
than any other town we have been in.
Our two friendly visitors were with us this evening,
and gave us a full opportunity of explaining our principles and doctrines;
they heard us with great attention, and appeared to be sensible men,
saying that the longer they were with us, the more they loved us:
we gave them some books, and parted in much affection.

"`5th. At the best inns in Germany, the charges are very high,
but they are remarkably decent and quiet.
We rode through a beautiful country, about three miles,
when it became more sandy and barren;
and arrived at Brandenburg about nine o`'clock at night.
The king of Prussia suffers no smoking in the streets of the cities or villages,
under a penalty of fifty dollars,
or being sent for some months to work at the fortifications;
this is trying to the Germans.
Here is a fine river, about one hundred yards wide, which runs into the Elbe,
and goes up to Berlin, with a number of good mills upon it.
There are many people in this place, who,
though not in strict communion with the Moravians, seem much inclined to them.
That society has a town and large congregation in Saxony, perhaps fifteen miles off.

"`6th. Lewis Seebohm found a man of a religious character,
who said there were upwards of forty men and women,
who met at times in his house to edify one another.
Lewis asked if we could have an opportunity with them before we left Brandenburg;
he thought it would be acceptable, but would let us know soon.
A pious young man came to our inn,
and invited us to the house where they met at four o`'clock, which,
though some of our company had gone out, I consented to.
At four o`'clock we all went, and found several religious people,
who received us in a very loving manner, said they were a people seeking God,
and were very willing to collect at six o`'clock in the evening,
to give us an opportunity of opening our minds to them.
They were rejoiced to find that we were come to Germany on so important an occasion;
said the love of God was great and unsearchable,
that He should thus send us among them at the risk of our lives,
and enable us to leave all for his sake; and they shed tears of gladness.
At six we went,
and found forty or more gathered in an upper chamber--
the man of the house gave out a short hymn,
which they sung; he then told them where we came from,
and our concern to visit this land, and desired they might all retire in their minds,
and be attentive to what the Lord might give us to say among them.
After a time of solemn silence,
David Sands and myself were severally opened in testimony,
and the meeting ended in prayer.
They were very solid, and most of them much tendered,
seemed scarcely able to part with us, and expressed with many tears,
their thankfulness to the Father of mercies for sending us; we all thought it a favored,
contriting season.
Surely the Lord is preparing a people in this land,
who shall not be afraid to own him and his testimonies, in his own time.
We left them a number of books.

"`7th. Just as we were setting off for Potsdam, a good-looking woman came up,
and said in an affectionate manner, we must not go until we had seen her father, who,
being out of town last evening, had not seen us,
but was not easy to let us go without requesting our company.
We went to see the old man, who is about seventy years of age:
he had been the first promoter of the meetings of these pious people,
and appeared like an Israelite indeed.
Some religious communication being offered to him and the family, they were much broken,
and were made near to us in the covenant of love and life.
O! the simplicity of these dear people! they parted from us with regret,
and said those who were with us last evening at meeting
would not forget us as long as they lived.
The people everywhere in Prussia are astonished when we tell them we are from America,
and entertain us with the strange ideas they have formed respecting the country.
They suppose our homes are quite on the other side of the world--that
when in our own country our feet were toward theirs,
and asked if the sun rose and set as it does here:
they lift up their hands and are astonished that we should come so far from home,
and we can scarcely convince them that we have no lucrative motives.

"`On arriving at Potsdam, we underwent a strict scrutiny, had our names taken,
and a soldier sent to see us to the inn,
where another officer took our names and examined all our trunks.
They not only take our names as we pass through every town,
but also the place we last came from, our several places of residence,
our business in this country and the character we travel in, whether officers, merchants,
etc., to all which we have learned to answer generally,
that we are on a visit and travel as '`particulars,`' a word they have taught us,
which mostly satisfies them.
This town is pretty large: the river Havel, which leads into the Elbe,
affords them a water communication with Hamburg, two hundred and thirty miles.
The streets are wide, the houses large,
the palace and many other buildings being very spacious,
have an appearance of much grandeur,
and it is by far the most magnificent city we have seen.

"`8th. The new palace and the buildings attached to it,
far exceed anything to be seen in England,
as well as the ideas I had formed by reading of human pomp and grandeur.
As a description would be foreign to our principal concern,
it will be wisdom in us to turn our minds from such things, and stay them upon God,
who alone can strengthen us to finish the important
work He has required us to be engaged in,
to his own praise and the peace of our minds.
The more those who love the humble path of Jesus,
see of the greatness and glory of this world, and how empty and vain it is,
the more they will be constrained to draw nigh unto him,
who is their dignity and their riches, and will finally be their everlasting glory.
Thus I hope it was with us, in turning away from these sumptuous palaces.
The road to Berlin is through a poor sandy soil,
much of which is covered with scrubby pines.
It is paved all the way, and lined on each side with Lornbardy poplars;
we passed through two or three villages, and entered Berlin at the Brandenburg gate,
which is lately built, and must strike every stranger with its magnificence:
there we were again examined by a polite young officer,
who sent a soldier with us to the Inspector`'s office, where,
after a good deal of persuasion,
they consented to examine our trunks and bags this evening,
which at first they did not seem disposed to, intending to lock them up until tomorrow.
This took up so much time, that we did not get to the inn until it was quite dark.

"`First-day morning, 9th. Lewis Seebohm went out to seek for some religious characters,
and while absent, two Jews came into our rooms, one after the other,
wanting to trade with us, either to buy, sell, or exchange money.
I mention this, because in all the large towns,
strangers will find such people exceedingly troublesome,
for custom seems to have given them, and also women with fruit and trinkets,
and other persons of that class, liberty to come into the inns, open your room doors,
etc., and impose themselves upon you when they please; and so importunate are they,
that it is difficult to get rid of them.
Generally, the people are respectful and complaisant,
especially those who have had a tolerable education.
In our retirement,
our minds having been much exercised during the morning with a feeling of discouragement,
the spirit of prayer was granted,
and through renewed mercy we were strengthened to put our confidence in that
gracious Arm that had hitherto preserved us in this trying field of labor,
and enabled us to discharge our duty, so as to leave every place so far peacefully.
Two of our company going out to seek for religious persons,
brought back some of the books we had left at Magdeburg, in the hands of +++_______+++,
the tutor in the college there, who appeared very kind when we parted,
and gave us a letter, speaking favorably of us to a person here, named Herman.
But it appeared by a counter letter, which was read to Lewis Seebohm,
that though he acknowledged we were religious men,
and had preached the Gospel to them to their comfort and satisfaction,
yet upon reading our books, he says he finds we hold erroneous opinions,
reject baptism and the supper, and do not hold the Scriptures to be the Word of God;
so that he could not unite with us,
and had therefore sent the books with this information to Herman,
requesting him to return them to us.
This brought us under additional exercise and suffering from an unexpected quarter.
Herman being a leading man among those who meet
for the edification of each other in this place,
who are pretty numerous,
we did not doubt but he would spread sentiments among them to our prejudice,
and we feared our way would be quite shut up in Berlin;
for the subjects of the letter had taken a deep hold on his mind.
Lewis had much conversation with him, which appeared to soften him in some degree;
but not to convince him.

"`The tutor at Magdeburg was a man of learning and of some influence,
but evidently puffed up with his own importance,
and could not submit to be deprived of it by adopting
the simplicity of the doctrines of Truth;
but if he had been a man of candor, he would have replied to us when we were present,
as we had much conversation,
particularly on the points he lays most stress upon in his second letter to Herman,
viz. the Holy Scriptures, our views of which we fully explained to him at that time,
apparently to his satisfaction;
so that after it he wrote of his own accord our letter of recommendation,
embraced us and parted from us with every token of brotherly love.
We left at Magdeburg a number of books besides those sent back,
which we hope will still be of use to a number of valuable seeking persons there,
who were made near to us.
Our present situation at Berlin is as trying as any I was ever in.
In addition to the exercise we are under,
in feeling the darkness and gross depravity of many of the inhabitants,
it appears as though we should obtain but little
intercourse with those who are religiously inclined.
We sat together in a low, discouraged state, almost ready to wish ourselves away,
but concluded that here we must stay, endeavor to clear ourselves,
and contend for the faith as ability might be given, through suffering.
While thus engaged, a religious man whom Lewis had seen in the morning,
came to invite us to their meeting at seven o`'clock.
He said he had acquainted several, and he believed we should be kindly received;
but we felt most easy to decline it at present.
We continued thoughtful where it would end,
as we were among strangers with whose laws we were unacquainted,
and things might spread among them to our disadvantage;
yet a secret confidence was afforded, that we were under the protection and care of Him,
whose cause we were drawn here to espouse; and that if we abode in patience,
He would make way for us; yet it was a deeply trying, and almost a sleepless night.

"`10th. Conversed with several religious characters,
who promised us a visit in the evening.
Berlin is a very large and populous city,
said to contain one hundred and fifty thousand inhabitants, including the soldiery.
There are between three and four thousand Jews; thirty-three places of worship,
of which the greater part are Lutherans; but the Calvinists, Moravians, Roman Catholics,
and Jews, have also their houses for public worship.
There are several large palaces for the king, queen, and royal family, which,
as well as the public buildings, and many private houses, bridges, etc.,
are crowded with statuary.
The streets are wide, and the houses generally the largest of any place we have been in;
and taking it altogether, the city is superior in grandeur, perhaps,
to most places in Europe.
Many of the inhabitants are rich, and a considerable number of coaches are kept.

"`11th. In the evening six religious men visited us, one of whom was a man of rank;
they appeared glad to see us,
and asked us many questions concerning our faith and religious opinions,
which we answered to their satisfaction,
and we hoped the three hours we were together were profitably spent.
Near the close of the interview, quietness prevailing, some religious service ensued;
and after prayer, during which they all kneeled, we parted.
This gave us encouragement, and a hope that it would be introductory to further service;
they said the letter from the tutor at Magdeburg had not
prejudiced them--they owned us as brothers in Christ,
and thought he did not do right.
In the evening two religious young men came to see us,
who appeared very loving and tender.
They were rejoiced to see brethren who had taken so long a journey for the Gospel sake,
and said there were great numbers of awakened minds in Berlin;
but they were scattered over the town, and met in separate companies;
that a man named Drewits held meetings at his house, to which many,
especially young people, resorted; and that they were now going thither,
and would conduct us if we thought proper.
Apprehending some persons might call to see us,
it was concluded that Lewis Seebohm and David Sands should go,
and the rest of us continue in our chambers.
About nine o`'clock they returned, having attended the meeting;
the man preached and prayed, which was the common practice, but there was no singing.
David Sands had an opportunity of speaking before they broke up, to his satisfaction,
though they were shy of them at first entering the room, seeing them keep their hats on;
yet they parted lovingly: there were about thirty men and women.
We make our way by inches in this place, the people being very wary,
afraid of being interrupted by the authorities, and meeting with suffering,
as some have heretofore; so that our trials are great;
yet we do not doubt that our being here is in our heavenly Master`'s appointment,
and desire to abide in patience all his appointed time.

"`Fourth-day, 12th. Several of the friendly people visited us;
and we proposed a meeting in the evening, which was agreeable to them.
We took a walk round the city, the magnificence of which is surprising;
many of the houses are from one hundred to one hundred and fifty feet front,
and ornamented in a beautiful manner;
it being the residence of many of the great officers of the kingdom,
both civil and military; and one thing is remarkable, we have not seen a beggar,
and but few miserable looking people in the streets, though many are low in the world;
but the employment they receive from the army and grandees of the court,
with the many charitable institutions, supply all their real wants.
In the evening at six, between thirty and forty persons collected in our rooms,
which are convenient and retired; among them were two parsons, one a Lutheran,
the other a Calvinist.
I had conversation with one before the people were all gathered,
and found him possessed of some lovely and valuable traits.
The company being gathered into silence, a solemnity covered us which was precious,
and we were favored with the spirit of prayer;
after which David Sands and myself were engaged in testimony: the people were solid,
and through Divine mercy it proved a satisfactory season to us and them,
as far as appeared.
They all took leave of us in a very affectionate manner,
and some stayed late in religious conversation.
A pious young woman, in particular, took our attention,
who continued for some time after the meeting was over,
lifting up her eyes and pouring forth pious
ejaculations and praises to the Father of mercies,
who had thus favored us together.
Here we had fresh occasion to acknowledge the continued goodness of God,
who thus unexpectedly made way for us: '`Surely there is no rock like unto God.`'

"`13th. We felt our minds drawn to visit Freyenwalde,
a town about thirty-five miles north-east of Berlin,
where the Koenig`'s Rath Albinus had retired,
after laying down his lucrative office for conscience sake.
We arrived there in the evening,
and finding a number of awakened people lived in the place,
our friend Albinus proposed to collect as many as he could in about an hour,
in the house where he boarded.
We went there at the time appointed, and about twelve persons came in,
with whom we had a solid meeting, in which the Lord favored with matter and utterance,
we believed suited to the states of this tender people,
and we parted in much love and brokenness of spirit.
Albinus accompanied us to the inn, after ten o`'clock, where he stayed and supped;
his countenance and spirit bespoke him to be a brother beloved in Christ.
He is a single man, about forty years of age, of good education and polished manners.
He proposed taking a seat in our wagon to accompany us to Berlin,
which was very agreeable to us.

"`14th. The woman of the house where the meeting was held last night,
having requested us to visit her husband, who was sick in his chamber,
and could not have the benefit of the meeting, we breakfasted early,
and had a precious opportunity with him,
his amiable tender-spirited wife and our friend Albinus in the chamber,
and parted from them and divers others who were at meeting last evening,
in near affection and with their prayers.
On the way to Berlin, at the place where we dined and changed horses,
I accidentally fell in with the president of the Chamber of Justice at Berlin,
who conversed with much freedom respecting America,
and was particularly desirous of information on the
subject of our abolishing corporal punishments,
with which he seemed pleased;
but had doubts whether it would answer the desirable end in view.
Travelling in a convenient wagon with our friend Albinus,
gave an opportunity of much free religious conversation, for which his mind was prepared,
and he made several very pertinent remarks and inquiries; he is,
by the teaching of Divine Grace on his own mind, nearly united with us in principle,
and earnestly endeavoring to conform in practice; though he sees plainly, as we do also,
that the cross will be great if he is altogether faithful to the light he has received.
If he is favored to stand fast on the foundation,
of which we do not at present see any room to doubt,
he may be made an instrument of much good in this country;
though it undoubtedly will be through suffering.

"`We arrived at Berlin about seven o`'clock,
where we were subjected to an examination of our trunks; this is a trying circumstance,
and occasions great detention to weary travellers,
but must be submitted to at every fortified town, though it may be twice in a day.
Albinus took up his lodgings with us at the inn where we stayed
before--the landlord and servants received us gladly.
Some conversation taking place respecting the mode of cutting the hair and powdering it,
common here even among the religious people,
it appeared that he had felt himself restrained from the general custom;
we sympathize with him, and have strong desires he may be favored to go forward,
step by step.

"`15th. Lewis Seebohm and Albinus visited several religious people,
and a minister named Jenike, who was at our meeting on the twelfth.
He holds an assembly every seventh-day evening in a large room at his house,
to which many young people come.
Lewis queried, whether we could not attend and hold the meeting in our way.
He behaved kindly, but informed our friend,
that he found by the letter Herman had received from Magdeburg,
that we did not own water baptism nor the supper;
and that our preaching tended to draw the people from a dependence on their teachers;
that it had already been under consideration among the ruling clergy,
to apply to the magistrates to send us out of the city;
though for his own part he should have nothing against our coming to the meeting,
but it would give great offence to his superiors;
said he had been well satisfied and edified the evening he was at our meeting,
and wished us well.

"`Concluding to hold a meeting in our chambers tomorrow evening,
we wrote a note to Jenike,
requesting he would give the people notice who assembled at his house this evening;
which he did according to his promise; but told them at the same time,
that we were no doubt good men in our way;
yet we held some doctrines tending to lay waste their ordinances,
and to draw people from their pastors,
and that the superior clergy had already taken into consideration to
apply to the magistrates to send us out of the city.
Our friend +++_______+++, being present, vindicated us,
and came from thence with the information.
At the request of some, we met them at six this evening,
and had some discourse respecting baptism and the supper.
They were men of talents, and furnished with arguments in support of their opinions,
equal to most who attempt it; a small degree of warmth
appeared at one time in the course of disputation,
for they were very zealous, religious men,
and were very loath to give up their strong holds; but that soon subsided,
and much brotherly love prevailed;
and though they did not acknowledge themselves fully convinced of our doctrines,
we had reason to believe the opportunity had been blessed to them;
several others coming in, the evening was closed in prayer,
and we parted in a friendly manner,
having fresh occasion to say the Lord hath not forsaken us.

"`First-day, 16th. Held a meeting in our chamber,
with a few of the most serious of our friends here, among whom was secretary Hoyer,
one of those who were with us last night; it proved,
through the renewing of our heavenly Father`'s love, a time of refreshment and comfort.
Dined by invitation with Johann Christopher Henefusz;
and several other religious people being present, there was some service in the ministry.
The family were made very near to us in the love of Christ.
A young woman of good countenance and innocent manners,
daughter of one who dined with us, came in; she had not seen us before,
but on hearing her father speak of us,
she sent a book with a collection of religious scraps in it, to our lodgings,
requesting us to put our names in it, and each to add a text of Scripture,
such as might occur to us for her instruction; which we did;
this appears to be a practice among the religious people here.
In the evening, the people began to gather an hour before the appointed time,
many crowded into the meeting whom we had never seen before, so that our four rooms,
which communicated with each other, were soon filled;
some who took an account of the number, thought there was not much short of two hundred,
divers of whom were people of rank in the world.
Our minds were much humbled in the prospect of the necessity of Holy direction,
that Truth might not suffer among this discerning people.
Our heavenly Father, who is graciously pleased to be with those who trust in him,
was in a very remarkable manner, mouth and wisdom, tongue and utterance to us;
an uncommon solemnity prevailed over the assembly,
such as I have seldom seen in my own country amongst a mixed multitude of strangers,
and great brokenness was among them.
Although the meeting continued three hours,
and many had to stand in a crowded situation the whole time,
yet nothing like restlessness appeared; we rejoiced in the hope,
that Truth was in dominion over all; for which favor,
the glory and the praise was rendered unto God, to whom only it is due.
The Lord causes all things to work together for good to them that fear him.
We had reason to believe that this meeting was increased even
by the opposition we had met with from Herman and others.

"`17th. Many of the tender people who were at meeting yesterday, visited us,
and acknowledged their unity and satisfaction.
A young man also came with some money, which his mother desired we would accept,
towards bearing our expenses: we thanked them for their kind intention,
but could not receive it,
and it gave us an opportunity of explaining ourselves to the
satisfaction of several respecting the free gift of Gospel ministry.
Another poor woman sent us a pot of honey and some cakes,
and many appeared ready to do us any service in their power,
which manifestations of their love for us, were grateful and encouraging.
A Roman Catholic hearing there were some priests arrived from a foreign country,
came to see us, and inquired if we received the confessions of the people:
we told him it was best to confess his sins to God,
who would forgive him upon repentance; and he went away satisfied.
At the request of the people, we gave away almost all the books in our possession,
and those sent back from Magdeburg answered a good purpose.
Several parents brought their children, desiring we would give them some counsel;
and in many ways they expressed their attachment to us.
Truly the Lord has a tender-hearted people in this place,
whom he is gathering to the spirituality of his kingdom.
We visited an ancient woman who had been many years helpless from palsy;
the people of the house had been at our meeting, and several neighbors coming in,
we had a truly refreshing, tendering opportunity,
which we trust will not soon be forgotten by some of them.
At our return found several visitors had taken possession of our room,
to whom we had some religious communication.
In the evening there were several with us,
some of them men of considerable rank in the world, of enlarged understanding,
and measurably enlightened to see the spirituality of Christ`'s day;
they rejoiced to see us on our present errand, and say the Lord`'s hand is in it.

"`18th. We are here kept day after day, through the Grace that is mercifully granted us,
without murmuring.
The Lord has many sheep, whom in his own time he will gather,
and establish upon that foundation, which the fear of man will not be able to overthrow.
We were united in appointing another meeting at six in the evening;
and though the time was short, and the seeking people much scattered,
yet upwards of one hundred attended with great readiness,
many of whom we had not seen before:
and what is remarkable and different from any other places is,
that the zeal of these people occasions them to
be mostly collected before the hour appointed.
The time of silence was solemn, and David Sands appeared largely in the ministry,
being much favored; after which, having travelled with him in near unity,
I felt excused from any addition,
and the meeting ended in prayer and praises to our heavenly Helper.
The people took leave of us in great brokenness of spirit,
with many tears and prayers for our preservation;
so that we are made thankful that Truth is making its way in many minds,
although there are not a few adversaries, who, we fear, are watching over us for evil.
Experience teaches that where Truth is gaining in the hearts of people,
Satan raises up enemies to it.

"`19th. In the morning we had some hopes we might have left Berlin in the afternoon;
but many of the people coming in,
we were engaged with them until dinner-time in religious conversation.
A Major Marconnay, who had been a man of note, and held an office under the king,
had been several times to visit us, and attended the meeting last night;
and now came with a desire to open to us the religious exercises of his mind.
He related how he had sought the Truth among a variety of professors,
and had not been satisfied, though divers of them had held up high pretensions;
at length he had left all, laid down his office and lived a retired life;
but he had found that among us, which he never was acquainted with before; saying,
he believed we were sent there in the will of God, for his and others`' help.
He had a few questions to ask us, which he did in a very tender frame,
and was much broken with the answers that were given him;
and after some religious communication and prayer, we parted; his mind being relieved,
and we hope convinced of the way of Truth as professed by us,
and with desires to walk in it.

"`Time will not admit of particularizing our
almost continual engagements in this great city,
where we find a large number of seeking souls, and every day brings new ones to see us;
who, while they are honestly striving to find the new and living way,
are very various in their opinions, but all appear glad of an interview with us,
and open their minds with great freedom.
Some have separated themselves from all outward ceremonies and modes of worship,
and walk alone.
Our being with them brings them into acquaintance with each other,
and we do not yet find ourselves easy to go away.
Towards evening we proposed another meeting to be at six o`'clock; the notice was short,
but about one hundred and twenty came.
Our minds were engaged to enlarge upon most of our fundamental doctrines,
which they received with great stillness and attention;
some staying a little after the meeting, professed their full unity with the doctrines,
and I believe received the word with gladness,
as it corresponded with what they had secretly felt for years.
They took a solemn leave of us in tears, recommending us to the heavenly Shepherd,
and requested our prayers when we were separated from each other.
One young woman of noble countenance was much broken,
and seemed to part with great reluctance.
Dear David Sands and myself, on comparing our sense and feelings at different times,
were united in belief that we never were among
people to whom the love of God more richly flowed,
than to many in this place,
nor any that were made more near to us in the love and life of Christ.
Our whole company (the travellers) were frequently much broken among them,
and led to marvel at the goodness of our heavenly Father,
who had thus unexpectedly been with us in this distant and strange place;
and more especially so,
as we were sensible that the priests and worldly-wise professors were much alarmed,
and there was every reason to suppose they would interrupt and probably persecute us.
Yet we were strengthened to hold our meetings and distribute our books openly;
and though clouds seemed to gather about us at times,
the Lord was graciously pleased to dispel them all,
and great freedom we had in our labors among them,
to our encouragement and holy confidence in Him that puts forth and goes before.
Though many in this great city are very dissolute,
and have proceeded to great lengths in pride and vanity,
the Lord hath many sheep and lambs, whom if they keep steadfast,
he will doubtless bring home to his fold of rest in his own way and time,
and to him we commend them at present.
Our friend Lewis Seebohm being so devoted to the cause we are engaged in,
and clear in our testimonies, is able to unite with us in our services,
and to deliver what we offer to the people, with so much energy and quickness,
that nothing seems to be lost by his interpretation;
and though we cannot but feel for him in long meetings, his frame not being strong,
yet it is cause of thankfulness that he is
enabled to go through it with great cheerfulness.

"`20th. Several came to take leave of us, and a tender parting it was.
Our kind landlord and all his family, children, servants, etc., embraced us,
and with many tears manifested the place we had in their minds:
they have been very kind and attentive to us all the time of our stay,
have forwarded our meetings with cheerfulness, preparing seats, showing up the people,
etc., so that we believe there was a Divine hand in sending us to this house.

"`Left Berlin at ten o`'clock, after visiting the mayor,
and leaving with him a note and a copy of Barclay`'s Apology for the king,
whom we had a desire to visit; but he being only a short time in the city,
we could not obtain an interview, and were easy to go on for Brandenburg.
We were obliged, in consequence of the road being very sandy,
to put up nine miles short of this place, at a poor inn, where we found several Jews,
who looked like pitiable objects, dressed little better than the American Indians,
and little, if any, more polished in their manners.
We were informed that great numbers of the poor
Polanders were driven through this place like cattle,
having very little clothing, and some clad with skins of beasts;
their living only the coarsest rye bread and water;
and in this condition they were taking them to the army.
O the miseries of war!
