== Chapter VI.

[.chapter-synopsis]
* Dublin
* Poverty and wretchedness
* Limerick
* Fertile land
* Cork
* Foundlings
* Clonmel
* Rich Friends
* St. Patrick`'s Well
* Affecting partings
* Widow Usher and daughters
* Abraham Shackleton and his notions
* Arrival in Wales
* Manners and habits
* Bristol
* Bath
* Hannah More
* William Wilberforce
* London
* Norwich
* Newspaper commendations
* Benjamin West
* Visit to the King, Queen, and Princesses
* Meetings in London
* War Taxes
* Mary Fletcher
* Shrewsbury
* Wrexham
* Opposition and meeting at Ormskirk
* Liverpool
* Reenters Wales
* Large meetings
* Sails for Ireland
* Dublin Yearly Meeting
* Defection in fundamental principles
* Violations of the testimony against war
* Arduous labor to counteract unsound doctrine
* Return to England
* Birmingham
* Soup-houses
* London Yearly Meeting
* Long walks to Yearly Meeting
* Interviews at Newgate
* Difficulty of obtaining a passage home
* Murders by the Catholics in Ireland
* Embarks at Bristol for America
* Detention at Cork
* Notes of the voyage
* Arrival at home
* Sickness and death

"`Dublin is certainly a very fine city; many of the streets are wide and elegantly built,
perhaps Sackville street is not excelled by many, if any, in Europe;
it is one hundred and twenty feet wide--that and
some others have lamps before every door;
indeed, it is the best lighted city I have seen.
Many of the houses are four or five stories high,
of pretty good brick--the best streets uniform and straight, with good flagged foot-ways.
The public buildings are grand, exceeding those of London, especially the custom-house,
college, parliament-house, exchange, etc

"`The trade to Dublin is not great for its size; perhaps one hundred vessels are in port,
the greater part of which are colliers.
The city may contain two hundred and fifty thousand inhabitants,
many of whom roll in luxury;
but there is no comparison that I have seen in Europe
for wretched habitations in the alleys and back streets,
which are filled with human beings, who, in their present filthy mode of living,
nakedness, depravity and morals, are really the most affecting sight to a humane,
feeling mind, that perhaps any city in the world can exhibit:
many of them are exceedingly hurt by drinking the pernicious spirits made of malt, rye,
etc., called whiskey, of which an immense quantity is distilled in Ireland.
Another source of misery is, the numerous lottery offices in the city,
which make a splendid appearance after candle-light;
in some streets there are many whose doors are continually surrounded by poor,
half-naked people, who lay out their little all, which, perhaps, they have begged,
in the hope of gaining by their chance;
but the keepers of these offices have made such nice calculations upon chances,
that they are sure to gain.
This is noted as being a great source of misery to thousands of poor,
even such as swarm about the streets begging,
who are induced to venture their small pittances, in hopes of obtaining more,
in which they are often greatly deceived;
and if one in a great many should gain something, it serves to keep up the delusion.
In the present state of things,
it does not appear probable but that Dublin will continue to harbor
from twenty to forty thousand miserable beings as it now does,
until some employment can be found for them, and they, by some means,
be brought to labor for their own support.
Indeed, in all parts of the kingdom, this class more or less abounds.

"`12th. Being the Monthly Meeting, we produced our certificates;
and Friends thinking it would be a satisfaction to the women`'s meeting to bear them,
William Farrer and myself, with Thomas Fayle, went in,
and through renewed mercy had a tendering time among them.
On lying down to rest, it was clear in my mind,
that now it would be right to leave Dublin.

"`13th. Arrived at Rathangan in the afternoon,
and found Joshua Wilson`'s carriage waiting for us at the side of the canal;
we went to his house, about a mile from Rathangan.

"`14th. Breakfasted with our friend Jane Watson, and went to their meeting,
where a number of people attended, and it was thought to be a solid, good meeting;
Jane said it was a comfort to her.

"`15th. Set off for Mountmellick, the weather being wet and stormy;
before we got to Portarlington, a town of some note,
principally inhabited by the descendants of the French Hugenots,
who were banished out of the kingdom, one of the felloes of a wheel of our chaise broke;
we walked into the town and hired a post-chaise,
but before we got a mile from thence our post-chaise broke down in a very dirty place,
Jane Watson, William Farrer and myself in it.
It rained very fast, and being invited, we went into a miserable cabin with little fire,
where lived two wretched families with several children, to whom we gave some money,
and they poured forth a profusion of blessings as usual.
Most of the poor being Roman Catholics, their benedictions are often very singular.
We had to stay a considerable time before another chaise could be procured,
and were very cold, though well clad;
yet most of the family were without shoos or stockings:
I thought we ought not to complain, but be thankful.
When we entered our third chaise, it still raining hard and the waters much raised,
we were in some danger; but by going one mile round we arrived safely in the evening,
and were kindly received by J. Pim and wife.
Mary Ridgway being there waiting for us, we were mutually glad to see each other.

"`16th. Visited the provincial school for the province of Leinster,
consisting of about fifty scholars, healthy and very decent;
we had a tendering time with them and their tutors;
and also visited the boarding school for girls, wherein they were much broken into tears.
The town of Mountmellick is not large,
consisting of only one street about half a mile long.

"`First-day, 17th. Attended their meeting, consisting only of Friends;
had a few words to say at the close, which being of a very singular kind,
I was glad that Mary Ridgway and Jane Watson could
acknowledge their great satisfaction and unity with it,^
footnote:[It is cause of admiration and humbling acknowledgment, that Divine influence,
the only real qualification for Gospel ministry,
should thus preserve and guide the messengers of
the Lord`'s love and mercy to the people,
as that they should in their labors be led in the same line,
and give them to feel and expose defection,
however secretly held or glossed over with very plausible pretences,
even in some of the foremost rank.
Our friend Nicholas Wain, when on a visit to this nation, in the year 1795,
without any previous information, opened in the Province Meeting at this place,
an intimation which had impressed his mind with great exercise and painful concern;
showing, that however disguised and hidden,
there was a spirit at work that would divide and scatter,
and draw off many that were then in high stations,
into self-sufficiency and disbelief of the truths of the Gospel.
This was such a surprise to some, that they were for passing a censure upon him;
but a few deeply experienced minds fully united with and encouraged him.
Now, when our friend William Savery was here, this rending,
disorganizing spirit was again impressively felt and detected;
soon afterwards it showed itself by a false profession of more
enlightened and liberal views of the Christian character,
setting little value on the Holy Scriptures,
and endeavoring to destroy the faith in the eternal
divinity of our Lord and Saviour Jesus Christ;
treating his atonement and propitiation as a fabulous scheme,
invented to impose upon the credulous,
and not worthy of the enlarged ideas of philosophic minds; which caused great distress,
and almost broke up the meetings in several parts of the nation.]
my mind having been much exercised during the meeting.
The afternoon meeting was also a trying, painful time to me, though quite silent.
Friends having heard of my general line of service among other people,
marvelled that I did not appoint a meeting of that kind for the evening;
but all seemed closed, and I could not attempt it.
After tea, finding a freedom to propose a meeting of the scholars of both the schools,
and the children of Friends in town,
in which my two friends Mary Ridgway and Jane Watson united,
we met with them in the provincial school--about one hundred children in all,
their master, mistresses, and thirty or forty other Friends.
My mind, which had been so exercised all day, presently after sitting down,
felt sweetly opened to them; they were soon broken into tears,
and a more precious opportunity I never remember with children.
They took leave of us in tears, and I felt much refreshed and comforted,
and have reason daily to acknowledge, that it is the Lord who opens and none can shut,
and shuts and none can open.

"`20th. Being at Limerick, I appointed a meeting this evening;
the house was filled--three priests of different congregations sat with us,
and it was thought to be an open, satisfactory time.

"`The new part of this town is regular and well built; it is on the Shannon,
fifty miles from the sea.
Pork here is bought at twenty-two shillings per one hundred and twelve pounds,
but much inferior to American;--beef excellent, and much of both are salted and shipped.
Some of the poor in this neighborhood give six guineas, and some more, a year,
for an acre of potato ground, when manured by the landlord.
To earn this six guineas takes a great deal of the year in labor for their landlord,
at six-pence or eight-pence per day and food;
so that the state of the poor is indeed a very hopeless one in this country.
It takes them considerable time to cut and dry their turf,
and in some places they now pay high for the privilege of getting it from the bogs,
and many of the poor have no way of getting it home,
but as the women carry it a long distance on their backs:

"`22nd. Went to their week-day meeting, where many other professors came,
also two ministers of the church of England;
and through the merciful condescension of our heavenly Father,
it appeared to be a good meeting;
after which William Farrer and myself went off in a post-chaise for Cork.
Passed through a fine country of rich land.
It being near the time called Christmas, the people everywhere seemed preparing for it;
most of the poor get some meat or poultry,
and were bringing home on their backs plenty of broom, furze, turf, etc.,
to keep better fires than usual:
most of the women and children were without stockings or shoes,
and also many of the men at this cold season of the year,
the air being very chilling and wet.
The verdure of the fields and meadows,
and their prolific appearance is such as I have never seen in any country.
The lands in the counties of Limerick, Cork and Tipperary, are so rich naturally,
that much of it wants but little manure.
Got to Cork this evening, the cost of the carriage, turnpike,
etc. for sixty-three English miles, was about four guineas.

"`First-day, 24th. The meeting held in silence;
but near the close I believed it right to
propose an evening meeting with other professors.
Dined in company with Mary Dudley, etc.
The meeting in the evening was very crowded--David Sands,
who had been confined here with indisposition for several weeks, attended;
also Mary Dudley--the people were quiet and attentive,
and the opportunity ended in solemn prayer.
Appointed another for Third-day evening.

"`On the 25th, after dinner, observing a large gate near the house with an inscription,
informing that the walls enclosed a foundling hospital,
I felt an inclination to go over and see the children.
The masters and mistresses soon collected the children,
about two hundred and twenty boys and girls, from five to fourteen years old,
tolerably clothed, though mostly without shoes or stockings.
After a little time in silence, David Sands, Mary Dudley and myself,
had something to offer to the company:
many of the children were attentive and some in tears:
the masters and superintendents expressed their satisfaction.
The institution is principally supported by a tax on coals, and the children,
when about the age of fourteen,
are bound out apprentices to such business as they incline to.
The city of Cork is large, and many streets wide, handsome and well built;
yet a more dirty, disagreeable city to walk in, I have scarcely seen;
it is built on both sides of the river Lee,
and may contain one hundred thousand inhabitants.

"`Third-day.
The common meeting was pretty well attended;
Mary Dudley was large and instructive in her testimony, and it ended in prayer.
Went to the appointed meeting in the evening, and found the house well filled:
the knowledge of God and of Jesus Christ his Son,
was shown to be of more value than all other science.
Many people of the first rank were present, some priests, etc.
David Sands had a good testimony and closed the meeting in prayer.
I believe that through mercy the Truth was in dominion;
the people were very quiet and attentive,
said to be the most so ever remembered in Cork at those promiscuous meetings.
I felt my mind much relieved, and though greatly unexpected,
concluded to leave Cork in the morning.

"`27th. Took leave of several Friends who were very affectionately attached,
and I do not remember ever having left a city with so
general an expression against my hasty departure;
but I believe all is right.
Passed through a pretty village where Samuel Neale formerly lived,
and got to Youghall in the evening.

"`28th. Attended their week-day meeting, which was silent;
and proposed a public meeting for six o`'clock in the evening.
The house was nearly filled--several officers and soldiers attended: it seemed,
for some time, to be laborious, but the people being still,
and towards the latter part tender, we separated in much solemnity.

"`29th. Accompanied by several Friends, we proceeded on our journey;
but having taken a cold,
so that I could neither stoop nor draw my breath without pain and difficulty,
and the road being rough, I rode in great pain.
The country is more beautifully green at this season
than any I know of in America in any season.
Got to Robert and Mary Dudley`'s, at Clonmel, in the evening.

"`First-day, 31st. Was at their forenoon meeting,
after which I mentioned my prospect of having an opportunity
with other professors at six o`'clock in the evening:
the meeting-house, which was large, was soon filled,
and it was said that several hundreds were out of doors.
The crowded situation of the people kept them uneasy for a little time,
but afterwards it became more quiet:
the people outside being very desirous of seeing and hearing, they talked much;
but were at length induced to be still, and we had a solid, favored conclusion,
through condescending mercy, in solemn prayer and praises.
The officers and soldiers behaved well, and my mind was filled with thankfulness.

"`Second-day, 1st of First month, 1798.
Attended an appointed meeting in the forenoon, which was not so large as last evening.
It was not my judgment to have it at this time of day,
but it seemed necessary to condescend to the sentiments of some Friends,
who afterwards believed that the evening would have been better;
I however was enabled to get through to my own satisfaction,
in exposing the pernicious doctrine of Deism;
and the opportunity was owned by the Divine presence and power;
and it afterwards appeared that there were three professed Deists present.

"`Friends in Ireland seem to live like princes of the earth,
more than in any country I have seen--their gardens, horses,
carriages and various conveniences, with the abundance of their tables,
appeared to me to call for much more gratitude and humility, than in some instances,
it is to be feared, is the case.
The easy situation of some has been an injury to them and their families:
many have been much shaken, seriously tried and afflicted;
and may all work together for their good!
This town of Clonmel is larger and better built than Youghall;
it may contain twenty thousand inhabitants,
is situated on the banks of a little river called Suir,
on which they carry their produce in flat boats to Waterford.
I had some serious conversation with dear Mary Dudley,
on divers matters that had taken my attention in Ireland.
In the evening it being the usual time when the scholars at the school,
instituted by Sarah Grubb, sit down in the manner of a meeting;
we had the children of Friends of the town added to them,
and it was a comfortable opportunity; about eighty children being present,
Mary Dudley was favored in her testimony and the children much affected.

"`First month, 3rd. At a Friend`'s house about three miles from town,
a very sumptuous establishment indeed,
which I did not omit to tell him was quite too much so.
On this place is a large run of water, called St. Patrick`'s Well,
to which the poor Roman Catholics resort on St. Patrick`'s day,
and wade in the water till they are very cold;
and at other times of the year many come from a distance,
some sent by the priests to do penance, who thereby suppose they wash away their sins:
it is kept almost constantly muddy by the people so frequently going into it.
Three fourths of the people in Dublin, and southward in Ireland,
are supposed to be Roman Catholics; and some say seven eighths.
They are an oppressed people,
and it is thought that two out of three do not get meat six times in the year.
They have but little milk, and indeed scarcely anything but potatoes and salt.
At present they are very uneasy, commit many riots, robberies and murders;
refuse to pay tithes of the few potatoes, etc., which they raise,
and seem to be almost lawless.

"`I visited a public charity school, principally attended by Ann Grubb;
and if it was not for the care and support given by Friends,
it is supposed it must have dropped; it is held in the old meeting-house of Friends;
one hundred and fifty poor ragged children, boys and girls, are taught reading, writing,
knitting and sewing--the boys nearly all without shoes or stockings,
and also the greater part of the girls.

"`4th. Attended the Monthly Meeting, the forepart of which was held in silence.
I went into the women`'s meeting,
and through renewed favor it was a solid satisfactory time.
Elizabeth Pim, a minister, was acceptably engaged in prayer.
Appointed a public meeting to be at six o`'clock this evening, which was large,
solid and relieving to me.
Mary Dudley was drawn forth in prayer and praises at the close,
to our refreshment and comfort.

"`5th. Went to the widow Grubb`'s, at Anner Mills,
and after breakfast proceeded to Carrick, a considerable town,
where almost all the inhabitants are Roman Catholics.
Our dear friends Deborah Darby and Rebecca Young having appointed a meeting here,
we attended it; about three hundred persons were present,
and Deborah Darby had an open time, and it closed with solemnity;
though the Catholics are so walled round that it is hard to penetrate them.
After dinner, being about to separate, I felt heavy,
thinking it might be a final parting between dear Deborah Darby,
Rebecca Young and myself: retiring into silence, some few expressions were uttered,
and Deborah Darby was preciously drawn to supplicate
the Father of mercies for preservation,
especially of us who had been united in his love by sea and by land;
most of the Friends present were much broken into tears;
and thus we solemnly took leave of each other.
It was also a very tender parting between us, who were going for Waterford,
and our kind hostess, Mary Dudley and her daughter.
William Farrer and myself went with our friend Ann Fayle,
in her carriage to a Friend`'s house about nine miles from Waterford,
at which place we arrived on the 6th.

"`A great trade is carried on here in provisions, as pork, beef, butter, etc.
Notwithstanding the great abundance of provisions that appear everywhere, this, place,
like most others in Ireland, abounds in poor and beggars;
and all the suburbs for a great distance are made up of poor thatched cabins.

"`First-day, 7th. Attended their morning meeting, which was large for this country:
at the close I proposed a meeting for the town`'s people this evening,
which was very large and crowded; it was thought there were one thousand persons present,
and yet many went away.
Great stillness prevailed, and the people were very attentive;
through renewed mercy it broke up in a solid, tender frame,
and I appointed another for Third-day evening.

"`8th. Went to see the place intended for a boarding school, which is a fine,
healthy spot; from thence we visited the widow Usher,
a valuable woman of excellent understanding,
who has been received among Friends within a year past;
since which she has lost two excellent daughters in consumption,
a third is now near her end, and a fourth evidently going the same way.
She has been supported in her affliction marvellously,
and her daughters have made a precious end, as the one now going will also soon do.
She was sensible,
and looked on us with a sweet countenance--all felt like peace around her bed,
and I was comforted in being with the family.

"`At my lodgings in the evening came Robert Greer and Abraham Shackleton,
the latter from Ballitore, who had come forty-two miles in order to see me.
He holds opinions of a singular nature;
objects '`to the five first books of Moses in particular,
but in general to the accounts of the Jews in the Old Testament,
and various parts of the New Testament;
professes to think there is little if any need
of books of any kind on religious subjects;
that they only darken the mind and keep it from turning itself wholly unto God,
the fountain of all light and life.
But of all books of a religious kind, he especially dislikes Friends`' Journals,
and has but a slight opinion of ministry and discipline,
and all secondary helps in general;
but is for having all people turned to the Divine Light in themselves alone.
Christ, he says, was a good man, the leader of the people,
because he was wholly obedient to this light,
which he was in an especial manner filled with.
He thinks the Evangelists are poor historians,
that Paul brought much of his epistles from the feet of Gamaliel,
and many parts of them are therefore rabbinical stuff,--Christianity
was the same to those who were obedient to the anointing,
before the coming of Christ in the flesh, as since,`' etc.
I perceived all this was accompanied with a pretended looking
towards a greater state of perfection and redemption,
than our Society has yet arrived at.
For my part, I could not see as he did,
nor unite with him in his erroneous expressions and opinions,
and I feel a fear they will produce much hurt,
if he and others in this nation are not brought into deep abasement;
his talents and morality making error in his hands more dangerous.
We separated without much satisfaction, at least on my side.^
footnote:[We have here a further disclosure of some of
the deleterious principles of the deceitful,
subtle spirit,
which worked under the specious garb of outside
morality and great professions of universal benevolence,
and carried away many unsuspecting souls into the vortex of Deism,
and at length into Atheism.
It is very remarkable,
that a great withering and falling away overtook nearly all of them,
and upon some of the principal promulgators of those unrighteous doctrines,
an awful blast was-evidently brought.
This same insidious spirit having since got into America,
lamentable desolation of a considerable number of
meetings of Friends in different parts ensued;
and it is to be feared that numerous individuals,
who at first had no idea of its destructive nature,
have been plunged into complete infidelity,
and entire repugnance to the doctrines of the Gospel,
and the unspeakable benefits conferred upon man,
through the propitiatory sacrifice of the Lord Jesus.]

"`After retiring to rest,
I could get but little sleep for some hours--Satan is
indeed full of subtleties--who can discover them,
but He who dwelleth in and covereth himself with unapproachable light?
I thought or dreamed, that I saw a man in a field,
who appeared to be attempting to pluck a few tares that were growing among choice wheat,
but he pulled up more wheat than tares, and trod down abundance more with his feet;
and I thought he had far better let them alone until the harvest.

"`First month, 9th. Attended the week-day meeting: my mind was much exercised and heavy,
but near the close was drawn forth in prayer, and afterwards felt peaceful.
Went with Abraham Shackleton to a Friend`'s house,
and opened to him more of my disapprobation than I had before.
Attended the public meeting in the evening, which was large;
much solemnity and quiet prevailed, and it ended in praises.

"`10th. Stayed much at my lodgings, writing;
and received a letter from Abraham Shackleton,
in which he appears lovingly disposed towards me, but evidently wrong,
so far as I am able to judge, in many of his opinions--took leave of him,
and had much concern on his account, and in that state went to bed.
Fifth-day, seeing ten miserable beggars sitting round a Friend`'s door,
I sent for ten loaves of bread, but before they were distributed thirty others appeared,
and each had the same quantity.
This is the way in Ireland, and there is no coming to an end of the business.
Another letter came from Abraham Shackleton who has gone for his home,
and I am not sorry for his leaving us; he has given me much exercise.

"`11th. Dined in company with several Friends, one of whom belonging to Enniscorthy,
appeared much concerned at the new opinions that had been manifested in their quarter.
My mind was exercised with much thought,
whether it might not be proper for me to go to Ross, about ten miles off,
where a person of some note had been convinced and come amongst Friends,
though I cannot but desire, as a man,
to get through my engagements as soon as possible in this land.
Lord! strengthen me to say, '`thy will be done,`' for in this only there is peace.

"`12th. Visited Elizabeth Usher,
and found her in much Christian resignation to the will of the Lord,
though her third lovely daughter was to be buried today;
having lost two others in a consumption, and a son in another way, within a twelvemonth;
her father at this time lying a corpse,
and her fourth and last daughter likely very
soon to follow her sisters in the same disease.
Her state of mind, as well as that of her dear remaining daughter,
was truly instructive to me.
Her son, who had not professed with Friends, came a few hours before Judith`'s death,
to take leave of her; she looked at him with much serenity of countenance,
bid him farewell, and said with a voice louder than she had for some time,
'`All is peace, sweet peace,`' and so departed,
praising God in joyful hope of a blessed change approaching.
Her corpse was carried to the meetinghouse,
but not brought in where the meeting was held, but loft in the women`'s meeting room,
which is their custom; for as they are surrounded by Roman Catholics,
they might take up the opinion that Friends brought the corpse into the meeting,
with the idea that it would be profitable to the departed spirit to pray over it.
Through the renewed mercy of our heavenly Father, it was a precious parting meeting;
many of the dear youth were much affected, as also others.
The corpse being put in a plain oak coffin, and placed upon a hearse,
was led slowly through the streets to the burying-ground; friends, relations,
etc. following promiscuously:--all business seemed to cease as we passed along,
and much stillness appeared among the people, many of whom knew the family,
they being of high rank; the grand-father who lay a corpse,
was the eldest alderman of the city.
At the graveyard, a multitude were collected, both Friends and others, high and low,
and I believed it my duty to say a few words,
and rehearse the comforting expressions of the deceased;
after which there was a further communication from another Friend,
and many not of our Society were much broken.
The Lord be praised for his goodness.

"`Feeling my mind much comforted and relieved of going to Ross,
or anywhere else in Ireland,
I took is affectionate leave of many Friends in the graveyard,
at which divers expressed their surprise, and wishes to detain me over First-day;
but believing it was a good time to leave them,
I got into a post-chaise and went about seven English miles,
where the packets for Wales lay.
After dinner we sailed, there being no cabin passengers but William Farrer and myself;
we passed down the river Suir,
and were out at sea soon after the light appeared at the light-house.

"`13th. Arriving at Milford in Wales, we set off for Haverfordwest;
the road and country very hilly,
yet exhibiting some pleasant prospects of well-cultivated farms,
but the soil much inferior to that we had left in Ireland.

"`First-day, 14th. The meeting at Haverfordwest consisted of about sixty persons`',
and was a solid, tendering time to myself and others:
there are about five families of those professing with us at this place.
Had an appointed meeting in the evening, but the house was not half filled,
owing as was believed to the person who undertook to give the notice being in low repute,
and had done the business very imperfectly.
The people in the street hearing my voice, kept coming in,
which rather unsettled the meeting; but near the close we had a little quiet,
and it ended quite as well as I expected.

"`15th. Proceeded through a hilly country as before, the valleys pleasant and fertile,
though the land is generally poor,
except where it is made otherwise by lime and other manure.
Pembrokeshire exhibits a pleasant picture; the houses of the farmers,
scattered among the hills, appear neat and comfortable, the people warmly clad,
and few barefoot or ragged,
as we have lately been accustomed to see in Ireland;--the houses are mostly thatched,
and all are white-washed outside, which gives them an agreeable appearance at a distance.
The women all wear hats, like men--we met many of the farmers`' daughters,
well mounted on horseback,
with great-coats and hats on;--riding on horseback is preferred in this hilly country.
Much simplicity of manners was obvious in the people of our inn,
and they accommodated us with kindness and good lodging.

"`16th. Got to breakfast at Carmarthen, which is a decent town,
perhaps ten thousand inhabitants, beautifully situated on the side of a small river,
which empties into the Bristol channel; it is surrounded with high hills,
well improved and cultivated to the tops;
the country much more fertile than that we passed through yesterday;
the valleys and hills covered with beautiful verdure,
look as green as ours in the fourth month.
The weather is more serene and clear than in Ireland, and the people very respectful,
industrious, and not fond of show and finery--they work hard for a little money;
a woman with one or two pack-horses or asses, will travel on foot eight or nine miles,
with about one and a half bushels of oats,
which brings them about fourteen pence more than they cost;
and in summer not more than nine pence.
Laborers have six pence a day and their provision.

"`17th. Had a meeting appointed at Swansea, which was pretty well attended;
the people were quiet and attentive; I thought it was, through Divine mercy,
a good meeting, and I left it peacefully.

"`19th. In passing through the country, I saw several large ancient castles,
the parks and fields beautifully green, surrounded with hills; and hundreds of sheep,
deer, goats, and cattle feeding--an attractive spot of earth indeed.
Got on to Marlborough:
the inn we stopped at had formerly been a seat of the Duke of Marlborough;
it was the largest and most splendidly furnished I have seen in England; the gardens,
park, forest, etc., make it a great resort of gentry to spend a few days.
Arrived at Bristol in the evening, and on the 20th visited a number of Friends,
and had some thought of moving on in the morning; but upon considering it more fully,
I concluded to stay at Bristol.

"`First-day, 21st. The meeting was large, many not professing with us coming in.
Some of our Society here make an appearance unbecoming our religious profession.
Through heavenly goodness a solemnity soon spread over us,
and it was a satisfactory meeting, for which I felt thankful.
That held in the evening was very crowded, but still and orderly;
there were several ministers of other societies present,
and the opportunity appeared to be favored with the
presence of the great and good Master of assemblies,
and ended in thankfulness to Him for this additional mercy.

"`22nd. My good friend and companion, William Farrer, having received a letter from home,
informing of the illness of his nephew and partner, thought it his place to return there,
which was some trial to me,
having travelled in true fellowship on the continent
and on these islands ten months together;
and we parted in the same, both being affected at the separation.
Several Friends accompanied me to Bath, at which we arrived before`" noon.
The public meeting this evening was large,
a considerable number of other professors attended, and many could not get in;
they behaved with great propriety, and I felt my mind relieved to my own satisfaction.
Very few of the members of our Society here have the appearance of Friends,
and some said they were sorry they could not attend,
but they were engaged on parties at that hour.
Having paid a visit in the forenoon to the famous Hannah More and her four sisters,
some of them being present at the meeting, came and invited us to their house again;
there came also a middle-aged, well-dressed woman, who shook hands with me,
and asked when it would suit me to receive a visit,
as she wanted to have some conversation with me.
I told her this evening, and while at supper she came; she stayed about half an hour,
appeared to be a singular and extraordinary character,
had been bred a Roman Catholic in London,
but growing uneasy with the practices of that people, she went off to Rome,
expecting her mind "`would be relieved at that fountain-head of religion,
but was greatly deceived; and after residing there three years,
protesting against their errors,
for which she had several times been likely to lose her life,
she returned through France.
Not finding true religion there, she had come to Bath about nine months since,
disgusted with all professions and separated from them, yet seeking the Truth;
she was overjoyed at being at the meeting,
having never thought of inquiring among Friends for religion:
after expressing a little to her, we parted.

"`23rd. This being the season for drinking the waters, the town is crowded with gentry,
who make a splendid appearance, and live in great dissipation,
to the disgrace of religion and morality--it is said that one
thousand persons attended the concert last night.
Believing it right to have another meeting,
one was accordingly appointed at a meeting-house of the dissenters,
which was thought would hold twelve hundred persons or more; and it was presently filled,
and proved, through the adorable mercy of our heavenly Father, to whom be all the praise,
a precious season, ending in solemn prayer and praises.
Hannah More having desired a Friend to bring me to their house again,
I there found the celebrated William Wilberforce, who had been at the meeting,
which I knew not of; but it was somewhat remarkable and unusual,
that I should be led to touch upon the enormity of the slave trade;
we soon became quite familiar,
and he asked me many questions about the state of religion in
the different parts of the continent where I had been,
and appeared much pleased that I had had an interview with Thomas Paine.
Hannah More and her sisters are all unmarried, live in good style,
and do a great deal of good--they have written and compiled many excellent works,
some for the use of charity schools, etc.
They are a band of sisters,
desirous of employing their time in doing what may be beneficial in the world,
and avoid all the gay and dissipating amusements of Bath.
We did not retire to bed till near twelve o`'clock, and after the fatigues of the day,
I was favored to lie down rejoicing in the goodness and mercy of God.

"`24th. On leaving Bath, I was persuaded,
that notwithstanding the great dissipation abounding in the place,
the Lord hath a considerable number of sincere-hearted, seeking children there,
though our Society is indeed at a very low ebb.
Looking back at my visit among the people, thankfulness covered my mind,
that the Lord had preserved me, as I humbly hope,
from wounding the blessed cause of Truth, which is at times above all things dear to me.
I had dreaded going there, but was convinced that the Lord is sufficient for his own work.
Got on to Melksham, and had a meeting in the evening;
the house was not large enough to hold the people, but though crowded,
they soon became quiet and solid, and it appeared to me to be an open, tendering time,
ending with much solemnity--praised be the great name of Him,
whose is the power and the glory.
Passed on to Devizes, but felt no necessity to make much stay there:
walking through the market, I took notice of a monument in the middle of the street,
erected to commemorate the sudden death of a woman, who told a deliberate lie,
in order to defraud.
The inscription is a solemn warning,
to deter people from frauds and lies in making bargains.

"`26th. Went through Windsor, where the royal family were:
the enormous pile of buildings, called Windsor Castle, is near a mile in circumference,
standing on very high ground, and commanding an extensive view.
As we rode through the forest, I saw many servants, and some of the nobility,
who were attending on a hunting excursion.
At Staines, I thought it right to appoint a meeting for this evening,
and Friends being active in giving notice, though it was now late in the afternoon,
the meeting-house was soon filled--many stood, and some could not get in;
the people were still and attentive.
I believed there were many religious persons present, but also some Deists;
many were much tendered, and through renewed mercy it was a time of favor.

"`27th. Got to London,
and was kindly received by my beloved friends Joseph Savory and others,
after a separation of near eight months.

"`28th. Attended two meetings, and two burials.
Had an appointed meeting in the evening,
which was much crowded with people of other religious professions;
my mind was solemnly covered, and I was favored with much openness, to the praise of Him,
who is the Author of all good, and to my own abasement,
as unworthy of so great and repeated mercy:
dear George Dillwyn made a solid and pertinent addition,
and the meeting closed in prayer and praises--returned to my lodgings wearied,
but comforted in looking back on the labors of the day.

"`Second month.
3rd. Went in a post-chaise for Norwich,
and reached a Friend`'s house about half a mile out of the town.

"`First-day, 4th of the month.
Attended their meeting; some not members, stepped in,
and there were about two hundred under our name; very few middle-aged, or young persons,
who had a consistent appearance in their dress; indeed,
I thought it the gayest meeting of Friends I ever sat in, and was grieved to see it.
I expected to pass the meeting in silent suffering,
but at length believed it most for my peace to express a little,
and through gracious condescension was favored to relieve my mind,
and many were tendered.
Had a meeting in the evening, in a large meeting-house in another part of the town:
there seems to be but few upright standard-bearers left among the members in this place,
yet they are not entirely removed.

"`Attended the public meeting, and the house, though very large,
could not contain the people by several hundreds;
but considering their crowded situation, many being obliged to stand,
they soon became settled, and through mercy it proved a remarkably open,
satisfactory meeting, ending in prayer and praise to the Author of every blessing.
The marks of wealth and grandeur are too obvious
in several families of Friends in this place,
which made me sorrowful, yet saw but little opening to relieve my mind;
several of the younger branches, though they are enabled, through Divine grace,
to see what the Truth leads to, yet it is uncertain whether,
with all the alluring things of this world around them, they will choose the simple,
safe path of self-denial.
This city is supposed to contain-about sixty thousand-inhabitants, which, perhaps,
is too high an estimate: it is pleasantly situated, but has many poor,
and numerous beggars in the streets.

"`6th. Attended the Monthly Meeting at Ipswich, in which they read my certificate,
and in the women`'s meeting I had a little to communicate:
in the evening had an appointed meeting for other professors, which appeared to be heavy;
yet I believe, that through the preservation of the heavenly Shepherd,
there was nothing lost.

"`8th. Was at Bury: this town is not large,
but bears the marks of great antiquity--has many singular ruins in and about it,
and is considered one of the handsomest small towns in England.
King Edmund is said to have died, and been buried here.
The public meeting, this evening, was crowded, but still,
and through the regard of our heavenly Father, a good opportunity.

"`11th. At meeting at Hitchen; and visited the boarding-school,
where my mind was drawn towards tho children in much affection,
and they were all broken into tears; it was, indeed, a time of special favor.
The appointed public meeting, this evening, was large, many went away for want of room,
and many stood outside, in the yard, all the time;
and through infinite mercy it proved a favored
time--closing in prayer and praises to God.

"`12th. Visited several elderly Friends, and then went to Hartford,
which is a large county town;
and not feeling easy to pass it without a meeting with the inhabitants,
one was accordingly appointed for this evening;--the house was not quite filled,
and for some time the meeting seemed rather heavy;
but through the condescension of our heavenly Father,
it proved at length a good and comfortable.

"`13th. Passed on through many villages,
and arrived at my usual lodgings in London before noon.
In this last turn was out eleven days,
and felt peace and quietness to attend me in the close.

"`Second month 14th. A publication appeared in one of the public
papers approving of what was delivered at Norwich and Bath;
but I thank my God, who has yet preserved me from being elated or much depressed,
by the well or ill-done of the world.
If I can but obtain the answer of a conscience void of offence to God and man,
that is the great object of my concern and will be enough.

"`After having visited a number of Friends, and attended several meetings,
I went to Horselydown on first-day, the 18th; was at their meeting,
and appointed a public meeting for the evening, which was very crowded;
some of the most respectable people being present--a great
solemnity seemed to spread over us in the time of silence,
and though I felt remarkably poor and tried at entering it,
yet through the gracious condescension of our heavenly Father,
it was one of the most comfortable meetings to myself, I remember to have sat in London:
praises to the Author of every blessing.

"`First-day, 25th. Visited a number of Friends last week;
today attended the meetings at Westminster,
and appointed one for other people this evening, which proved a good meeting,
to the praise of Him, whose is the power and the glory of all.

"`27th. From a particular impression on my mind, I visited a man in prison,
who was under sentence of death.
His cell being small, damp and dark, the jailer invited us, with the criminal,
into a better room.
He was about fifty years of age, and his wife was staying with him to see his end.
After his condemnation, he was at first much distressed on account of his condition,
but having been favored to find a place of repentance,
he had hope in the mercy of God and was not afraid to die:--he seemed in a calm,
quiet state of mind, but not boasting.
Some advice was communicated to him, and we left him thankful for our visit.

"`Third month,
5th. Visited the soup-house which is principally under the care of Friends;
there are several of these charities in and about London.
The soup is made very good and nourishing, and the poor give a penny a quart for it;
this one is in Brick-lane,
and makes about fifteen hundred quarts a day--it is a great relief to the poor,
for which they express many blessings to Friends as they pass through the streets.

"`7th. Having appointed a public meeting, I went to it this evening in much fear:
it soon became exceedingly crowded, and the passages being filled,
some hundreds stood round the doors; many respectable people attended,
and much solemnity prevailed in the time of silence.
I was led to speak of the awful signs of the times,
and on some passages in the Revelations; the Lord was good to us,
and the way was opened in a remarkable manner to declare the Truth;
and He condescended to tender my own heart, and also most of the congregation,
for which there was an offering of thanksgiving to Him; after which I was much humbled,
saw and felt myself unworthy of his many mercies,
and retired to rest with much thankfulness.

"`10th. Dined at Benjamin West`'s, in company with George Dillwyn;
and he having concerted the necessary measures
preparatory to a visit to the royal family,
George Dillwyn, Mary Knowles and myself,
went with him in his carriage to Buckingham-house, where we arrived about six o`'clock.
The queen ordered the pages to show us into one of the apartments,
where we waited about five minutes,
when one of the lords came to conduct us to the drawing-room.
The king, queen and three of the princesses, with prince Ernest Augustus,
met us with pleasant countenances.
Being informed of my late journey on the continent, the prince asked me many questions,
but with rather too much rapidity.
He particularly wished to be informed of the present state of Lyons,
which gave me an opportunity of expressing my
feelings on the horrors and miseries of war,
and that it must be devoutly wished by every good Christian,
that a total cessation of that dreadful, practice should take place; and which every one,
according to his rank and station in the world, ought to labour to promote:
to this the queen and princesses, who stood close round us in a group,
gave an emphatic assent.
The king and queen asked questions on several subjects,
to which I gave answers as I was qualified.

The king engaging in conversation with George Dillwyn,
I turned to the queen and princesses, who all appeared highly pleased with the interview.
She gave me the names of the children and their ages,
and told Mary to bring her sister Amelia, who was unwell,
but she came in;--she is a tall girl of fourteen.
We conversed with the king, queen and children, like old acquaintances;
and I told them I was grateful for their condescension in receiving us in this
social manner--for there was not a single person with us in the room all the time.
The king asking me about the situation of things between France and America,
I told him I seldom meddled at all with politics, as it was not my business.
No, no, no, said he, I understand;
but as a people you can never form so natural an
attachment with any nation of Europe as England;
we are united by religion, relationship, commerce, disposition, etc.
I replied, that I valued the connection,
and hoped the family compact would never be broken;--and the queen,
who had caught a part of the conversation, desired I would repeat it;
was much pleased with the idea, and spoke of it to her daughters with satisfaction.
The king spoke of the Theophilanthropists in France, but had not a right idea of them.
I told him I desired to embrace the good as my brethren,
under every different modification of outward form and
profession in the world;--to which he and the queen replied,
'`A good Christian must do so,
for he has the same regard for good people of different
professions.`' After much free conversation,
I could hardly take leave of them without tears.
Benjamin West made a motion; the king and queen, with the children, drew a little hack,
and with gestures of respect, bid us a '`good evening.`' I said a few words at parting;
George Dillwyn also expressed a little.
After we retired, Benjamin West staying a little, heard the king say to the queen,
'`Charlotte, how satisfactory this has been.`'

"`First-day, 11th. Attended meetings at Ratcliff and appointed one for this evening,
which was held in a malt store--above one thousand people attended;
and though all could not get seats, they behaved remarkably well.
It was thought to be a solid, favored time,
but my mind was very much stripped at the close;
surely the Lord is good to sustain and support so poor a creature as I am,
under these weighty engagements.

"`16th. Concluded to hold a meeting this evening with the people,
in the king`'s dock-yards, at Chatham.
I admired the quiet and order of the workmen, a great number of whom are Methodists;
the meeting was full, mostly from the dock-yard,
and it appeared to be a solid comfortable season.

"`18th. At London, and attended their meeting at Gracechurch street.
A public meeting being appointed for this evening,
great numbers came together--many of the gay families in and round Loudon were present,
with a multitude of other professions, supposed to he upwards of two thousand;
yet they were very quiet and attentive, and the Lord was pleased to be with me,
so that I rejoiced in a hope,
that Truth had risen as high as in any of the public meetings I had had about London;
it ended in thanksgiving, and I took leave of the people,
not doubting I should now depart from this city soon.

"`19th. I mentioned my prospect of appointing a meeting for Friends only;
and though I felt weak and fearful about it,
yet was most easy to appoint one for tomorrow evening.
Walked to the soup-house in Spittal fields,
where a few Friends were busily employed in
distributing about fourteen hundred quarts of soup,
which they do in about two hours--the poor people bless
the Quakers and seem very grateful for this relief.

"`20th. Attended the appointed meeting, which was large;
a great many had to stand all the time--a solemnity prevailed; and it was made,
through the heavenly Father`'s love, a season long to be remembered; the light and airy,
as well as the formal and precise professors, were tenderly spoken to; and the humble,
upright-hearted among the youth and others, comforted.
It was such a time of cementing union and love with my brethren and sisters in Society,
as I never experienced in England before.
At the close George Dillwyn kneeled down, and in a lively manner gave God the glory,
which was and ever will be his due.
A considerable number expressed a hope they should see me again in London,
and my own mind was doubtful whether it was a final parting; however,
I believed it a right time to leave the city at present,
and commit the future to the direction of Him,
who hath been pleased to be mercifully with me,
far beyond my deserts:--many were in tears,
and it was after nine o`'clock before I could get out of the meeting-house.
I retired to rest relieved of London,
and with much thankfulness of heart to the Father of mercies.

"`23rd. After having visited several Friends, went on to Shipstone;
and being informed of the burial of a young woman at Chipping Norton,
I felt most easy to attend it, though several miles off.
A large company were present, so that the meeting-house was much too small for them.
I had some remarks to communicate, and it appeared to be a favored, contriting season.
The grave was walled up about one foot and a half high, with brick,
and floored with the same, laid in mortar;
the coffin was let down and covered with flat stones, laid on the brick wall in mortar.
Went on through a part of Oxfordshire to Evesham, a large market-town in Worcestershire,
where there are a few Friends and a meeting.
Friends here were under a good deal of concern, as I have found in many other places,
about paying taxes declared to be for the express purpose of carrying on the war.
I think our peaceable testimony is so much concerned in it,
that many Friends will find it the way to peace, to suffer, rather than actively comply:
it will no doubt be a trying time to many,
through which I hope the standard will be held up a
little higher against the horrid practice of war,
than has yet been the case in England.

"`24th. Passed through a good country to Bridgenorth, on the head of the Severn:
most of the town stands on a high rocky hill; the lower town in the vale.
The rock is so soft that many of the poor live in chambers cut out of it;
some families one story above another.
Great simplicity prevails among the country people;
their language partaking a little of Welch,
and differing from any I have heard in England.
We rode over very high and uneven ground, the Severn flowing below us,
and passed through the town of Brosely, among the iron works and over the iron bridge.
This valley, for a mile or more, is filled with iron works;
the hills are steep and rugged, yet covered with houses, gardens, etc;
for the people are dependent on the works.
It has a very dark appearance,
even the trees and bushes are quite blackened with the smoke;
and in the night the fires have a terrific appearance.
We arrived at Sunny-side, and were received at Sarah Darby`'s with much kindness.
Dear Deborah Darby resides here, and Rebecca Young was here also.

"`First-day, 25th. Visited our ancient, honorable Friend, Ann Summerland,
a minister beloved,
and now in her eighty-ninth year--she leaned on my arm to the meeting-house:
many not professing with us came into the meeting,
and at the close I appointed a public meeting for the people generally.
The meeting in the evening was large for the place,
and appeared to be a solid time throughout.
Mary Fletcher, widow of the late John Fletcher, of this parish,
having had a numerous meeting in the Dale this afternoon,
occasioned more people to be at ours;
she preaches much in various places round this neighborhood;
bears an excellent character for piety, both from Friends and others,
and is certainly an extraordinary woman.

"`26th. Went on to Shrewsbury, where Rebecca Young lives,
and had an appointed meeting this evening.
As it was the time of the assizes, many came in,
so that the house was too small for the company;
yet the people were very quiet and attentive,
and through the goodness of our heavenly Shepherd, it closed to our comfort,
in praises to his great and ever worthy name.
A messenger being sent on, a meeting was appointed at Elsemere, on the borders of Wales,
sixteen miles from Shrewsbury,
which we attended the 27th. The people not being accustomed to see Friends often,
were somewhat uncivil as we passed through the street.
The room held about three hundred, but more were outside and thronging to get in.
On explaining to them our reasons for appointing such meetings and
the necessity laid upon us both to labor and to suffer reproach,
if the Lord permitted it, for his name sake, they became quiet,
and though impatient to get in were serious and still.
Deborah Darby had a favored time, and I made some addition,
and Rebecca Young closed the meeting in prayer;
so through the mercy and goodness of the Lord our helper, Truth came into dominion,
and at parting with the people, they thanked us for our visit.
An ancient woman seemed very loving,
and told Deborah Darby there had never been a meeting
of Friends in the town since her remembrance,
and that she was thankful for this.

"`Went to Wrexham on the 28th, and held an appointed meeting at eleven o`'clock;
and it being fairtime, which continues a week, the inn and streets were crowded:
the manufacturers from Manchester and Birmingham, were here to get orders for goods,
and the Irish traders with linen,
so that it looked like an unfavorable time for a meeting:
about one hundred and fifty came in, but seemed rather restless;
and the waiter of the inn frequently called one or other out to some who had business.
Deborah Darby spoke, and for a time they were pretty still,
yet several were moving out and in;
a considerable part of the company being such
who had come out of the country to the fair,
and probably had never seen a Friends`' meeting before.
I having something to offer, and speaking pretty loud, many came up from below stairs;
and though there was still much unsettlement,
yet a number were solid and quiet to the end; it closed in prayer, and on parting,
with the more serious class, they lamented that,
the meeting had not been at another time, when we should have had a large company,
and the people more settled.
Went on for Liverpool, and travelled through a pretty country to Chester,
where we arrived alter much detention, about nine o`'clock at night.

"`29th. Attended their meeting--my mind today much exercised about right direction,
when and how to move towards my dear home,
desiring to be released as soon as the Lord may please to make way for it in pence.

"`Fourth month, 1st. Went out to Bickerstaff,
which had once been as large as most country meetings;
but for seven years past no members have resided there, except two old people;
the house is the most antique and simple of any I have seen,
and was nearly filled with plain, honest looking country people,
chiefly farmers and laborers from the neighborhood, who were still; many were tender,
especially some of the most aged, and I trust the good Shepherd was with us.
Friends having obtained leave for a meeting at
three o`'clock in the Town Hall of Ormskirk,
we proceeded thither;
but found that some prejudiced people had been influencing the magistrate who gave leave,
to countermand it.
He said, that upon consideration, he did not think such meetings ought to be encouraged,
especially on the sabbath day,
when every person ought to be at their own place of worship;
and he therefore ordered the constable to stand at the door and suffer no one to go in.
The place had been seated, and the notices spread in the town.
I felt calm, expecting the people would not all be pleased with the order.
It appeared that a person,
by the initials supposed to be one of the new lights from Ireland,
had been there some weeks past, and said something that offended the minds of many,
and the people behaved rudely.
I was concerned how it might end; thinking if any prejudices had got in,
and we were obstinately refused a meeting,
I must endeavor to vindicate our principles and testimony,
either out of the windows of the inn, or in the market-place.

"`I ate but little at dinner,
and before three o`'clock a servant came to inform us from the constable,
we might hold our meeting at four o`'clock, when the public worship would be over.
Some of the young men stood at the Hall door, and also pasted up a paper,
informing that the meeting was postponed till four o`'clock;
at which time we went--the constable having just opened the door,
vast numbers were crowding up stairs, and they came in,
until no more could either stand or sit:
it was supposed about five hundred persons were there,
some of them the most respectable people of the town, who sat near us;
but it was very evident they came with prejudiced minds in a general way,
and expected to have something to ridicule.
It is certainly a very important engagement, and fraught with serious consequences,
to attempt to hold such meetings,
and to leave them so as to shut up the way of those who may come after; which, indeed,
is injuring the cause we profess to promote.

"`Believing it right to stand up and express a text of Scripture, many began to smile,
and I had not been in such a meeting for a long time;
yet feeling my strength increase as I proceeded, and the heavenly Shepherd near,
the people dropped their countenances and became
serious--many at length were much affected;
and towards the close,
which was under a feeling of reverent thankfulness to the Lord our helper,
an evidence was granted,
that the holy Truth was as able as formerly to chain
down light spirits and put to silence the scorner.
Returned to Liverpool.
Several vessels going for America, I am tried with daily anxiety about home,
in a manner I have not experienced since I left it,
and my mind much exercised that I might know the will of God and do it,
whether to go from England at present or tarry a little longer.

"`First-day, fourth month 8th. At meeting my mind was opened in an unusual manner,
and I felt comforted in believing the gracious Helper
of the poor was near and his presence with us.
Appointed a public meeting for this evening, which was large,
their commodious house being filled,
and it was said that many of the first rank in the town were present.
The call of the Lord`'s people out of Babylon was opened;
showing that Babylon signifies confusion, and that all priestcraft and false foundations,
laid by human wisdom and authority, in establishing systems and modes of worship,
not proceeding from Divine wisdom, were in the confusion,
as well as the civil policy that involved nations in cruel and destructive wars,
and permitted men to ravage foreign countries and carry their
inhabitants into the most inhuman hands of slave-masters.
The meeting was still and attentive, and much solemnity reigned, for which,
impressed with a sense of the mercy and goodness of God in thus favouring us,
the meeting closed in prayer and praises--retired to bed with thankfulness
to the Author of every blessing for support through the day.

"`10th. Having attended Hardshaw Monthly Meeting,
in which the business appeared to be well conducted, I returned to Liverpool.
The roads were dusty,
and the people diverting themselves in the fields with dancing and other sports,
which they call '`folly fair,`' a proper name for such vanity.
Low in mind, not seeing how to move for the best as respects my leaving this country.
My natural feelings are strongly drawn towards home, but no light seems to shine upon it;
and I never had more need to ask for patience than at present.

"`14th. Went for Lancaster:
the land through this part of the country appears to be but an indifferent soil;
the farms, hedges, etc.,
not in that neatness which is apparent in many other places in England.

"`First-day, 15th. Attended their meeting,
and appointed one for other professors in the evening, which was crowded.
I was considerably enlarged in communication, respecting the righteous of former ages,
both under the law and the Gospel,
and the manner in which they obtained confidence in God;
and that the same means would produce the like effect now,
both to individuals and nations: the people were quiet, remarkably attentive,
and through holy condescension it was a favored opportunity--the
praise of all was solemnly rendered unto Him who is forever worthy.

"`16th. Got on to Liverpool, and on the 17th was at the meeting of ministers and elders,
and it appeared to be a profitable season.
At the Quarterly Meeting for Discipline,
the subject of paying taxes for the support of war was considered,
and it appeared that many Friends were much straitened in their minds about the practice,
in most of the Quarters in the nation.

"`18th. The meeting this afternoon was large;
it was thought there were two thousand people present:
some doctrinal subjects were opened by William Jephson,
in a remarkably clear and convincing manner, and it was a favored time;
ending in prayer and praises unto God, who helped and strengthened us.
Many of the people expected another meeting, and seemed loth to depart.

"`20th. A ship is to sail in two days for Philadelphia, and my mind is much exercised,
not feeling liberty to return to America.
A public meeting this evening was large, at which were Deborah Darby, Rebecca Young,
and Charity Cook: the Lord in great mercy owned us,
and favored with a renewed eating and drinking together as in his presence,
where his banner over us was love;
in which I believe many not professing with us partook, and parted in great sweetness.

"`21st. Went on for Chester, and on First-day, the 22nd,
had a public meeting there--the house filled--Deborah Darby had an open favored time;
the people were solid and a number expressed their thankfulness,
wishing for another meeting; but one having been appointed at Wrexham,
twelve miles off in Wales, for this evening, we left Chester; passed through a pleasant,
well-cultivated country to that town.
Held the meeting in a large room, supposed to contain six hundred,
but it was much too small; and that and a room adjoining were crowded to such a degree,
that it became very warm, so that some were ready to faint;
yet the people seemed inclined to be still.
After speaking some time, numbers pushing to get in caused uneasiness and unsettlement,
and I then proposed, that if another place could be immediately obtained,
we had better proceed thither.
A respectable looking man said, the Independent meeting was at our service,
if we chose to go there;
but dear Deborah Darby not being willing to go
into a place of worship of another society,
stood up and spoke to the people, which had a good effect.
The crowd however was too great to continue, and we broke up the meeting,
and appointed another at ten o`'clock in the forenoon, at the same place.
The people seemed sorry it could not be continued,
as many of them were poor and could not well attend on a working day.

"`23rd. The meeting being accordingly held, about eight hundred attended,
and it proved a satisfactory time, to the refreshment and comfort of many;
much tenderness being apparent,
the people were full of expressions of their satisfaction, and many asked for books,
which we had not to give them, but promised to send them some.
Wrexham is one of the largest towns in Wales,
and may contain eight or ten thousand inhabitants.

"`Proceeded to Oswestry, a considerable town, about sixteen miles distant;
and passed through many pleasant vales, etc.
A large room being prepared for a meeting,
it was supposed seven hundred persons were present;
and after considerable communication we parted with the people in
much tenderness--many acknowledging the Truth and asking for books.

"`24th. Going towards Welchpool, we found the roads very much cut and hilly;
the valleys were beautiful,
and many barren mountains were in view--the farm houses generally small,
and the dress of the people rather mean.
Several Friends from Colebrookdale having joined us,
we held a meeting in the evening at our inn but it was an hour
before more than forty persons came--two Friends spoke;
after which, feeling an engagement to speak, and my voice being heard at a distance,
the people crowded up stairs and filled both rooms;
they were quiet and attentive--a few persons who
had been drinking too freely were unsettled,
yet the meeting ended well, and we appointed another for tomorrow evening.

"`25th. Attended the meeting of ministers and ciders this morning,
which was small but solid;
the poor Welch Friends were much affected with the
smallness of their number and with their weakness.
The meeting for Discipline, which is held only twice a year in Wales,
and is similar to a Quarterly Meeting,
consisted of about thirty-two men of their own members, sixteen of them Welch,
and as many from Shropshire.
I felt very low about the meeting to be held this evening,
Friends saying the people have never been very free in coming to them.
Deborah Darby and Rebecca Young being much wearied, excused themselves from attending.
The Town-house had been obtained, and it was soon filled,
and a large number stood in the street, but so situated as to be able to hear;
they were still both within doors and without, and many were much tendered:
the opportunity ended in prayer, and Friends thought that, through Divine favour,
it was the most solid meeting they had known in that town.

"`26th. Attended the meeting for Discipline,
and went into the women`'s meeting with my certificates, where I had an open,
tendering time,
and dear Deborah Darby appeared in prayer in a solemn and comforting manner.
A person who lived at Montgomeryshire, eight miles off;
requesting Friends to hold a meeting there,
and Deborah Darby and Rebecca Young having wished to have one there a few months back,
which the parson prevented, they now thought it right to go;
and believing it required of me to go another way, though much in the cross,
I took an affectionate leave of them, in order to proceed to Dublin Yearly Meeting.
Passed through a mountainous country, having very little appearance of wealth or luxury;
the inhabitants spoke little else among themselves but Welch,
and many of them speak English with difficulty; they look like a healthy,
hardy race--the women almost universally wear hats like men,
and work much in the fields and barn.
The inhabitants seemed to live in humble style,
and to be much unacquainted with the fashionable world.
Giving our coachmen, at different stages,
a little extra pay to get us on as fast as they could, to Holyhead,
we arrived there the 27th at night,
and found a-packet just hoisting sail and the passengers going on board.
They allowed us a quarter of an hour to procure provisions for the voyage;
so that if we had been half an hour later, we should have missed our passage.
There were only three passengers besides ourselves, and a good sloop,
in which we were well accommodated.
On the morning of the 28th,
we plainly discovered the mountains of Wicklow--and the captain.
A+++.+++ Savory and myself, being the only persons who had lain in provisions,
it was all brought upon deck, the others joined in our repast,
and we all eat very heartily.

"`29th. When about two miles from the Dublin lighthouse,
a boat came to take the passengers on shore;
at such ports many are seeking to empty the pockets of travellers.
We breakfasted at a miserably dirty, though large hotel,
showing us at once that we were out of England.
Went to Meath street meeting-house,
where Friends were assembled--the widow Usher of Waterford, spoke a few words in prayer,
and Friends seemed glad to see me come into the meeting.
Appointed a public meeting at six o`'clock in the evening, which was,
through the renewing of our heavenly Master`'s favor, an open, satisfactory time,
and the praise was returned to Him who alone is worthy.

"`80th. Second-day; the Meeting for Discipline was held,
and much solemnity was apparent at the opening.
Leinster province meeting contains almost as many Friends as Ulster and Munster,
and there is only one small meeting in Connaught.
In considering the reports from the different meetings,
the subject of reading the Scriptures took up the attention of Friends.

Some of the accounts being deficient, Friends could not easily get over it,
but were not sufficiently clear and explicit in mentioning their painful apprehensions,
and were about to pass it by.
I pressed their closer attention to it, but some were for going on,
though many minds were oppressed, knowing the pernicious sentiments that had obtained,
even among some members in high stations.
I now saw in part what brought me to Ireland again.
I urged it again, when Friends spoke their minds freely,
and it appeared that a number in different parts of the nation were
in a disposition to lay waste in great measure the Holy Scriptures,
disputed the Divinity of Christ,
and were not united with the present ministry or discipline of our religious Society,
but yet professed to exalt the Divine Light and immediate revelation very highly.
After several hours spent on the subject,
a large committee was appointed to take the matter into consideration,
and join with the women Friends in bringing in a report.
David Sands and myself were requested to sit with them.
Went to my lodgings fatigued, but convinced that it was my duty to attend this meeting.

"`Fifth month,
1st. The meeting of ministers and elders was exercised on the
same painful subject as the Meeting for Discipline;
some of the disaffected were present; several active members, and one elder of Dublin,
sat with their hats on while David Sands was in supplication.

"`2nd. The committee of men and women Friends, respecting the Scriptures of Truth, met,
and also a number of concerned Friends, both men and women:
several Friends said they knew members,
who not only openly allowed their disbelief and
disregard of a great part of the Holy Scriptures,
but who also denied the Divinity of Christ,
and many things recorded concerning him--and pretended that they were
so illuminated as to have no occasion for books or outward helps--
some of these they believed had come into the committee,
who might speak for themselves.
I urged such who were dissatisfied with the doctrines of Friends in these respects,
to be candid and open, that we might discover what their sentiments were,
observing that no honest man ought to hold sentiments he was ashamed of.
I told them it was well to take one thing at a time,
and to read the head of the chapter on the Holy Scriptures in Robert Barclay,
and if Abraham Shackleton or any other, who I supposed to be the cause of uneasiness,
had anything to object, I hoped they would stand forth.
On its being read, J. B y said he agreed to the proposition that Barclay had laid down,
but there were several parts of the Scriptures he could
neither call holy nor require his children to read--he would
not go so far as to deny the authenticity of them in general.
Abraham Shackleton agreed in words at least, but was for mutilating the Scriptures,
saying that many parts were unprofitable,
and some things derogatory to the Divine Being--there were five books, he observed,
between Genesis and Job, but did not say which, that he could very well spare,
and some other parts of both the Old and New Testaments--he
did not deny that Jesus Christ was a Divine person,
but it was not clear what his ideas of the Divinity were.
After we had sat about three hours, those who were not of the committee withdrew,
and Friends then spending another hour in considering the subjects,
appointed three men to bring in a report.
On attending the committee in the afternoon, a report was brought in,
but before there was time to go through it, adjourned until tomorrow.

"`Fifth month,
3rd. The committee on the Holy Scriptures and on the
unsound doctrines held by some members of Society,
having met, a report drawn up by the sub-committee to be presented to the Yearly Meeting,
was read, setting forth that there was reason to believe,
that some members of Society held the Scriptures, particularly some parts of them,
in very light, estimation, and were also tinctured with unsound doctrines,
and proposing it to be recommended,
that such should be tenderly treated with by the Monthly Meetings,
and if they could not be brought to condemn their errors,
the Monthly Meetings should request the assistance of
the Quarters to labor further with them,
and if they still persisted to hold those pernicious opinions,
Friends were then to declare their disunity with them.^
footnote:[Most of the persons who had unhappily
imbibed these unsound and pernicious opinions,
which were the cause of so much sorrow and concern to the Society,
soon after relinquished their membership or were disowned.]

"`The meeting again assembling at five o`'clock, the report of the committee,
with some small alteration, was adopted and sent into the women`'s meeting.
Some Friends having obtained the freedom of cities,
by taking an affirmation to keep a gun and bayonet in their houses,
and a few others being at present contractors for the army,
this very serious subject took up much time at this sitting of the meeting,
and it was ordered that a minute should be brought to the next sitting,
directing Monthly Meetings to deal with such delinquents.
The first is a practice of many years`' standing,
and but lately taken notice of in a Society capacity.
Some who were so circumstanced, sent to the corporations a resignation of their freedoms.

"`4th. Attended the meeting at Sycamore alley,
and had to mention the expressions '`the memory of the just is
blessed,`' bringing to the remembrance of the company present,
the worthies of our Society who had been formerly raised up in Ireland;
the youth were tendered, and through Divine mercy and favor,
it appeared to be a profitable, good meeting.
In one hour after this, the meeting of ministers and elders met again,
when my certificates being read,
some Friends were appointed to draw a returning one from this meeting.
J+++.+++ B. sent in a note, desiring to be admitted into the meeting to relieve his mind;
Friends sent out a committee to hear him,
but did not admit him--he was one of those persons who
thought lightly of some part of the Scriptures.
Attended the Meeting for Discipline,
which recommended its representatives not to urge in the Yearly Meeting of London,
the request for a distinct Yearly Meeting in Ireland; all who spoke to the business,
thought it was no time to break up the connection, in which I much united.

"`5th. The meeting was brought under the consideration of appointing
a committee to visit Quarterly and Monthly Meetings in this nation,
as it appeared to be a trying time to Friends,
from circumstances both within and without the Society,
which subject I had felt impressed on my mind for several sittings.
Three or four of those members who had given the meeting much exercise and trouble,
opposed the motion, but a solemn calm coming over the meeting,
many Friends expressed their unity with the concern, and six men Friends were appointed.
The meeting adjourned until afternoon, when it sat till eight o`'clock at night,
and closed in a solid and comfortable manner.
Though it had been a painful, exercising week to many,
it was thought to be as profitable a meeting as had been held for a number of years.

"`First-day, 6th of the month.
Attended their meetings for worship and appointed a public meeting for the evening,
which was very large, more than the house would hold;
there were many people of high rank, some officers,
and several of those called clergymen present.
I was led to combat the Deistical opinions,
and through the continued mercy of our heavenly Father, it was one of the most solid,
satisfactory meetings I ever sat in Dublin.

"`7th. Meeting of ministers and elders:
a lively zeal was manifest to stir up Friends to attend to their several gifts,
and to be watchful in keeping down those who may
attempt to introduce unsound doctrines among Friends.
Our certificates were signed by all except three members who are leaning,
it is to be feared, to the new opinions--the meeting concluded in a serious,
satisfactory manner,
after having agreed to print Robert Barclay`'s chapter on the Scriptures.

"`8th. At meeting at Meath street, I mentioned the passage in which it is said,
that our Lord passed through certain cities without doing many miracles,
because of their unbelief.
Mary Ridgway then took up the subject, and had a lively testimony;
David Sands closed the service on the same,
and it was thought to be a profitable meeting--Friends
took leave of each other in much tenderness.
In the afternoon there being many Friends at the house where I was,
I took an affectionate leave of them all,
several expressing they believed I was right in coming again to Dublin,
for which I was thankful and felt encouraged.

"`9th. Went on board the packet with a number of Friends who are going with us to England.
Arrived in the evening at Holyhead, and our baggage being taken to the Custom-house,
I searched in vain for my trunk, which could not be found,
and was very uneasy at the loss, as many valuable articles were in it.
I determined to stay at Holyhead until I could learn something about my trunk;
it was rather a dreary time to my cousin A. Savory and myself.
The town is small, and a dull place,
except when the packets are either going out or arriving from Ireland;
there are perhaps about one hundred houses in it, and as to trade it seems very dead.

"`12th. Early in the morning the bar-keeper came into my room and said,
your portmanteau is in my possession.
It had been found after we sailed from Dublin, and sent on by my friend Joseph Wilson.
Rode to Bangor ferry--most of the towns in Wales are very dull,
both as to navigation and inland trade.
Got to Aberconway, one of the most ancient little cities I "`have seen,
particularly its walls and towers: being a thoroughfare from Dublin to London,
draws travellers to it, and the money thus disbursed,
furnishes the inhabitants with their principal support.
Rode in sight of the Irish channel, and crossed several mountains, one very high,
the road being cut into the side of it with the sea almost perpendicularly under it.
From this height there is a very agreeable view of the ships sailing in the channel;
of the verdant, beautiful valleys, and humble cottages, with their inhabitants,
between the mountains; the horses, cattle, ploughs and people, so far below us,
that they appeared very diminutive.
Men and women seemed to take an equal share of labor in the fields.
Got to St. Asaph, which is but a small town, having rode sixty miles today.

"`First-day, 13th. Passed through a well-cultivated country,
and one of the finest valleys in Great Britain, the fields and meadows luxuriant,
timber trees in the hedges, etc.; much rural simplicity prevails.
Arrived at Wrexham.
Several hundreds of soldiers having come into the town on their way to Ireland,
the people seemed in a bustle and no probability of a meeting among them to advantage,
so we sat down quietly to our bibles.
In the evening it plainly appeared,
that a meeting could not have been held to satisfaction,
ts the people began to be very noisy, and much taken is with the soldiery.

"`14th. Put on through Elsemere and Shrewsbury, to Shefnal:
saw a great number of furnaces and forges at Ketly,
which with the coal pits and smoke from numerous steam engines,
made the country appear black for many miles, covering the trees, shrubs, houses, etc.,
and with the blackness of the people and many fires burning,
formed altogether an extraordinary scene.
With much diligence we got to Birmingham and stayed a little while among our Friends.
Went to a house where they were delivering a quart of soup and
a half-penny worth of bread to each poor persons,
for a penny.
Friends are the chief supporters of this benevolent institution,
from which the London associations took their rise;
they brought each of us a little of the soup, which was well relished and good.
They serve about one thousand per day,
the applicants looked poor but far removed from the filthy,
degraded and wretched condition of the poor in Ireland;
it did my heart good to see this mode of relief promoted and patronised by Friends.
They sell the soup very low rather than give it,
which in great measure prevents those from partaking of it,
who would sell it if given gratis, and apply the money to get strong drink.
I had a public meeting in the evening, which was very large,
the crowd and heat being great, several young women fainted,
which occasioned some disturbance.
Afterwards the people sat in great quietness,
and Friends hoped that the testimony of Truth was owned
by many in the meeting not of our religious profession.
After meeting, one of the ordained ministers, a man of pious character,
endeavoured to encourage me, apparently with much sincerity.

"`16th. Went through a fertile country, abounding in rich pastures, fine sheep,
large cows, etc.
Got to Coventry, and it being their meeting-day, we went to it:
the house was nearly full, and it appeared to end with solidity.
In company with Friends going to the Yearly Meeting, went to Towcester.
My mind very low about entering London again, which I had left comfortably,
with a hope that it would not be my lot to see it again in this visit,
yet could see no other way for me.
My friends endeavored to cheer me,
as some of them thought when I left it I should not get
away peacefully without attending the Yearly Meeting;
and I endeavored after resignation.
The people knowing it is the time of the Yearly Meeting,
look pleasantly on Friends as they pass along the roads, especially the innkeepers,
as Friends have to stop at their houses--they were very obliging,
but were hard set to provide all with post-horses.

"`18th. Attended the usual morning meeting preceding the Yearly Meeting.
Thomas Scattergood appeared in prayer, and also Elizabeth Usher from Ireland;
Friends kept their seats a considerable time after she kneeled, not knowing her,
for which I was sorry.
I stood np, and Friends followed my example;
much solemnity appeared to cover the meeting, and it so ended.
Dear Deborah Darby, Rebecca Young and myself,
agreed to be at the meeting at Wandsworth on First-day, the 20th,
and to have an evening meeting at Stockwell.

"`20th. The meeting at Wandsworth was large,
many of the rich gentry having seats thereabouts were present,
and several Friends from London.
Deborah Darby and Rebecca Young were favored with living testimonies,
and through renewed mercy we were comforted in believing it was a good meeting.
The meeting at Stockwell was held in a corn store, which being large and well seated,
it was thought that five hundred persons were present, yet great numbers did not get in.
The people were quiet,
but the ceiling being low and the windows and doors much stopped up by the crowd,
it became very warm, yet the company kept very still.
After I had relieved my mind, Deborah Darby had a powerful testimony,
and the opportunity ended in prayer; the people withdrew in an orderly manner,
desiring another meeting.`"
These complimentary notices had little or no weight with him,
having in himself the indubitable sense and feeling,
that if any good was done it was of the Lord`'s mercy, to whom alone all praise is due.

"`21st. In the meeting for business,
much was said by several Friends to keep the members to
plainness and simplicity without formality,
there being much room for better example in the families of some in high stations.

"`23rd. A Friend of Lancashire spoke a few words in the ministry, with which I had unity.
He was formerly sailing-master of a frigate, in the time of the American war,
but was now an acknowledged minister, keeps a school for a livelihood,
and he and his wife walked up to the Yearly Meeting, nearly three hundred miles,
as did also another minister of Cumberland,
who is in the station of a servant--several others
walked from fifty to one hundred and fifty miles.

"`24th. I thought it my place to go into the women`'s meeting, which being united with,
I was favored to relieve my mind respecting the departures
from Gospel simplicity in some of the rich and great.
Deborah Darby in much sweetness offered up a solemn prayer.
With the great wealth that is among Friends,
there are many generous hearts who are disposed
to apply it for approved and religious purposes.

"`First-day, 27th. Attended an appointed meeting this evening at Islington,
which was held in Friends`' school and work-house, called Clerkenwell;
it was much crowded and oppressively warm,
and many out in the yard--the people still and attentive.
Deborah Darby was preciously drawn forth in prayer and praises,
and through renewed mercy we parted solemnly.
Lodged at a Friend`'s house at Hempstead; the grounds, garden, etc. were in high style,
I thought much beyond true simplicity.
Being on one side of Hempstead heath, it is a fine, open situation,
and seems to combine almost everything this world could afford;
and the owner gives a welcome reception to Friends;
but more conformity to the simplicity and ways of Truth
would have made it still pleasanter to me--his taxes,
charities and other expenses, amount to near four thousand pounds sterling, per annum.

"`30th. The Yearly Meeting closed, having held thirteen days.

"`Sixth month, 1st. Was at the Meeting for Sufferings,
wherein Friends were encouraged to keep in remembrance
the professors with us in Germany and France.
Attended a public meeting at Westminster this evening,
in which Deborah Darby was largely engaged, and Rebecca Young also lively and pertinent,
and it ended in thanks to Him who is ever worthy.

"`First-day, 3rd. Was at a public meeting this evening held at the Park meeting-house,
which was so crowded that the young people of our Society were
requested to go out to give room for others,
which many of them did and stayed in the yard.
Through Divine favor and mercy I was enabled to
relieve my mind far beyond my expectation,
for I entered the house in great fear.
This is often my situation before these large, important meetings,
and the prayer of my heart in secret is,
'`Lord preserve me from wounding thy holy cause;`' and blessed be his name,
He has often manifested himself to be strength in
weakness and a present helper in the needful time;
for which, under a present sense of my own great unworthiness,
I desire in the depth of humility to render unto him the praise of his own works.

"`4th. For several days past my mind has been much
turned to think of the poor prisoners in Newgate;
four men and one woman were executed last week, and several more intended for this week.
It is truly an afflicting circumstance,
that numbers are continually sent out of the world in that way, in this country;
many for small crimes`'. The woman now under sentence,
had passed a bank-note of only twenty shillings value, knowing it to be counterfeit;
her master gave her an excellent character, except in that one instance,
yet no pardon could be obtained.
Believing it right to make the attempt,
though it was very trying to me again to enter those dismal abodes of the wretched,
and having the company of a few Friends, we were readily admitted.
Had an interview with a young man of a respectable family,
condemned for a species of forgery, though it was believed, by most people,
that no fraud was designed.
We had a humbling time--such another baptizing
season I never remember on a like occasion;
he was greatly contrited, and bathed in tears, and his wife being present,
was very thankful, and it was with difficulty we retired from this most extraordinary,
affecting scene, which I have no language to describe, but trust I shall never forget it:
in the midst of judgment, the Lord eminently remembered mercy.
The poor man continued calm,
and died in reverent hope in the mercy of God through Christ Jesus.
Much interest had been made for him, but to Do purpose,
so sanguinary are the laws of this country.
Visited two others, and had a quiet, solid time with them.
Oh, when will these legal murders cease?
We went out of these abodes of human wretchedness, thankful to our ever gracious Helper,
and peaceful in having submitted to such a trying service.

"`Sixth month, 6th. Went on board several American ships,
but could determine upon nothing respecting taking passage; most of them have guns,
or go under protection of armed vessels.
The thought of being detained here as a prisoner after my business is over,
and the difficulty of procuring a passage, sunk me very low.

"`13th. Went to meet with the captain of the William Penn,
and to my great disappointment, found all his berths for cabin passengers were engaged,
though he had not yet taken in a bale of goods--
having set my mind much on going in this ship,
I became quite discouraged.

"`16th. Was again on board the William Penn, her cabin berths being all engaged,
I looked at the steerage, and thought it might he worthy of consideration,
whether I should go in that, but determined upon nothing;
returned to my lodgings in much heaviness,
on account of the difficulties that seem to
attend an attempt to return to my beloved home.

"`17th. At Devonshire-house meeting, which was large; Christiana Hustler,
though very weak in body, had a lively testimony.
I proposed a public meeting there at six o`'clock in the evening,
which I went to in much fear; the people collecting in multitudes, several of high rank,
and conducted with stillness and much solidity.
I thought it a more laborious meeting than some I had been at in that house,
yet it closed with much comfort to my mind in prayer and praises.

"`18th. Went again on board the William Penn, and found the captain;
there being still room in the steerage, concluded to keep it under consideration.
By a letter from Ross, in Ireland, we were informed that all the Friends in that town,
of which there are about six families, were preserved from injury in person or property,
during the great slaughter and burning lately perpetrated there: the Friend writes,
that he could count two hundred and fifty dead bodies at once in the streets,
from his own window.
It is a special mercy from the Lord, that Friends have been so preserved.

"`First-day, 24th. Was at Devonshire-house meeting this afternoon;
my mind was led into sympathy with some not of our Society,
who were looking fur some great thing to be done to convince them of our faith;
and I was led forth much more largely into labor than I expected,
and hope the Lord was pleased to favor with his help
and presence--the opportunity closed solemnly.

"`27th. Went in company with three Friends to visit William Wilberforce,
to lay before him the distressed state of the people in Ireland,
as we had been informed of it by a recent letter from a Friend there.
We had a private interview with him, and freely expressed our sentiments,
which seemed to give him much satisfaction; then returned to London,
having reason to believe our visit would not be wholly lost.

"`29th. Visited the school and work-house at Clerkenwell;
most Friends speak of the comfort and sweetness they find in attending this institution,
which has been abundantly blessed;
several who have been educated there have become valuable ministers,
and also many are useful and promising young people in Friends`' families.
On my return to my lodgings,
observed a man who I believe was first awakened
to religious concern in a meeting at Horselydown,
about a year past, preaching to a great crowd of people in Moorfields:
his expression and looks betrayed much wildness,
and I was afraid the ardour of his mind would land him in insanity,
the people were generally civil.
I had much conversation with him;
his weakness is an apprehension of great and extraordinary revelations.
At first his state of mind was calm and quiet,
but by associating with some men of warm imaginations and high opinions of themselves,
he seemed now likely to lose even his understanding.

"`First-day, Seventh month,
1st. Went to Staines to attend a burial--many people came to the
meeting the greater part of whom were not members of our Society;
some of the young people were much affected, and it proved a solid opportunity.
Appointed an evening meeting for people of other societies, which iras very large,
it being thought that as many stood out of the house as were in it.
I arose with a concern which the apostle had clearly expressed for me,
and I think it best in a general way for ministers to
make use of Scripture expressions in their testimonies:
the words were these, '`Take heed, brethren,
lest there be in any of you an evil heart of unbelief in departing from the
living God;`' and I was led to speak on the danger of an unbelieving heart.
The forepart of the time seemed very laborious, but afterwards,
as the Lord opened the way for it, I had to address a different class,
and through great condescension it was a season of much brokenness and favor,
and the meeting ended in thanksgiving to the everlasting Fountain of all spiritual help.
I was afterwards informed there were some at the meeting who held Deistical opinions.`"

Seventh month,
7th. Being detained by not finding a suitable vessel to take his passage for America,
he spent the time in attending meetings and visiting the sick, aged and infirm,
yet under much depression at being so long prevented from returning home.

"`First-day, 8th. Went to Deptford,
where some of the most sober of the people attended the meeting;
and though not so large as was expected, it was through mercy a comfortable season.
Dined at a young woman`'s named Jane Jefferys, in company with several Friends.
She was convinced of our religious principles about two years since,
received into membership and sometimes speaks a few words acceptably in meetings.
Her parents being displeased at her change, turned her out of doors;
she commenced a little mercer`'s shop and mending of
umbrellas--her business is now increased,
and she appears to be blessed for her integrity.
A person who had been at our meeting here last year and then accommodated us,
sent to know if he should fit up a place for a public meeting in the evening,
which being my prospect, he took much pains in putting the place is order.
It was a large hop and malt house, and notice being given, though a wet evening,
it was supposed tint seven or eight hundred attended; were very quiet and well behaved,
and through Divine mercy and goodness it proved a tendering, favored opportunity,
ending is praises to our ever gracious Helper and Preserver:
many appeared thankful for it, and one well-dressed woman with tears,
expressed her gladness at having been present.

"`10th. Set off for Bristol to seek for a passage,
and arrived there about half-past ten o`'clock at night,
it being one hundred and sixteen miles.

"`11th. Went on board a vessel which was small
and her accommodations but poor--then to another,
but it being uncertain when she would be ready,
and also taking guns on board for defence, I could not agree to take passage in her.
Visited several Friends,
and in the evening had another interview with the man
who is before noticed as speaking in Moorfields:
he had been convinced in Guernsey,
was filled with an opinion that he was called to some great work in this nation,
and abounded in visions and revelations.
I retired to rest with deep inquiry on my mind,
'`Lord what wouldst thou have me to do in my present situation?,
not yet seeing with clearness the ship to return in.
Affecting accounts are received from Ireland of the ruin and devastation there,
so that it is said many Protestants have abjured their religion to save their lives.
Friends have also been required to embrace the Romish religion in some instances,
as the insurgents have said there should be but one religion in the country,
yet no violence was offered to any member on that account.
Two young men,
who had latterly appeared under convincement and attended Friends`' meetings at times,
declaring they could neither take an oath nor deny their faith, suffered death.
One who was a member having departed from the testimony of Truth,
and associated with others to oppose the insurgents, was killed with all his party,
about twenty in number.
One innocent young man was shot at behind his master`'s counter in mistake,
being taken for another person.
The Quarterly Meeting being held at Enniscorthy the next day
but one after the great slaughter and burning of that town,
Friends had to remove the dead bodies out of the way of the carriage wheels.
The meeting was small but solid, and Friends met with no interruption,
which was a great favor from the good hand of Providence,
worthy of grateful thanksgiving.

"`13th. Attended the week-day meeting at Bristol, which I hope was an instructive one:
the expectations of both Friends and others being for a public meeting in the evening,
they requested to know if one should be appointed,
but I felt nothing sufficient to authorize it.
In company with several Friends, I had another opportunity with the man mentioned before,
who thinks his call is to all people--refuses to work at his trade, etc:
much tender advice was given to him, but it had little or no effect upon him.
Such is the state of those who are so unhappy as to exalt
their own imaginations into the seat of revelation,
be they ever so inconsistent with Scripture and reason,
concluding they are the command of God to them.
On this score our Society and others have suffered much.

"`14th. Set off to reach London if possible tonight,
and with great diligence arrived there about nine o`'clock in the evening,
said to be on this route one hundred and eighteen or one hundred and twenty miles.

"`First-day, 15th. Attended Grace-church street meeting,
and at the close believed it my place to appoint an evening meeting,
which was much crowded, the people remarkably still, and it was satisfactory;
our gracious and heavenly Shepherd,
notwithstanding our unworthiness and manifold infirmities,
continues to be a present help to those who call upon Him.

"`20th. Concluded to take passage in a vessel I had before been on board of at Bristol,
though she was not likely to afford such comfortable
accommodation as some others which had guns for defence.
The kind expressions of care and love for me from my friends,
humbled me into tears of gratitude before the Author of every mercy,
who had graciously preserved me in unity with my brethren.

"`First-day, 22nd. Had an appointed meeting at the Peel,
the house became so crowded that the young people were desired to give way to strangers,
which they generally did, yet it was said that some hundreds went away for want of room.
My mind was much humbled: the people, though greatly crowded, were still,
and a solemnity prevailed that made us joyful in the house of prayer and praise,
with which the meeting ended,
and Friends said they did not remember so orderly a public meeting in that house.`"

After this he had several religious opportunities both at meetings and in families,
there being much unity and attachment manifested by Friends towards him.
He took coach on the 26th for Bristol,
being accompanied by several of his particular friends,
but did not get there until half-past eleven o`'clock at night.

"`First-day,
29th. My kind friends have manifested great attention
and benevolence towards me in several respects.
Attended their meeting this forenoon, where I was favored to relieve my mind comfortably,
and the meeting appeared to end well.
Was at an appointed meeting in the evening which was very large,
and I felt my mind strengthened under an apprehension of duty,
to show that as God is love, there was an obligation on us as Christians,
to endeavor to live in Him, that we might also manifest a living in love with each other.
The meeting ended in prayer and praises to the Author of every mercy,
for this renewed favor.
I was comforted in spirit for the Lord`'s goodness in granting relief to my mind,
as ever since leaving Bristol last,
I believed it would be my duty to attempt another meeting of this kind:
no doubt with me the Lord hath many sheep in this city, not yet nominally of our fold.

"`31st. While in meeting a messenger came in and beckoned me to come out,
informing that my passport was come from the duke of Portland,
and desired I would immediately go with him to the custom-house,
as the controller was waiting beyond his usual
hour to grant me liberty to sail for America.
My mind not being quite relieved of the meeting, I desired of him a little delay,
and returned to the women`'s meeting, where I had an open, tender parting.
Then went to the custom-house and was soon cleared.
Many Friends came to my lodgings in the evening,
and it pleased our good Master to grant us his presence.

"`Eighth month 1st. A number of Friends accompanying,
we went to a place about two miles from where the vessel lay,
and in an upper room of the inn had a comfortable, religious opportunity.
I had in much brokenness to express my thankfulness to my blessed and good Shepherd,
who had carried me through a great journey and voyage,
and notwithstanding my many infirmities,
had granted me now in the close a portion of sweet peace,
which was not of merit but of his own mere mercy;
and it closed in prayer and praises to Him who is ever worthy;
we then parted with many tears.

"`Getting on board we soon set sail, but our captain not liking to go to sea that night,
we dropped anchor under the shore of Wales.

"`6th. After a rough passage, got into the cove of Cork, and dropped anchor;
I took boat and went on shore, then in a post-chaise to Cork,
and next day attended their usual week-day meeting.

"`8th. Returned to the vessel.
Cove is a poor, dirty town, and may contain three hundred houses,
the greater part of which are very mean;
the inhabitants depend upon the shipping for a livelihood, and provisions are very low,
except when the fleet comes in; butcher`'s meat from three to four pence per pound;
poultry, fish, potatoes, etc., in like proportion.

"`12th. Went to Passage in our boat, then took horse and got to Cork to their meeting,
which was pretty large, and I hope a profitable one.

"`14th. Was at their usual meeting, and after dinner took boat for the vessel,
it not being prudent to stay long on shore,
as the sailing of the fleet was daily expected.
In our passage in the boat it rained much,
and night coming on it was very dark and boisterous;
we searched long from one vessel to another, but could not find ours,
and being as wet as we could be, determined to go to land,
as it was dangerous staying on the water much longer.
This was a miserable alternative to go to a town
with so little hope of getting a lodging,
but we providentially landed safely, though not without danger,
and the lads belonging to the boat, after much inquiry found me a bed,
the people lent me a few dry clothes while mine were put to dry,
and with a little refreshment I went to sleep,
and on the 15th got on board the ship again.

"`First-day, 19th. Went on shore again and attended their afternoon meeting,
and also a burial, at which was a great concourse of people,
and I had some religious service,
which appeared to be a time of favor and comfort to the relatives of the deceased.

"`First-day, 26th. Went to Cork, attended their meeting,
and appointed a public meeting for the evening,
it having been on my mind since my first landing; it was large,
and several Friends with myself thought the Lord favored us with his presence.

"`27th. Was very desirous to get to the ship, and procured a horse and proceeded to Cove,
but no boatman would go to the vessel, as the wind was high and it rained very hard:
I was therefore obliged to stay at an uncomfortable house that night.

"`Eighth month, 30th. Very uneasy at our detention; went to Cork,
and attended the meeting, which was chiefly in silence, but a time of comfort.

"`31st. The ship of war fired a gun about six o`'clock in the morning to put to sea.
Our captain being on shore, we were among the hindermost in getting off;
and coming on board in great haste,
brought no fresh provisions except ii few pounds of beef.
About ten o`'clock all the ships were under sail, said to be ninety-six.
Several Friends came off in a boat and brought us a number of fine vegetables, etc.
We had a religious sitting together and parted most affectionately,
not expecting to meet again on these shores.
The wind becoming unfavorable we had to return, which damped our spirits much,
but there seemed no other alternative than to anchor again at Cove,
yet under this great disappointment we endeavored to encourage each other in resignation.

"`First-day, Ninth month 2nd. Held a meeting in the cabin,
the captain and passengers were present, and we were favored with a solid,
comforting season.

"`8th. A signal being given for the fleet to get under weigh,
all the harbor seemed to resound with acclamations of joy,
and by the middle of the afternoon we were in the
centre of the fleet off the old head of Kinsale,
and next morning out of sight of land.

"`12th. The sea and wind having for two days been very high,
the waves frequently dashing over the vessel and pouring down the cabin stairs,
our dead-lights were put in, the cabin-doors closed,
and our situation became truly gloomy--a great part of our live stock was destroyed.
Our captain and mate are very vigilant and proved
themselves masters in the science of navigation.
The helm being lashed we lay to for some hours,
and such an awful scene I had never before been in at sea;
the fleet was so scattered we could see but eight or ten ships.
I kept my berth the greater part of the day---our situation called
for resignation and confidence in Him whom the winds and sea obey,
and I was thankful for the portion that was mercifully granted me, yet was desirous,
if consistent with his will, to see my beloved connections and friends at home.

"`18th. The storm had considerably abated, the sea gradually subsided,
and the wind though light was fair;
we passed the day in some degree of ease and went to bed in thankful acknowledgment,
that '`the winds which blew at heaven`'s command,
at heaven`'s command were still.`' Found we had
for two or three days been off the bay of Biscay,
a place of much danger with respect to the French.

"`15th. Saw no vessels and supposed we were separated from the fleet,
but in the afternoon some of them came in sight.
I was only desirous of having company on account of our vessel being leaky,
and by no means fit to put to sea alone,
and also an apprehension that we should be short of
provisions and water if the passage proved tedious.
I never wished to have any other protection from
an enemy than the arm of a gracious Providence.

"`First-day, 16th. The weather being fine, the captain,
all the passengers and some of the crew, sat down, with us at meeting in the cabin,
which proved a time of profitable reflection on the Lord`'s
goodness in preserving us through the late storm.
We were for some time made uneasy by an apprehension
that our captain had an intention of leaving the fleet,
and considering the state of our vessel were obliged to remonstrate with him,
and though he assured us he would find the fleet,
yet we were not without suspicions that he did not desire to join it.

"`22nd. Had entirely lost sight of it.
After seeking it for two days past,
a general dissatisfaction appeared both among the seamen and passengers,
several of the former having been prisoners with the French; for my own part,
the only desire I had of continuing with the fleet,
arose from an apprehension of more safety as respected our continual leaking.

"`First-day, 23rd. Held our meeting as usual,
and had cause to believe we were owned by the holy Head of the church.

"`27th. Early in the morning the captain came to my
room and informed me there was a ship in sight,
but he could not yet discover whether it was an enemy or not:
as she was bearing towards us the passengers and seamen were in alarm,
some securing their most valuable things, putting on their best clothes, etc:
the captain also endeavoring to appear to the best advantage.
I sat down quietly waiting the issue; the prevalent opinion among our people was,
that she was a Frenchman, and our seamen seemed confident that she was.
This suspense and fear lasted more than an hour:
I was preserved from fear or disturbance,
and said I was under no great apprehension of danger.
When they came up they ordered us to lay to till they came on board, which they did,
being armed, no hats but handkerchiefs tied round their heads,
with strong appearances of being neither Americans nor Englishmen;
all our people seemed in consternation and dismay,
but when their captain boarded us and shook hands with ours,
all countenances brightened again, yet with a mixture of fear and doubt.
The captain of the stranger said he knew me, had seen me in France,
and was pleased to meet me again as a friend--
they spent an hour with us in a social manner,
informed us that the ship was the Camilla, a letter of marque from Boston for Malaga,
had fourteen guns and thirty-five men; and ordering his men into the shrouds,
they gave us three cheers, fired a gun and parted from us.
By the papers they left us,
I found that the yellow fever was prevailing in several towns and cities,
and that the deaths in my dear native city had
amounted to between thirty and forty per day,
for three days the week previous, which depressed my spirits much.
O Philadelphia!
Philadelphia! thou whom the Lord has known and
favored above all the cities I have ever seen,
is there not a cause why thou shouldst so repeatedly be
made to read the roll written within and without,
with mourning, lamentation and woe?
Doubtless there is,
or thy God would still have preserved the walls of salvation around thee,
and thy gates would have resounded with anthems of praise.

"`My companions in the ship seemed unusually happy all day after our escape,
but the situation of my dear and tender connections and friends at home, now in distress,
lay so near my heart, that I retired to my room very heavy.

"`First-day, 30th. Held meeting as usual,
and was sensible of the necessity of rendering praise unto God for the favors received,
and endeavoring to walk more worthy of them, lest He should withdraw them from us;
his mercies are indeed new every morning.

"`Tenth month, 1st. High wind and rain, the cabin close shut up,
and the passengers in the steerage were kept down all day.

"`4th. Being on the banks of Newfoundland, we took plenty of fine fish,
to the joy of the ship`'s company.

"`First-day, 7th. The wind being high, the ship rolling and tossing so much,
and several of the passengers not well, it did not appear practicable to hold a meeting,
but we got the children and lads to read each a chapter in the Bible.

"`First-day, 14th. Held our meeting, and being now in sight of land,
the people on board were not so settled as could be wished,
but it ended better than I expected.
Our leak, which was the cause of so much serious uneasiness, was not so now,
and the consideration of again beholding my native land,
frequently filled my heart with gratitude,
gladness and thankfulness to the Author of every mercy.
But alas! how short-lived are our times of rejoicing in this ever-changing scene.
A pilot came on board and informed that the yellow fever was raging in New York,
and with still greater violence in my endeared Philadelphia,
which struck me with sadness.
It being almost a perfect calm,
we made very little way for several days--found that
several vessels of the fleet that sailed when we did,
had arrived at New York about a week since.

"`18th. Were near the desired port.`"

He landed at New York, soon proceeded toward Philadelphia,
and finding his wife and family had retired a few miles out of the city,
on account of like awful prevalence of the pestilential
disease which then had become very mortal,
he got to them as early as practicable.
When the sickness and mortality had subsided he returned to Philadelphia,
and as usual was industriously engaged in his mechanical business,
as well as in visiting the sick and infirm,
and in the diligent attendance of religious meetings.
His tender, sympathizing mind, not being easy without endeavoring as far as in his power,
to alleviate the afflictions of his fellow-citizens,
occasioned him to be frequently in the abodes of suffering and misery.
As the yellow fever had for several years visited the city,
and he was much within the sphere of its virulence,
he thought it most prudent to be very sparing in the use of animal food,
and almost totally abstained from it,
which some of his friends believed tended to weaken his frame,
and rendered the system more accessible to other disorders.

From-an apprehension of religious duty,
he attended the Yearly Meeting of New York in the year 1800,
having the full concurrence of his Monthly Meeting in the service,
and on his return home produced a minute expressive of the satisfaction of
Friends with his company and Gospel services among them.
In the Ninth month, 1801, under similar feelings and with the unity of his brethren,
he attended the Yearly Meeting in Baltimore,
where his labors of love appear to have been cordial and encouraging to Friends.

Excepting these engagements,
it does not appear that he travelled much after his return from Europe,
but was diligent in the discharge of his weighty
trust as a minister of the Gospel of Christ.

His constitution having become much impaired, indications of dropsical disease appeared;
he however continued to attend meetings, and to visit the sick and afflicted.

In the Third month, 1804, he was confined to the house,
except occasionally riding for the benefit of exercise and change of air.
Daring the course of his sickness he was supported in resignation to the Divine will,
and notwithstanding his abundant labors in the service of his Lord and Master,
was led to take a very humbling view of himself, as an unprofitable servant,
having nothing to depend on but the long suffering and goodness of God--observing,
"`I thought I was once strong for the work,
but now I am a child brought back to my hornbook,
and have nothing to trust to but the mercy of God through Christ my Saviour.`"
He had been remarkable for his firm and unshaken
belief in the divinity of our Lord and Saviour,
Jesus Christ, in his propitiatory sacrifice for the sins of the world,
and in all his glorious offices for the salvation of mankind,
being often fervently engaged in setting forth these blessed
Gospel doctrines and enforcing them on his hearers;
and in the solemn moments of disease and death,
his reverent dependence and hope in his Saviour did not fail him,
but proved as an anchor to his soul.
And a short time before his death, under a sense and feeling immediately imparted,
he expressed "`glory to God,`" and continued in great composure of mind,
until the 19th day of the Sixth month, 1804,
when he calmly resigned his spirit into the hands of Him who gave it.
